# GRIB VSRT + SHRT 병합 강수 시계열 추출

**`read_kma_grib_merged`** 로 동일 폴더의 VSRT·SHRT 파일을 자동 감지해 하나의 hourly 시계열로 합칩니다.

- 겹치는 시각은 **VSRT 우선** (단기보다 정확)
- Sub-hourly VSRT 데이터는 **1시간 합산**으로 자동 변환
- 결과를 다중 지점에 대해 `OUTPUT_CSV`에 저장

**패키지:** `pygrib`, `pandas`, `numpy`

In [1]:
from __future__ import annotations

from pathlib import Path

import pandas as pd

from read_grib_timeseries import read_kma_grib_merged

## 1) 설정: 폴더, VSRT/SHRT 파일 패턴, 지점 CSV

`points_input.csv` 형식: `point_name`(또는 `name`), `lat`, `lon`.  
결과 `OUTPUT_CSV`에는 아래 `OUTPUT_COLS` 열만 저장됩니다.

In [2]:
# GRIB 파일이 있는 폴더 (노트북 기준 상대 경로 또는 절대 경로)
DATA_FOLDER = Path("forecast_rainfall")

# VSRT / SHRT 파일 검색 패턴 (필요 시 수정)
VSRT_GLOB = "*VSRT*PCP*"
SHRT_GLOB = "*SHRT*PCP*"

# 지점 목록 CSV (UTF-8 BOM 가능)
#   열 이름 예: point_name(또는 name), lat(또는 y), lon(또는 x), code(선택)
POINTS_CSV = Path("kr_rf_obs_st.csv")


def load_points_csv(path: Path | str) -> list[dict]:
    path = Path(path)

    last_error: Exception | None = None
    for enc in ("utf-8-sig", "cp949", "euc-kr", "utf-8"):
        try:
            df = pd.read_csv(path, encoding=enc)
            break
        except UnicodeDecodeError as e:
            last_error = e
    else:
        raise UnicodeDecodeError(
            "csv", b"", 0, 1,
            f"{path} 인코딩을 읽을 수 없습니다. utf-8-sig/cp949/euc-kr로 저장 후 다시 시도하세요.",
        ) from last_error

    df.columns = [str(c).strip() for c in df.columns]
    lower = {c.lower(): c for c in df.columns}

    def col(*candidates: str) -> str | None:
        for k in candidates:
            if k.strip().lower() in lower:
                return lower[k.strip().lower()]
        return None

    c_name = col("name", "point_name")
    c_lat = col("y", "lat", "latitude")
    c_lon = col("x", "lon", "longitude")
    c_code = col("code")
    if c_lat is None or c_lon is None:
        raise ValueError(
            f"{path}에 위도/경도 열이 필요합니다. 현재 열: {list(df.columns)}"
        )

    points: list[dict] = []
    for _, row in df.iterrows():
        lat = float(row[c_lat])
        lon = float(row[c_lon])
        name = (
            str(row[c_name]).strip()
            if c_name is not None and pd.notna(row[c_name]) and str(row[c_name]).strip()
            else f"{lat:.4f}_{lon:.4f}"
        )
        code = (
            str(row[c_code]).strip()
            if c_code is not None and pd.notna(row[c_code]) and str(row[c_code]).strip()
            else ""
        )
        points.append({"name": name, "lat": lat, "lon": lon, "code": code})
    return points


POINTS = load_points_csv(POINTS_CSV)
print(f"지점 수: {len(POINTS)}")
for p in POINTS:
    code_str = f"  [{p['code']}]" if p.get("code") else ""
    print(f"  {p['name']}{code_str}  ({p['lat']}, {p['lon']})")

# 결과 CSV
OUTPUT_CSV = Path("kr_rf_forecast.csv")
OUTPUT_COLS = [
    "point_name",
    "point_code",
    "base_time",
    "forecast_hour",
    "valid_time",
    "variable",
    "value",
    "forecast_type",   # VSRT / SHRT
]

지점 수: 266
  금산  [8000238]  (36.10565, 127.48185)
  세천  [8000643]  (36.34019, 127.49378)
  장동  [8000648]  (36.41347, 127.43821)
  설천봉  [8000314]  (35.86621, 127.74312)
  무주  [8000701]  (36.001683, 127.668358)
  덕유산  [8000735]  (35.89424, 127.77306)
  진안주천  [8000757]  (35.97436, 127.43596)
  동향  [8000758]  (35.83519, 127.57117)
  공성  [8000821]  (36.28187, 128.07393)
  화서  [8000834]  (36.44122, 127.9442)
  추풍령  [8000135]  (36.22025, 127.99458)
  보은  [8000226]  (36.48761, 127.73415)
  옥천  [8000604]  (36.29995, 127.59654)
  영동  [8000605]  (36.16, 127.755)
  옥천청산  [8000626]  (36.37052, 127.81538)
  가덕  [8000641]  (36.5461, 127.52388)
  청남대  [8000888]  (36.46267, 127.49074)
  금산군(금성면)  [8004701]  (36.12584, 127.49408)
  영동군(심천면)  [8007732]  (36.20687, 127.71638)
  팔음산  [8003897]  (36.3504, 127.8795)
  탑산  [8003899]  (36.3236, 127.6436)
  삼봉산  [8003900]  (36.13, 127.8436)
  염동산  [8003903]  (36.48726, 127.63905)
  청주 불당상봉  [8003912]  (36.49826, 127.55856)
  옥천 암산  [8003913]  (36.39459, 127.62834)
  옥천 거멍산  [8003914]  (36.43603, 127.67226)
  옥천 금적산  [8003916]  (36.38596, 127.70188)
  보은 노성산  [8003918]  (36.45745, 127.62589)
  성주산  [8004890]  (36.07694, 127.63033)
  금산 성치산  [8004900]  (36.01051, 127.45918)
  금산 백암산  [8004901]  (36.05146, 127.39897)
  계족산  [8004912]  (36.3879, 127.4569)
  무주 민주지산  [8005908]  (36.01256, 127.84766)
  덕유산  [8005910]  (35.8964, 127.8271)
  산흥초교  [8004125]  (36.2287, 127.4484)
  모동면  [8007299]  (36.3201, 127.9594)
  화남면  [8007311]  (36.4483, 127.9055)
  진안_용담면  [8005221]  (35.96662, 127.52003)
  군북두두  [8004167]  (36.1689, 127.5277)
  금성상가  [8004170]  (36.1308, 127.4539)
  제원제원  [8004172]  (36.1125, 127.5462)
  남일초현  [8004173]  (36.0429, 127.5044)
  남이하금  [8004174]  (36.0454, 127.4367)
  부리현내  [8004175]  (36.0608, 127.555)
  미천  [8003184]  (36.51762, 127.49627)
  척산  [8003193]  (36.56066, 127.43347)
  거교  [8003118]  (36.44547, 127.57925)
  구티  [8003120]  (36.55208, 127.73274)
  원남  [8003122]  (36.39588, 127.72779)
  장안  [8004931]  (36.4698, 127.78879)
  하장  [8003127]  (36.43072, 127.79613)
  후평  [8003128]  (36.47938, 127.69875)
  산계  [8003148]  (36.32704, 127.75947)
  삼양  [8003149]  (36.30664, 127.57154)
  가곡  [8003129]  (36.12233, 127.66902)
  계산  [8003130]  (36.17515, 127.78376)
  남성  [8003134]  (36.22851, 127.91031)
  노천  [8003135]  (36.19089, 127.93212)
  서산  [8003138]  (36.09938, 127.68486)
  심천  [8003139]  (36.23826, 127.72172)
  용화  [8003140]  (36.02082, 127.76731)
  임산  [8004770]  (36.14876, 127.91411)
  백련사  [8005924]  (35.86042, 127.7653)
  안성1  [8005925]  (35.83139, 127.73694)
  월음령  [8005928]  (35.87109, 127.78567)
  적상산  [8005931]  (35.9563, 127.69843)
  문장대  [8007924]  (36.56679, 127.86211)
  보은군(법주분교)  [1004410]  (36.51027778, 127.8063889)
  보은군(법주사)  [1004430]  (36.54083333, 127.8325)
  보은군(탁주리)  [9000133]  (36.56972222, 127.7488889)
  상주시(하송리)  [2008430]  (36.47138889, 127.9663889)
  상주시(화북초교)  [2006440]  (36.56666667, 127.9119444)
  무주군(안성초교)  [3001410]  (35.86555556, 127.655)
  무주군(무주중앙초교)  [3003452]  (36.01194444, 127.6630556)
  무주군(적상초교)  [3003420]  (35.93166667, 127.6566667)
  무주군(구천정수장)  [3003454]  (35.88583333, 127.7769444)
  상주시(삼포리)  [3005452]  (36.33861111, 127.9577778)
  영동군(궁촌리)  [3005454]  (36.10777778, 127.9175)
  상주시(화동초교)  [3007455]  (36.39222222, 127.9519444)
  상주시(화령초교)  [3007450]  (36.4475, 127.9522222)
  영동군(웅북리)  [3005450]  (36.25694444, 128.0202778)
  옥천군(청산초교)  [3007477]  (36.34611111, 127.7941667)
  보은군(삼산초교)  [3007483]  (36.485, 127.7166667)
  보은군(관기초교)  [3007479]  (36.43555556, 127.8219444)
  옥천군(도로관리사업소)  [3007435]  (36.37333333, 127.7341667)
  보은군(동정리)  [3007425]  (36.47361111, 127.6641667)
  보은군(이원리)  [3007430]  (36.54222222, 127.6777778)
  옥천군(묘금리)  [3007460]  (36.27583333, 127.7322222)
  보은군(송죽초교)  [3007440]  (36.43722222, 127.7344444)
  보은군(삼가분교)  [3007481]  (36.49111111, 127.8608333)
  옥천군(안내초교)  [3008420]  (36.39416667, 127.6616667)
  청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
  대전시(원촌교)  [3009420]  (36.37833333, 127.41)
  대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
  청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
  진안군(신괴리)  [9000027]  (35.8669444, 127.5466667)
  진안군(주양리)  [9000029]  (35.9677778, 127.4261111)
  무주군(삼가리)  [3003430]  (35.8930556, 127.6605556)
  무주군(증산리)  [3003450]  (35.9463889, 127.8472222)
  무주군(기곡리)  [3003431]  (36.0127778, 127.7180556)
  금산군(선원리)  [3004430]  (36.0705556, 127.5366667)
  영동군(산막리)  [3004440]  (36.1113889, 127.7913889)
  영동군(남성리)  [3005440]  (36.2358333, 127.9163889)
  상주시(득수리)  [9000016]  (36.3311111, 127.9002778)
  영동군(궁촌리2)  [9000018]  (36.3311111, 127.9288889)
  옥천군(원동리)  [3005430]  (36.2388889, 127.6525)
  보은군(구병리)  [3007487]  (36.4752778, 127.8772222)
  보은군(신함리)  [3007470]  (36.5166667, 127.7272222)
  옥천군(산계리)  [3007475]  (36.3108333, 127.7372222)
  옥천군(대정리)  [3008430]  (36.3847222, 127.5416667)
  금산군(마전리)  [3008440]  (36.19, 127.4694444)
  금산군(상곡리)  [3008450]  (36.2047222, 127.5763889)
  청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
  옥천군(인포리)  [9000019]  (36.3697222, 127.6561111)
  김천시(월곡리)  [2010432]  (35.98222222, 127.9438889)
  김천시(파천리)  [2010434]  (36.02777778, 127.9469444)
  대전  [8000133]  (36.37199, 127.3721)
  천안  [8000232]  (36.76217, 127.29282)
  부여  [8000236]  (36.27242, 126.92078)
  금산  [8000238]  (36.10565, 127.48185)
  세종  [8000239]  (36.48522, 127.24438)
  세종고운  [8000494]  (36.53152, 127.24064)
  세종금남  [8000496]  (36.45853, 127.26876)
  세종연서  [8000611]  (36.56667, 127.28056)
  공주  [8000612]  (36.48284, 127.13646)
  서천  [8000614]  (36.06248, 126.70411)
  논산  [8000615]  (36.21164, 127.10815)
  청양  [8000618]  (36.42371, 126.77906)
  세종전의  [8000629]  (36.69076, 127.20047)
  유구  [8000632]  (36.54069, 126.93356)
  정안  [8000633]  (36.55114, 127.09383)
  양화  [8000635]  (36.1319, 126.86024)
  계룡  [8000636]  (36.3132, 127.2407)
  오월드  [8000642]  (36.29129, 127.39586)
  세천  [8000643]  (36.34019, 127.49378)
  연무  [8000644]  (36.13662, 127.09004)
  장동  [8000648]  (36.41347, 127.43821)
  계룡산  [8000659]  (36.343, 127.2057)
  정산  [8000691]  (36.38617, 126.95652)
  함라  [8000733]  (36.0461, 126.8917)
  여산  [8000763]  (36.0592, 127.062)
  청주  [8000131]  (36.63935, 127.44089)
  서청주  [8000181]  (36.63972, 127.396944)
  청주금천  [8000327]  (36.62611111, 127.5127778)
  금왕  [8000600]  (36.97369, 127.58973)
  진천  [8000602]  (36.86338, 127.46231)
  증평  [8000623]  (36.7956, 127.562)
  가덕  [8000641]  (36.5461, 127.52388)
  위성센터  [8000676]  (36.9906, 127.42985)
  오창  [8000693]  (36.72319, 127.44011)
  청남대  [8000888]  (36.46267, 127.49074)
  오창가곡  [8000977]  (36.72455, 127.46688)
  사곡면  [8004870]  (36.52611, 127.03107)
  공주시(우성면)  [8004710]  (36.4934, 127.09924)
  음성 개미산  [8003023]  (36.87073, 127.62391)
  청주 오봉산  [8003911]  (36.58329, 127.61647)
  축융봉  [8004891]  (36.32578, 126.77832)
  공주 국사봉  [8004893]  (36.61002, 127.04296)
  장군산  [8004897]  (36.46854, 127.19491)
  천안 국사봉  [8004898]  (36.6263, 127.15825)
  논산 묘련봉  [8004899]  (36.16843, 127.2661)
  관불산  [8004910]  (36.5704, 127.2054)
  칠불산  [8004911]  (36.4864, 127.3465)
  산내동  [8004102]  (36.2818, 127.4677)
  기성동  [8004104]  (36.2557, 127.3416)
  정림동  [8004106]  (36.3045, 127.3667)
  구즉동  [8004107]  (36.4404, 127.3838)
  진잠동  [8004110]  (36.2998, 127.3165)
  대덕구청  [8004115]  (36.3467, 127.4156)
  산흥초교  [8004125]  (36.2287, 127.4484)
  노은터널  [8004127]  (36.36512, 127.30841)
  어진동  [8004142]  (36.5158, 127.2617)
  연동내판  [8004266]  (36.55522, 127.32729)
  전동노장  [8004267]  (36.6628, 127.23358)
  시청보람동  [8004270]  (36.47993, 127.28882)
  군산_나포면  [8005113]  (36.03047, 126.83204)
  익산_용안면  [8005128]  (36.12, 126.9523)
  완주_대둔산  [8005200]  (36.11517, 127.3333)
  우성동대  [8004157]  (36.4709, 127.0497)
  공주봉황  [8004158]  (36.4471, 127.1192)
  신풍산정  [8004159]  (36.5147, 126.9554)
  계룡월암  [8004162]  (36.3603, 127.1419)
  복수곡남  [8004166]  (36.1665, 127.3983)
  벌곡한삼천  [8004180]  (36.2059, 127.2648)
  성동원남  [8004185]  (36.2035, 127.0336)
  가야곡육곡  [8004186]  (36.1368, 127.1587)
  노성읍내  [8004187]  (36.2782, 127.1302)
  임천군사  [8004214]  (36.1912, 126.8949)
  남면회동  [8004216]  (36.2121, 126.8063)
  은산신대  [8004219]  (36.3105, 126.8542)
  내산운치  [8004223]  (36.2752, 126.7806)
  석성증산  [8004226]  (36.2532, 127.0024)
  문산신농  [8004245]  (36.1423, 126.7522)
  송악역촌  [8004261]  (36.4353, 127.009)
  장평중추  [8004308]  (36.3418, 126.893)
  북면보건지소  [8004394]  (36.8276, 127.2732)
  목천보건지소  [8004395]  (36.785, 127.2347)
  성남보건지소  [8004397]  (36.7429, 127.236)
  동면보건지소  [8004400]  (36.7762, 127.3441)
  선동  [8003186]  (36.48657, 127.42401)
  신대  [8003187]  (36.73901, 127.54172)
  오산  [8003188]  (36.66461, 127.37557)
  오송  [8003189]  (36.60915, 127.324454)
  척산  [8003193]  (36.56066, 127.43347)
  탑연  [8003194]  (36.62083, 127.35731)
  남차  [8003224]  (36.72401, 127.62135)
  옥성  [8003175]  (36.78457, 127.43723)
  석현  [8003176]  (36.88395, 127.37683)
  용몽  [8003178]  (36.9138, 127.5094)
  노원  [8003179]  (36.92567, 127.42846)
  용정  [8003181]  (36.8461, 127.52639)
  사담  [8003105]  (36.81691, 127.64871)
  읍내  [8003108]  (36.772, 127.63951)
  덕정  [8003156]  (37.01838, 127.49516)
  쌍정  [8003159]  (36.9302, 127.5627)
  동학사  [8004921]  (36.35921, 127.24289)
  갑사분소  [8004922]  (36.36947, 127.18212)
  청주공항*  [8000128]  (36.71666667, 127.5)
  괴산군(고마리)  [1004424]  (36.8155556, 127.7363889)
  부여군(삼산리)  [9000038]  (36.3427778, 126.7169444)
  금산군(마전리)  [3008440]  (36.19, 127.4694444)
  청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
  미원(전)  [28]  (36.7402778, 127.6711111)
  청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
  대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
  대전시(두계교)  [9000079]  (36.26638889, 127.2788889)
  대전시(만년교)  [9000117]  (36.35166667, 127.3497222)
  대전시(원촌교)  [3009420]  (36.37833333, 127.41)
  세종시(부강면사무소)  [3011440]  (36.52916667, 127.3711111)
  진천군(진천여중)  [3011420]  (36.86916667, 127.4561111)
  증평군(반탄교)  [3011450]  (36.78361111, 127.5725)
  청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
  청주시(흥덕교)  [3011460]  (36.64666667, 127.4813889)
  천안시(병천초교)  [3011410]  (36.765, 127.3)
  괴산군(문당리)  [9000078]  (36.74055, 127.67111)
  안성시(안성서운중교)  [1101422]  (36.94472, 127.26305)
  음성군(음성고교)  [1004428]  (36.93416, 127.68611)
  천안시(성거읍사무소)  [1101424]  (36.87805, 127.19916)
  음성군(대소보건지소)  [3011440]  (36.9725, 127.4838889)
  음성군(쌍봉리)  [9000188]  (37.00277778, 127.5552778)
  세종시(농정원)  [3011470]  (36.5925, 127.2925)
  세종시(문성교)  [9000191]  (36.51472222, 127.1961111)
  천안시(화청교)  [9000194]  (36.76194444, 127.3980556)
  천안시(신흥교)  [9000200]  (36.70305556, 127.1133333)
  공주시(금강교)  [3012405]  (36.47027778, 127.1277778)
  금산군(신대리)  [3009410]  (36.21388889, 127.3791667)
  공주시(정안면사무소)  [3012430]  (36.60861111, 127.1202778)
  공주시(반포중)  [3012425]  (36.40361111, 127.2430556)
  공주시(복룡리)  [3012440]  (36.34555556, 127.0680556)
  공주시(유구초교)  [3012445]  (36.55361111, 126.9505556)
  부여군(홍산초교)  [3012410]  (36.2175, 126.7625)
  부여군(백제교)  [3012450]  (36.27583333, 126.8916667)
  청양군(청양읍사무소)  [3012420]  (36.45361111, 126.8066667)
  청양군(119안전센터)  [3012435]  (36.41805556, 126.94)
  보령시(미산면사무소)  [3203442]  (36.21083333, 126.6775)
  논산시(연산중)  [3013420]  (36.21333333, 127.2069444)
  논산시(동산초교)  [3013440]  (36.14027778, 127.2416667)
  논산시(토양리)  [9000190]  (36.14916667, 127.1025)
  논산시(황산리)  [3013410]  (36.15444444, 127.0086111)
  서천군(망월리)  [3203440]  (36.02944444, 126.7569444)
  서천군(충남디자인예술고)  [3014430]  (36.08916667, 126.8036111)
  진안군(대불리)  [3001442]  (35.96166667, 127.365)
  완주군(장선초교)  [3013430]  (36.09111111, 127.2791667)
  익산시(함열초교)  [3014410]  (36.07972222, 126.9652778)
  군산시(임피초교)  [9000216]  (35.98748, 126.84899)
  익산시(연동리)  [3014420]  (36.03388889, 127.035)

## 2) 폴더 내 VSRT / SHRT 파일 확인

In [3]:
def list_grib_files(folder: Path | str, pattern: str = "*") -> list[str]:
    folder = Path(folder)
    if not folder.is_dir():
        raise NotADirectoryError(folder)
    return [str(p) for p in sorted(folder.glob(pattern)) if p.is_file()]


vsrt_files = list_grib_files(DATA_FOLDER, VSRT_GLOB)
shrt_files = list_grib_files(DATA_FOLDER, SHRT_GLOB)

print(f"VSRT 파일 ({len(vsrt_files)}개):")
for fp in vsrt_files:
    print(f"  {Path(fp).name}")

print(f"\nSHRT 파일 ({len(shrt_files)}개):")
for fp in shrt_files:
    print(f"  {Path(fp).name}")

VSRT 파일 (1개):
  DFS_VSRT_GRD_GRB6_PCP.202605102000_202605110520

SHRT 파일 (1개):
  DFS_SHRT_GRD_GRB5_PCP.202605102000

## 3) VSRT / SHRT 개별 데이터 확인

`read_kma_grib`으로 VSRT와 SHRT 파일을 **개별** 읽어 각 지점의 DataFrame을 확인합니다.  
CSV 저장 전 데이터 품질(결측, 이상값, 시간 범위 등)을 점검하세요.

In [4]:
from read_grib_timeseries import read_kma_grib, _to_hourly

_vsrt_files = globals().get('vsrt_files', [])
_shrt_files = globals().get('shrt_files', [])
_points    = globals().get('POINTS', [])
if not _points:
    raise RuntimeError('POINTS가 없습니다. 설정 셀(섹션 1)을 먼저 실행하세요.')

# ── VSRT 개별 읽기: 원본 10분 데이터 → 1시간 합산 ──────────
print('=' * 60)
print('▶ VSRT 개별 읽기 (10분 원본 → 1시간 합산)')
print('=' * 60)

_vsrt_frames: list[pd.DataFrame] = []
if not _vsrt_files:
    print('VSRT 파일 없음 — 건너뜁니다.')
else:
    for _pt in _points:
        _name = _pt.get('name') or f"{_pt['lat']:.4f}_{_pt['lon']:.4f}"
        _code = _pt.get('code', '')
        print(f"\n{'─'*50}")
        print(f"지점: {_name}  [{_code}]  ({_pt['lat']}, {_pt['lon']})")

        # 원본 10분 데이터
        _df_raw = read_kma_grib(_vsrt_files, float(_pt['lat']), float(_pt['lon']))
        _df_raw.insert(0, 'point_code', _code)
        _df_raw.insert(0, 'point_name', _name)
        print(f"\n  [원본 10분 데이터 — {len(_df_raw)}행]")
        display(_df_raw)

        # 1시간 합산 (point_name, point_code 열 제외하고 변환 후 재삽입)
        _df_h = _to_hourly(_df_raw.drop(columns=['point_name', 'point_code']))
        _df_h.insert(0, 'point_code', _code)
        _df_h.insert(0, 'point_name', _name)
        print(f"\n  [1시간 합산 데이터 — {len(_df_h)}행]")
        display(_df_h)

        _vsrt_frames.append(_df_h)

# ── SHRT 개별 읽기 ──────────────────────────────────────────
print('\n' + '=' * 60)
print('▶ SHRT 개별 읽기')
print('=' * 60)

_shrt_frames: list[pd.DataFrame] = []
if not _shrt_files:
    print('SHRT 파일 없음 — 건너뜁니다.')
else:
    for _pt in _points:
        _name = _pt.get('name') or f"{_pt['lat']:.4f}_{_pt['lon']:.4f}"
        _code = _pt.get('code', '')
        print(f"\n{'─'*50}")
        print(f"지점: {_name}  [{_code}]  ({_pt['lat']}, {_pt['lon']})")
        _df = read_kma_grib(_shrt_files, float(_pt['lat']), float(_pt['lon']))
        _df.insert(0, 'point_code', _code)
        _df.insert(0, 'point_name', _name)
        print(f"\n  [SHRT 데이터 — {len(_df)}행]")
        display(_df)
        _shrt_frames.append(_df)

============================================================
▶ VSRT 개별 읽기 (10분 원본 → 1시간 합산)
============================================================

──────────────────────────────────────────────────
지점: 금산  [8000238]  (36.10565, 127.48185)
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산,8000238,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산,8000238,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산,8000238,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산,8000238,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산,8000238,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산,8000238,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산,8000238,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산,8000238,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산,8000238,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산,8000238,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산,8000238,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산,8000238,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산,8000238,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산,8000238,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산,8000238,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산,8000238,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산,8000238,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산,8000238,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산,8000238,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산,8000238,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산,8000238,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산,8000238,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산,8000238,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산,8000238,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산,8000238,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산,8000238,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산,8000238,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산,8000238,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산,8000238,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산,8000238,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산,8000238,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산,8000238,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산,8000238,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산,8000238,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산,8000238,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산,8000238,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산,8000238,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산,8000238,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산,8000238,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산,8000238,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산,8000238,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산,8000238,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세천  [8000643]  (36.34019, 127.49378)
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세천,8000643,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세천,8000643,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세천,8000643,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세천,8000643,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세천,8000643,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세천,8000643,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세천,8000643,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세천,8000643,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세천,8000643,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세천,8000643,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세천,8000643,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세천,8000643,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세천,8000643,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세천,8000643,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세천,8000643,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세천,8000643,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세천,8000643,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세천,8000643,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세천,8000643,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세천,8000643,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세천,8000643,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세천,8000643,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세천,8000643,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세천,8000643,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세천,8000643,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세천,8000643,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세천,8000643,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세천,8000643,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세천,8000643,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세천,8000643,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세천,8000643,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세천,8000643,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세천,8000643,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세천,8000643,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세천,8000643,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세천,8000643,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세천,8000643,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세천,8000643,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세천,8000643,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세천,8000643,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세천,8000643,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세천,8000643,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장동  [8000648]  (36.41347, 127.43821)
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장동,8000648,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,장동,8000648,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,장동,8000648,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,장동,8000648,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,장동,8000648,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,장동,8000648,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,장동,8000648,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,장동,8000648,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,장동,8000648,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,장동,8000648,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,장동,8000648,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,장동,8000648,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,장동,8000648,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,장동,8000648,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,장동,8000648,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,장동,8000648,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,장동,8000648,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,장동,8000648,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,장동,8000648,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,장동,8000648,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,장동,8000648,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,장동,8000648,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,장동,8000648,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,장동,8000648,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,장동,8000648,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,장동,8000648,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,장동,8000648,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,장동,8000648,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,장동,8000648,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,장동,8000648,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,장동,8000648,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,장동,8000648,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,장동,8000648,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,장동,8000648,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,장동,8000648,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,장동,8000648,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,장동,8000648,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,장동,8000648,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,장동,8000648,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,장동,8000648,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,장동,8000648,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,장동,8000648,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 설천봉  [8000314]  (35.86621, 127.74312)
📍 요청 위치: (35.8662°N, 127.7431°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,설천봉,8000314,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,설천봉,8000314,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,설천봉,8000314,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,설천봉,8000314,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,설천봉,8000314,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,설천봉,8000314,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,설천봉,8000314,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,설천봉,8000314,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,설천봉,8000314,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,설천봉,8000314,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,설천봉,8000314,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,설천봉,8000314,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,설천봉,8000314,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,설천봉,8000314,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,설천봉,8000314,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,설천봉,8000314,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,설천봉,8000314,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,설천봉,8000314,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,설천봉,8000314,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,설천봉,8000314,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,설천봉,8000314,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,설천봉,8000314,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,설천봉,8000314,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,설천봉,8000314,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,설천봉,8000314,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,설천봉,8000314,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,설천봉,8000314,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,설천봉,8000314,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,설천봉,8000314,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,설천봉,8000314,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,설천봉,8000314,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,설천봉,8000314,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,설천봉,8000314,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,설천봉,8000314,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,설천봉,8000314,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,설천봉,8000314,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,설천봉,8000314,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,설천봉,8000314,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,설천봉,8000314,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,설천봉,8000314,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,설천봉,8000314,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,설천봉,8000314,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주  [8000701]  (36.001683, 127.668358)
📍 요청 위치: (36.0017°N, 127.6684°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주,8000701,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주,8000701,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주,8000701,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주,8000701,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주,8000701,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주,8000701,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주,8000701,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주,8000701,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주,8000701,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주,8000701,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주,8000701,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주,8000701,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주,8000701,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주,8000701,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주,8000701,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주,8000701,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주,8000701,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주,8000701,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주,8000701,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주,8000701,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주,8000701,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주,8000701,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주,8000701,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주,8000701,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주,8000701,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주,8000701,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주,8000701,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주,8000701,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주,8000701,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주,8000701,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주,8000701,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주,8000701,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주,8000701,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주,8000701,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주,8000701,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주,8000701,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주,8000701,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주,8000701,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주,8000701,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주,8000701,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주,8000701,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주,8000701,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕유산  [8000735]  (35.89424, 127.77306)
📍 요청 위치: (35.8942°N, 127.7731°E)
📍 격자 좌표: (x=74, y=91)
📍 실제 위치: (35.9121°N, 127.7579°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕유산,8000735,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,덕유산,8000735,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,덕유산,8000735,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,덕유산,8000735,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,덕유산,8000735,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,덕유산,8000735,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,덕유산,8000735,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,덕유산,8000735,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,덕유산,8000735,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,덕유산,8000735,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,덕유산,8000735,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,덕유산,8000735,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,덕유산,8000735,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,덕유산,8000735,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,덕유산,8000735,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,덕유산,8000735,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,덕유산,8000735,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,덕유산,8000735,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,덕유산,8000735,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,덕유산,8000735,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,덕유산,8000735,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,덕유산,8000735,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,덕유산,8000735,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,덕유산,8000735,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,덕유산,8000735,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,덕유산,8000735,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,덕유산,8000735,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,덕유산,8000735,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,덕유산,8000735,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,덕유산,8000735,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,덕유산,8000735,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,덕유산,8000735,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,덕유산,8000735,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,덕유산,8000735,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,덕유산,8000735,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,덕유산,8000735,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,덕유산,8000735,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,덕유산,8000735,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,덕유산,8000735,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,덕유산,8000735,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,덕유산,8000735,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,덕유산,8000735,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안주천  [8000757]  (35.97436, 127.43596)
📍 요청 위치: (35.9744°N, 127.4360°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안주천,8000757,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진안주천,8000757,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진안주천,8000757,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진안주천,8000757,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진안주천,8000757,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진안주천,8000757,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진안주천,8000757,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진안주천,8000757,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진안주천,8000757,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진안주천,8000757,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진안주천,8000757,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진안주천,8000757,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진안주천,8000757,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진안주천,8000757,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진안주천,8000757,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진안주천,8000757,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진안주천,8000757,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진안주천,8000757,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진안주천,8000757,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진안주천,8000757,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진안주천,8000757,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진안주천,8000757,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진안주천,8000757,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진안주천,8000757,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진안주천,8000757,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진안주천,8000757,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진안주천,8000757,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진안주천,8000757,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진안주천,8000757,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진안주천,8000757,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진안주천,8000757,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진안주천,8000757,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진안주천,8000757,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진안주천,8000757,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진안주천,8000757,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진안주천,8000757,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진안주천,8000757,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진안주천,8000757,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진안주천,8000757,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진안주천,8000757,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진안주천,8000757,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진안주천,8000757,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동향  [8000758]  (35.83519, 127.57117)
📍 요청 위치: (35.8352°N, 127.5712°E)
📍 격자 좌표: (x=71, y=89)
📍 실제 위치: (35.8232°N, 127.5856°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동향,8000758,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,동향,8000758,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,동향,8000758,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,동향,8000758,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,동향,8000758,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,동향,8000758,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,동향,8000758,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,동향,8000758,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,동향,8000758,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,동향,8000758,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,동향,8000758,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,동향,8000758,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,동향,8000758,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,동향,8000758,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,동향,8000758,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,동향,8000758,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,동향,8000758,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,동향,8000758,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,동향,8000758,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,동향,8000758,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,동향,8000758,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,동향,8000758,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,동향,8000758,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,동향,8000758,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,동향,8000758,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,동향,8000758,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,동향,8000758,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,동향,8000758,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,동향,8000758,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,동향,8000758,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,동향,8000758,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,동향,8000758,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,동향,8000758,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,동향,8000758,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,동향,8000758,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,동향,8000758,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,동향,8000758,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,동향,8000758,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,동향,8000758,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,동향,8000758,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,동향,8000758,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,동향,8000758,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공성  [8000821]  (36.28187, 128.07393)
📍 요청 위치: (36.2819°N, 128.0739°E)
📍 격자 좌표: (x=79, y=99)
📍 실제 위치: (36.2741°N, 128.0530°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공성,8000821,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공성,8000821,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공성,8000821,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공성,8000821,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공성,8000821,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공성,8000821,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공성,8000821,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공성,8000821,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공성,8000821,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공성,8000821,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공성,8000821,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공성,8000821,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공성,8000821,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공성,8000821,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공성,8000821,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공성,8000821,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공성,8000821,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공성,8000821,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공성,8000821,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공성,8000821,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공성,8000821,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공성,8000821,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공성,8000821,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공성,8000821,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공성,8000821,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공성,8000821,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공성,8000821,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공성,8000821,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공성,8000821,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공성,8000821,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공성,8000821,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공성,8000821,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공성,8000821,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공성,8000821,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공성,8000821,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공성,8000821,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공성,8000821,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공성,8000821,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공성,8000821,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공성,8000821,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공성,8000821,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공성,8000821,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 화서  [8000834]  (36.44122, 127.9442)
📍 요청 위치: (36.4412°N, 127.9442°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,화서,8000834,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,화서,8000834,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,화서,8000834,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,화서,8000834,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,화서,8000834,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,화서,8000834,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,화서,8000834,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,화서,8000834,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,화서,8000834,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,화서,8000834,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,화서,8000834,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,화서,8000834,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,화서,8000834,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,화서,8000834,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,화서,8000834,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,화서,8000834,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,화서,8000834,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,화서,8000834,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,화서,8000834,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,화서,8000834,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,화서,8000834,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,화서,8000834,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,화서,8000834,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,화서,8000834,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,화서,8000834,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,화서,8000834,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,화서,8000834,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,화서,8000834,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,화서,8000834,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,화서,8000834,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,화서,8000834,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,화서,8000834,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,화서,8000834,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,화서,8000834,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,화서,8000834,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,화서,8000834,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,화서,8000834,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,화서,8000834,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,화서,8000834,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,화서,8000834,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,화서,8000834,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,화서,8000834,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 추풍령  [8000135]  (36.22025, 127.99458)
📍 요청 위치: (36.2203°N, 127.9946°E)
📍 격자 좌표: (x=78, y=98)
📍 실제 위치: (36.2294°N, 127.9945°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,추풍령,8000135,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,추풍령,8000135,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,추풍령,8000135,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,추풍령,8000135,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,추풍령,8000135,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,추풍령,8000135,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,추풍령,8000135,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,추풍령,8000135,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,추풍령,8000135,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,추풍령,8000135,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,추풍령,8000135,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,추풍령,8000135,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,추풍령,8000135,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,추풍령,8000135,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,추풍령,8000135,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,추풍령,8000135,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,추풍령,8000135,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,추풍령,8000135,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,추풍령,8000135,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,추풍령,8000135,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,추풍령,8000135,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,추풍령,8000135,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,추풍령,8000135,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,추풍령,8000135,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,추풍령,8000135,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,추풍령,8000135,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,추풍령,8000135,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,추풍령,8000135,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,추풍령,8000135,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,추풍령,8000135,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,추풍령,8000135,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,추풍령,8000135,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,추풍령,8000135,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,추풍령,8000135,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,추풍령,8000135,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,추풍령,8000135,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,추풍령,8000135,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,추풍령,8000135,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,추풍령,8000135,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,추풍령,8000135,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,추풍령,8000135,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,추풍령,8000135,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은  [8000226]  (36.48761, 127.73415)
📍 요청 위치: (36.4876°N, 127.7341°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은,8000226,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은,8000226,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은,8000226,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은,8000226,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은,8000226,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은,8000226,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은,8000226,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은,8000226,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은,8000226,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은,8000226,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은,8000226,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은,8000226,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은,8000226,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은,8000226,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은,8000226,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은,8000226,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은,8000226,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은,8000226,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은,8000226,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은,8000226,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은,8000226,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은,8000226,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은,8000226,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은,8000226,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은,8000226,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은,8000226,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은,8000226,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은,8000226,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은,8000226,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은,8000226,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은,8000226,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은,8000226,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은,8000226,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은,8000226,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은,8000226,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은,8000226,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은,8000226,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은,8000226,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은,8000226,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은,8000226,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은,8000226,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은,8000226,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천  [8000604]  (36.29995, 127.59654)
📍 요청 위치: (36.3000°N, 127.5965°E)
📍 격자 좌표: (x=71, y=99)
📍 실제 위치: (36.2825°N, 127.5969°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천,8000604,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천,8000604,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천,8000604,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천,8000604,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천,8000604,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천,8000604,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천,8000604,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천,8000604,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천,8000604,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천,8000604,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천,8000604,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천,8000604,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천,8000604,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천,8000604,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천,8000604,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천,8000604,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천,8000604,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천,8000604,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천,8000604,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천,8000604,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천,8000604,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천,8000604,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천,8000604,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천,8000604,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천,8000604,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천,8000604,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천,8000604,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천,8000604,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천,8000604,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천,8000604,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천,8000604,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천,8000604,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천,8000604,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천,8000604,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천,8000604,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천,8000604,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천,8000604,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천,8000604,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천,8000604,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천,8000604,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천,8000604,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천,8000604,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동  [8000605]  (36.16, 127.755)
📍 요청 위치: (36.1600°N, 127.7550°E)
📍 격자 좌표: (x=74, y=96)
📍 실제 위치: (36.1418°N, 127.7642°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동,8000605,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동,8000605,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동,8000605,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동,8000605,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동,8000605,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동,8000605,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동,8000605,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동,8000605,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동,8000605,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동,8000605,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동,8000605,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동,8000605,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동,8000605,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동,8000605,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동,8000605,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동,8000605,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동,8000605,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동,8000605,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동,8000605,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동,8000605,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동,8000605,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동,8000605,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동,8000605,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동,8000605,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동,8000605,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동,8000605,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동,8000605,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동,8000605,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동,8000605,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동,8000605,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동,8000605,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동,8000605,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동,8000605,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동,8000605,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동,8000605,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동,8000605,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동,8000605,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동,8000605,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동,8000605,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동,8000605,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동,8000605,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동,8000605,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천청산  [8000626]  (36.37052, 127.81538)
📍 요청 위치: (36.3705°N, 127.8154°E)
📍 격자 좌표: (x=75, y=101)
📍 실제 위치: (36.3705°N, 127.8275°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천청산,8000626,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천청산,8000626,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천청산,8000626,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천청산,8000626,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천청산,8000626,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천청산,8000626,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천청산,8000626,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천청산,8000626,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천청산,8000626,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천청산,8000626,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천청산,8000626,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천청산,8000626,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천청산,8000626,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천청산,8000626,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천청산,8000626,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천청산,8000626,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천청산,8000626,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천청산,8000626,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천청산,8000626,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천청산,8000626,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천청산,8000626,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천청산,8000626,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천청산,8000626,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천청산,8000626,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천청산,8000626,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천청산,8000626,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천청산,8000626,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천청산,8000626,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천청산,8000626,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천청산,8000626,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천청산,8000626,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천청산,8000626,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천청산,8000626,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천청산,8000626,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천청산,8000626,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천청산,8000626,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천청산,8000626,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천청산,8000626,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천청산,8000626,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천청산,8000626,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천청산,8000626,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천청산,8000626,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가덕  [8000641]  (36.5461, 127.52388)
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가덕,8000641,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,가덕,8000641,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,가덕,8000641,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,가덕,8000641,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,가덕,8000641,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,가덕,8000641,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,가덕,8000641,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,가덕,8000641,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,가덕,8000641,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,가덕,8000641,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,가덕,8000641,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,가덕,8000641,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,가덕,8000641,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,가덕,8000641,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,가덕,8000641,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,가덕,8000641,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,가덕,8000641,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,가덕,8000641,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,가덕,8000641,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,가덕,8000641,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,가덕,8000641,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,가덕,8000641,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,가덕,8000641,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,가덕,8000641,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,가덕,8000641,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,가덕,8000641,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,가덕,8000641,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,가덕,8000641,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,가덕,8000641,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,가덕,8000641,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,가덕,8000641,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,가덕,8000641,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,가덕,8000641,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,가덕,8000641,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,가덕,8000641,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,가덕,8000641,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,가덕,8000641,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,가덕,8000641,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청남대  [8000888]  (36.46267, 127.49074)
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청남대,8000888,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청남대,8000888,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청남대,8000888,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청남대,8000888,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청남대,8000888,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청남대,8000888,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청남대,8000888,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청남대,8000888,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청남대,8000888,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청남대,8000888,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청남대,8000888,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청남대,8000888,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청남대,8000888,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청남대,8000888,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청남대,8000888,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청남대,8000888,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청남대,8000888,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청남대,8000888,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청남대,8000888,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청남대,8000888,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청남대,8000888,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청남대,8000888,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청남대,8000888,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청남대,8000888,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청남대,8000888,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청남대,8000888,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청남대,8000888,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청남대,8000888,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청남대,8000888,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청남대,8000888,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청남대,8000888,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청남대,8000888,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청남대,8000888,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청남대,8000888,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청남대,8000888,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청남대,8000888,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청남대,8000888,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청남대,8000888,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(금성면)  [8004701]  (36.12584, 127.49408)
📍 요청 위치: (36.1258°N, 127.4941°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(금성면),8004701,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(금성면),8004701,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(금성면),8004701,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(금성면),8004701,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(금성면),8004701,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(금성면),8004701,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(금성면),8004701,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(금성면),8004701,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(금성면),8004701,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(금성면),8004701,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(금성면),8004701,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(금성면),8004701,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(금성면),8004701,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(금성면),8004701,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(금성면),8004701,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(금성면),8004701,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(금성면),8004701,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(금성면),8004701,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(금성면),8004701,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(금성면),8004701,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(금성면),8004701,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(금성면),8004701,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(금성면),8004701,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(금성면),8004701,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(금성면),8004701,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(금성면),8004701,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(금성면),8004701,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(금성면),8004701,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(금성면),8004701,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(금성면),8004701,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(금성면),8004701,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(금성면),8004701,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(금성면),8004701,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(금성면),8004701,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(금성면),8004701,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(금성면),8004701,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(금성면),8004701,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(금성면),8004701,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(금성면),8004701,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(금성면),8004701,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(금성면),8004701,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(금성면),8004701,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(심천면)  [8007732]  (36.20687, 127.71638)
📍 요청 위치: (36.2069°N, 127.7164°E)
📍 격자 좌표: (x=73, y=97)
📍 실제 위치: (36.1887°N, 127.7085°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(심천면),8007732,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(심천면),8007732,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(심천면),8007732,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(심천면),8007732,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(심천면),8007732,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(심천면),8007732,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(심천면),8007732,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(심천면),8007732,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(심천면),8007732,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(심천면),8007732,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(심천면),8007732,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(심천면),8007732,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(심천면),8007732,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(심천면),8007732,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(심천면),8007732,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(심천면),8007732,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(심천면),8007732,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(심천면),8007732,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(심천면),8007732,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(심천면),8007732,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(심천면),8007732,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(심천면),8007732,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(심천면),8007732,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(심천면),8007732,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(심천면),8007732,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(심천면),8007732,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(심천면),8007732,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(심천면),8007732,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(심천면),8007732,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(심천면),8007732,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(심천면),8007732,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(심천면),8007732,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(심천면),8007732,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(심천면),8007732,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(심천면),8007732,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(심천면),8007732,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(심천면),8007732,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(심천면),8007732,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(심천면),8007732,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(심천면),8007732,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(심천면),8007732,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(심천면),8007732,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 팔음산  [8003897]  (36.3504, 127.8795)
📍 요청 위치: (36.3504°N, 127.8795°E)
📍 격자 좌표: (x=76, y=101)
📍 실제 위치: (36.3695°N, 127.8846°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,팔음산,8003897,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,팔음산,8003897,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,팔음산,8003897,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,팔음산,8003897,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,팔음산,8003897,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,팔음산,8003897,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,팔음산,8003897,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,팔음산,8003897,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,팔음산,8003897,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,팔음산,8003897,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,팔음산,8003897,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,팔음산,8003897,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,팔음산,8003897,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,팔음산,8003897,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,팔음산,8003897,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,팔음산,8003897,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,팔음산,8003897,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,팔음산,8003897,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,팔음산,8003897,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,팔음산,8003897,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,팔음산,8003897,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,팔음산,8003897,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,팔음산,8003897,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,팔음산,8003897,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,팔음산,8003897,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,팔음산,8003897,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,팔음산,8003897,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,팔음산,8003897,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,팔음산,8003897,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,팔음산,8003897,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,팔음산,8003897,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,팔음산,8003897,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,팔음산,8003897,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,팔음산,8003897,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,팔음산,8003897,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,팔음산,8003897,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,팔음산,8003897,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,팔음산,8003897,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,팔음산,8003897,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,팔음산,8003897,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,팔음산,8003897,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,팔음산,8003897,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 탑산  [8003899]  (36.3236, 127.6436)
📍 요청 위치: (36.3236°N, 127.6436°E)
📍 격자 좌표: (x=72, y=100)
📍 실제 위치: (36.3276°N, 127.6551°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,탑산,8003899,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,탑산,8003899,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,탑산,8003899,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,탑산,8003899,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,탑산,8003899,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,탑산,8003899,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,탑산,8003899,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,탑산,8003899,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,탑산,8003899,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,탑산,8003899,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,탑산,8003899,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,탑산,8003899,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,탑산,8003899,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,탑산,8003899,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,탑산,8003899,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,탑산,8003899,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,탑산,8003899,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,탑산,8003899,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,탑산,8003899,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,탑산,8003899,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,탑산,8003899,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,탑산,8003899,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,탑산,8003899,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,탑산,8003899,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,탑산,8003899,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,탑산,8003899,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,탑산,8003899,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,탑산,8003899,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,탑산,8003899,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,탑산,8003899,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,탑산,8003899,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,탑산,8003899,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,탑산,8003899,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,탑산,8003899,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,탑산,8003899,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,탑산,8003899,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,탑산,8003899,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,탑산,8003899,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,탑산,8003899,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,탑산,8003899,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,탑산,8003899,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,탑산,8003899,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 삼봉산  [8003900]  (36.13, 127.8436)
📍 요청 위치: (36.1300°N, 127.8436°E)
📍 격자 좌표: (x=75, y=96)
📍 실제 위치: (36.1408°N, 127.8211°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,삼봉산,8003900,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,삼봉산,8003900,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,삼봉산,8003900,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,삼봉산,8003900,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,삼봉산,8003900,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,삼봉산,8003900,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,삼봉산,8003900,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,삼봉산,8003900,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,삼봉산,8003900,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,삼봉산,8003900,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,삼봉산,8003900,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,삼봉산,8003900,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,삼봉산,8003900,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,삼봉산,8003900,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,삼봉산,8003900,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,삼봉산,8003900,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,삼봉산,8003900,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,삼봉산,8003900,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,삼봉산,8003900,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,삼봉산,8003900,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,삼봉산,8003900,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,삼봉산,8003900,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,삼봉산,8003900,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,삼봉산,8003900,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,삼봉산,8003900,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,삼봉산,8003900,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,삼봉산,8003900,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,삼봉산,8003900,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,삼봉산,8003900,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,삼봉산,8003900,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,삼봉산,8003900,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,삼봉산,8003900,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,삼봉산,8003900,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,삼봉산,8003900,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,삼봉산,8003900,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,삼봉산,8003900,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,삼봉산,8003900,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,삼봉산,8003900,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,삼봉산,8003900,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,삼봉산,8003900,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,삼봉산,8003900,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,삼봉산,8003900,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 염동산  [8003903]  (36.48726, 127.63905)
📍 요청 위치: (36.4873°N, 127.6390°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,염동산,8003903,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,염동산,8003903,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,염동산,8003903,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,염동산,8003903,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,염동산,8003903,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,염동산,8003903,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,염동산,8003903,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,염동산,8003903,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,염동산,8003903,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,염동산,8003903,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,염동산,8003903,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,염동산,8003903,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,염동산,8003903,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,염동산,8003903,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,염동산,8003903,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,염동산,8003903,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,염동산,8003903,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,염동산,8003903,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,염동산,8003903,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,염동산,8003903,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,염동산,8003903,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,염동산,8003903,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,염동산,8003903,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,염동산,8003903,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,염동산,8003903,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,염동산,8003903,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,염동산,8003903,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,염동산,8003903,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,염동산,8003903,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,염동산,8003903,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,염동산,8003903,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,염동산,8003903,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,염동산,8003903,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,염동산,8003903,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,염동산,8003903,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,염동산,8003903,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,염동산,8003903,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,염동산,8003903,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,염동산,8003903,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,염동산,8003903,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,염동산,8003903,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,염동산,8003903,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주 불당상봉  [8003912]  (36.49826, 127.55856)
📍 요청 위치: (36.4983°N, 127.5586°E)
📍 격자 좌표: (x=70, y=104)
📍 실제 위치: (36.5133°N, 127.5454°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주 불당상봉,8003912,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주 불당상봉,8003912,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주 불당상봉,8003912,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주 불당상봉,8003912,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주 불당상봉,8003912,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주 불당상봉,8003912,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주 불당상봉,8003912,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주 불당상봉,8003912,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주 불당상봉,8003912,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주 불당상봉,8003912,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주 불당상봉,8003912,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주 불당상봉,8003912,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주 불당상봉,8003912,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주 불당상봉,8003912,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주 불당상봉,8003912,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주 불당상봉,8003912,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주 불당상봉,8003912,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주 불당상봉,8003912,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주 불당상봉,8003912,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주 불당상봉,8003912,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주 불당상봉,8003912,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주 불당상봉,8003912,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주 불당상봉,8003912,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주 불당상봉,8003912,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주 불당상봉,8003912,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주 불당상봉,8003912,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주 불당상봉,8003912,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주 불당상봉,8003912,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주 불당상봉,8003912,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주 불당상봉,8003912,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주 불당상봉,8003912,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주 불당상봉,8003912,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주 불당상봉,8003912,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주 불당상봉,8003912,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주 불당상봉,8003912,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주 불당상봉,8003912,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주 불당상봉,8003912,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주 불당상봉,8003912,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주 불당상봉,8003912,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주 불당상봉,8003912,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주 불당상봉,8003912,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주 불당상봉,8003912,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 암산  [8003913]  (36.39459, 127.62834)
📍 요청 위치: (36.3946°N, 127.6283°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 암산,8003913,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천 암산,8003913,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천 암산,8003913,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천 암산,8003913,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천 암산,8003913,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천 암산,8003913,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천 암산,8003913,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천 암산,8003913,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천 암산,8003913,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천 암산,8003913,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천 암산,8003913,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천 암산,8003913,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천 암산,8003913,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천 암산,8003913,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천 암산,8003913,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천 암산,8003913,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천 암산,8003913,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천 암산,8003913,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천 암산,8003913,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천 암산,8003913,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천 암산,8003913,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천 암산,8003913,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천 암산,8003913,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천 암산,8003913,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천 암산,8003913,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천 암산,8003913,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천 암산,8003913,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천 암산,8003913,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천 암산,8003913,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천 암산,8003913,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천 암산,8003913,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천 암산,8003913,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천 암산,8003913,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천 암산,8003913,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천 암산,8003913,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천 암산,8003913,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천 암산,8003913,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천 암산,8003913,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천 암산,8003913,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천 암산,8003913,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천 암산,8003913,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천 암산,8003913,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 거멍산  [8003914]  (36.43603, 127.67226)
📍 요청 위치: (36.4360°N, 127.6723°E)
📍 격자 좌표: (x=72, y=102)
📍 실제 위치: (36.4195°N, 127.6574°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 거멍산,8003914,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천 거멍산,8003914,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천 거멍산,8003914,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천 거멍산,8003914,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천 거멍산,8003914,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천 거멍산,8003914,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천 거멍산,8003914,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천 거멍산,8003914,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천 거멍산,8003914,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천 거멍산,8003914,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천 거멍산,8003914,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천 거멍산,8003914,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천 거멍산,8003914,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천 거멍산,8003914,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천 거멍산,8003914,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천 거멍산,8003914,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천 거멍산,8003914,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천 거멍산,8003914,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천 거멍산,8003914,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천 거멍산,8003914,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천 거멍산,8003914,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천 거멍산,8003914,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천 거멍산,8003914,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천 거멍산,8003914,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천 거멍산,8003914,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천 거멍산,8003914,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천 거멍산,8003914,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천 거멍산,8003914,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천 거멍산,8003914,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천 거멍산,8003914,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천 거멍산,8003914,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천 거멍산,8003914,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천 거멍산,8003914,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천 거멍산,8003914,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천 거멍산,8003914,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천 거멍산,8003914,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천 거멍산,8003914,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천 거멍산,8003914,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천 거멍산,8003914,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천 거멍산,8003914,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천 거멍산,8003914,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천 거멍산,8003914,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 금적산  [8003916]  (36.38596, 127.70188)
📍 요청 위치: (36.3860°N, 127.7019°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 금적산,8003916,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천 금적산,8003916,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천 금적산,8003916,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천 금적산,8003916,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천 금적산,8003916,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천 금적산,8003916,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천 금적산,8003916,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천 금적산,8003916,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천 금적산,8003916,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천 금적산,8003916,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천 금적산,8003916,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천 금적산,8003916,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천 금적산,8003916,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천 금적산,8003916,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천 금적산,8003916,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천 금적산,8003916,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천 금적산,8003916,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천 금적산,8003916,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천 금적산,8003916,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천 금적산,8003916,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천 금적산,8003916,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천 금적산,8003916,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천 금적산,8003916,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천 금적산,8003916,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천 금적산,8003916,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천 금적산,8003916,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천 금적산,8003916,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천 금적산,8003916,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천 금적산,8003916,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천 금적산,8003916,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천 금적산,8003916,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천 금적산,8003916,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천 금적산,8003916,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천 금적산,8003916,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천 금적산,8003916,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천 금적산,8003916,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천 금적산,8003916,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천 금적산,8003916,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천 금적산,8003916,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천 금적산,8003916,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천 금적산,8003916,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천 금적산,8003916,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은 노성산  [8003918]  (36.45745, 127.62589)
📍 요청 위치: (36.4575°N, 127.6259°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은 노성산,8003918,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은 노성산,8003918,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은 노성산,8003918,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은 노성산,8003918,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은 노성산,8003918,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은 노성산,8003918,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은 노성산,8003918,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은 노성산,8003918,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은 노성산,8003918,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은 노성산,8003918,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은 노성산,8003918,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은 노성산,8003918,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은 노성산,8003918,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은 노성산,8003918,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은 노성산,8003918,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은 노성산,8003918,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은 노성산,8003918,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은 노성산,8003918,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은 노성산,8003918,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은 노성산,8003918,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은 노성산,8003918,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은 노성산,8003918,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은 노성산,8003918,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은 노성산,8003918,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은 노성산,8003918,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은 노성산,8003918,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은 노성산,8003918,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은 노성산,8003918,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은 노성산,8003918,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은 노성산,8003918,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은 노성산,8003918,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은 노성산,8003918,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은 노성산,8003918,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은 노성산,8003918,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은 노성산,8003918,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은 노성산,8003918,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은 노성산,8003918,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은 노성산,8003918,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은 노성산,8003918,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은 노성산,8003918,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은 노성산,8003918,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은 노성산,8003918,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성주산  [8004890]  (36.07694, 127.63033)
📍 요청 위치: (36.0769°N, 127.6303°E)
📍 격자 좌표: (x=72, y=95)
📍 실제 위치: (36.0978°N, 127.6492°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성주산,8004890,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,성주산,8004890,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,성주산,8004890,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,성주산,8004890,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,성주산,8004890,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,성주산,8004890,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,성주산,8004890,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,성주산,8004890,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,성주산,8004890,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,성주산,8004890,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,성주산,8004890,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,성주산,8004890,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,성주산,8004890,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,성주산,8004890,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,성주산,8004890,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,성주산,8004890,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,성주산,8004890,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,성주산,8004890,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,성주산,8004890,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,성주산,8004890,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,성주산,8004890,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,성주산,8004890,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,성주산,8004890,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,성주산,8004890,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,성주산,8004890,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,성주산,8004890,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,성주산,8004890,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,성주산,8004890,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,성주산,8004890,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,성주산,8004890,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,성주산,8004890,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,성주산,8004890,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,성주산,8004890,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,성주산,8004890,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,성주산,8004890,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,성주산,8004890,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,성주산,8004890,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,성주산,8004890,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,성주산,8004890,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,성주산,8004890,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,성주산,8004890,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,성주산,8004890,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산 성치산  [8004900]  (36.01051, 127.45918)
📍 요청 위치: (36.0105°N, 127.4592°E)
📍 격자 좌표: (x=69, y=93)
📍 실제 위치: (36.0086°N, 127.4765°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산 성치산,8004900,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산 성치산,8004900,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산 성치산,8004900,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산 성치산,8004900,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산 성치산,8004900,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산 성치산,8004900,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산 성치산,8004900,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산 성치산,8004900,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산 성치산,8004900,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산 성치산,8004900,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산 성치산,8004900,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산 성치산,8004900,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산 성치산,8004900,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산 성치산,8004900,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산 성치산,8004900,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산 성치산,8004900,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산 성치산,8004900,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산 성치산,8004900,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산 성치산,8004900,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산 성치산,8004900,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산 성치산,8004900,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산 성치산,8004900,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산 성치산,8004900,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산 성치산,8004900,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산 성치산,8004900,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산 성치산,8004900,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산 성치산,8004900,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산 성치산,8004900,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산 성치산,8004900,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산 성치산,8004900,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산 성치산,8004900,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산 성치산,8004900,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산 성치산,8004900,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산 성치산,8004900,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산 성치산,8004900,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산 성치산,8004900,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산 성치산,8004900,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산 성치산,8004900,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산 성치산,8004900,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산 성치산,8004900,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산 성치산,8004900,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산 성치산,8004900,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산 백암산  [8004901]  (36.05146, 127.39897)
📍 요청 위치: (36.0515°N, 127.3990°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산 백암산,8004901,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산 백암산,8004901,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산 백암산,8004901,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산 백암산,8004901,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산 백암산,8004901,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산 백암산,8004901,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산 백암산,8004901,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산 백암산,8004901,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산 백암산,8004901,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산 백암산,8004901,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산 백암산,8004901,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산 백암산,8004901,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산 백암산,8004901,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산 백암산,8004901,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산 백암산,8004901,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산 백암산,8004901,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산 백암산,8004901,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산 백암산,8004901,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산 백암산,8004901,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산 백암산,8004901,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산 백암산,8004901,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산 백암산,8004901,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산 백암산,8004901,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산 백암산,8004901,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산 백암산,8004901,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산 백암산,8004901,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산 백암산,8004901,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산 백암산,8004901,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산 백암산,8004901,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산 백암산,8004901,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산 백암산,8004901,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산 백암산,8004901,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산 백암산,8004901,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산 백암산,8004901,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산 백암산,8004901,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산 백암산,8004901,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산 백암산,8004901,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산 백암산,8004901,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산 백암산,8004901,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산 백암산,8004901,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산 백암산,8004901,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산 백암산,8004901,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계족산  [8004912]  (36.3879, 127.4569)
📍 요청 위치: (36.3879°N, 127.4569°E)
📍 격자 좌표: (x=69, y=101)
📍 실제 위치: (36.3762°N, 127.4850°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계족산,8004912,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,계족산,8004912,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,계족산,8004912,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,계족산,8004912,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,계족산,8004912,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,계족산,8004912,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,계족산,8004912,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,계족산,8004912,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,계족산,8004912,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,계족산,8004912,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,계족산,8004912,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,계족산,8004912,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,계족산,8004912,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,계족산,8004912,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,계족산,8004912,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,계족산,8004912,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,계족산,8004912,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,계족산,8004912,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,계족산,8004912,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,계족산,8004912,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,계족산,8004912,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,계족산,8004912,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,계족산,8004912,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,계족산,8004912,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,계족산,8004912,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,계족산,8004912,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,계족산,8004912,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,계족산,8004912,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,계족산,8004912,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,계족산,8004912,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,계족산,8004912,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,계족산,8004912,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,계족산,8004912,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,계족산,8004912,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,계족산,8004912,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,계족산,8004912,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,계족산,8004912,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,계족산,8004912,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,계족산,8004912,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,계족산,8004912,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,계족산,8004912,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,계족산,8004912,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주 민주지산  [8005908]  (36.01256, 127.84766)
📍 요청 위치: (36.0126°N, 127.8477°E)
📍 격자 좌표: (x=76, y=93)
📍 실제 위치: (36.0019°N, 127.8739°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주 민주지산,8005908,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주 민주지산,8005908,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주 민주지산,8005908,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주 민주지산,8005908,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주 민주지산,8005908,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주 민주지산,8005908,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주 민주지산,8005908,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주 민주지산,8005908,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주 민주지산,8005908,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주 민주지산,8005908,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주 민주지산,8005908,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주 민주지산,8005908,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주 민주지산,8005908,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주 민주지산,8005908,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주 민주지산,8005908,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주 민주지산,8005908,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주 민주지산,8005908,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주 민주지산,8005908,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주 민주지산,8005908,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주 민주지산,8005908,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주 민주지산,8005908,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주 민주지산,8005908,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주 민주지산,8005908,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주 민주지산,8005908,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주 민주지산,8005908,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주 민주지산,8005908,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주 민주지산,8005908,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주 민주지산,8005908,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주 민주지산,8005908,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주 민주지산,8005908,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주 민주지산,8005908,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주 민주지산,8005908,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주 민주지산,8005908,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주 민주지산,8005908,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주 민주지산,8005908,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주 민주지산,8005908,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주 민주지산,8005908,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주 민주지산,8005908,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주 민주지산,8005908,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주 민주지산,8005908,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주 민주지산,8005908,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주 민주지산,8005908,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕유산  [8005910]  (35.8964, 127.8271)
📍 요청 위치: (35.8964°N, 127.8271°E)
📍 격자 좌표: (x=75, y=91)
📍 실제 위치: (35.9111°N, 127.8146°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕유산,8005910,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,덕유산,8005910,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,덕유산,8005910,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,덕유산,8005910,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,덕유산,8005910,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,덕유산,8005910,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,덕유산,8005910,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,덕유산,8005910,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,덕유산,8005910,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,덕유산,8005910,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,덕유산,8005910,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,덕유산,8005910,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,덕유산,8005910,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,덕유산,8005910,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,덕유산,8005910,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,덕유산,8005910,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,덕유산,8005910,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,덕유산,8005910,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,덕유산,8005910,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,덕유산,8005910,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,덕유산,8005910,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,덕유산,8005910,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,덕유산,8005910,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,덕유산,8005910,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,덕유산,8005910,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,덕유산,8005910,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,덕유산,8005910,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,덕유산,8005910,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,덕유산,8005910,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,덕유산,8005910,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,덕유산,8005910,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,덕유산,8005910,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,덕유산,8005910,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,덕유산,8005910,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,덕유산,8005910,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,덕유산,8005910,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,덕유산,8005910,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,덕유산,8005910,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,덕유산,8005910,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,덕유산,8005910,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,덕유산,8005910,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,덕유산,8005910,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산흥초교  [8004125]  (36.2287, 127.4484)
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산흥초교,8004125,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,산흥초교,8004125,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,산흥초교,8004125,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,산흥초교,8004125,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,산흥초교,8004125,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,산흥초교,8004125,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,산흥초교,8004125,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,산흥초교,8004125,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,산흥초교,8004125,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,산흥초교,8004125,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,산흥초교,8004125,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,산흥초교,8004125,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,산흥초교,8004125,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,산흥초교,8004125,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,산흥초교,8004125,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,산흥초교,8004125,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,산흥초교,8004125,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,산흥초교,8004125,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,산흥초교,8004125,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,산흥초교,8004125,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,산흥초교,8004125,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,산흥초교,8004125,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,산흥초교,8004125,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,산흥초교,8004125,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,산흥초교,8004125,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,산흥초교,8004125,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,산흥초교,8004125,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,산흥초교,8004125,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,산흥초교,8004125,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,산흥초교,8004125,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,산흥초교,8004125,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,산흥초교,8004125,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,산흥초교,8004125,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,산흥초교,8004125,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 모동면  [8007299]  (36.3201, 127.9594)
📍 요청 위치: (36.3201°N, 127.9594°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,모동면,8007299,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,모동면,8007299,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,모동면,8007299,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,모동면,8007299,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,모동면,8007299,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,모동면,8007299,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,모동면,8007299,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,모동면,8007299,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,모동면,8007299,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,모동면,8007299,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,모동면,8007299,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,모동면,8007299,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,모동면,8007299,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,모동면,8007299,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,모동면,8007299,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,모동면,8007299,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,모동면,8007299,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,모동면,8007299,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,모동면,8007299,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,모동면,8007299,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,모동면,8007299,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,모동면,8007299,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,모동면,8007299,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,모동면,8007299,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,모동면,8007299,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,모동면,8007299,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,모동면,8007299,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,모동면,8007299,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,모동면,8007299,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,모동면,8007299,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,모동면,8007299,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,모동면,8007299,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,모동면,8007299,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,모동면,8007299,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,모동면,8007299,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,모동면,8007299,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,모동면,8007299,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,모동면,8007299,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,모동면,8007299,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,모동면,8007299,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,모동면,8007299,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,모동면,8007299,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 화남면  [8007311]  (36.4483, 127.9055)
📍 요청 위치: (36.4483°N, 127.9055°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,화남면,8007311,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,화남면,8007311,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,화남면,8007311,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,화남면,8007311,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,화남면,8007311,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,화남면,8007311,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,화남면,8007311,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,화남면,8007311,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,화남면,8007311,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,화남면,8007311,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,화남면,8007311,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,화남면,8007311,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,화남면,8007311,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,화남면,8007311,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,화남면,8007311,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,화남면,8007311,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,화남면,8007311,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,화남면,8007311,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,화남면,8007311,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,화남면,8007311,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,화남면,8007311,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,화남면,8007311,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,화남면,8007311,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,화남면,8007311,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,화남면,8007311,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,화남면,8007311,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,화남면,8007311,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,화남면,8007311,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,화남면,8007311,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,화남면,8007311,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,화남면,8007311,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,화남면,8007311,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,화남면,8007311,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,화남면,8007311,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,화남면,8007311,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,화남면,8007311,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,화남면,8007311,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,화남면,8007311,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,화남면,8007311,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,화남면,8007311,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,화남면,8007311,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,화남면,8007311,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안_용담면  [8005221]  (35.96662, 127.52003)
📍 요청 위치: (35.9666°N, 127.5200°E)
📍 격자 좌표: (x=70, y=92)
📍 실제 위치: (35.9618°N, 127.5322°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안_용담면,8005221,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진안_용담면,8005221,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진안_용담면,8005221,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진안_용담면,8005221,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진안_용담면,8005221,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진안_용담면,8005221,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진안_용담면,8005221,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진안_용담면,8005221,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진안_용담면,8005221,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진안_용담면,8005221,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진안_용담면,8005221,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진안_용담면,8005221,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진안_용담면,8005221,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진안_용담면,8005221,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진안_용담면,8005221,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진안_용담면,8005221,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진안_용담면,8005221,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진안_용담면,8005221,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진안_용담면,8005221,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진안_용담면,8005221,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진안_용담면,8005221,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진안_용담면,8005221,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진안_용담면,8005221,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진안_용담면,8005221,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진안_용담면,8005221,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진안_용담면,8005221,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진안_용담면,8005221,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진안_용담면,8005221,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진안_용담면,8005221,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진안_용담면,8005221,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진안_용담면,8005221,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진안_용담면,8005221,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진안_용담면,8005221,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진안_용담면,8005221,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진안_용담면,8005221,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진안_용담면,8005221,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진안_용담면,8005221,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진안_용담면,8005221,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진안_용담면,8005221,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진안_용담면,8005221,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진안_용담면,8005221,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진안_용담면,8005221,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군북두두  [8004167]  (36.1689, 127.5277)
📍 요청 위치: (36.1689°N, 127.5277°E)
📍 격자 좌표: (x=70, y=97)
📍 실제 위치: (36.1915°N, 127.5377°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군북두두,8004167,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,군북두두,8004167,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,군북두두,8004167,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,군북두두,8004167,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,군북두두,8004167,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,군북두두,8004167,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,군북두두,8004167,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,군북두두,8004167,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,군북두두,8004167,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,군북두두,8004167,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,군북두두,8004167,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,군북두두,8004167,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,군북두두,8004167,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,군북두두,8004167,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,군북두두,8004167,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,군북두두,8004167,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,군북두두,8004167,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,군북두두,8004167,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,군북두두,8004167,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,군북두두,8004167,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,군북두두,8004167,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,군북두두,8004167,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,군북두두,8004167,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,군북두두,8004167,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,군북두두,8004167,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,군북두두,8004167,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,군북두두,8004167,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,군북두두,8004167,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,군북두두,8004167,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,군북두두,8004167,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,군북두두,8004167,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,군북두두,8004167,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,군북두두,8004167,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,군북두두,8004167,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,군북두두,8004167,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,군북두두,8004167,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,군북두두,8004167,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,군북두두,8004167,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,군북두두,8004167,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,군북두두,8004167,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,군북두두,8004167,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,군북두두,8004167,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금성상가  [8004170]  (36.1308, 127.4539)
📍 요청 위치: (36.1308°N, 127.4539°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금성상가,8004170,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금성상가,8004170,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금성상가,8004170,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금성상가,8004170,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금성상가,8004170,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금성상가,8004170,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금성상가,8004170,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금성상가,8004170,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금성상가,8004170,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금성상가,8004170,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금성상가,8004170,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금성상가,8004170,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금성상가,8004170,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금성상가,8004170,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금성상가,8004170,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금성상가,8004170,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금성상가,8004170,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금성상가,8004170,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금성상가,8004170,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금성상가,8004170,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금성상가,8004170,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금성상가,8004170,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금성상가,8004170,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금성상가,8004170,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금성상가,8004170,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금성상가,8004170,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금성상가,8004170,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금성상가,8004170,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금성상가,8004170,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금성상가,8004170,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금성상가,8004170,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금성상가,8004170,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금성상가,8004170,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금성상가,8004170,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금성상가,8004170,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금성상가,8004170,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금성상가,8004170,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금성상가,8004170,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금성상가,8004170,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금성상가,8004170,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금성상가,8004170,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금성상가,8004170,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 제원제원  [8004172]  (36.1125, 127.5462)
📍 요청 위치: (36.1125°N, 127.5462°E)
📍 격자 좌표: (x=70, y=95)
📍 실제 위치: (36.0996°N, 127.5355°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,제원제원,8004172,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,제원제원,8004172,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,제원제원,8004172,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,제원제원,8004172,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,제원제원,8004172,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,제원제원,8004172,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,제원제원,8004172,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,제원제원,8004172,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,제원제원,8004172,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,제원제원,8004172,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,제원제원,8004172,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,제원제원,8004172,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,제원제원,8004172,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,제원제원,8004172,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,제원제원,8004172,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,제원제원,8004172,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,제원제원,8004172,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,제원제원,8004172,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,제원제원,8004172,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,제원제원,8004172,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,제원제원,8004172,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,제원제원,8004172,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,제원제원,8004172,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,제원제원,8004172,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,제원제원,8004172,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,제원제원,8004172,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,제원제원,8004172,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,제원제원,8004172,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,제원제원,8004172,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,제원제원,8004172,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,제원제원,8004172,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,제원제원,8004172,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,제원제원,8004172,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,제원제원,8004172,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,제원제원,8004172,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,제원제원,8004172,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,제원제원,8004172,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,제원제원,8004172,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,제원제원,8004172,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,제원제원,8004172,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,제원제원,8004172,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,제원제원,8004172,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남일초현  [8004173]  (36.0429, 127.5044)
📍 요청 위치: (36.0429°N, 127.5044°E)
📍 격자 좌표: (x=69, y=94)
📍 실제 위치: (36.0546°N, 127.4776°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남일초현,8004173,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,남일초현,8004173,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,남일초현,8004173,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,남일초현,8004173,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,남일초현,8004173,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,남일초현,8004173,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,남일초현,8004173,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,남일초현,8004173,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,남일초현,8004173,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,남일초현,8004173,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,남일초현,8004173,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,남일초현,8004173,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,남일초현,8004173,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,남일초현,8004173,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,남일초현,8004173,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,남일초현,8004173,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,남일초현,8004173,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,남일초현,8004173,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,남일초현,8004173,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,남일초현,8004173,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,남일초현,8004173,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,남일초현,8004173,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,남일초현,8004173,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,남일초현,8004173,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,남일초현,8004173,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,남일초현,8004173,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,남일초현,8004173,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,남일초현,8004173,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,남일초현,8004173,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,남일초현,8004173,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,남일초현,8004173,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,남일초현,8004173,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,남일초현,8004173,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,남일초현,8004173,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,남일초현,8004173,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,남일초현,8004173,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,남일초현,8004173,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,남일초현,8004173,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,남일초현,8004173,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,남일초현,8004173,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,남일초현,8004173,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,남일초현,8004173,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남이하금  [8004174]  (36.0454, 127.4367)
📍 요청 위치: (36.0454°N, 127.4367°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남이하금,8004174,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,남이하금,8004174,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,남이하금,8004174,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,남이하금,8004174,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,남이하금,8004174,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,남이하금,8004174,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,남이하금,8004174,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,남이하금,8004174,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,남이하금,8004174,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,남이하금,8004174,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,남이하금,8004174,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,남이하금,8004174,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,남이하금,8004174,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,남이하금,8004174,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,남이하금,8004174,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,남이하금,8004174,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,남이하금,8004174,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,남이하금,8004174,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,남이하금,8004174,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,남이하금,8004174,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,남이하금,8004174,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,남이하금,8004174,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,남이하금,8004174,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,남이하금,8004174,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,남이하금,8004174,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,남이하금,8004174,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,남이하금,8004174,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,남이하금,8004174,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,남이하금,8004174,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,남이하금,8004174,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,남이하금,8004174,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,남이하금,8004174,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,남이하금,8004174,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,남이하금,8004174,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,남이하금,8004174,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,남이하금,8004174,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,남이하금,8004174,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,남이하금,8004174,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,남이하금,8004174,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,남이하금,8004174,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,남이하금,8004174,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,남이하금,8004174,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부리현내  [8004175]  (36.0608, 127.555)
📍 요청 위치: (36.0608°N, 127.5550°E)
📍 격자 좌표: (x=70, y=94)
📍 실제 위치: (36.0537°N, 127.5344°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부리현내,8004175,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,부리현내,8004175,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,부리현내,8004175,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,부리현내,8004175,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,부리현내,8004175,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,부리현내,8004175,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,부리현내,8004175,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,부리현내,8004175,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,부리현내,8004175,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,부리현내,8004175,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,부리현내,8004175,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,부리현내,8004175,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,부리현내,8004175,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,부리현내,8004175,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,부리현내,8004175,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,부리현내,8004175,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,부리현내,8004175,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,부리현내,8004175,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,부리현내,8004175,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,부리현내,8004175,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,부리현내,8004175,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,부리현내,8004175,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,부리현내,8004175,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,부리현내,8004175,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,부리현내,8004175,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,부리현내,8004175,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,부리현내,8004175,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,부리현내,8004175,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,부리현내,8004175,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,부리현내,8004175,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,부리현내,8004175,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,부리현내,8004175,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,부리현내,8004175,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,부리현내,8004175,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,부리현내,8004175,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,부리현내,8004175,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,부리현내,8004175,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,부리현내,8004175,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,부리현내,8004175,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,부리현내,8004175,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,부리현내,8004175,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,부리현내,8004175,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 미천  [8003184]  (36.51762, 127.49627)
📍 요청 위치: (36.5176°N, 127.4963°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,미천,8003184,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,미천,8003184,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,미천,8003184,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,미천,8003184,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,미천,8003184,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,미천,8003184,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,미천,8003184,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,미천,8003184,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,미천,8003184,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,미천,8003184,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,미천,8003184,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,미천,8003184,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,미천,8003184,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,미천,8003184,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,미천,8003184,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,미천,8003184,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,미천,8003184,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,미천,8003184,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,미천,8003184,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,미천,8003184,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,미천,8003184,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,미천,8003184,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,미천,8003184,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,미천,8003184,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,미천,8003184,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,미천,8003184,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,미천,8003184,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,미천,8003184,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,미천,8003184,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,미천,8003184,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,미천,8003184,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,미천,8003184,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,미천,8003184,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,미천,8003184,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,미천,8003184,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,미천,8003184,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,미천,8003184,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,미천,8003184,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,미천,8003184,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,미천,8003184,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,미천,8003184,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,미천,8003184,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 척산  [8003193]  (36.56066, 127.43347)
📍 요청 위치: (36.5607°N, 127.4335°E)
📍 격자 좌표: (x=68, y=105)
📍 실제 위치: (36.5610°N, 127.4320°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,척산,8003193,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,척산,8003193,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,척산,8003193,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,척산,8003193,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,척산,8003193,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,척산,8003193,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,척산,8003193,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,척산,8003193,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,척산,8003193,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,척산,8003193,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,척산,8003193,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,척산,8003193,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,척산,8003193,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,척산,8003193,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,척산,8003193,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,척산,8003193,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,척산,8003193,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,척산,8003193,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,척산,8003193,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,척산,8003193,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,척산,8003193,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,척산,8003193,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,척산,8003193,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,척산,8003193,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,척산,8003193,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,척산,8003193,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,척산,8003193,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,척산,8003193,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,척산,8003193,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,척산,8003193,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,척산,8003193,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,척산,8003193,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,척산,8003193,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,척산,8003193,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,척산,8003193,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,척산,8003193,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,척산,8003193,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,척산,8003193,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,척산,8003193,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,척산,8003193,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,척산,8003193,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,척산,8003193,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 거교  [8003118]  (36.44547, 127.57925)
📍 요청 위치: (36.4455°N, 127.5793°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,거교,8003118,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,거교,8003118,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,거교,8003118,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,거교,8003118,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,거교,8003118,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,거교,8003118,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,거교,8003118,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,거교,8003118,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,거교,8003118,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,거교,8003118,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,거교,8003118,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,거교,8003118,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,거교,8003118,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,거교,8003118,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,거교,8003118,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,거교,8003118,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,거교,8003118,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,거교,8003118,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,거교,8003118,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,거교,8003118,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,거교,8003118,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,거교,8003118,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,거교,8003118,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,거교,8003118,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,거교,8003118,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,거교,8003118,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,거교,8003118,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,거교,8003118,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,거교,8003118,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,거교,8003118,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,거교,8003118,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,거교,8003118,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,거교,8003118,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,거교,8003118,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,거교,8003118,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,거교,8003118,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,거교,8003118,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,거교,8003118,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,거교,8003118,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,거교,8003118,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,거교,8003118,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,거교,8003118,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 구티  [8003120]  (36.55208, 127.73274)
📍 요청 위치: (36.5521°N, 127.7327°E)
📍 격자 좌표: (x=73, y=105)
📍 실제 위치: (36.5565°N, 127.7183°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,구티,8003120,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,구티,8003120,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,구티,8003120,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,구티,8003120,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,구티,8003120,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,구티,8003120,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,구티,8003120,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,구티,8003120,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,구티,8003120,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,구티,8003120,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,구티,8003120,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,구티,8003120,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,구티,8003120,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,구티,8003120,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,구티,8003120,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,구티,8003120,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,구티,8003120,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,구티,8003120,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,구티,8003120,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,구티,8003120,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,구티,8003120,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,구티,8003120,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,구티,8003120,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,구티,8003120,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,구티,8003120,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,구티,8003120,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,구티,8003120,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,구티,8003120,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,구티,8003120,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,구티,8003120,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,구티,8003120,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,구티,8003120,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,구티,8003120,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,구티,8003120,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,구티,8003120,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,구티,8003120,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,구티,8003120,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,구티,8003120,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,구티,8003120,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,구티,8003120,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,구티,8003120,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,구티,8003120,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 원남  [8003122]  (36.39588, 127.72779)
📍 요청 위치: (36.3959°N, 127.7278°E)
📍 격자 좌표: (x=73, y=102)
📍 실제 위치: (36.4185°N, 127.7146°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,원남,8003122,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,원남,8003122,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,원남,8003122,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,원남,8003122,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,원남,8003122,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,원남,8003122,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,원남,8003122,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,원남,8003122,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,원남,8003122,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,원남,8003122,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,원남,8003122,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,원남,8003122,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,원남,8003122,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,원남,8003122,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,원남,8003122,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,원남,8003122,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,원남,8003122,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,원남,8003122,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,원남,8003122,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,원남,8003122,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,원남,8003122,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,원남,8003122,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,원남,8003122,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,원남,8003122,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,원남,8003122,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,원남,8003122,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,원남,8003122,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,원남,8003122,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,원남,8003122,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,원남,8003122,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,원남,8003122,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,원남,8003122,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,원남,8003122,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,원남,8003122,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,원남,8003122,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,원남,8003122,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,원남,8003122,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,원남,8003122,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,원남,8003122,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,원남,8003122,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,원남,8003122,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,원남,8003122,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장안  [8004931]  (36.4698, 127.78879)
📍 요청 위치: (36.4698°N, 127.7888°E)
📍 격자 좌표: (x=74, y=103)
📍 실제 위치: (36.4635°N, 127.7730°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장안,8004931,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,장안,8004931,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,장안,8004931,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,장안,8004931,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,장안,8004931,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,장안,8004931,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,장안,8004931,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,장안,8004931,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,장안,8004931,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,장안,8004931,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,장안,8004931,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,장안,8004931,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,장안,8004931,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,장안,8004931,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,장안,8004931,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,장안,8004931,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,장안,8004931,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,장안,8004931,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,장안,8004931,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,장안,8004931,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,장안,8004931,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,장안,8004931,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,장안,8004931,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,장안,8004931,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,장안,8004931,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,장안,8004931,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,장안,8004931,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,장안,8004931,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,장안,8004931,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,장안,8004931,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,장안,8004931,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,장안,8004931,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,장안,8004931,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,장안,8004931,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,장안,8004931,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,장안,8004931,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,장안,8004931,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,장안,8004931,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,장안,8004931,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,장안,8004931,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,장안,8004931,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,장안,8004931,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 하장  [8003127]  (36.43072, 127.79613)
📍 요청 위치: (36.4307°N, 127.7961°E)
📍 격자 좌표: (x=74, y=102)
📍 실제 위치: (36.4175°N, 127.7717°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,하장,8003127,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,하장,8003127,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,하장,8003127,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,하장,8003127,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,하장,8003127,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,하장,8003127,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,하장,8003127,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,하장,8003127,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,하장,8003127,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,하장,8003127,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,하장,8003127,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,하장,8003127,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,하장,8003127,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,하장,8003127,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,하장,8003127,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,하장,8003127,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,하장,8003127,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,하장,8003127,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,하장,8003127,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,하장,8003127,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,하장,8003127,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,하장,8003127,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,하장,8003127,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,하장,8003127,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,하장,8003127,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,하장,8003127,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,하장,8003127,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,하장,8003127,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,하장,8003127,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,하장,8003127,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,하장,8003127,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,하장,8003127,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,하장,8003127,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,하장,8003127,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,하장,8003127,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,하장,8003127,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,하장,8003127,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,하장,8003127,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,하장,8003127,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,하장,8003127,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,하장,8003127,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,하장,8003127,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 후평  [8003128]  (36.47938, 127.69875)
📍 요청 위치: (36.4794°N, 127.6988°E)
📍 격자 좌표: (x=73, y=103)
📍 실제 위치: (36.4645°N, 127.7158°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,후평,8003128,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,후평,8003128,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,후평,8003128,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,후평,8003128,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,후평,8003128,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,후평,8003128,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,후평,8003128,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,후평,8003128,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,후평,8003128,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,후평,8003128,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,후평,8003128,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,후평,8003128,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,후평,8003128,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,후평,8003128,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,후평,8003128,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,후평,8003128,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,후평,8003128,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,후평,8003128,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,후평,8003128,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,후평,8003128,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,후평,8003128,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,후평,8003128,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,후평,8003128,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,후평,8003128,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,후평,8003128,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,후평,8003128,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,후평,8003128,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,후평,8003128,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,후평,8003128,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,후평,8003128,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,후평,8003128,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,후평,8003128,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,후평,8003128,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,후평,8003128,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,후평,8003128,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,후평,8003128,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,후평,8003128,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,후평,8003128,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,후평,8003128,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,후평,8003128,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,후평,8003128,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,후평,8003128,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산계  [8003148]  (36.32704, 127.75947)
📍 요청 위치: (36.3270°N, 127.7595°E)
📍 격자 좌표: (x=74, y=100)
📍 실제 위치: (36.3256°N, 127.7692°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산계,8003148,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,산계,8003148,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,산계,8003148,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,산계,8003148,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,산계,8003148,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,산계,8003148,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,산계,8003148,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,산계,8003148,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,산계,8003148,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,산계,8003148,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,산계,8003148,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,산계,8003148,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,산계,8003148,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,산계,8003148,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,산계,8003148,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,산계,8003148,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,산계,8003148,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,산계,8003148,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,산계,8003148,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,산계,8003148,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,산계,8003148,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,산계,8003148,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,산계,8003148,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,산계,8003148,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,산계,8003148,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,산계,8003148,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,산계,8003148,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,산계,8003148,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,산계,8003148,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,산계,8003148,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,산계,8003148,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,산계,8003148,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,산계,8003148,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,산계,8003148,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,산계,8003148,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,산계,8003148,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,산계,8003148,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,산계,8003148,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,산계,8003148,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,산계,8003148,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,산계,8003148,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,산계,8003148,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 삼양  [8003149]  (36.30664, 127.57154)
📍 요청 위치: (36.3066°N, 127.5715°E)
📍 격자 좌표: (x=71, y=100)
📍 실제 위치: (36.3285°N, 127.5980°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,삼양,8003149,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,삼양,8003149,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,삼양,8003149,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,삼양,8003149,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,삼양,8003149,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,삼양,8003149,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,삼양,8003149,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,삼양,8003149,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,삼양,8003149,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,삼양,8003149,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,삼양,8003149,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,삼양,8003149,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,삼양,8003149,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,삼양,8003149,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,삼양,8003149,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,삼양,8003149,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,삼양,8003149,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,삼양,8003149,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,삼양,8003149,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,삼양,8003149,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,삼양,8003149,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,삼양,8003149,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,삼양,8003149,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,삼양,8003149,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,삼양,8003149,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,삼양,8003149,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,삼양,8003149,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,삼양,8003149,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,삼양,8003149,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,삼양,8003149,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,삼양,8003149,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,삼양,8003149,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,삼양,8003149,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,삼양,8003149,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,삼양,8003149,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,삼양,8003149,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,삼양,8003149,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,삼양,8003149,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,삼양,8003149,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,삼양,8003149,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,삼양,8003149,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,삼양,8003149,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가곡  [8003129]  (36.12233, 127.66902)
📍 요청 위치: (36.1223°N, 127.6690°E)
📍 격자 좌표: (x=72, y=96)
📍 실제 위치: (36.1437°N, 127.6504°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가곡,8003129,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,가곡,8003129,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,가곡,8003129,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,가곡,8003129,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,가곡,8003129,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,가곡,8003129,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,가곡,8003129,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,가곡,8003129,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,가곡,8003129,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,가곡,8003129,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,가곡,8003129,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,가곡,8003129,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,가곡,8003129,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,가곡,8003129,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,가곡,8003129,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,가곡,8003129,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,가곡,8003129,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,가곡,8003129,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,가곡,8003129,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,가곡,8003129,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,가곡,8003129,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,가곡,8003129,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,가곡,8003129,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,가곡,8003129,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,가곡,8003129,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,가곡,8003129,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,가곡,8003129,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,가곡,8003129,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,가곡,8003129,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,가곡,8003129,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,가곡,8003129,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,가곡,8003129,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,가곡,8003129,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,가곡,8003129,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,가곡,8003129,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,가곡,8003129,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,가곡,8003129,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,가곡,8003129,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,가곡,8003129,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,가곡,8003129,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,가곡,8003129,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,가곡,8003129,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계산  [8003130]  (36.17515, 127.78376)
📍 요청 위치: (36.1752°N, 127.7838°E)
📍 격자 좌표: (x=74, y=97)
📍 실제 위치: (36.1877°N, 127.7654°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계산,8003130,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,계산,8003130,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,계산,8003130,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,계산,8003130,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,계산,8003130,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,계산,8003130,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,계산,8003130,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,계산,8003130,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,계산,8003130,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,계산,8003130,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,계산,8003130,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,계산,8003130,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,계산,8003130,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,계산,8003130,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,계산,8003130,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,계산,8003130,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,계산,8003130,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,계산,8003130,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,계산,8003130,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,계산,8003130,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,계산,8003130,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,계산,8003130,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,계산,8003130,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,계산,8003130,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,계산,8003130,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,계산,8003130,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,계산,8003130,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,계산,8003130,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,계산,8003130,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,계산,8003130,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,계산,8003130,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,계산,8003130,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,계산,8003130,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,계산,8003130,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,계산,8003130,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,계산,8003130,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,계산,8003130,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,계산,8003130,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,계산,8003130,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,계산,8003130,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,계산,8003130,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,계산,8003130,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남성  [8003134]  (36.22851, 127.91031)
📍 요청 위치: (36.2285°N, 127.9103°E)
📍 격자 좌표: (x=77, y=98)
📍 실제 위치: (36.2305°N, 127.9376°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남성,8003134,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,남성,8003134,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,남성,8003134,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,남성,8003134,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,남성,8003134,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,남성,8003134,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,남성,8003134,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,남성,8003134,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,남성,8003134,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,남성,8003134,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,남성,8003134,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,남성,8003134,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,남성,8003134,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,남성,8003134,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,남성,8003134,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,남성,8003134,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,남성,8003134,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,남성,8003134,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,남성,8003134,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,남성,8003134,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,남성,8003134,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,남성,8003134,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,남성,8003134,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,남성,8003134,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,남성,8003134,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,남성,8003134,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,남성,8003134,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,남성,8003134,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,남성,8003134,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,남성,8003134,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,남성,8003134,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,남성,8003134,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,남성,8003134,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,남성,8003134,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,남성,8003134,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,남성,8003134,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,남성,8003134,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,남성,8003134,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,남성,8003134,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,남성,8003134,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,남성,8003134,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,남성,8003134,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노천  [8003135]  (36.19089, 127.93212)
📍 요청 위치: (36.1909°N, 127.9321°E)
📍 격자 좌표: (x=77, y=97)
📍 실제 위치: (36.1845°N, 127.9362°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노천,8003135,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,노천,8003135,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,노천,8003135,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,노천,8003135,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,노천,8003135,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,노천,8003135,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,노천,8003135,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,노천,8003135,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,노천,8003135,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,노천,8003135,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,노천,8003135,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,노천,8003135,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,노천,8003135,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,노천,8003135,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,노천,8003135,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,노천,8003135,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,노천,8003135,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,노천,8003135,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,노천,8003135,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,노천,8003135,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,노천,8003135,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,노천,8003135,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,노천,8003135,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,노천,8003135,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,노천,8003135,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,노천,8003135,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,노천,8003135,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,노천,8003135,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,노천,8003135,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,노천,8003135,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,노천,8003135,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,노천,8003135,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,노천,8003135,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,노천,8003135,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,노천,8003135,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,노천,8003135,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,노천,8003135,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,노천,8003135,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,노천,8003135,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,노천,8003135,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,노천,8003135,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,노천,8003135,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서산  [8003138]  (36.09938, 127.68486)
📍 요청 위치: (36.0994°N, 127.6849°E)
📍 격자 좌표: (x=73, y=95)
📍 실제 위치: (36.0968°N, 127.7061°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서산,8003138,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,서산,8003138,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,서산,8003138,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,서산,8003138,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,서산,8003138,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,서산,8003138,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,서산,8003138,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,서산,8003138,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,서산,8003138,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,서산,8003138,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,서산,8003138,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,서산,8003138,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,서산,8003138,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,서산,8003138,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,서산,8003138,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,서산,8003138,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,서산,8003138,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,서산,8003138,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,서산,8003138,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,서산,8003138,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,서산,8003138,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,서산,8003138,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,서산,8003138,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,서산,8003138,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,서산,8003138,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,서산,8003138,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,서산,8003138,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,서산,8003138,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,서산,8003138,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,서산,8003138,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,서산,8003138,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,서산,8003138,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,서산,8003138,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,서산,8003138,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,서산,8003138,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,서산,8003138,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,서산,8003138,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,서산,8003138,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,서산,8003138,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,서산,8003138,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,서산,8003138,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,서산,8003138,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 심천  [8003139]  (36.23826, 127.72172)
📍 요청 위치: (36.2383°N, 127.7217°E)
📍 격자 좌표: (x=73, y=98)
📍 실제 위치: (36.2347°N, 127.7097°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,심천,8003139,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,심천,8003139,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,심천,8003139,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,심천,8003139,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,심천,8003139,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,심천,8003139,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,심천,8003139,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,심천,8003139,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,심천,8003139,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,심천,8003139,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,심천,8003139,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,심천,8003139,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,심천,8003139,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,심천,8003139,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,심천,8003139,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,심천,8003139,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,심천,8003139,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,심천,8003139,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,심천,8003139,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,심천,8003139,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,심천,8003139,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,심천,8003139,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,심천,8003139,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,심천,8003139,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,심천,8003139,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,심천,8003139,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,심천,8003139,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,심천,8003139,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,심천,8003139,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,심천,8003139,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,심천,8003139,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,심천,8003139,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,심천,8003139,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,심천,8003139,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,심천,8003139,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,심천,8003139,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,심천,8003139,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,심천,8003139,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,심천,8003139,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,심천,8003139,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,심천,8003139,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,심천,8003139,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용화  [8003140]  (36.02082, 127.76731)
📍 요청 위치: (36.0208°N, 127.7673°E)
📍 격자 좌표: (x=74, y=93)
📍 실제 위치: (36.0040°N, 127.7604°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용화,8003140,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,용화,8003140,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,용화,8003140,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,용화,8003140,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,용화,8003140,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,용화,8003140,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,용화,8003140,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,용화,8003140,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,용화,8003140,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,용화,8003140,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,용화,8003140,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,용화,8003140,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,용화,8003140,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,용화,8003140,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,용화,8003140,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,용화,8003140,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,용화,8003140,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,용화,8003140,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,용화,8003140,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,용화,8003140,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,용화,8003140,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,용화,8003140,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,용화,8003140,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,용화,8003140,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,용화,8003140,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,용화,8003140,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,용화,8003140,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,용화,8003140,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,용화,8003140,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,용화,8003140,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,용화,8003140,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,용화,8003140,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,용화,8003140,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,용화,8003140,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,용화,8003140,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,용화,8003140,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,용화,8003140,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,용화,8003140,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,용화,8003140,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,용화,8003140,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,용화,8003140,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,용화,8003140,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 임산  [8004770]  (36.14876, 127.91411)
📍 요청 위치: (36.1488°N, 127.9141°E)
📍 격자 좌표: (x=77, y=96)
📍 실제 위치: (36.1386°N, 127.9348°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,임산,8004770,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,임산,8004770,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,임산,8004770,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,임산,8004770,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,임산,8004770,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,임산,8004770,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,임산,8004770,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,임산,8004770,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,임산,8004770,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,임산,8004770,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,임산,8004770,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,임산,8004770,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,임산,8004770,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,임산,8004770,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,임산,8004770,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,임산,8004770,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,임산,8004770,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,임산,8004770,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,임산,8004770,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,임산,8004770,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,임산,8004770,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,임산,8004770,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,임산,8004770,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,임산,8004770,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,임산,8004770,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,임산,8004770,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,임산,8004770,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,임산,8004770,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,임산,8004770,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,임산,8004770,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,임산,8004770,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,임산,8004770,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,임산,8004770,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,임산,8004770,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,임산,8004770,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,임산,8004770,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,임산,8004770,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,임산,8004770,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,임산,8004770,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,임산,8004770,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,임산,8004770,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,임산,8004770,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 백련사  [8005924]  (35.86042, 127.7653)
📍 요청 위치: (35.8604°N, 127.7653°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,백련사,8005924,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,백련사,8005924,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,백련사,8005924,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,백련사,8005924,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,백련사,8005924,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,백련사,8005924,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,백련사,8005924,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,백련사,8005924,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,백련사,8005924,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,백련사,8005924,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,백련사,8005924,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,백련사,8005924,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,백련사,8005924,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,백련사,8005924,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,백련사,8005924,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,백련사,8005924,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,백련사,8005924,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,백련사,8005924,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,백련사,8005924,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,백련사,8005924,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,백련사,8005924,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,백련사,8005924,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,백련사,8005924,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,백련사,8005924,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,백련사,8005924,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,백련사,8005924,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,백련사,8005924,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,백련사,8005924,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,백련사,8005924,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,백련사,8005924,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,백련사,8005924,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,백련사,8005924,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,백련사,8005924,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,백련사,8005924,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,백련사,8005924,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,백련사,8005924,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,백련사,8005924,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,백련사,8005924,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,백련사,8005924,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,백련사,8005924,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,백련사,8005924,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,백련사,8005924,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 안성1  [8005925]  (35.83139, 127.73694)
📍 요청 위치: (35.8314°N, 127.7369°E)
📍 격자 좌표: (x=74, y=89)
📍 실제 위치: (35.8203°N, 127.7554°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,안성1,8005925,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,안성1,8005925,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,안성1,8005925,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,안성1,8005925,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,안성1,8005925,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,안성1,8005925,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,안성1,8005925,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,안성1,8005925,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,안성1,8005925,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,안성1,8005925,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,안성1,8005925,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,안성1,8005925,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,안성1,8005925,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,안성1,8005925,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,안성1,8005925,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,안성1,8005925,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,안성1,8005925,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,안성1,8005925,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,안성1,8005925,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,안성1,8005925,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,안성1,8005925,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,안성1,8005925,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,안성1,8005925,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,안성1,8005925,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,안성1,8005925,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,안성1,8005925,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,안성1,8005925,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,안성1,8005925,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,안성1,8005925,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,안성1,8005925,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,안성1,8005925,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,안성1,8005925,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,안성1,8005925,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,안성1,8005925,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,안성1,8005925,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,안성1,8005925,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,안성1,8005925,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,안성1,8005925,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,안성1,8005925,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,안성1,8005925,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,안성1,8005925,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,안성1,8005925,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 월음령  [8005928]  (35.87109, 127.78567)
📍 요청 위치: (35.8711°N, 127.7857°E)
📍 격자 좌표: (x=75, y=90)
📍 실제 위치: (35.8652°N, 127.8133°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,월음령,8005928,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,월음령,8005928,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,월음령,8005928,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,월음령,8005928,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,월음령,8005928,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,월음령,8005928,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,월음령,8005928,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,월음령,8005928,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,월음령,8005928,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,월음령,8005928,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,월음령,8005928,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,월음령,8005928,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,월음령,8005928,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,월음령,8005928,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,월음령,8005928,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,월음령,8005928,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,월음령,8005928,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,월음령,8005928,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,월음령,8005928,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,월음령,8005928,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,월음령,8005928,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,월음령,8005928,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,월음령,8005928,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,월음령,8005928,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,월음령,8005928,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,월음령,8005928,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,월음령,8005928,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,월음령,8005928,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,월음령,8005928,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,월음령,8005928,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,월음령,8005928,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,월음령,8005928,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,월음령,8005928,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,월음령,8005928,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,월음령,8005928,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,월음령,8005928,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,월음령,8005928,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,월음령,8005928,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,월음령,8005928,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,월음령,8005928,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,월음령,8005928,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,월음령,8005928,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 적상산  [8005931]  (35.9563, 127.69843)
📍 요청 위치: (35.9563°N, 127.6984°E)
📍 격자 좌표: (x=73, y=92)
📍 실제 위치: (35.9590°N, 127.7024°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,적상산,8005931,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,적상산,8005931,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,적상산,8005931,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,적상산,8005931,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,적상산,8005931,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,적상산,8005931,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,적상산,8005931,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,적상산,8005931,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,적상산,8005931,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,적상산,8005931,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,적상산,8005931,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,적상산,8005931,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,적상산,8005931,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,적상산,8005931,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,적상산,8005931,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,적상산,8005931,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,적상산,8005931,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,적상산,8005931,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,적상산,8005931,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,적상산,8005931,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,적상산,8005931,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,적상산,8005931,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,적상산,8005931,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,적상산,8005931,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,적상산,8005931,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,적상산,8005931,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,적상산,8005931,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,적상산,8005931,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,적상산,8005931,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,적상산,8005931,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,적상산,8005931,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,적상산,8005931,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,적상산,8005931,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,적상산,8005931,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,적상산,8005931,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,적상산,8005931,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,적상산,8005931,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,적상산,8005931,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,적상산,8005931,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,적상산,8005931,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,적상산,8005931,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,적상산,8005931,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 문장대  [8007924]  (36.56679, 127.86211)
📍 요청 위치: (36.5668°N, 127.8621°E)
📍 격자 좌표: (x=76, y=105)
📍 실제 위치: (36.5534°N, 127.8900°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,문장대,8007924,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,문장대,8007924,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,문장대,8007924,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,문장대,8007924,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,문장대,8007924,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,문장대,8007924,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,문장대,8007924,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,문장대,8007924,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,문장대,8007924,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,문장대,8007924,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,문장대,8007924,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,문장대,8007924,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,문장대,8007924,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,문장대,8007924,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,문장대,8007924,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,문장대,8007924,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,문장대,8007924,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,문장대,8007924,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,문장대,8007924,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,문장대,8007924,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,문장대,8007924,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,문장대,8007924,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,문장대,8007924,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,문장대,8007924,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,문장대,8007924,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,문장대,8007924,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,문장대,8007924,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,문장대,8007924,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,문장대,8007924,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,문장대,8007924,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,문장대,8007924,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,문장대,8007924,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,문장대,8007924,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,문장대,8007924,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,문장대,8007924,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,문장대,8007924,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,문장대,8007924,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,문장대,8007924,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,문장대,8007924,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,문장대,8007924,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,문장대,8007924,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,문장대,8007924,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(법주분교)  [1004410]  (36.51027778, 127.8063889)
📍 요청 위치: (36.5103°N, 127.8064°E)
📍 격자 좌표: (x=75, y=104)
📍 실제 위치: (36.5085°N, 127.8315°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(법주분교),1004410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(법주분교),1004410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(법주분교),1004410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(법주분교),1004410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(법주분교),1004410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(법주분교),1004410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(법주분교),1004410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(법주분교),1004410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(법주분교),1004410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(법주분교),1004410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(법주분교),1004410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(법주분교),1004410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(법주분교),1004410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(법주분교),1004410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(법주분교),1004410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(법주분교),1004410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(법주분교),1004410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(법주분교),1004410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(법주분교),1004410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(법주분교),1004410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(법주분교),1004410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(법주분교),1004410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(법주분교),1004410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(법주분교),1004410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(법주분교),1004410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(법주분교),1004410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(법주분교),1004410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(법주분교),1004410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(법주분교),1004410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(법주분교),1004410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(법주분교),1004410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(법주분교),1004410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(법주분교),1004410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(법주분교),1004410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(법주분교),1004410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(법주분교),1004410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(법주분교),1004410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(법주분교),1004410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(법주분교),1004410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(법주분교),1004410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(법주분교),1004410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(법주분교),1004410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(법주사)  [1004430]  (36.54083333, 127.8325)
📍 요청 위치: (36.5408°N, 127.8325°E)
📍 격자 좌표: (x=75, y=105)
📍 실제 위치: (36.5545°N, 127.8328°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(법주사),1004430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(법주사),1004430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(법주사),1004430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(법주사),1004430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(법주사),1004430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(법주사),1004430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(법주사),1004430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(법주사),1004430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(법주사),1004430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(법주사),1004430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(법주사),1004430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(법주사),1004430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(법주사),1004430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(법주사),1004430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(법주사),1004430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(법주사),1004430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(법주사),1004430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(법주사),1004430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(법주사),1004430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(법주사),1004430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(법주사),1004430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(법주사),1004430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(법주사),1004430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(법주사),1004430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(법주사),1004430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(법주사),1004430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(법주사),1004430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(법주사),1004430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(법주사),1004430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(법주사),1004430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(법주사),1004430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(법주사),1004430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(법주사),1004430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(법주사),1004430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(법주사),1004430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(법주사),1004430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(법주사),1004430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(법주사),1004430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(법주사),1004430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(법주사),1004430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(법주사),1004430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(법주사),1004430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(탁주리)  [9000133]  (36.56972222, 127.7488889)
📍 요청 위치: (36.5697°N, 127.7489°E)
📍 격자 좌표: (x=74, y=105)
📍 실제 위치: (36.5555°N, 127.7755°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(탁주리),9000133,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(탁주리),9000133,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(탁주리),9000133,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(탁주리),9000133,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(탁주리),9000133,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(탁주리),9000133,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(탁주리),9000133,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(탁주리),9000133,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(탁주리),9000133,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(탁주리),9000133,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(탁주리),9000133,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(탁주리),9000133,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(탁주리),9000133,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(탁주리),9000133,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(탁주리),9000133,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(탁주리),9000133,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(탁주리),9000133,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(탁주리),9000133,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(탁주리),9000133,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(탁주리),9000133,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(탁주리),9000133,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(탁주리),9000133,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(탁주리),9000133,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(탁주리),9000133,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(탁주리),9000133,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(탁주리),9000133,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(탁주리),9000133,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(탁주리),9000133,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(탁주리),9000133,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(탁주리),9000133,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(탁주리),9000133,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(탁주리),9000133,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(탁주리),9000133,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(탁주리),9000133,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(탁주리),9000133,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(탁주리),9000133,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(탁주리),9000133,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(탁주리),9000133,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(탁주리),9000133,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(탁주리),9000133,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(탁주리),9000133,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(탁주리),9000133,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(하송리)  [2008430]  (36.47138889, 127.9663889)
📍 요청 위치: (36.4714°N, 127.9664°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(하송리),2008430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(하송리),2008430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(하송리),2008430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(하송리),2008430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(하송리),2008430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(하송리),2008430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(하송리),2008430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(하송리),2008430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(하송리),2008430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(하송리),2008430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(하송리),2008430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(하송리),2008430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(하송리),2008430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(하송리),2008430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(하송리),2008430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(하송리),2008430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(하송리),2008430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(하송리),2008430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(하송리),2008430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(하송리),2008430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(하송리),2008430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(하송리),2008430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(하송리),2008430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(하송리),2008430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(하송리),2008430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(하송리),2008430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(하송리),2008430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(하송리),2008430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(하송리),2008430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(하송리),2008430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(하송리),2008430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(하송리),2008430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(하송리),2008430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(하송리),2008430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(하송리),2008430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(하송리),2008430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(하송리),2008430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(하송리),2008430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(하송리),2008430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(하송리),2008430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(하송리),2008430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(하송리),2008430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화북초교)  [2006440]  (36.56666667, 127.9119444)
📍 요청 위치: (36.5667°N, 127.9119°E)
📍 격자 좌표: (x=76, y=105)
📍 실제 위치: (36.5534°N, 127.8900°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화북초교),2006440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(화북초교),2006440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(화북초교),2006440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(화북초교),2006440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(화북초교),2006440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(화북초교),2006440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(화북초교),2006440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(화북초교),2006440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(화북초교),2006440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(화북초교),2006440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(화북초교),2006440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(화북초교),2006440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(화북초교),2006440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(화북초교),2006440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(화북초교),2006440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(화북초교),2006440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(화북초교),2006440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(화북초교),2006440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(화북초교),2006440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(화북초교),2006440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(화북초교),2006440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(화북초교),2006440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(화북초교),2006440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(화북초교),2006440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(화북초교),2006440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(화북초교),2006440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(화북초교),2006440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(화북초교),2006440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(화북초교),2006440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(화북초교),2006440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(화북초교),2006440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(화북초교),2006440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(화북초교),2006440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(화북초교),2006440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(화북초교),2006440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(화북초교),2006440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(화북초교),2006440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(화북초교),2006440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(화북초교),2006440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(화북초교),2006440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(화북초교),2006440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(화북초교),2006440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(안성초교)  [3001410]  (35.86555556, 127.655)
📍 요청 위치: (35.8656°N, 127.6550°E)
📍 격자 좌표: (x=72, y=90)
📍 실제 위치: (35.8682°N, 127.6434°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(안성초교),3001410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(안성초교),3001410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(안성초교),3001410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(안성초교),3001410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(안성초교),3001410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(안성초교),3001410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(안성초교),3001410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(안성초교),3001410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(안성초교),3001410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(안성초교),3001410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(안성초교),3001410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(안성초교),3001410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(안성초교),3001410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(안성초교),3001410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(안성초교),3001410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(안성초교),3001410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(안성초교),3001410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(안성초교),3001410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(안성초교),3001410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(안성초교),3001410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(안성초교),3001410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(안성초교),3001410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(안성초교),3001410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(안성초교),3001410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(안성초교),3001410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(안성초교),3001410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(안성초교),3001410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(안성초교),3001410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(안성초교),3001410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(안성초교),3001410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(안성초교),3001410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(안성초교),3001410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(안성초교),3001410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(안성초교),3001410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(안성초교),3001410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(안성초교),3001410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(안성초교),3001410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(안성초교),3001410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(안성초교),3001410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(안성초교),3001410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(안성초교),3001410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(안성초교),3001410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(무주중앙초교)  [3003452]  (36.01194444, 127.6630556)
📍 요청 위치: (36.0119°N, 127.6631°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(무주중앙초교),3003452,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(무주중앙초교),3003452,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(무주중앙초교),3003452,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(무주중앙초교),3003452,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(무주중앙초교),3003452,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(무주중앙초교),3003452,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(적상초교)  [3003420]  (35.93166667, 127.6566667)
📍 요청 위치: (35.9317°N, 127.6567°E)
📍 격자 좌표: (x=72, y=91)
📍 실제 위치: (35.9141°N, 127.6445°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(적상초교),3003420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(적상초교),3003420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(적상초교),3003420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(적상초교),3003420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(적상초교),3003420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(적상초교),3003420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(적상초교),3003420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(적상초교),3003420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(적상초교),3003420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(적상초교),3003420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(적상초교),3003420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(적상초교),3003420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(적상초교),3003420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(적상초교),3003420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(적상초교),3003420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(적상초교),3003420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(적상초교),3003420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(적상초교),3003420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(적상초교),3003420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(적상초교),3003420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(적상초교),3003420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(적상초교),3003420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(적상초교),3003420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(적상초교),3003420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(적상초교),3003420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(적상초교),3003420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(적상초교),3003420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(적상초교),3003420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(적상초교),3003420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(적상초교),3003420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(적상초교),3003420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(적상초교),3003420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(적상초교),3003420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(적상초교),3003420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(적상초교),3003420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(적상초교),3003420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(적상초교),3003420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(적상초교),3003420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(적상초교),3003420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(적상초교),3003420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(적상초교),3003420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(적상초교),3003420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(구천정수장)  [3003454]  (35.88583333, 127.7769444)
📍 요청 위치: (35.8858°N, 127.7769°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(구천정수장),3003454,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(구천정수장),3003454,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(구천정수장),3003454,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(구천정수장),3003454,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(구천정수장),3003454,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(구천정수장),3003454,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(구천정수장),3003454,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(구천정수장),3003454,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(구천정수장),3003454,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(구천정수장),3003454,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(구천정수장),3003454,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(구천정수장),3003454,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(구천정수장),3003454,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(구천정수장),3003454,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(구천정수장),3003454,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(구천정수장),3003454,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(구천정수장),3003454,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(삼포리)  [3005452]  (36.33861111, 127.9577778)
📍 요청 위치: (36.3386°N, 127.9578°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(삼포리),3005452,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(삼포리),3005452,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(삼포리),3005452,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(삼포리),3005452,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(삼포리),3005452,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(삼포리),3005452,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(삼포리),3005452,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(삼포리),3005452,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(삼포리),3005452,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(삼포리),3005452,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(삼포리),3005452,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(삼포리),3005452,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(삼포리),3005452,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(삼포리),3005452,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(삼포리),3005452,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(삼포리),3005452,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(삼포리),3005452,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(삼포리),3005452,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(삼포리),3005452,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(삼포리),3005452,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(삼포리),3005452,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(삼포리),3005452,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(삼포리),3005452,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(삼포리),3005452,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(삼포리),3005452,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(삼포리),3005452,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(삼포리),3005452,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(삼포리),3005452,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(삼포리),3005452,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(삼포리),3005452,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(삼포리),3005452,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(삼포리),3005452,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(삼포리),3005452,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(삼포리),3005452,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(삼포리),3005452,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(삼포리),3005452,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(삼포리),3005452,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(삼포리),3005452,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(삼포리),3005452,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(삼포리),3005452,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(삼포리),3005452,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(삼포리),3005452,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(궁촌리)  [3005454]  (36.10777778, 127.9175)
📍 요청 위치: (36.1078°N, 127.9175°E)
📍 격자 좌표: (x=77, y=95)
📍 실제 위치: (36.0927°N, 127.9334°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(궁촌리),3005454,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(궁촌리),3005454,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(궁촌리),3005454,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(궁촌리),3005454,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(궁촌리),3005454,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(궁촌리),3005454,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(궁촌리),3005454,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(궁촌리),3005454,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(궁촌리),3005454,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(궁촌리),3005454,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(궁촌리),3005454,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(궁촌리),3005454,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(궁촌리),3005454,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(궁촌리),3005454,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(궁촌리),3005454,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(궁촌리),3005454,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(궁촌리),3005454,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화동초교)  [3007455]  (36.39222222, 127.9519444)
📍 요청 위치: (36.3922°N, 127.9519°E)
📍 격자 좌표: (x=77, y=102)
📍 실제 위치: (36.4143°N, 127.9431°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화동초교),3007455,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(화동초교),3007455,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(화동초교),3007455,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(화동초교),3007455,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(화동초교),3007455,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(화동초교),3007455,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(화동초교),3007455,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(화동초교),3007455,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(화동초교),3007455,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(화동초교),3007455,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(화동초교),3007455,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(화동초교),3007455,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(화동초교),3007455,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(화동초교),3007455,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(화동초교),3007455,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(화동초교),3007455,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(화동초교),3007455,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(화동초교),3007455,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(화동초교),3007455,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(화동초교),3007455,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(화동초교),3007455,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(화동초교),3007455,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(화동초교),3007455,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(화동초교),3007455,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(화동초교),3007455,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(화동초교),3007455,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(화동초교),3007455,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(화동초교),3007455,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(화동초교),3007455,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(화동초교),3007455,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(화동초교),3007455,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(화동초교),3007455,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(화동초교),3007455,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(화동초교),3007455,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(화동초교),3007455,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(화동초교),3007455,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(화동초교),3007455,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(화동초교),3007455,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(화동초교),3007455,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(화동초교),3007455,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(화동초교),3007455,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(화동초교),3007455,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화령초교)  [3007450]  (36.4475, 127.9522222)
📍 요청 위치: (36.4475°N, 127.9522°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화령초교),3007450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(화령초교),3007450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(화령초교),3007450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(화령초교),3007450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(화령초교),3007450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(화령초교),3007450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(화령초교),3007450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(화령초교),3007450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(화령초교),3007450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(화령초교),3007450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(화령초교),3007450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(화령초교),3007450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(화령초교),3007450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(화령초교),3007450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(화령초교),3007450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(화령초교),3007450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(화령초교),3007450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(화령초교),3007450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(화령초교),3007450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(화령초교),3007450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(화령초교),3007450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(화령초교),3007450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(화령초교),3007450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(화령초교),3007450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(화령초교),3007450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(화령초교),3007450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(화령초교),3007450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(화령초교),3007450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(화령초교),3007450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(화령초교),3007450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(화령초교),3007450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(화령초교),3007450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(화령초교),3007450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(화령초교),3007450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(화령초교),3007450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(화령초교),3007450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(화령초교),3007450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(화령초교),3007450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(화령초교),3007450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(화령초교),3007450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(화령초교),3007450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(화령초교),3007450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(웅북리)  [3005450]  (36.25694444, 128.0202778)
📍 요청 위치: (36.2569°N, 128.0203°E)
📍 격자 좌표: (x=78, y=99)
📍 실제 위치: (36.2753°N, 127.9960°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(웅북리),3005450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(웅북리),3005450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(웅북리),3005450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(웅북리),3005450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(웅북리),3005450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(웅북리),3005450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(웅북리),3005450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(웅북리),3005450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(웅북리),3005450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(웅북리),3005450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(웅북리),3005450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(웅북리),3005450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(웅북리),3005450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(웅북리),3005450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(웅북리),3005450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(웅북리),3005450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(웅북리),3005450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(웅북리),3005450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(웅북리),3005450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(웅북리),3005450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(웅북리),3005450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(웅북리),3005450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(웅북리),3005450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(웅북리),3005450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(웅북리),3005450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(웅북리),3005450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(웅북리),3005450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(웅북리),3005450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(웅북리),3005450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(웅북리),3005450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(웅북리),3005450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(웅북리),3005450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(웅북리),3005450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(웅북리),3005450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(웅북리),3005450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(웅북리),3005450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(웅북리),3005450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(웅북리),3005450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(웅북리),3005450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(웅북리),3005450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(웅북리),3005450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(웅북리),3005450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(청산초교)  [3007477]  (36.34611111, 127.7941667)
📍 요청 위치: (36.3461°N, 127.7942°E)
📍 격자 좌표: (x=74, y=100)
📍 실제 위치: (36.3256°N, 127.7692°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(청산초교),3007477,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(청산초교),3007477,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(청산초교),3007477,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(청산초교),3007477,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(청산초교),3007477,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(청산초교),3007477,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(청산초교),3007477,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(청산초교),3007477,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(청산초교),3007477,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(청산초교),3007477,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(청산초교),3007477,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(청산초교),3007477,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(청산초교),3007477,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(청산초교),3007477,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(청산초교),3007477,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(청산초교),3007477,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(청산초교),3007477,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(삼산초교)  [3007483]  (36.485, 127.7166667)
📍 요청 위치: (36.4850°N, 127.7167°E)
📍 격자 좌표: (x=73, y=103)
📍 실제 위치: (36.4645°N, 127.7158°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(삼산초교),3007483,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(삼산초교),3007483,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(삼산초교),3007483,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(삼산초교),3007483,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(삼산초교),3007483,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(삼산초교),3007483,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(삼산초교),3007483,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(삼산초교),3007483,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(삼산초교),3007483,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(삼산초교),3007483,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(삼산초교),3007483,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(삼산초교),3007483,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(삼산초교),3007483,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(삼산초교),3007483,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(삼산초교),3007483,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(삼산초교),3007483,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(삼산초교),3007483,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(관기초교)  [3007479]  (36.43555556, 127.8219444)
📍 요청 위치: (36.4356°N, 127.8219°E)
📍 격자 좌표: (x=75, y=102)
📍 실제 위치: (36.4165°N, 127.8288°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(관기초교),3007479,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(관기초교),3007479,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(관기초교),3007479,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(관기초교),3007479,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(관기초교),3007479,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(관기초교),3007479,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(관기초교),3007479,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(관기초교),3007479,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(관기초교),3007479,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(관기초교),3007479,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(관기초교),3007479,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(관기초교),3007479,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(관기초교),3007479,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(관기초교),3007479,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(관기초교),3007479,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(관기초교),3007479,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(관기초교),3007479,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(관기초교),3007479,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(관기초교),3007479,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(관기초교),3007479,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(관기초교),3007479,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(관기초교),3007479,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(관기초교),3007479,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(관기초교),3007479,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(관기초교),3007479,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(관기초교),3007479,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(관기초교),3007479,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(관기초교),3007479,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(관기초교),3007479,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(관기초교),3007479,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(관기초교),3007479,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(관기초교),3007479,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(관기초교),3007479,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(관기초교),3007479,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(관기초교),3007479,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(관기초교),3007479,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(관기초교),3007479,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(관기초교),3007479,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(관기초교),3007479,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(관기초교),3007479,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(관기초교),3007479,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(관기초교),3007479,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(도로관리사업소)  [3007435]  (36.37333333, 127.7341667)
📍 요청 위치: (36.3733°N, 127.7342°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(도로관리사업소),3007435,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(도로관리사업소),3007435,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(도로관리사업소),3007435,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(도로관리사업소),3007435,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(도로관리사업소),3007435,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(도로관리사업소),3007435,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(동정리)  [3007425]  (36.47361111, 127.6641667)
📍 요청 위치: (36.4736°N, 127.6642°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(동정리),3007425,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(동정리),3007425,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(동정리),3007425,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(동정리),3007425,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(동정리),3007425,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(동정리),3007425,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(동정리),3007425,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(동정리),3007425,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(동정리),3007425,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(동정리),3007425,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(동정리),3007425,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(동정리),3007425,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(동정리),3007425,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(동정리),3007425,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(동정리),3007425,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(동정리),3007425,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(동정리),3007425,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(동정리),3007425,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(동정리),3007425,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(동정리),3007425,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(동정리),3007425,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(동정리),3007425,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(동정리),3007425,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(동정리),3007425,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(동정리),3007425,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(동정리),3007425,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(동정리),3007425,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(동정리),3007425,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(동정리),3007425,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(동정리),3007425,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(동정리),3007425,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(동정리),3007425,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(동정리),3007425,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(동정리),3007425,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(동정리),3007425,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(동정리),3007425,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(동정리),3007425,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(동정리),3007425,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(동정리),3007425,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(동정리),3007425,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(동정리),3007425,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(동정리),3007425,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(이원리)  [3007430]  (36.54222222, 127.6777778)
📍 요청 위치: (36.5422°N, 127.6778°E)
📍 격자 좌표: (x=72, y=105)
📍 실제 위치: (36.5575°N, 127.6610°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(이원리),3007430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(이원리),3007430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(이원리),3007430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(이원리),3007430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(이원리),3007430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(이원리),3007430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(이원리),3007430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(이원리),3007430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(이원리),3007430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(이원리),3007430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(이원리),3007430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(이원리),3007430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(이원리),3007430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(이원리),3007430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(이원리),3007430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(이원리),3007430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(이원리),3007430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(이원리),3007430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(이원리),3007430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(이원리),3007430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(이원리),3007430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(이원리),3007430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(이원리),3007430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(이원리),3007430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(이원리),3007430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(이원리),3007430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(이원리),3007430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(이원리),3007430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(이원리),3007430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(이원리),3007430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(이원리),3007430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(이원리),3007430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(이원리),3007430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(이원리),3007430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(이원리),3007430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(이원리),3007430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(이원리),3007430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(이원리),3007430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(이원리),3007430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(이원리),3007430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(이원리),3007430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(이원리),3007430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(묘금리)  [3007460]  (36.27583333, 127.7322222)
📍 요청 위치: (36.2758°N, 127.7322°E)
📍 격자 좌표: (x=73, y=99)
📍 실제 위치: (36.2806°N, 127.7109°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(묘금리),3007460,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(묘금리),3007460,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(묘금리),3007460,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(묘금리),3007460,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(묘금리),3007460,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(묘금리),3007460,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(묘금리),3007460,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(묘금리),3007460,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(묘금리),3007460,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(묘금리),3007460,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(묘금리),3007460,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(묘금리),3007460,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(묘금리),3007460,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(묘금리),3007460,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(묘금리),3007460,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(묘금리),3007460,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(묘금리),3007460,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(송죽초교)  [3007440]  (36.43722222, 127.7344444)
📍 요청 위치: (36.4372°N, 127.7344°E)
📍 격자 좌표: (x=73, y=102)
📍 실제 위치: (36.4185°N, 127.7146°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(송죽초교),3007440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(송죽초교),3007440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(송죽초교),3007440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(송죽초교),3007440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(송죽초교),3007440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(송죽초교),3007440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(송죽초교),3007440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(송죽초교),3007440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(송죽초교),3007440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(송죽초교),3007440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(송죽초교),3007440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(송죽초교),3007440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(송죽초교),3007440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(송죽초교),3007440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(송죽초교),3007440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(송죽초교),3007440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(송죽초교),3007440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(삼가분교)  [3007481]  (36.49111111, 127.8608333)
📍 요청 위치: (36.4911°N, 127.8608°E)
📍 격자 좌표: (x=76, y=104)
📍 실제 위치: (36.5074°N, 127.8887°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(삼가분교),3007481,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(삼가분교),3007481,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(삼가분교),3007481,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(삼가분교),3007481,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(삼가분교),3007481,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(삼가분교),3007481,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(삼가분교),3007481,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(삼가분교),3007481,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(삼가분교),3007481,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(삼가분교),3007481,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(삼가분교),3007481,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(삼가분교),3007481,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(삼가분교),3007481,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(삼가분교),3007481,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(삼가분교),3007481,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(삼가분교),3007481,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(삼가분교),3007481,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(안내초교)  [3008420]  (36.39416667, 127.6616667)
📍 요청 위치: (36.3942°N, 127.6617°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(안내초교),3008420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(안내초교),3008420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(안내초교),3008420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(안내초교),3008420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(안내초교),3008420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(안내초교),3008420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(안내초교),3008420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(안내초교),3008420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(안내초교),3008420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(안내초교),3008420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(안내초교),3008420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(안내초교),3008420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(안내초교),3008420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(안내초교),3008420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(안내초교),3008420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(안내초교),3008420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(안내초교),3008420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
📍 요청 위치: (36.4550°N, 127.4442°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(문화재조사연구단),3008460,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(원촌교)  [3009420]  (36.37833333, 127.41)
📍 요청 위치: (36.3783°N, 127.4100°E)
📍 격자 좌표: (x=68, y=101)
📍 실제 위치: (36.3771°N, 127.4279°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(원촌교),3009420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(원촌교),3009420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(원촌교),3009420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(원촌교),3009420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(원촌교),3009420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(원촌교),3009420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(원촌교),3009420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(원촌교),3009420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(원촌교),3009420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(원촌교),3009420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(원촌교),3009420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(원촌교),3009420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(원촌교),3009420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(원촌교),3009420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(원촌교),3009420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(원촌교),3009420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(원촌교),3009420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(원촌교),3009420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(원촌교),3009420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(원촌교),3009420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(원촌교),3009420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(원촌교),3009420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(원촌교),3009420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(원촌교),3009420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(원촌교),3009420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(원촌교),3009420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(원촌교),3009420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(원촌교),3009420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(원촌교),3009420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(원촌교),3009420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(원촌교),3009420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(원촌교),3009420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
📍 요청 위치: (36.3236°N, 127.4344°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(인창교),9000121,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(인창교),9000121,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(인창교),9000121,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(인창교),9000121,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(인창교),9000121,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(인창교),9000121,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(인창교),9000121,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(인창교),9000121,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(인창교),9000121,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(인창교),9000121,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(인창교),9000121,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(인창교),9000121,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(인창교),9000121,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(인창교),9000121,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(인창교),9000121,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(인창교),9000121,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(인창교),9000121,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(인창교),9000121,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(인창교),9000121,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(인창교),9000121,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(인창교),9000121,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(인창교),9000121,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(인창교),9000121,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(인창교),9000121,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(인창교),9000121,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(인창교),9000121,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(인창교),9000121,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(인창교),9000121,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(인창교),9000121,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(인창교),9000121,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(인창교),9000121,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(인창교),9000121,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(인창교),9000121,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(인창교),9000121,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
📍 요청 위치: (36.5781°N, 127.5775°E)
📍 격자 좌표: (x=71, y=105)
📍 실제 위치: (36.5584°N, 127.6037°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(가덕초교),3011430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(가덕초교),3011430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(신괴리)  [9000027]  (35.8669444, 127.5466667)
📍 요청 위치: (35.8669°N, 127.5467°E)
📍 격자 좌표: (x=70, y=90)
📍 실제 위치: (35.8700°N, 127.5301°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(신괴리),9000027,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진안군(신괴리),9000027,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진안군(신괴리),9000027,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진안군(신괴리),9000027,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진안군(신괴리),9000027,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진안군(신괴리),9000027,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진안군(신괴리),9000027,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진안군(신괴리),9000027,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진안군(신괴리),9000027,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진안군(신괴리),9000027,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진안군(신괴리),9000027,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진안군(신괴리),9000027,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진안군(신괴리),9000027,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진안군(신괴리),9000027,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진안군(신괴리),9000027,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진안군(신괴리),9000027,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진안군(신괴리),9000027,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진안군(신괴리),9000027,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진안군(신괴리),9000027,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진안군(신괴리),9000027,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진안군(신괴리),9000027,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진안군(신괴리),9000027,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진안군(신괴리),9000027,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진안군(신괴리),9000027,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진안군(신괴리),9000027,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진안군(신괴리),9000027,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진안군(신괴리),9000027,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진안군(신괴리),9000027,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진안군(신괴리),9000027,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진안군(신괴리),9000027,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진안군(신괴리),9000027,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진안군(신괴리),9000027,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진안군(신괴리),9000027,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진안군(신괴리),9000027,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진안군(신괴리),9000027,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진안군(신괴리),9000027,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진안군(신괴리),9000027,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진안군(신괴리),9000027,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진안군(신괴리),9000027,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진안군(신괴리),9000027,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진안군(신괴리),9000027,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진안군(신괴리),9000027,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(주양리)  [9000029]  (35.9677778, 127.4261111)
📍 요청 위치: (35.9678°N, 127.4261°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(주양리),9000029,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진안군(주양리),9000029,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진안군(주양리),9000029,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진안군(주양리),9000029,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진안군(주양리),9000029,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진안군(주양리),9000029,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진안군(주양리),9000029,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진안군(주양리),9000029,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진안군(주양리),9000029,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진안군(주양리),9000029,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진안군(주양리),9000029,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진안군(주양리),9000029,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진안군(주양리),9000029,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진안군(주양리),9000029,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진안군(주양리),9000029,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진안군(주양리),9000029,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진안군(주양리),9000029,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진안군(주양리),9000029,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진안군(주양리),9000029,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진안군(주양리),9000029,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진안군(주양리),9000029,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진안군(주양리),9000029,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진안군(주양리),9000029,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진안군(주양리),9000029,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진안군(주양리),9000029,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진안군(주양리),9000029,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진안군(주양리),9000029,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진안군(주양리),9000029,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진안군(주양리),9000029,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진안군(주양리),9000029,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진안군(주양리),9000029,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진안군(주양리),9000029,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진안군(주양리),9000029,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진안군(주양리),9000029,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진안군(주양리),9000029,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진안군(주양리),9000029,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진안군(주양리),9000029,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진안군(주양리),9000029,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진안군(주양리),9000029,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진안군(주양리),9000029,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진안군(주양리),9000029,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진안군(주양리),9000029,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(삼가리)  [3003430]  (35.8930556, 127.6605556)
📍 요청 위치: (35.8931°N, 127.6606°E)
📍 격자 좌표: (x=72, y=91)
📍 실제 위치: (35.9141°N, 127.6445°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(삼가리),3003430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(삼가리),3003430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(삼가리),3003430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(삼가리),3003430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(삼가리),3003430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(삼가리),3003430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(삼가리),3003430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(삼가리),3003430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(삼가리),3003430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(삼가리),3003430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(삼가리),3003430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(삼가리),3003430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(삼가리),3003430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(삼가리),3003430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(삼가리),3003430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(삼가리),3003430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(삼가리),3003430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(삼가리),3003430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(삼가리),3003430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(삼가리),3003430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(삼가리),3003430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(삼가리),3003430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(삼가리),3003430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(삼가리),3003430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(삼가리),3003430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(삼가리),3003430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(삼가리),3003430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(삼가리),3003430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(삼가리),3003430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(삼가리),3003430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(삼가리),3003430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(삼가리),3003430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(삼가리),3003430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(삼가리),3003430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(삼가리),3003430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(삼가리),3003430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(삼가리),3003430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(삼가리),3003430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(삼가리),3003430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(삼가리),3003430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(삼가리),3003430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(삼가리),3003430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(증산리)  [3003450]  (35.9463889, 127.8472222)
📍 요청 위치: (35.9464°N, 127.8472°E)
📍 격자 좌표: (x=76, y=92)
📍 실제 위치: (35.9560°N, 127.8726°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(증산리),3003450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(증산리),3003450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(증산리),3003450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(증산리),3003450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(증산리),3003450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(증산리),3003450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(증산리),3003450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(증산리),3003450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(증산리),3003450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(증산리),3003450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(증산리),3003450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(증산리),3003450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(증산리),3003450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(증산리),3003450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(증산리),3003450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(증산리),3003450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(증산리),3003450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(증산리),3003450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(증산리),3003450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(증산리),3003450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(증산리),3003450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(증산리),3003450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(증산리),3003450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(증산리),3003450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(증산리),3003450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(증산리),3003450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(증산리),3003450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(증산리),3003450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(증산리),3003450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(증산리),3003450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(증산리),3003450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(증산리),3003450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(증산리),3003450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(증산리),3003450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(증산리),3003450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(증산리),3003450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(증산리),3003450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(증산리),3003450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(증산리),3003450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(증산리),3003450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(증산리),3003450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(증산리),3003450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(기곡리)  [3003431]  (36.0127778, 127.7180556)
📍 요청 위치: (36.0128°N, 127.7181°E)
📍 격자 좌표: (x=73, y=93)
📍 실제 위치: (36.0050°N, 127.7036°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(기곡리),3003431,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,무주군(기곡리),3003431,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,무주군(기곡리),3003431,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,무주군(기곡리),3003431,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,무주군(기곡리),3003431,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,무주군(기곡리),3003431,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,무주군(기곡리),3003431,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,무주군(기곡리),3003431,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,무주군(기곡리),3003431,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,무주군(기곡리),3003431,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,무주군(기곡리),3003431,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,무주군(기곡리),3003431,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,무주군(기곡리),3003431,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,무주군(기곡리),3003431,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,무주군(기곡리),3003431,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,무주군(기곡리),3003431,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,무주군(기곡리),3003431,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,무주군(기곡리),3003431,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,무주군(기곡리),3003431,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,무주군(기곡리),3003431,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,무주군(기곡리),3003431,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,무주군(기곡리),3003431,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,무주군(기곡리),3003431,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,무주군(기곡리),3003431,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,무주군(기곡리),3003431,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,무주군(기곡리),3003431,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,무주군(기곡리),3003431,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,무주군(기곡리),3003431,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,무주군(기곡리),3003431,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,무주군(기곡리),3003431,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,무주군(기곡리),3003431,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,무주군(기곡리),3003431,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,무주군(기곡리),3003431,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,무주군(기곡리),3003431,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,무주군(기곡리),3003431,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,무주군(기곡리),3003431,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,무주군(기곡리),3003431,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,무주군(기곡리),3003431,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,무주군(기곡리),3003431,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,무주군(기곡리),3003431,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,무주군(기곡리),3003431,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,무주군(기곡리),3003431,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(선원리)  [3004430]  (36.0705556, 127.5366667)
📍 요청 위치: (36.0706°N, 127.5367°E)
📍 격자 좌표: (x=70, y=94)
📍 실제 위치: (36.0537°N, 127.5344°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(선원리),3004430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(선원리),3004430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(선원리),3004430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(선원리),3004430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(선원리),3004430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(선원리),3004430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(선원리),3004430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(선원리),3004430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(선원리),3004430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(선원리),3004430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(선원리),3004430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(선원리),3004430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(선원리),3004430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(선원리),3004430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(선원리),3004430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(선원리),3004430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(선원리),3004430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(선원리),3004430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(선원리),3004430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(선원리),3004430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(선원리),3004430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(선원리),3004430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(선원리),3004430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(선원리),3004430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(선원리),3004430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(선원리),3004430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(선원리),3004430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(선원리),3004430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(선원리),3004430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(선원리),3004430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(선원리),3004430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(선원리),3004430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(선원리),3004430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(선원리),3004430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(선원리),3004430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(선원리),3004430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(선원리),3004430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(선원리),3004430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(선원리),3004430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(선원리),3004430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(선원리),3004430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(선원리),3004430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(산막리)  [3004440]  (36.1113889, 127.7913889)
📍 요청 위치: (36.1114°N, 127.7914°E)
📍 격자 좌표: (x=74, y=95)
📍 실제 위치: (36.0958°N, 127.7629°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(산막리),3004440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(산막리),3004440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(산막리),3004440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(산막리),3004440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(산막리),3004440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(산막리),3004440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(산막리),3004440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(산막리),3004440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(산막리),3004440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(산막리),3004440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(산막리),3004440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(산막리),3004440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(산막리),3004440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(산막리),3004440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(산막리),3004440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(산막리),3004440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(산막리),3004440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(산막리),3004440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(산막리),3004440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(산막리),3004440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(산막리),3004440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(산막리),3004440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(산막리),3004440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(산막리),3004440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(산막리),3004440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(산막리),3004440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(산막리),3004440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(산막리),3004440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(산막리),3004440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(산막리),3004440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(산막리),3004440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(산막리),3004440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(산막리),3004440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(산막리),3004440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(산막리),3004440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(산막리),3004440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(산막리),3004440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(산막리),3004440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(산막리),3004440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(산막리),3004440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(산막리),3004440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(산막리),3004440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(남성리)  [3005440]  (36.2358333, 127.9163889)
📍 요청 위치: (36.2358°N, 127.9164°E)
📍 격자 좌표: (x=77, y=98)
📍 실제 위치: (36.2305°N, 127.9376°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(남성리),3005440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(남성리),3005440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(남성리),3005440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(남성리),3005440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(남성리),3005440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(남성리),3005440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(남성리),3005440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(남성리),3005440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(남성리),3005440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(남성리),3005440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(남성리),3005440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(남성리),3005440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(남성리),3005440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(남성리),3005440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(남성리),3005440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(남성리),3005440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(남성리),3005440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(남성리),3005440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(남성리),3005440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(남성리),3005440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(남성리),3005440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(남성리),3005440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(남성리),3005440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(남성리),3005440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(남성리),3005440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(남성리),3005440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(남성리),3005440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(남성리),3005440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(남성리),3005440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(남성리),3005440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(남성리),3005440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(남성리),3005440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(남성리),3005440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(남성리),3005440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(남성리),3005440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(남성리),3005440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(남성리),3005440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(남성리),3005440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(남성리),3005440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(남성리),3005440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(남성리),3005440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(남성리),3005440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(득수리)  [9000016]  (36.3311111, 127.9002778)
📍 요청 위치: (36.3311°N, 127.9003°E)
📍 격자 좌표: (x=76, y=100)
📍 실제 위치: (36.3235°N, 127.8833°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(득수리),9000016,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,상주시(득수리),9000016,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,상주시(득수리),9000016,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,상주시(득수리),9000016,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,상주시(득수리),9000016,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,상주시(득수리),9000016,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,상주시(득수리),9000016,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,상주시(득수리),9000016,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,상주시(득수리),9000016,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,상주시(득수리),9000016,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,상주시(득수리),9000016,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,상주시(득수리),9000016,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,상주시(득수리),9000016,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,상주시(득수리),9000016,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,상주시(득수리),9000016,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,상주시(득수리),9000016,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,상주시(득수리),9000016,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,상주시(득수리),9000016,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,상주시(득수리),9000016,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,상주시(득수리),9000016,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,상주시(득수리),9000016,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,상주시(득수리),9000016,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,상주시(득수리),9000016,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,상주시(득수리),9000016,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,상주시(득수리),9000016,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,상주시(득수리),9000016,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,상주시(득수리),9000016,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,상주시(득수리),9000016,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,상주시(득수리),9000016,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,상주시(득수리),9000016,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,상주시(득수리),9000016,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,상주시(득수리),9000016,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,상주시(득수리),9000016,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,상주시(득수리),9000016,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,상주시(득수리),9000016,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,상주시(득수리),9000016,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,상주시(득수리),9000016,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,상주시(득수리),9000016,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,상주시(득수리),9000016,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,상주시(득수리),9000016,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,상주시(득수리),9000016,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,상주시(득수리),9000016,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(궁촌리2)  [9000018]  (36.3311111, 127.9288889)
📍 요청 위치: (36.3311°N, 127.9289°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(궁촌리2),9000018,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,영동군(궁촌리2),9000018,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,영동군(궁촌리2),9000018,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,영동군(궁촌리2),9000018,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,영동군(궁촌리2),9000018,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,영동군(궁촌리2),9000018,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,영동군(궁촌리2),9000018,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,영동군(궁촌리2),9000018,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,영동군(궁촌리2),9000018,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,영동군(궁촌리2),9000018,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,영동군(궁촌리2),9000018,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,영동군(궁촌리2),9000018,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,영동군(궁촌리2),9000018,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,영동군(궁촌리2),9000018,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,영동군(궁촌리2),9000018,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,영동군(궁촌리2),9000018,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,영동군(궁촌리2),9000018,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(원동리)  [3005430]  (36.2388889, 127.6525)
📍 요청 위치: (36.2389°N, 127.6525°E)
📍 격자 좌표: (x=72, y=98)
📍 실제 위치: (36.2356°N, 127.6527°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(원동리),3005430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(원동리),3005430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(원동리),3005430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(원동리),3005430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(원동리),3005430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(원동리),3005430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(원동리),3005430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(원동리),3005430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(원동리),3005430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(원동리),3005430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(원동리),3005430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(원동리),3005430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(원동리),3005430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(원동리),3005430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(원동리),3005430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(원동리),3005430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(원동리),3005430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(원동리),3005430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(원동리),3005430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(원동리),3005430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(원동리),3005430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(원동리),3005430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(원동리),3005430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(원동리),3005430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(원동리),3005430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(원동리),3005430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(원동리),3005430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(원동리),3005430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(원동리),3005430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(원동리),3005430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(원동리),3005430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(원동리),3005430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(원동리),3005430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(원동리),3005430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(원동리),3005430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(원동리),3005430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(원동리),3005430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(원동리),3005430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(원동리),3005430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(원동리),3005430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(원동리),3005430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(원동리),3005430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(구병리)  [3007487]  (36.4752778, 127.8772222)
📍 요청 위치: (36.4753°N, 127.8772°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(구병리),3007487,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(구병리),3007487,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(구병리),3007487,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(구병리),3007487,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(구병리),3007487,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(구병리),3007487,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(구병리),3007487,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(구병리),3007487,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(구병리),3007487,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(구병리),3007487,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(구병리),3007487,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(구병리),3007487,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(구병리),3007487,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(구병리),3007487,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(구병리),3007487,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(구병리),3007487,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(구병리),3007487,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(구병리),3007487,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(구병리),3007487,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(구병리),3007487,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(구병리),3007487,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(구병리),3007487,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(구병리),3007487,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(구병리),3007487,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(구병리),3007487,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(구병리),3007487,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(구병리),3007487,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(구병리),3007487,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(구병리),3007487,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(구병리),3007487,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(구병리),3007487,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(구병리),3007487,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(구병리),3007487,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(구병리),3007487,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(구병리),3007487,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(구병리),3007487,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(구병리),3007487,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(구병리),3007487,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(구병리),3007487,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(구병리),3007487,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(구병리),3007487,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(구병리),3007487,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(신함리)  [3007470]  (36.5166667, 127.7272222)
📍 요청 위치: (36.5167°N, 127.7272°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(신함리),3007470,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보은군(신함리),3007470,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보은군(신함리),3007470,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보은군(신함리),3007470,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보은군(신함리),3007470,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보은군(신함리),3007470,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보은군(신함리),3007470,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보은군(신함리),3007470,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보은군(신함리),3007470,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보은군(신함리),3007470,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보은군(신함리),3007470,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보은군(신함리),3007470,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보은군(신함리),3007470,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보은군(신함리),3007470,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보은군(신함리),3007470,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보은군(신함리),3007470,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보은군(신함리),3007470,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보은군(신함리),3007470,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보은군(신함리),3007470,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보은군(신함리),3007470,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보은군(신함리),3007470,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보은군(신함리),3007470,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보은군(신함리),3007470,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보은군(신함리),3007470,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보은군(신함리),3007470,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보은군(신함리),3007470,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보은군(신함리),3007470,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보은군(신함리),3007470,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보은군(신함리),3007470,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보은군(신함리),3007470,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보은군(신함리),3007470,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보은군(신함리),3007470,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보은군(신함리),3007470,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보은군(신함리),3007470,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보은군(신함리),3007470,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보은군(신함리),3007470,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보은군(신함리),3007470,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보은군(신함리),3007470,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보은군(신함리),3007470,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보은군(신함리),3007470,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보은군(신함리),3007470,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보은군(신함리),3007470,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(산계리)  [3007475]  (36.3108333, 127.7372222)
📍 요청 위치: (36.3108°N, 127.7372°E)
📍 격자 좌표: (x=73, y=100)
📍 실제 위치: (36.3266°N, 127.7121°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(산계리),3007475,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(산계리),3007475,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(산계리),3007475,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(산계리),3007475,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(산계리),3007475,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(산계리),3007475,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(산계리),3007475,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(산계리),3007475,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(산계리),3007475,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(산계리),3007475,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(산계리),3007475,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(산계리),3007475,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(산계리),3007475,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(산계리),3007475,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(산계리),3007475,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(산계리),3007475,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(산계리),3007475,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(산계리),3007475,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(산계리),3007475,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(산계리),3007475,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(산계리),3007475,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(산계리),3007475,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(산계리),3007475,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(산계리),3007475,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(산계리),3007475,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(산계리),3007475,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(산계리),3007475,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(산계리),3007475,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(산계리),3007475,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(산계리),3007475,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(산계리),3007475,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(산계리),3007475,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(산계리),3007475,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(산계리),3007475,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(산계리),3007475,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(산계리),3007475,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(산계리),3007475,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(산계리),3007475,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(산계리),3007475,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(산계리),3007475,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(산계리),3007475,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(산계리),3007475,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(대정리)  [3008430]  (36.3847222, 127.5416667)
📍 요청 위치: (36.3847°N, 127.5417°E)
📍 격자 좌표: (x=70, y=101)
📍 실제 위치: (36.3754°N, 127.5421°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(대정리),3008430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(대정리),3008430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(대정리),3008430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(대정리),3008430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(대정리),3008430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(대정리),3008430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(대정리),3008430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(대정리),3008430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(대정리),3008430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(대정리),3008430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(대정리),3008430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(대정리),3008430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(대정리),3008430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(대정리),3008430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(대정리),3008430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(대정리),3008430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(대정리),3008430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(대정리),3008430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(대정리),3008430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(대정리),3008430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(대정리),3008430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(대정리),3008430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(대정리),3008430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(대정리),3008430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(대정리),3008430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(대정리),3008430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(대정리),3008430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(대정리),3008430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(대정리),3008430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(대정리),3008430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(대정리),3008430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(대정리),3008430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(대정리),3008430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(대정리),3008430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(대정리),3008430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(대정리),3008430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(대정리),3008430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(대정리),3008430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(대정리),3008430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(대정리),3008430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(대정리),3008430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(대정리),3008430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(마전리)  [3008440]  (36.19, 127.4694444)
📍 요청 위치: (36.1900°N, 127.4694°E)
📍 격자 좌표: (x=69, y=97)
📍 실제 위치: (36.1924°N, 127.4807°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(마전리),3008440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(마전리),3008440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(마전리),3008440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(마전리),3008440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(마전리),3008440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(마전리),3008440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(마전리),3008440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(마전리),3008440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(마전리),3008440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(마전리),3008440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(마전리),3008440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(마전리),3008440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(마전리),3008440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(마전리),3008440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(마전리),3008440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(마전리),3008440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(마전리),3008440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(마전리),3008440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(마전리),3008440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(마전리),3008440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(마전리),3008440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(마전리),3008440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(마전리),3008440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(마전리),3008440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(마전리),3008440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(마전리),3008440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(마전리),3008440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(마전리),3008440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(마전리),3008440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(마전리),3008440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(마전리),3008440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(마전리),3008440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(마전리),3008440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(마전리),3008440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(상곡리)  [3008450]  (36.2047222, 127.5763889)
📍 요청 위치: (36.2047°N, 127.5764°E)
📍 격자 좌표: (x=71, y=97)
📍 실제 위치: (36.1906°N, 127.5946°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(상곡리),3008450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(상곡리),3008450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(상곡리),3008450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(상곡리),3008450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(상곡리),3008450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(상곡리),3008450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(상곡리),3008450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(상곡리),3008450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(상곡리),3008450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(상곡리),3008450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(상곡리),3008450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(상곡리),3008450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(상곡리),3008450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(상곡리),3008450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(상곡리),3008450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(상곡리),3008450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(상곡리),3008450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(상곡리),3008450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(상곡리),3008450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(상곡리),3008450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(상곡리),3008450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(상곡리),3008450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(상곡리),3008450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(상곡리),3008450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(상곡리),3008450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(상곡리),3008450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(상곡리),3008450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(상곡리),3008450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(상곡리),3008450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(상곡리),3008450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(상곡리),3008450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(상곡리),3008450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(상곡리),3008450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(상곡리),3008450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(상곡리),3008450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(상곡리),3008450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(상곡리),3008450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(상곡리),3008450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(상곡리),3008450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(상곡리),3008450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(상곡리),3008450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(상곡리),3008450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
📍 요청 위치: (36.5128°N, 127.5086°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(상장리),9000017,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(상장리),9000017,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(상장리),9000017,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(상장리),9000017,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(상장리),9000017,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(상장리),9000017,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(상장리),9000017,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(상장리),9000017,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(상장리),9000017,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(상장리),9000017,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(상장리),9000017,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(상장리),9000017,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(상장리),9000017,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(상장리),9000017,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(상장리),9000017,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(상장리),9000017,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(상장리),9000017,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(상장리),9000017,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(상장리),9000017,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(상장리),9000017,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(상장리),9000017,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(상장리),9000017,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(상장리),9000017,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(상장리),9000017,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(상장리),9000017,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(상장리),9000017,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(상장리),9000017,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(상장리),9000017,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(상장리),9000017,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(상장리),9000017,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(상장리),9000017,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(상장리),9000017,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(상장리),9000017,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(상장리),9000017,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(인포리)  [9000019]  (36.3697222, 127.6561111)
📍 요청 위치: (36.3697°N, 127.6561°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(인포리),9000019,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥천군(인포리),9000019,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥천군(인포리),9000019,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥천군(인포리),9000019,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥천군(인포리),9000019,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥천군(인포리),9000019,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥천군(인포리),9000019,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥천군(인포리),9000019,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥천군(인포리),9000019,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥천군(인포리),9000019,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥천군(인포리),9000019,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥천군(인포리),9000019,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥천군(인포리),9000019,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥천군(인포리),9000019,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥천군(인포리),9000019,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥천군(인포리),9000019,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥천군(인포리),9000019,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥천군(인포리),9000019,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥천군(인포리),9000019,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥천군(인포리),9000019,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥천군(인포리),9000019,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥천군(인포리),9000019,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥천군(인포리),9000019,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥천군(인포리),9000019,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥천군(인포리),9000019,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥천군(인포리),9000019,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥천군(인포리),9000019,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥천군(인포리),9000019,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥천군(인포리),9000019,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥천군(인포리),9000019,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥천군(인포리),9000019,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥천군(인포리),9000019,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥천군(인포리),9000019,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥천군(인포리),9000019,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥천군(인포리),9000019,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥천군(인포리),9000019,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥천군(인포리),9000019,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥천군(인포리),9000019,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥천군(인포리),9000019,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥천군(인포리),9000019,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥천군(인포리),9000019,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥천군(인포리),9000019,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 김천시(월곡리)  [2010432]  (35.98222222, 127.9438889)
📍 요청 위치: (35.9822°N, 127.9439°E)
📍 격자 좌표: (x=77, y=93)
📍 실제 위치: (36.0008°N, 127.9307°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,김천시(월곡리),2010432,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,김천시(월곡리),2010432,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,김천시(월곡리),2010432,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,김천시(월곡리),2010432,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,김천시(월곡리),2010432,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,김천시(월곡리),2010432,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,김천시(월곡리),2010432,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,김천시(월곡리),2010432,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,김천시(월곡리),2010432,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,김천시(월곡리),2010432,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,김천시(월곡리),2010432,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,김천시(월곡리),2010432,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,김천시(월곡리),2010432,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,김천시(월곡리),2010432,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,김천시(월곡리),2010432,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,김천시(월곡리),2010432,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,김천시(월곡리),2010432,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,김천시(월곡리),2010432,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,김천시(월곡리),2010432,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,김천시(월곡리),2010432,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,김천시(월곡리),2010432,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,김천시(월곡리),2010432,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,김천시(월곡리),2010432,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,김천시(월곡리),2010432,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,김천시(월곡리),2010432,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,김천시(월곡리),2010432,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,김천시(월곡리),2010432,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,김천시(월곡리),2010432,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,김천시(월곡리),2010432,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,김천시(월곡리),2010432,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,김천시(월곡리),2010432,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,김천시(월곡리),2010432,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,김천시(월곡리),2010432,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,김천시(월곡리),2010432,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,김천시(월곡리),2010432,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,김천시(월곡리),2010432,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,김천시(월곡리),2010432,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,김천시(월곡리),2010432,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,김천시(월곡리),2010432,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,김천시(월곡리),2010432,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,김천시(월곡리),2010432,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,김천시(월곡리),2010432,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 김천시(파천리)  [2010434]  (36.02777778, 127.9469444)
📍 요청 위치: (36.0278°N, 127.9469°E)
📍 격자 좌표: (x=77, y=94)
📍 실제 위치: (36.0467°N, 127.9321°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,김천시(파천리),2010434,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,김천시(파천리),2010434,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,김천시(파천리),2010434,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,김천시(파천리),2010434,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,김천시(파천리),2010434,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,김천시(파천리),2010434,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,김천시(파천리),2010434,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,김천시(파천리),2010434,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,김천시(파천리),2010434,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,김천시(파천리),2010434,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,김천시(파천리),2010434,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,김천시(파천리),2010434,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,김천시(파천리),2010434,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,김천시(파천리),2010434,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,김천시(파천리),2010434,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,김천시(파천리),2010434,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,김천시(파천리),2010434,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,김천시(파천리),2010434,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,김천시(파천리),2010434,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,김천시(파천리),2010434,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,김천시(파천리),2010434,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,김천시(파천리),2010434,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,김천시(파천리),2010434,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,김천시(파천리),2010434,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,김천시(파천리),2010434,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,김천시(파천리),2010434,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,김천시(파천리),2010434,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,김천시(파천리),2010434,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,김천시(파천리),2010434,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,김천시(파천리),2010434,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,김천시(파천리),2010434,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,김천시(파천리),2010434,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,김천시(파천리),2010434,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,김천시(파천리),2010434,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,김천시(파천리),2010434,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,김천시(파천리),2010434,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,김천시(파천리),2010434,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,김천시(파천리),2010434,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,김천시(파천리),2010434,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,김천시(파천리),2010434,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,김천시(파천리),2010434,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,김천시(파천리),2010434,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전  [8000133]  (36.37199, 127.3721)
📍 요청 위치: (36.3720°N, 127.3721°E)
📍 격자 좌표: (x=67, y=101)
📍 실제 위치: (36.3779°N, 127.3708°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전,8000133,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전,8000133,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전,8000133,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전,8000133,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전,8000133,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전,8000133,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전,8000133,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전,8000133,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전,8000133,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전,8000133,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전,8000133,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전,8000133,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전,8000133,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전,8000133,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전,8000133,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전,8000133,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전,8000133,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전,8000133,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전,8000133,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전,8000133,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전,8000133,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전,8000133,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전,8000133,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전,8000133,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전,8000133,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전,8000133,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전,8000133,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전,8000133,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전,8000133,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전,8000133,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전,8000133,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전,8000133,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전,8000133,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전,8000133,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전,8000133,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전,8000133,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전,8000133,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전,8000133,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전,8000133,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전,8000133,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전,8000133,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전,8000133,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안  [8000232]  (36.76217, 127.29282)
📍 요청 위치: (36.7622°N, 127.2928°E)
📍 격자 좌표: (x=66, y=109)
📍 실제 위치: (36.7466°N, 127.3212°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안,8000232,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안,8000232,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안,8000232,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안,8000232,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안,8000232,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안,8000232,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안,8000232,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안,8000232,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안,8000232,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안,8000232,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안,8000232,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안,8000232,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안,8000232,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안,8000232,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안,8000232,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안,8000232,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안,8000232,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안,8000232,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안,8000232,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안,8000232,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안,8000232,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안,8000232,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안,8000232,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안,8000232,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안,8000232,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안,8000232,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안,8000232,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안,8000232,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안,8000232,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안,8000232,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안,8000232,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안,8000232,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안,8000232,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안,8000232,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안,8000232,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안,8000232,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안,8000232,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안,8000232,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안,8000232,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안,8000232,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안,8000232,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안,8000232,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여  [8000236]  (36.27242, 126.92078)
📍 요청 위치: (36.2724°N, 126.9208°E)
📍 격자 좌표: (x=59, y=99)
📍 실제 위치: (36.2912°N, 126.9126°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여,8000236,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,부여,8000236,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,부여,8000236,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,부여,8000236,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,부여,8000236,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,부여,8000236,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,부여,8000236,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,부여,8000236,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,부여,8000236,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,부여,8000236,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,부여,8000236,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,부여,8000236,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,부여,8000236,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,부여,8000236,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,부여,8000236,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,부여,8000236,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,부여,8000236,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,부여,8000236,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,부여,8000236,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,부여,8000236,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,부여,8000236,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,부여,8000236,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,부여,8000236,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,부여,8000236,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,부여,8000236,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,부여,8000236,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,부여,8000236,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,부여,8000236,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,부여,8000236,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,부여,8000236,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,부여,8000236,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,부여,8000236,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,부여,8000236,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,부여,8000236,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,부여,8000236,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,부여,8000236,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,부여,8000236,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,부여,8000236,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,부여,8000236,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,부여,8000236,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,부여,8000236,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,부여,8000236,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산  [8000238]  (36.10565, 127.48185)
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산,8000238,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산,8000238,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산,8000238,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산,8000238,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산,8000238,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산,8000238,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산,8000238,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산,8000238,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산,8000238,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산,8000238,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산,8000238,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산,8000238,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산,8000238,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산,8000238,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산,8000238,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산,8000238,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산,8000238,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산,8000238,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산,8000238,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산,8000238,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산,8000238,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산,8000238,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산,8000238,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산,8000238,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산,8000238,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산,8000238,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산,8000238,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산,8000238,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산,8000238,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산,8000238,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산,8000238,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산,8000238,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산,8000238,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산,8000238,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산,8000238,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산,8000238,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산,8000238,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산,8000238,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산,8000238,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산,8000238,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산,8000238,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산,8000238,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종  [8000239]  (36.48522, 127.24438)
📍 요청 위치: (36.4852°N, 127.2444°E)
📍 격자 좌표: (x=65, y=103)
📍 실제 위치: (36.4713°N, 127.2583°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종,8000239,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종,8000239,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종,8000239,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종,8000239,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종,8000239,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종,8000239,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종,8000239,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종,8000239,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종,8000239,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종,8000239,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종,8000239,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종,8000239,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종,8000239,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종,8000239,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종,8000239,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종,8000239,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종,8000239,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종,8000239,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종,8000239,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종,8000239,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종,8000239,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종,8000239,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종,8000239,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종,8000239,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종,8000239,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종,8000239,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종,8000239,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종,8000239,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종,8000239,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종,8000239,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종,8000239,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종,8000239,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종,8000239,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종,8000239,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종,8000239,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종,8000239,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종,8000239,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종,8000239,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종,8000239,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종,8000239,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종,8000239,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종,8000239,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종고운  [8000494]  (36.53152, 127.24064)
📍 요청 위치: (36.5315°N, 127.2406°E)
📍 격자 좌표: (x=65, y=104)
📍 실제 위치: (36.5173°N, 127.2592°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종고운,8000494,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종고운,8000494,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종고운,8000494,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종고운,8000494,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종고운,8000494,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종고운,8000494,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종고운,8000494,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종고운,8000494,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종고운,8000494,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종고운,8000494,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종고운,8000494,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종고운,8000494,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종고운,8000494,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종고운,8000494,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종고운,8000494,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종고운,8000494,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종고운,8000494,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종고운,8000494,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종고운,8000494,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종고운,8000494,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종고운,8000494,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종고운,8000494,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종고운,8000494,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종고운,8000494,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종고운,8000494,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종고운,8000494,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종고운,8000494,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종고운,8000494,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종고운,8000494,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종고운,8000494,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종고운,8000494,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종고운,8000494,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종고운,8000494,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종고운,8000494,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종고운,8000494,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종고운,8000494,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종고운,8000494,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종고운,8000494,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종고운,8000494,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종고운,8000494,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종고운,8000494,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종고운,8000494,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종금남  [8000496]  (36.45853, 127.26876)
📍 요청 위치: (36.4585°N, 127.2688°E)
📍 격자 좌표: (x=65, y=103)
📍 실제 위치: (36.4713°N, 127.2583°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종금남,8000496,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종금남,8000496,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종금남,8000496,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종금남,8000496,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종금남,8000496,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종금남,8000496,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종금남,8000496,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종금남,8000496,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종금남,8000496,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종금남,8000496,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종금남,8000496,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종금남,8000496,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종금남,8000496,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종금남,8000496,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종금남,8000496,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종금남,8000496,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종금남,8000496,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종금남,8000496,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종금남,8000496,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종금남,8000496,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종금남,8000496,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종금남,8000496,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종금남,8000496,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종금남,8000496,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종금남,8000496,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종금남,8000496,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종금남,8000496,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종금남,8000496,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종금남,8000496,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종금남,8000496,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종금남,8000496,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종금남,8000496,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종금남,8000496,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종금남,8000496,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종금남,8000496,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종금남,8000496,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종금남,8000496,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종금남,8000496,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종금남,8000496,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종금남,8000496,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종금남,8000496,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종금남,8000496,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종연서  [8000611]  (36.56667, 127.28056)
📍 요청 위치: (36.5667°N, 127.2806°E)
📍 격자 좌표: (x=65, y=105)
📍 실제 위치: (36.5633°N, 127.2601°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종연서,8000611,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종연서,8000611,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종연서,8000611,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종연서,8000611,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종연서,8000611,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종연서,8000611,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종연서,8000611,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종연서,8000611,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종연서,8000611,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종연서,8000611,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종연서,8000611,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종연서,8000611,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종연서,8000611,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종연서,8000611,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종연서,8000611,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종연서,8000611,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종연서,8000611,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종연서,8000611,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종연서,8000611,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종연서,8000611,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종연서,8000611,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종연서,8000611,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종연서,8000611,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종연서,8000611,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종연서,8000611,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종연서,8000611,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종연서,8000611,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종연서,8000611,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종연서,8000611,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종연서,8000611,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종연서,8000611,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종연서,8000611,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종연서,8000611,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종연서,8000611,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종연서,8000611,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종연서,8000611,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종연서,8000611,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종연서,8000611,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종연서,8000611,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종연서,8000611,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종연서,8000611,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종연서,8000611,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주  [8000612]  (36.48284, 127.13646)
📍 요청 위치: (36.4828°N, 127.1365°E)
📍 격자 좌표: (x=63, y=103)
📍 실제 위치: (36.4727°N, 127.1440°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주,8000612,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주,8000612,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주,8000612,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주,8000612,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주,8000612,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주,8000612,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주,8000612,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주,8000612,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주,8000612,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주,8000612,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주,8000612,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주,8000612,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주,8000612,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주,8000612,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주,8000612,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주,8000612,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주,8000612,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주,8000612,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주,8000612,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주,8000612,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주,8000612,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주,8000612,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주,8000612,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주,8000612,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주,8000612,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주,8000612,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주,8000612,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주,8000612,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주,8000612,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주,8000612,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주,8000612,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주,8000612,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주,8000612,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주,8000612,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주,8000612,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주,8000612,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주,8000612,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주,8000612,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주,8000612,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주,8000612,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주,8000612,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주,8000612,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천  [8000614]  (36.06248, 126.70411)
📍 요청 위치: (36.0625°N, 126.7041°E)
📍 격자 좌표: (x=55, y=94)
📍 실제 위치: (36.0632°N, 126.6820°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천,8000614,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,서천,8000614,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,서천,8000614,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,서천,8000614,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,서천,8000614,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,서천,8000614,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,서천,8000614,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,서천,8000614,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,서천,8000614,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,서천,8000614,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,서천,8000614,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,서천,8000614,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,서천,8000614,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,서천,8000614,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,서천,8000614,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,서천,8000614,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,서천,8000614,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,서천,8000614,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,서천,8000614,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,서천,8000614,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,서천,8000614,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,서천,8000614,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,서천,8000614,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,서천,8000614,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,서천,8000614,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,서천,8000614,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,서천,8000614,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,서천,8000614,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,서천,8000614,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,서천,8000614,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,서천,8000614,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,서천,8000614,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,서천,8000614,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,서천,8000614,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,서천,8000614,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,서천,8000614,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,서천,8000614,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,서천,8000614,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,서천,8000614,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,서천,8000614,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,서천,8000614,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,서천,8000614,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산  [8000615]  (36.21164, 127.10815)
📍 요청 위치: (36.2116°N, 127.1081°E)
📍 격자 좌표: (x=62, y=97)
📍 실제 위치: (36.1975°N, 127.0821°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산,8000615,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산,8000615,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산,8000615,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산,8000615,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산,8000615,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산,8000615,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산,8000615,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산,8000615,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산,8000615,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산,8000615,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산,8000615,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산,8000615,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산,8000615,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산,8000615,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산,8000615,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산,8000615,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산,8000615,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산,8000615,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산,8000615,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산,8000615,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산,8000615,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산,8000615,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산,8000615,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산,8000615,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산,8000615,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산,8000615,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산,8000615,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산,8000615,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산,8000615,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산,8000615,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산,8000615,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산,8000615,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산,8000615,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산,8000615,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산,8000615,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산,8000615,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산,8000615,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산,8000615,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산,8000615,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산,8000615,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산,8000615,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산,8000615,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양  [8000618]  (36.42371, 126.77906)
📍 요청 위치: (36.4237°N, 126.7791°E)
📍 격자 좌표: (x=57, y=102)
📍 실제 위치: (36.4301°N, 126.8002°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양,8000618,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청양,8000618,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청양,8000618,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청양,8000618,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청양,8000618,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청양,8000618,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청양,8000618,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청양,8000618,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청양,8000618,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청양,8000618,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청양,8000618,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청양,8000618,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청양,8000618,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청양,8000618,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청양,8000618,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청양,8000618,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청양,8000618,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청양,8000618,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청양,8000618,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청양,8000618,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청양,8000618,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청양,8000618,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청양,8000618,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청양,8000618,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청양,8000618,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청양,8000618,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청양,8000618,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청양,8000618,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청양,8000618,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청양,8000618,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청양,8000618,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청양,8000618,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청양,8000618,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청양,8000618,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청양,8000618,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청양,8000618,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청양,8000618,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청양,8000618,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청양,8000618,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청양,8000618,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청양,8000618,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청양,8000618,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종전의  [8000629]  (36.69076, 127.20047)
📍 요청 위치: (36.6908°N, 127.2005°E)
📍 격자 좌표: (x=64, y=108)
📍 실제 위치: (36.7021°N, 127.2055°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종전의,8000629,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종전의,8000629,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종전의,8000629,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종전의,8000629,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종전의,8000629,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종전의,8000629,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종전의,8000629,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종전의,8000629,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종전의,8000629,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종전의,8000629,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종전의,8000629,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종전의,8000629,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종전의,8000629,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종전의,8000629,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종전의,8000629,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종전의,8000629,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종전의,8000629,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종전의,8000629,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종전의,8000629,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종전의,8000629,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종전의,8000629,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종전의,8000629,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종전의,8000629,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종전의,8000629,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종전의,8000629,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종전의,8000629,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종전의,8000629,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종전의,8000629,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종전의,8000629,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종전의,8000629,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종전의,8000629,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종전의,8000629,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종전의,8000629,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종전의,8000629,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종전의,8000629,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종전의,8000629,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종전의,8000629,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종전의,8000629,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종전의,8000629,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종전의,8000629,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종전의,8000629,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종전의,8000629,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 유구  [8000632]  (36.54069, 126.93356)
📍 요청 위치: (36.5407°N, 126.9336°E)
📍 격자 좌표: (x=59, y=104)
📍 실제 위치: (36.5211°N, 126.9159°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,유구,8000632,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,유구,8000632,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,유구,8000632,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,유구,8000632,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,유구,8000632,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,유구,8000632,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,유구,8000632,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,유구,8000632,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,유구,8000632,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,유구,8000632,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,유구,8000632,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,유구,8000632,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,유구,8000632,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,유구,8000632,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,유구,8000632,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,유구,8000632,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,유구,8000632,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,유구,8000632,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,유구,8000632,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,유구,8000632,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,유구,8000632,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,유구,8000632,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,유구,8000632,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,유구,8000632,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,유구,8000632,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,유구,8000632,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,유구,8000632,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,유구,8000632,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,유구,8000632,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,유구,8000632,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,유구,8000632,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,유구,8000632,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,유구,8000632,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,유구,8000632,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,유구,8000632,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,유구,8000632,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,유구,8000632,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,유구,8000632,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,유구,8000632,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,유구,8000632,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,유구,8000632,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,유구,8000632,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정안  [8000633]  (36.55114, 127.09383)
📍 요청 위치: (36.5511°N, 127.0938°E)
📍 격자 좌표: (x=62, y=105)
📍 실제 위치: (36.5654°N, 127.0883°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정안,8000633,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,정안,8000633,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,정안,8000633,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,정안,8000633,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,정안,8000633,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,정안,8000633,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,정안,8000633,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,정안,8000633,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,정안,8000633,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,정안,8000633,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,정안,8000633,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,정안,8000633,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,정안,8000633,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,정안,8000633,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,정안,8000633,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,정안,8000633,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,정안,8000633,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,정안,8000633,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,정안,8000633,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,정안,8000633,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,정안,8000633,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,정안,8000633,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,정안,8000633,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,정안,8000633,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,정안,8000633,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,정안,8000633,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,정안,8000633,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,정안,8000633,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,정안,8000633,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,정안,8000633,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,정안,8000633,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,정안,8000633,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,정안,8000633,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,정안,8000633,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,정안,8000633,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,정안,8000633,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,정안,8000633,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,정안,8000633,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,정안,8000633,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,정안,8000633,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,정안,8000633,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,정안,8000633,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 양화  [8000635]  (36.1319, 126.86024)
📍 요청 위치: (36.1319°N, 126.8602°E)
📍 격자 좌표: (x=58, y=96)
📍 실제 위치: (36.1538°N, 126.8537°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,양화,8000635,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,양화,8000635,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,양화,8000635,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,양화,8000635,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,양화,8000635,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,양화,8000635,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,양화,8000635,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,양화,8000635,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,양화,8000635,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,양화,8000635,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,양화,8000635,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,양화,8000635,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,양화,8000635,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,양화,8000635,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,양화,8000635,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,양화,8000635,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,양화,8000635,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,양화,8000635,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,양화,8000635,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,양화,8000635,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,양화,8000635,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,양화,8000635,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,양화,8000635,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,양화,8000635,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,양화,8000635,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,양화,8000635,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,양화,8000635,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,양화,8000635,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,양화,8000635,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,양화,8000635,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,양화,8000635,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,양화,8000635,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,양화,8000635,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,양화,8000635,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,양화,8000635,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,양화,8000635,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,양화,8000635,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,양화,8000635,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,양화,8000635,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,양화,8000635,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,양화,8000635,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,양화,8000635,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡  [8000636]  (36.3132, 127.2407)
📍 요청 위치: (36.3132°N, 127.2407°E)
📍 격자 좌표: (x=65, y=100)
📍 실제 위치: (36.3334°N, 127.2557°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡,8000636,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,계룡,8000636,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,계룡,8000636,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,계룡,8000636,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,계룡,8000636,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,계룡,8000636,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,계룡,8000636,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,계룡,8000636,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,계룡,8000636,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,계룡,8000636,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,계룡,8000636,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,계룡,8000636,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,계룡,8000636,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,계룡,8000636,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,계룡,8000636,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,계룡,8000636,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,계룡,8000636,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,계룡,8000636,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,계룡,8000636,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,계룡,8000636,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,계룡,8000636,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,계룡,8000636,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,계룡,8000636,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,계룡,8000636,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,계룡,8000636,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,계룡,8000636,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,계룡,8000636,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,계룡,8000636,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,계룡,8000636,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,계룡,8000636,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,계룡,8000636,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,계룡,8000636,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,계룡,8000636,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,계룡,8000636,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,계룡,8000636,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,계룡,8000636,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,계룡,8000636,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,계룡,8000636,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,계룡,8000636,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,계룡,8000636,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,계룡,8000636,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,계룡,8000636,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오월드  [8000642]  (36.29129, 127.39586)
📍 요청 위치: (36.2913°N, 127.3959°E)
📍 격자 좌표: (x=67, y=99)
📍 실제 위치: (36.2859°N, 127.3688°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오월드,8000642,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,오월드,8000642,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,오월드,8000642,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,오월드,8000642,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,오월드,8000642,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,오월드,8000642,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,오월드,8000642,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,오월드,8000642,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,오월드,8000642,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,오월드,8000642,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,오월드,8000642,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,오월드,8000642,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,오월드,8000642,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,오월드,8000642,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,오월드,8000642,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,오월드,8000642,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,오월드,8000642,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,오월드,8000642,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,오월드,8000642,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,오월드,8000642,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,오월드,8000642,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,오월드,8000642,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,오월드,8000642,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,오월드,8000642,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,오월드,8000642,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,오월드,8000642,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,오월드,8000642,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,오월드,8000642,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,오월드,8000642,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,오월드,8000642,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,오월드,8000642,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,오월드,8000642,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,오월드,8000642,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,오월드,8000642,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,오월드,8000642,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,오월드,8000642,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,오월드,8000642,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,오월드,8000642,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,오월드,8000642,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,오월드,8000642,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,오월드,8000642,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,오월드,8000642,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세천  [8000643]  (36.34019, 127.49378)
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세천,8000643,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세천,8000643,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세천,8000643,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세천,8000643,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세천,8000643,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세천,8000643,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세천,8000643,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세천,8000643,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세천,8000643,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세천,8000643,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세천,8000643,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세천,8000643,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세천,8000643,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세천,8000643,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세천,8000643,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세천,8000643,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세천,8000643,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세천,8000643,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세천,8000643,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세천,8000643,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세천,8000643,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세천,8000643,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세천,8000643,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세천,8000643,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세천,8000643,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세천,8000643,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세천,8000643,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세천,8000643,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세천,8000643,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세천,8000643,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세천,8000643,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세천,8000643,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세천,8000643,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세천,8000643,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세천,8000643,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세천,8000643,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세천,8000643,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세천,8000643,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세천,8000643,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세천,8000643,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세천,8000643,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세천,8000643,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 연무  [8000644]  (36.13662, 127.09004)
📍 요청 위치: (36.1366°N, 127.0900°E)
📍 격자 좌표: (x=62, y=96)
📍 실제 위치: (36.1516°N, 127.0814°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,연무,8000644,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,연무,8000644,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,연무,8000644,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,연무,8000644,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,연무,8000644,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,연무,8000644,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,연무,8000644,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,연무,8000644,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,연무,8000644,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,연무,8000644,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,연무,8000644,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,연무,8000644,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,연무,8000644,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,연무,8000644,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,연무,8000644,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,연무,8000644,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,연무,8000644,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,연무,8000644,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,연무,8000644,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,연무,8000644,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,연무,8000644,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,연무,8000644,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,연무,8000644,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,연무,8000644,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,연무,8000644,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,연무,8000644,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,연무,8000644,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,연무,8000644,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,연무,8000644,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,연무,8000644,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,연무,8000644,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,연무,8000644,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,연무,8000644,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,연무,8000644,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,연무,8000644,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,연무,8000644,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,연무,8000644,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,연무,8000644,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,연무,8000644,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,연무,8000644,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,연무,8000644,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,연무,8000644,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장동  [8000648]  (36.41347, 127.43821)
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장동,8000648,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,장동,8000648,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,장동,8000648,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,장동,8000648,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,장동,8000648,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,장동,8000648,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,장동,8000648,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,장동,8000648,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,장동,8000648,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,장동,8000648,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,장동,8000648,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,장동,8000648,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,장동,8000648,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,장동,8000648,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,장동,8000648,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,장동,8000648,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,장동,8000648,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,장동,8000648,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,장동,8000648,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,장동,8000648,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,장동,8000648,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,장동,8000648,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,장동,8000648,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,장동,8000648,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,장동,8000648,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,장동,8000648,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,장동,8000648,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,장동,8000648,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,장동,8000648,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,장동,8000648,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,장동,8000648,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,장동,8000648,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,장동,8000648,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,장동,8000648,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,장동,8000648,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,장동,8000648,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,장동,8000648,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,장동,8000648,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,장동,8000648,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,장동,8000648,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,장동,8000648,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,장동,8000648,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡산  [8000659]  (36.343, 127.2057)
📍 요청 위치: (36.3430°N, 127.2057°E)
📍 격자 좌표: (x=64, y=100)
📍 실제 위치: (36.3341°N, 127.1986°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡산,8000659,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,계룡산,8000659,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,계룡산,8000659,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,계룡산,8000659,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,계룡산,8000659,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,계룡산,8000659,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,계룡산,8000659,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,계룡산,8000659,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,계룡산,8000659,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,계룡산,8000659,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,계룡산,8000659,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,계룡산,8000659,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,계룡산,8000659,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,계룡산,8000659,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,계룡산,8000659,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,계룡산,8000659,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,계룡산,8000659,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,계룡산,8000659,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,계룡산,8000659,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,계룡산,8000659,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,계룡산,8000659,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,계룡산,8000659,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,계룡산,8000659,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,계룡산,8000659,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,계룡산,8000659,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,계룡산,8000659,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,계룡산,8000659,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,계룡산,8000659,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,계룡산,8000659,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,계룡산,8000659,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,계룡산,8000659,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,계룡산,8000659,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,계룡산,8000659,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,계룡산,8000659,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,계룡산,8000659,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,계룡산,8000659,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,계룡산,8000659,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,계룡산,8000659,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,계룡산,8000659,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,계룡산,8000659,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,계룡산,8000659,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,계룡산,8000659,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정산  [8000691]  (36.38617, 126.95652)
📍 요청 위치: (36.3862°N, 126.9565°E)
📍 격자 좌표: (x=60, y=101)
📍 실제 위치: (36.3826°N, 126.9710°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정산,8000691,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,정산,8000691,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,정산,8000691,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,정산,8000691,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,정산,8000691,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,정산,8000691,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,정산,8000691,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,정산,8000691,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,정산,8000691,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,정산,8000691,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,정산,8000691,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,정산,8000691,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,정산,8000691,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,정산,8000691,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,정산,8000691,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,정산,8000691,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,정산,8000691,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,정산,8000691,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,정산,8000691,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,정산,8000691,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,정산,8000691,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,정산,8000691,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,정산,8000691,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,정산,8000691,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,정산,8000691,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,정산,8000691,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,정산,8000691,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,정산,8000691,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,정산,8000691,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,정산,8000691,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,정산,8000691,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,정산,8000691,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,정산,8000691,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,정산,8000691,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,정산,8000691,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,정산,8000691,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,정산,8000691,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,정산,8000691,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,정산,8000691,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,정산,8000691,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,정산,8000691,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,정산,8000691,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 함라  [8000733]  (36.0461, 126.8917)
📍 요청 위치: (36.0461°N, 126.8917°E)
📍 격자 좌표: (x=59, y=94)
📍 실제 위치: (36.0614°N, 126.9094°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,함라,8000733,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,함라,8000733,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,함라,8000733,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,함라,8000733,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,함라,8000733,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,함라,8000733,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,함라,8000733,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,함라,8000733,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,함라,8000733,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,함라,8000733,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,함라,8000733,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,함라,8000733,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,함라,8000733,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,함라,8000733,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,함라,8000733,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,함라,8000733,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,함라,8000733,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,함라,8000733,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,함라,8000733,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,함라,8000733,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,함라,8000733,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,함라,8000733,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,함라,8000733,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,함라,8000733,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,함라,8000733,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,함라,8000733,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,함라,8000733,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,함라,8000733,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,함라,8000733,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,함라,8000733,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,함라,8000733,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,함라,8000733,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,함라,8000733,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,함라,8000733,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,함라,8000733,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,함라,8000733,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,함라,8000733,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,함라,8000733,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,함라,8000733,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,함라,8000733,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,함라,8000733,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,함라,8000733,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 여산  [8000763]  (36.0592, 127.062)
📍 요청 위치: (36.0592°N, 127.0620°E)
📍 격자 좌표: (x=62, y=94)
📍 실제 위치: (36.0597°N, 127.0798°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,여산,8000763,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,여산,8000763,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,여산,8000763,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,여산,8000763,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,여산,8000763,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,여산,8000763,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,여산,8000763,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,여산,8000763,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,여산,8000763,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,여산,8000763,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,여산,8000763,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,여산,8000763,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,여산,8000763,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,여산,8000763,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,여산,8000763,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,여산,8000763,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,여산,8000763,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,여산,8000763,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,여산,8000763,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,여산,8000763,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,여산,8000763,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,여산,8000763,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,여산,8000763,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,여산,8000763,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,여산,8000763,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,여산,8000763,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,여산,8000763,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,여산,8000763,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,여산,8000763,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,여산,8000763,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,여산,8000763,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,여산,8000763,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,여산,8000763,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,여산,8000763,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,여산,8000763,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,여산,8000763,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,여산,8000763,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,여산,8000763,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,여산,8000763,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,여산,8000763,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,여산,8000763,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,여산,8000763,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주  [8000131]  (36.63935, 127.44089)
📍 요청 위치: (36.6394°N, 127.4409°E)
📍 격자 좌표: (x=68, y=107)
📍 실제 위치: (36.6530°N, 127.4340°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주,8000131,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주,8000131,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주,8000131,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주,8000131,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주,8000131,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주,8000131,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주,8000131,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주,8000131,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주,8000131,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주,8000131,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주,8000131,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주,8000131,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주,8000131,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주,8000131,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주,8000131,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주,8000131,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주,8000131,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주,8000131,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주,8000131,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주,8000131,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주,8000131,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주,8000131,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주,8000131,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주,8000131,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주,8000131,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주,8000131,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주,8000131,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주,8000131,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주,8000131,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주,8000131,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주,8000131,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주,8000131,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주,8000131,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주,8000131,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주,8000131,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주,8000131,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주,8000131,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주,8000131,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주,8000131,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주,8000131,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주,8000131,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주,8000131,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서청주  [8000181]  (36.63972, 127.396944)
📍 요청 위치: (36.6397°N, 127.3969°E)
📍 격자 좌표: (x=67, y=107)
📍 실제 위치: (36.6538°N, 127.3767°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서청주,8000181,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,서청주,8000181,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,서청주,8000181,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,서청주,8000181,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,서청주,8000181,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,서청주,8000181,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,서청주,8000181,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,서청주,8000181,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,서청주,8000181,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,서청주,8000181,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,서청주,8000181,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,서청주,8000181,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,서청주,8000181,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,서청주,8000181,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,서청주,8000181,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,서청주,8000181,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,서청주,8000181,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,서청주,8000181,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,서청주,8000181,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,서청주,8000181,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,서청주,8000181,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,서청주,8000181,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,서청주,8000181,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,서청주,8000181,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,서청주,8000181,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,서청주,8000181,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,서청주,8000181,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,서청주,8000181,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,서청주,8000181,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,서청주,8000181,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,서청주,8000181,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,서청주,8000181,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,서청주,8000181,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,서청주,8000181,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,서청주,8000181,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,서청주,8000181,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,서청주,8000181,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,서청주,8000181,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,서청주,8000181,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,서청주,8000181,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,서청주,8000181,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,서청주,8000181,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주금천  [8000327]  (36.62611111, 127.5127778)
📍 요청 위치: (36.6261°N, 127.5128°E)
📍 격자 좌표: (x=69, y=106)
📍 실제 위치: (36.6062°N, 127.4903°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주금천,8000327,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주금천,8000327,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주금천,8000327,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주금천,8000327,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주금천,8000327,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주금천,8000327,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주금천,8000327,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주금천,8000327,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주금천,8000327,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주금천,8000327,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주금천,8000327,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주금천,8000327,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주금천,8000327,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주금천,8000327,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주금천,8000327,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주금천,8000327,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주금천,8000327,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주금천,8000327,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주금천,8000327,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주금천,8000327,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주금천,8000327,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주금천,8000327,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주금천,8000327,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주금천,8000327,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주금천,8000327,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주금천,8000327,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주금천,8000327,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주금천,8000327,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주금천,8000327,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주금천,8000327,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주금천,8000327,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주금천,8000327,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주금천,8000327,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주금천,8000327,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주금천,8000327,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주금천,8000327,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주금천,8000327,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주금천,8000327,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주금천,8000327,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주금천,8000327,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주금천,8000327,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주금천,8000327,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금왕  [8000600]  (36.97369, 127.58973)
📍 요청 위치: (36.9737°N, 127.5897°E)
📍 격자 좌표: (x=71, y=114)
📍 실제 위치: (36.9726°N, 127.6141°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금왕,8000600,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금왕,8000600,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금왕,8000600,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금왕,8000600,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금왕,8000600,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금왕,8000600,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금왕,8000600,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금왕,8000600,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금왕,8000600,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금왕,8000600,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금왕,8000600,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금왕,8000600,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금왕,8000600,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금왕,8000600,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금왕,8000600,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금왕,8000600,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금왕,8000600,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금왕,8000600,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금왕,8000600,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금왕,8000600,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금왕,8000600,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금왕,8000600,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금왕,8000600,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금왕,8000600,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금왕,8000600,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금왕,8000600,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금왕,8000600,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금왕,8000600,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금왕,8000600,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금왕,8000600,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금왕,8000600,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금왕,8000600,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금왕,8000600,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금왕,8000600,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금왕,8000600,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금왕,8000600,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금왕,8000600,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금왕,8000600,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금왕,8000600,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금왕,8000600,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금왕,8000600,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금왕,8000600,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진천  [8000602]  (36.86338, 127.46231)
📍 요청 위치: (36.8634°N, 127.4623°E)
📍 격자 좌표: (x=68, y=112)
📍 실제 위치: (36.8831°N, 127.4392°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진천,8000602,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진천,8000602,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진천,8000602,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진천,8000602,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진천,8000602,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진천,8000602,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진천,8000602,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진천,8000602,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진천,8000602,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진천,8000602,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진천,8000602,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진천,8000602,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진천,8000602,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진천,8000602,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진천,8000602,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진천,8000602,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진천,8000602,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진천,8000602,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진천,8000602,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진천,8000602,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진천,8000602,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진천,8000602,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진천,8000602,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진천,8000602,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진천,8000602,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진천,8000602,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진천,8000602,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진천,8000602,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진천,8000602,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진천,8000602,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진천,8000602,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진천,8000602,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진천,8000602,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진천,8000602,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진천,8000602,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진천,8000602,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진천,8000602,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진천,8000602,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진천,8000602,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진천,8000602,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진천,8000602,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진천,8000602,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 증평  [8000623]  (36.7956, 127.562)
📍 요청 위치: (36.7956°N, 127.5620°E)
📍 격자 좌표: (x=70, y=110)
📍 실제 위치: (36.7894°N, 127.5520°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,증평,8000623,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,증평,8000623,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,증평,8000623,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,증평,8000623,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,증평,8000623,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,증평,8000623,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,증평,8000623,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,증평,8000623,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,증평,8000623,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,증평,8000623,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,증평,8000623,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,증평,8000623,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,증평,8000623,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,증평,8000623,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,증평,8000623,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,증평,8000623,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,증평,8000623,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,증평,8000623,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,증평,8000623,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,증평,8000623,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,증평,8000623,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,증평,8000623,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,증평,8000623,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,증평,8000623,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,증평,8000623,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,증평,8000623,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,증평,8000623,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,증평,8000623,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,증평,8000623,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,증평,8000623,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,증평,8000623,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,증평,8000623,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,증평,8000623,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,증평,8000623,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,증평,8000623,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,증평,8000623,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,증평,8000623,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,증평,8000623,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,증평,8000623,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,증평,8000623,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,증평,8000623,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,증평,8000623,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가덕  [8000641]  (36.5461, 127.52388)
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가덕,8000641,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,가덕,8000641,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,가덕,8000641,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,가덕,8000641,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,가덕,8000641,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,가덕,8000641,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,가덕,8000641,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,가덕,8000641,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,가덕,8000641,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,가덕,8000641,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,가덕,8000641,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,가덕,8000641,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,가덕,8000641,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,가덕,8000641,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,가덕,8000641,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,가덕,8000641,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,가덕,8000641,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,가덕,8000641,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,가덕,8000641,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,가덕,8000641,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,가덕,8000641,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,가덕,8000641,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,가덕,8000641,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,가덕,8000641,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,가덕,8000641,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,가덕,8000641,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,가덕,8000641,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,가덕,8000641,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,가덕,8000641,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,가덕,8000641,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,가덕,8000641,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,가덕,8000641,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,가덕,8000641,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,가덕,8000641,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,가덕,8000641,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,가덕,8000641,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,가덕,8000641,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,가덕,8000641,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 위성센터  [8000676]  (36.9906, 127.42985)
📍 요청 위치: (36.9906°N, 127.4299°E)
📍 격자 좌표: (x=68, y=114)
📍 실제 위치: (36.9752°N, 127.4412°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,위성센터,8000676,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,위성센터,8000676,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,위성센터,8000676,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,위성센터,8000676,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,위성센터,8000676,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,위성센터,8000676,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,위성센터,8000676,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,위성센터,8000676,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,위성센터,8000676,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,위성센터,8000676,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,위성센터,8000676,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,위성센터,8000676,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,위성센터,8000676,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,위성센터,8000676,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,위성센터,8000676,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,위성센터,8000676,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,위성센터,8000676,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,위성센터,8000676,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,위성센터,8000676,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,위성센터,8000676,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,위성센터,8000676,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,위성센터,8000676,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,위성센터,8000676,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,위성센터,8000676,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,위성센터,8000676,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,위성센터,8000676,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,위성센터,8000676,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,위성센터,8000676,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,위성센터,8000676,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,위성센터,8000676,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,위성센터,8000676,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,위성센터,8000676,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,위성센터,8000676,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,위성센터,8000676,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,위성센터,8000676,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,위성센터,8000676,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,위성센터,8000676,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,위성센터,8000676,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,위성센터,8000676,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,위성센터,8000676,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,위성센터,8000676,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,위성센터,8000676,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오창  [8000693]  (36.72319, 127.44011)
📍 요청 위치: (36.7232°N, 127.4401°E)
📍 격자 좌표: (x=68, y=109)
📍 실제 위치: (36.7450°N, 127.4361°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오창,8000693,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,오창,8000693,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,오창,8000693,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,오창,8000693,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,오창,8000693,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,오창,8000693,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,오창,8000693,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,오창,8000693,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,오창,8000693,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,오창,8000693,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,오창,8000693,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,오창,8000693,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,오창,8000693,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,오창,8000693,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,오창,8000693,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,오창,8000693,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,오창,8000693,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,오창,8000693,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,오창,8000693,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,오창,8000693,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,오창,8000693,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,오창,8000693,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,오창,8000693,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,오창,8000693,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,오창,8000693,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,오창,8000693,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,오창,8000693,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,오창,8000693,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,오창,8000693,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,오창,8000693,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,오창,8000693,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,오창,8000693,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,오창,8000693,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,오창,8000693,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,오창,8000693,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,오창,8000693,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,오창,8000693,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,오창,8000693,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,오창,8000693,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,오창,8000693,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,오창,8000693,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,오창,8000693,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청남대  [8000888]  (36.46267, 127.49074)
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청남대,8000888,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청남대,8000888,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청남대,8000888,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청남대,8000888,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청남대,8000888,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청남대,8000888,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청남대,8000888,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청남대,8000888,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청남대,8000888,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청남대,8000888,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청남대,8000888,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청남대,8000888,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청남대,8000888,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청남대,8000888,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청남대,8000888,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청남대,8000888,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청남대,8000888,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청남대,8000888,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청남대,8000888,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청남대,8000888,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청남대,8000888,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청남대,8000888,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청남대,8000888,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청남대,8000888,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청남대,8000888,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청남대,8000888,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청남대,8000888,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청남대,8000888,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청남대,8000888,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청남대,8000888,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청남대,8000888,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청남대,8000888,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청남대,8000888,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청남대,8000888,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청남대,8000888,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청남대,8000888,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청남대,8000888,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청남대,8000888,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오창가곡  [8000977]  (36.72455, 127.46688)
📍 요청 위치: (36.7246°N, 127.4669°E)
📍 격자 좌표: (x=69, y=109)
📍 실제 위치: (36.7442°N, 127.4935°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오창가곡,8000977,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,오창가곡,8000977,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,오창가곡,8000977,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,오창가곡,8000977,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,오창가곡,8000977,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,오창가곡,8000977,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,오창가곡,8000977,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,오창가곡,8000977,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,오창가곡,8000977,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,오창가곡,8000977,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,오창가곡,8000977,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,오창가곡,8000977,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,오창가곡,8000977,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,오창가곡,8000977,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,오창가곡,8000977,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,오창가곡,8000977,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,오창가곡,8000977,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,오창가곡,8000977,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,오창가곡,8000977,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,오창가곡,8000977,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,오창가곡,8000977,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,오창가곡,8000977,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,오창가곡,8000977,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,오창가곡,8000977,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,오창가곡,8000977,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,오창가곡,8000977,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,오창가곡,8000977,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,오창가곡,8000977,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,오창가곡,8000977,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,오창가곡,8000977,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,오창가곡,8000977,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,오창가곡,8000977,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,오창가곡,8000977,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,오창가곡,8000977,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,오창가곡,8000977,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,오창가곡,8000977,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,오창가곡,8000977,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,오창가곡,8000977,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,오창가곡,8000977,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,오창가곡,8000977,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,오창가곡,8000977,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,오창가곡,8000977,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 사곡면  [8004870]  (36.52611, 127.03107)
📍 요청 위치: (36.5261°N, 127.0311°E)
📍 격자 좌표: (x=61, y=104)
📍 실제 위치: (36.5200°N, 127.0303°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,사곡면,8004870,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,사곡면,8004870,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,사곡면,8004870,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,사곡면,8004870,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,사곡면,8004870,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,사곡면,8004870,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,사곡면,8004870,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,사곡면,8004870,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,사곡면,8004870,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,사곡면,8004870,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,사곡면,8004870,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,사곡면,8004870,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,사곡면,8004870,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,사곡면,8004870,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,사곡면,8004870,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,사곡면,8004870,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,사곡면,8004870,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,사곡면,8004870,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,사곡면,8004870,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,사곡면,8004870,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,사곡면,8004870,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,사곡면,8004870,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,사곡면,8004870,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,사곡면,8004870,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,사곡면,8004870,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,사곡면,8004870,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,사곡면,8004870,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,사곡면,8004870,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,사곡면,8004870,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,사곡면,8004870,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,사곡면,8004870,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,사곡면,8004870,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,사곡면,8004870,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,사곡면,8004870,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,사곡면,8004870,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,사곡면,8004870,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,사곡면,8004870,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,사곡면,8004870,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,사곡면,8004870,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,사곡면,8004870,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,사곡면,8004870,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,사곡면,8004870,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(우성면)  [8004710]  (36.4934, 127.09924)
📍 요청 위치: (36.4934°N, 127.0992°E)
📍 격자 좌표: (x=62, y=103)
📍 실제 위치: (36.4734°N, 127.0868°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(우성면),8004710,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(우성면),8004710,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(우성면),8004710,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(우성면),8004710,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(우성면),8004710,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(우성면),8004710,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(우성면),8004710,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(우성면),8004710,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(우성면),8004710,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(우성면),8004710,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(우성면),8004710,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(우성면),8004710,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(우성면),8004710,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(우성면),8004710,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(우성면),8004710,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(우성면),8004710,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(우성면),8004710,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(우성면),8004710,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(우성면),8004710,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(우성면),8004710,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(우성면),8004710,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(우성면),8004710,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(우성면),8004710,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(우성면),8004710,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(우성면),8004710,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(우성면),8004710,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(우성면),8004710,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(우성면),8004710,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(우성면),8004710,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(우성면),8004710,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(우성면),8004710,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(우성면),8004710,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(우성면),8004710,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(우성면),8004710,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(우성면),8004710,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(우성면),8004710,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(우성면),8004710,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(우성면),8004710,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(우성면),8004710,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(우성면),8004710,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(우성면),8004710,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(우성면),8004710,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성 개미산  [8003023]  (36.87073, 127.62391)
📍 요청 위치: (36.8707°N, 127.6239°E)
📍 격자 좌표: (x=71, y=112)
📍 실제 위치: (36.8805°N, 127.6118°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성 개미산,8003023,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,음성 개미산,8003023,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,음성 개미산,8003023,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,음성 개미산,8003023,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,음성 개미산,8003023,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,음성 개미산,8003023,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,음성 개미산,8003023,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,음성 개미산,8003023,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,음성 개미산,8003023,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,음성 개미산,8003023,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,음성 개미산,8003023,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,음성 개미산,8003023,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,음성 개미산,8003023,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,음성 개미산,8003023,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,음성 개미산,8003023,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,음성 개미산,8003023,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,음성 개미산,8003023,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,음성 개미산,8003023,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,음성 개미산,8003023,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,음성 개미산,8003023,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,음성 개미산,8003023,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,음성 개미산,8003023,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,음성 개미산,8003023,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,음성 개미산,8003023,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,음성 개미산,8003023,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,음성 개미산,8003023,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,음성 개미산,8003023,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,음성 개미산,8003023,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,음성 개미산,8003023,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,음성 개미산,8003023,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,음성 개미산,8003023,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,음성 개미산,8003023,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,음성 개미산,8003023,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,음성 개미산,8003023,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,음성 개미산,8003023,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,음성 개미산,8003023,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,음성 개미산,8003023,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,음성 개미산,8003023,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,음성 개미산,8003023,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,음성 개미산,8003023,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,음성 개미산,8003023,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,음성 개미산,8003023,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주 오봉산  [8003911]  (36.58329, 127.61647)
📍 요청 위치: (36.5833°N, 127.6165°E)
📍 격자 좌표: (x=71, y=106)
📍 실제 위치: (36.6044°N, 127.6049°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주 오봉산,8003911,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주 오봉산,8003911,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주 오봉산,8003911,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주 오봉산,8003911,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주 오봉산,8003911,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주 오봉산,8003911,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주 오봉산,8003911,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주 오봉산,8003911,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주 오봉산,8003911,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주 오봉산,8003911,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주 오봉산,8003911,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주 오봉산,8003911,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주 오봉산,8003911,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주 오봉산,8003911,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주 오봉산,8003911,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주 오봉산,8003911,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주 오봉산,8003911,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주 오봉산,8003911,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주 오봉산,8003911,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주 오봉산,8003911,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주 오봉산,8003911,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주 오봉산,8003911,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주 오봉산,8003911,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주 오봉산,8003911,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주 오봉산,8003911,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주 오봉산,8003911,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주 오봉산,8003911,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주 오봉산,8003911,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주 오봉산,8003911,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주 오봉산,8003911,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주 오봉산,8003911,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주 오봉산,8003911,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주 오봉산,8003911,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주 오봉산,8003911,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주 오봉산,8003911,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주 오봉산,8003911,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주 오봉산,8003911,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주 오봉산,8003911,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주 오봉산,8003911,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주 오봉산,8003911,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주 오봉산,8003911,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주 오봉산,8003911,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 축융봉  [8004891]  (36.32578, 126.77832)
📍 요청 위치: (36.3258°N, 126.7783°E)
📍 격자 좌표: (x=57, y=100)
📍 실제 위치: (36.3381°N, 126.7991°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,축융봉,8004891,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,축융봉,8004891,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,축융봉,8004891,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,축융봉,8004891,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,축융봉,8004891,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,축융봉,8004891,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,축융봉,8004891,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,축융봉,8004891,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,축융봉,8004891,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,축융봉,8004891,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,축융봉,8004891,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,축융봉,8004891,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,축융봉,8004891,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,축융봉,8004891,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,축융봉,8004891,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,축융봉,8004891,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,축융봉,8004891,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,축융봉,8004891,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,축융봉,8004891,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,축융봉,8004891,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,축융봉,8004891,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,축융봉,8004891,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,축융봉,8004891,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,축융봉,8004891,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,축융봉,8004891,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,축융봉,8004891,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,축융봉,8004891,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,축융봉,8004891,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,축융봉,8004891,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,축융봉,8004891,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,축융봉,8004891,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,축융봉,8004891,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,축융봉,8004891,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,축융봉,8004891,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,축융봉,8004891,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,축융봉,8004891,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,축융봉,8004891,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,축융봉,8004891,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,축융봉,8004891,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,축융봉,8004891,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,축융봉,8004891,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,축융봉,8004891,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주 국사봉  [8004893]  (36.61002, 127.04296)
📍 요청 위치: (36.6100°N, 127.0430°E)
📍 격자 좌표: (x=61, y=106)
📍 실제 위치: (36.6120°N, 127.0318°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주 국사봉,8004893,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주 국사봉,8004893,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주 국사봉,8004893,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주 국사봉,8004893,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주 국사봉,8004893,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주 국사봉,8004893,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주 국사봉,8004893,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주 국사봉,8004893,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주 국사봉,8004893,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주 국사봉,8004893,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주 국사봉,8004893,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주 국사봉,8004893,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주 국사봉,8004893,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주 국사봉,8004893,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주 국사봉,8004893,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주 국사봉,8004893,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주 국사봉,8004893,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주 국사봉,8004893,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주 국사봉,8004893,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주 국사봉,8004893,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주 국사봉,8004893,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주 국사봉,8004893,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주 국사봉,8004893,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주 국사봉,8004893,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주 국사봉,8004893,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주 국사봉,8004893,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주 국사봉,8004893,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주 국사봉,8004893,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주 국사봉,8004893,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주 국사봉,8004893,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주 국사봉,8004893,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주 국사봉,8004893,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주 국사봉,8004893,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주 국사봉,8004893,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주 국사봉,8004893,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주 국사봉,8004893,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주 국사봉,8004893,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주 국사봉,8004893,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주 국사봉,8004893,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주 국사봉,8004893,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주 국사봉,8004893,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주 국사봉,8004893,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장군산  [8004897]  (36.46854, 127.19491)
📍 요청 위치: (36.4685°N, 127.1949°E)
📍 격자 좌표: (x=64, y=103)
📍 실제 위치: (36.4721°N, 127.2012°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장군산,8004897,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,장군산,8004897,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,장군산,8004897,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,장군산,8004897,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,장군산,8004897,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,장군산,8004897,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,장군산,8004897,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,장군산,8004897,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,장군산,8004897,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,장군산,8004897,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,장군산,8004897,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,장군산,8004897,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,장군산,8004897,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,장군산,8004897,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,장군산,8004897,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,장군산,8004897,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,장군산,8004897,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,장군산,8004897,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,장군산,8004897,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,장군산,8004897,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,장군산,8004897,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,장군산,8004897,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,장군산,8004897,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,장군산,8004897,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,장군산,8004897,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,장군산,8004897,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,장군산,8004897,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,장군산,8004897,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,장군산,8004897,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,장군산,8004897,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,장군산,8004897,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,장군산,8004897,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,장군산,8004897,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,장군산,8004897,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,장군산,8004897,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,장군산,8004897,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,장군산,8004897,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,장군산,8004897,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,장군산,8004897,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,장군산,8004897,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,장군산,8004897,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,장군산,8004897,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안 국사봉  [8004898]  (36.6263, 127.15825)
📍 요청 위치: (36.6263°N, 127.1582°E)
📍 격자 좌표: (x=63, y=106)
📍 실제 위치: (36.6107°N, 127.1464°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안 국사봉,8004898,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안 국사봉,8004898,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안 국사봉,8004898,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안 국사봉,8004898,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안 국사봉,8004898,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안 국사봉,8004898,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안 국사봉,8004898,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안 국사봉,8004898,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안 국사봉,8004898,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안 국사봉,8004898,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안 국사봉,8004898,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안 국사봉,8004898,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안 국사봉,8004898,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안 국사봉,8004898,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안 국사봉,8004898,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안 국사봉,8004898,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안 국사봉,8004898,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안 국사봉,8004898,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안 국사봉,8004898,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안 국사봉,8004898,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안 국사봉,8004898,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안 국사봉,8004898,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안 국사봉,8004898,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안 국사봉,8004898,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안 국사봉,8004898,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안 국사봉,8004898,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안 국사봉,8004898,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안 국사봉,8004898,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안 국사봉,8004898,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안 국사봉,8004898,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안 국사봉,8004898,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안 국사봉,8004898,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안 국사봉,8004898,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안 국사봉,8004898,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안 국사봉,8004898,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안 국사봉,8004898,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안 국사봉,8004898,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안 국사봉,8004898,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안 국사봉,8004898,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안 국사봉,8004898,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안 국사봉,8004898,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안 국사봉,8004898,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산 묘련봉  [8004899]  (36.16843, 127.2661)
📍 요청 위치: (36.1684°N, 127.2661°E)
📍 격자 좌표: (x=65, y=96)
📍 실제 위치: (36.1496°N, 127.2521°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산 묘련봉,8004899,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산 묘련봉,8004899,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산 묘련봉,8004899,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산 묘련봉,8004899,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산 묘련봉,8004899,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산 묘련봉,8004899,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산 묘련봉,8004899,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산 묘련봉,8004899,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산 묘련봉,8004899,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산 묘련봉,8004899,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산 묘련봉,8004899,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산 묘련봉,8004899,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산 묘련봉,8004899,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산 묘련봉,8004899,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산 묘련봉,8004899,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산 묘련봉,8004899,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산 묘련봉,8004899,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산 묘련봉,8004899,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산 묘련봉,8004899,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산 묘련봉,8004899,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산 묘련봉,8004899,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산 묘련봉,8004899,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산 묘련봉,8004899,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산 묘련봉,8004899,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산 묘련봉,8004899,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산 묘련봉,8004899,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산 묘련봉,8004899,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산 묘련봉,8004899,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산 묘련봉,8004899,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산 묘련봉,8004899,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산 묘련봉,8004899,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산 묘련봉,8004899,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산 묘련봉,8004899,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산 묘련봉,8004899,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산 묘련봉,8004899,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산 묘련봉,8004899,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산 묘련봉,8004899,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산 묘련봉,8004899,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산 묘련봉,8004899,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산 묘련봉,8004899,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산 묘련봉,8004899,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산 묘련봉,8004899,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 관불산  [8004910]  (36.5704, 127.2054)
📍 요청 위치: (36.5704°N, 127.2054°E)
📍 격자 좌표: (x=64, y=105)
📍 실제 위치: (36.5640°N, 127.2029°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,관불산,8004910,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,관불산,8004910,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,관불산,8004910,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,관불산,8004910,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,관불산,8004910,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,관불산,8004910,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,관불산,8004910,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,관불산,8004910,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,관불산,8004910,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,관불산,8004910,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,관불산,8004910,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,관불산,8004910,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,관불산,8004910,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,관불산,8004910,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,관불산,8004910,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,관불산,8004910,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,관불산,8004910,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,관불산,8004910,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,관불산,8004910,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,관불산,8004910,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,관불산,8004910,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,관불산,8004910,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,관불산,8004910,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,관불산,8004910,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,관불산,8004910,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,관불산,8004910,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,관불산,8004910,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,관불산,8004910,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,관불산,8004910,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,관불산,8004910,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,관불산,8004910,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,관불산,8004910,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,관불산,8004910,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,관불산,8004910,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,관불산,8004910,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,관불산,8004910,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,관불산,8004910,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,관불산,8004910,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,관불산,8004910,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,관불산,8004910,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,관불산,8004910,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,관불산,8004910,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 칠불산  [8004911]  (36.4864, 127.3465)
📍 요청 위치: (36.4864°N, 127.3465°E)
📍 격자 좌표: (x=67, y=103)
📍 실제 위치: (36.4698°N, 127.3727°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,칠불산,8004911,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,칠불산,8004911,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,칠불산,8004911,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,칠불산,8004911,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,칠불산,8004911,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,칠불산,8004911,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,칠불산,8004911,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,칠불산,8004911,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,칠불산,8004911,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,칠불산,8004911,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,칠불산,8004911,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,칠불산,8004911,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,칠불산,8004911,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,칠불산,8004911,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,칠불산,8004911,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,칠불산,8004911,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,칠불산,8004911,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,칠불산,8004911,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,칠불산,8004911,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,칠불산,8004911,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,칠불산,8004911,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,칠불산,8004911,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,칠불산,8004911,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,칠불산,8004911,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,칠불산,8004911,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,칠불산,8004911,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,칠불산,8004911,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,칠불산,8004911,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,칠불산,8004911,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,칠불산,8004911,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,칠불산,8004911,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,칠불산,8004911,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,칠불산,8004911,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,칠불산,8004911,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,칠불산,8004911,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,칠불산,8004911,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,칠불산,8004911,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,칠불산,8004911,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,칠불산,8004911,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,칠불산,8004911,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,칠불산,8004911,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,칠불산,8004911,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산내동  [8004102]  (36.2818, 127.4677)
📍 요청 위치: (36.2818°N, 127.4677°E)
📍 격자 좌표: (x=69, y=99)
📍 실제 위치: (36.2843°N, 127.4829°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산내동,8004102,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,산내동,8004102,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,산내동,8004102,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,산내동,8004102,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,산내동,8004102,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,산내동,8004102,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,산내동,8004102,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,산내동,8004102,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,산내동,8004102,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,산내동,8004102,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,산내동,8004102,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,산내동,8004102,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,산내동,8004102,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,산내동,8004102,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,산내동,8004102,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,산내동,8004102,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,산내동,8004102,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,산내동,8004102,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,산내동,8004102,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,산내동,8004102,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,산내동,8004102,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,산내동,8004102,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,산내동,8004102,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,산내동,8004102,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,산내동,8004102,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,산내동,8004102,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,산내동,8004102,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,산내동,8004102,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,산내동,8004102,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,산내동,8004102,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,산내동,8004102,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,산내동,8004102,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,산내동,8004102,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,산내동,8004102,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,산내동,8004102,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,산내동,8004102,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,산내동,8004102,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,산내동,8004102,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,산내동,8004102,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,산내동,8004102,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,산내동,8004102,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,산내동,8004102,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 기성동  [8004104]  (36.2557, 127.3416)
📍 요청 위치: (36.2557°N, 127.3416°E)
📍 격자 좌표: (x=67, y=98)
📍 실제 위치: (36.2400°N, 127.3678°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,기성동,8004104,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,기성동,8004104,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,기성동,8004104,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,기성동,8004104,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,기성동,8004104,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,기성동,8004104,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,기성동,8004104,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,기성동,8004104,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,기성동,8004104,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,기성동,8004104,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,기성동,8004104,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,기성동,8004104,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,기성동,8004104,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,기성동,8004104,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,기성동,8004104,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,기성동,8004104,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,기성동,8004104,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,기성동,8004104,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,기성동,8004104,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,기성동,8004104,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,기성동,8004104,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,기성동,8004104,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,기성동,8004104,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,기성동,8004104,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,기성동,8004104,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,기성동,8004104,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,기성동,8004104,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,기성동,8004104,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,기성동,8004104,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,기성동,8004104,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,기성동,8004104,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,기성동,8004104,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,기성동,8004104,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,기성동,8004104,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,기성동,8004104,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,기성동,8004104,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,기성동,8004104,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,기성동,8004104,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,기성동,8004104,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,기성동,8004104,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,기성동,8004104,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,기성동,8004104,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정림동  [8004106]  (36.3045, 127.3667)
📍 요청 위치: (36.3045°N, 127.3667°E)
📍 격자 좌표: (x=67, y=99)
📍 실제 위치: (36.2859°N, 127.3688°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정림동,8004106,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,정림동,8004106,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,정림동,8004106,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,정림동,8004106,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,정림동,8004106,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,정림동,8004106,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,정림동,8004106,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,정림동,8004106,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,정림동,8004106,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,정림동,8004106,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,정림동,8004106,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,정림동,8004106,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,정림동,8004106,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,정림동,8004106,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,정림동,8004106,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,정림동,8004106,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,정림동,8004106,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,정림동,8004106,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,정림동,8004106,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,정림동,8004106,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,정림동,8004106,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,정림동,8004106,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,정림동,8004106,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,정림동,8004106,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,정림동,8004106,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,정림동,8004106,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,정림동,8004106,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,정림동,8004106,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,정림동,8004106,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,정림동,8004106,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,정림동,8004106,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,정림동,8004106,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,정림동,8004106,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,정림동,8004106,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,정림동,8004106,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,정림동,8004106,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,정림동,8004106,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,정림동,8004106,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,정림동,8004106,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,정림동,8004106,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,정림동,8004106,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,정림동,8004106,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 구즉동  [8004107]  (36.4404, 127.3838)
📍 요청 위치: (36.4404°N, 127.3838°E)
📍 격자 좌표: (x=67, y=102)
📍 실제 위치: (36.4239°N, 127.3717°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,구즉동,8004107,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,구즉동,8004107,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,구즉동,8004107,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,구즉동,8004107,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,구즉동,8004107,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,구즉동,8004107,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,구즉동,8004107,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,구즉동,8004107,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,구즉동,8004107,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,구즉동,8004107,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,구즉동,8004107,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,구즉동,8004107,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,구즉동,8004107,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,구즉동,8004107,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,구즉동,8004107,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,구즉동,8004107,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,구즉동,8004107,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,구즉동,8004107,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,구즉동,8004107,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,구즉동,8004107,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,구즉동,8004107,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,구즉동,8004107,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,구즉동,8004107,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,구즉동,8004107,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,구즉동,8004107,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,구즉동,8004107,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,구즉동,8004107,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,구즉동,8004107,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,구즉동,8004107,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,구즉동,8004107,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,구즉동,8004107,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,구즉동,8004107,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,구즉동,8004107,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,구즉동,8004107,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,구즉동,8004107,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,구즉동,8004107,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,구즉동,8004107,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,구즉동,8004107,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,구즉동,8004107,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,구즉동,8004107,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,구즉동,8004107,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,구즉동,8004107,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진잠동  [8004110]  (36.2998, 127.3165)
📍 요청 위치: (36.2998°N, 127.3165°E)
📍 격자 좌표: (x=66, y=99)
📍 실제 위치: (36.2867°N, 127.3118°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진잠동,8004110,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진잠동,8004110,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진잠동,8004110,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진잠동,8004110,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진잠동,8004110,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진잠동,8004110,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진잠동,8004110,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진잠동,8004110,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진잠동,8004110,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진잠동,8004110,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진잠동,8004110,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진잠동,8004110,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진잠동,8004110,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진잠동,8004110,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진잠동,8004110,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진잠동,8004110,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진잠동,8004110,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진잠동,8004110,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진잠동,8004110,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진잠동,8004110,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진잠동,8004110,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진잠동,8004110,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진잠동,8004110,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진잠동,8004110,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진잠동,8004110,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진잠동,8004110,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진잠동,8004110,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진잠동,8004110,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진잠동,8004110,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진잠동,8004110,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진잠동,8004110,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진잠동,8004110,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진잠동,8004110,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진잠동,8004110,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진잠동,8004110,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진잠동,8004110,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진잠동,8004110,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진잠동,8004110,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진잠동,8004110,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진잠동,8004110,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진잠동,8004110,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진잠동,8004110,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대덕구청  [8004115]  (36.3467, 127.4156)
📍 요청 위치: (36.3467°N, 127.4156°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대덕구청,8004115,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대덕구청,8004115,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대덕구청,8004115,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대덕구청,8004115,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대덕구청,8004115,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대덕구청,8004115,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대덕구청,8004115,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대덕구청,8004115,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대덕구청,8004115,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대덕구청,8004115,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대덕구청,8004115,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대덕구청,8004115,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대덕구청,8004115,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대덕구청,8004115,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대덕구청,8004115,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대덕구청,8004115,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대덕구청,8004115,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대덕구청,8004115,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대덕구청,8004115,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대덕구청,8004115,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대덕구청,8004115,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대덕구청,8004115,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대덕구청,8004115,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대덕구청,8004115,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대덕구청,8004115,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대덕구청,8004115,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대덕구청,8004115,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대덕구청,8004115,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대덕구청,8004115,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대덕구청,8004115,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대덕구청,8004115,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대덕구청,8004115,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대덕구청,8004115,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대덕구청,8004115,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대덕구청,8004115,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대덕구청,8004115,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대덕구청,8004115,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대덕구청,8004115,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대덕구청,8004115,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대덕구청,8004115,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대덕구청,8004115,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대덕구청,8004115,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산흥초교  [8004125]  (36.2287, 127.4484)
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산흥초교,8004125,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,산흥초교,8004125,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,산흥초교,8004125,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,산흥초교,8004125,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,산흥초교,8004125,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,산흥초교,8004125,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,산흥초교,8004125,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,산흥초교,8004125,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,산흥초교,8004125,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,산흥초교,8004125,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,산흥초교,8004125,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,산흥초교,8004125,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,산흥초교,8004125,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,산흥초교,8004125,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,산흥초교,8004125,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,산흥초교,8004125,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,산흥초교,8004125,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,산흥초교,8004125,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,산흥초교,8004125,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,산흥초교,8004125,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,산흥초교,8004125,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,산흥초교,8004125,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,산흥초교,8004125,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,산흥초교,8004125,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,산흥초교,8004125,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,산흥초교,8004125,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,산흥초교,8004125,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,산흥초교,8004125,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,산흥초교,8004125,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,산흥초교,8004125,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,산흥초교,8004125,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,산흥초교,8004125,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,산흥초교,8004125,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,산흥초교,8004125,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노은터널  [8004127]  (36.36512, 127.30841)
📍 요청 위치: (36.3651°N, 127.3084°E)
📍 격자 좌표: (x=66, y=101)
📍 실제 위치: (36.3786°N, 127.3137°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노은터널,8004127,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,노은터널,8004127,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,노은터널,8004127,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,노은터널,8004127,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,노은터널,8004127,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,노은터널,8004127,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,노은터널,8004127,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,노은터널,8004127,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,노은터널,8004127,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,노은터널,8004127,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,노은터널,8004127,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,노은터널,8004127,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,노은터널,8004127,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,노은터널,8004127,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,노은터널,8004127,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,노은터널,8004127,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,노은터널,8004127,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,노은터널,8004127,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,노은터널,8004127,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,노은터널,8004127,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,노은터널,8004127,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,노은터널,8004127,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,노은터널,8004127,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,노은터널,8004127,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,노은터널,8004127,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,노은터널,8004127,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,노은터널,8004127,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,노은터널,8004127,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,노은터널,8004127,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,노은터널,8004127,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,노은터널,8004127,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,노은터널,8004127,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,노은터널,8004127,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,노은터널,8004127,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,노은터널,8004127,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,노은터널,8004127,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,노은터널,8004127,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,노은터널,8004127,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,노은터널,8004127,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,노은터널,8004127,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,노은터널,8004127,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,노은터널,8004127,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 어진동  [8004142]  (36.5158, 127.2617)
📍 요청 위치: (36.5158°N, 127.2617°E)
📍 격자 좌표: (x=65, y=104)
📍 실제 위치: (36.5173°N, 127.2592°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,어진동,8004142,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,어진동,8004142,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,어진동,8004142,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,어진동,8004142,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,어진동,8004142,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,어진동,8004142,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,어진동,8004142,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,어진동,8004142,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,어진동,8004142,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,어진동,8004142,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,어진동,8004142,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,어진동,8004142,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,어진동,8004142,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,어진동,8004142,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,어진동,8004142,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,어진동,8004142,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,어진동,8004142,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,어진동,8004142,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,어진동,8004142,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,어진동,8004142,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,어진동,8004142,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,어진동,8004142,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,어진동,8004142,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,어진동,8004142,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,어진동,8004142,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,어진동,8004142,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,어진동,8004142,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,어진동,8004142,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,어진동,8004142,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,어진동,8004142,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,어진동,8004142,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,어진동,8004142,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,어진동,8004142,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,어진동,8004142,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,어진동,8004142,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,어진동,8004142,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,어진동,8004142,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,어진동,8004142,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,어진동,8004142,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,어진동,8004142,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,어진동,8004142,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,어진동,8004142,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 연동내판  [8004266]  (36.55522, 127.32729)
📍 요청 위치: (36.5552°N, 127.3273°E)
📍 격자 좌표: (x=66, y=105)
📍 실제 위치: (36.5626°N, 127.3174°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,연동내판,8004266,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,연동내판,8004266,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,연동내판,8004266,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,연동내판,8004266,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,연동내판,8004266,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,연동내판,8004266,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,연동내판,8004266,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,연동내판,8004266,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,연동내판,8004266,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,연동내판,8004266,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,연동내판,8004266,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,연동내판,8004266,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,연동내판,8004266,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,연동내판,8004266,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,연동내판,8004266,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,연동내판,8004266,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,연동내판,8004266,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,연동내판,8004266,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,연동내판,8004266,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,연동내판,8004266,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,연동내판,8004266,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,연동내판,8004266,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,연동내판,8004266,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,연동내판,8004266,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,연동내판,8004266,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,연동내판,8004266,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,연동내판,8004266,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,연동내판,8004266,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,연동내판,8004266,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,연동내판,8004266,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,연동내판,8004266,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,연동내판,8004266,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,연동내판,8004266,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,연동내판,8004266,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,연동내판,8004266,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,연동내판,8004266,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,연동내판,8004266,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,연동내판,8004266,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,연동내판,8004266,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,연동내판,8004266,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,연동내판,8004266,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,연동내판,8004266,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 전동노장  [8004267]  (36.6628, 127.23358)
📍 요청 위치: (36.6628°N, 127.2336°E)
📍 격자 좌표: (x=65, y=107)
📍 실제 위치: (36.6553°N, 127.2620°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,전동노장,8004267,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,전동노장,8004267,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,전동노장,8004267,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,전동노장,8004267,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,전동노장,8004267,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,전동노장,8004267,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,전동노장,8004267,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,전동노장,8004267,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,전동노장,8004267,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,전동노장,8004267,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,전동노장,8004267,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,전동노장,8004267,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,전동노장,8004267,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,전동노장,8004267,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,전동노장,8004267,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,전동노장,8004267,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,전동노장,8004267,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,전동노장,8004267,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,전동노장,8004267,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,전동노장,8004267,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,전동노장,8004267,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,전동노장,8004267,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,전동노장,8004267,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,전동노장,8004267,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,전동노장,8004267,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,전동노장,8004267,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,전동노장,8004267,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,전동노장,8004267,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,전동노장,8004267,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,전동노장,8004267,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,전동노장,8004267,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,전동노장,8004267,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,전동노장,8004267,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,전동노장,8004267,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,전동노장,8004267,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,전동노장,8004267,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,전동노장,8004267,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,전동노장,8004267,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,전동노장,8004267,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,전동노장,8004267,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,전동노장,8004267,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,전동노장,8004267,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 시청보람동  [8004270]  (36.47993, 127.28882)
📍 요청 위치: (36.4799°N, 127.2888°E)
📍 격자 좌표: (x=66, y=103)
📍 실제 위치: (36.4706°N, 127.3155°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,시청보람동,8004270,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,시청보람동,8004270,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,시청보람동,8004270,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,시청보람동,8004270,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,시청보람동,8004270,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,시청보람동,8004270,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,시청보람동,8004270,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,시청보람동,8004270,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,시청보람동,8004270,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,시청보람동,8004270,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,시청보람동,8004270,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,시청보람동,8004270,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,시청보람동,8004270,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,시청보람동,8004270,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,시청보람동,8004270,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,시청보람동,8004270,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,시청보람동,8004270,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,시청보람동,8004270,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,시청보람동,8004270,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,시청보람동,8004270,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,시청보람동,8004270,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,시청보람동,8004270,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,시청보람동,8004270,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,시청보람동,8004270,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,시청보람동,8004270,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,시청보람동,8004270,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,시청보람동,8004270,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,시청보람동,8004270,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,시청보람동,8004270,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,시청보람동,8004270,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,시청보람동,8004270,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,시청보람동,8004270,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,시청보람동,8004270,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,시청보람동,8004270,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,시청보람동,8004270,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,시청보람동,8004270,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,시청보람동,8004270,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,시청보람동,8004270,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,시청보람동,8004270,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,시청보람동,8004270,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,시청보람동,8004270,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,시청보람동,8004270,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군산_나포면  [8005113]  (36.03047, 126.83204)
📍 요청 위치: (36.0305°N, 126.8320°E)
📍 격자 좌표: (x=58, y=93)
📍 실제 위치: (36.0160°N, 126.8519°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군산_나포면,8005113,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,군산_나포면,8005113,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,군산_나포면,8005113,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,군산_나포면,8005113,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,군산_나포면,8005113,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,군산_나포면,8005113,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,군산_나포면,8005113,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,군산_나포면,8005113,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,군산_나포면,8005113,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,군산_나포면,8005113,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,군산_나포면,8005113,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,군산_나포면,8005113,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,군산_나포면,8005113,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,군산_나포면,8005113,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,군산_나포면,8005113,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,군산_나포면,8005113,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,군산_나포면,8005113,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,군산_나포면,8005113,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,군산_나포면,8005113,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,군산_나포면,8005113,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,군산_나포면,8005113,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,군산_나포면,8005113,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,군산_나포면,8005113,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,군산_나포면,8005113,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,군산_나포면,8005113,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,군산_나포면,8005113,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,군산_나포면,8005113,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,군산_나포면,8005113,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,군산_나포면,8005113,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,군산_나포면,8005113,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,군산_나포면,8005113,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,군산_나포면,8005113,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,군산_나포면,8005113,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,군산_나포면,8005113,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,군산_나포면,8005113,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,군산_나포면,8005113,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,군산_나포면,8005113,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,군산_나포면,8005113,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,군산_나포면,8005113,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,군산_나포면,8005113,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,군산_나포면,8005113,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,군산_나포면,8005113,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산_용안면  [8005128]  (36.12, 126.9523)
📍 요청 위치: (36.1200°N, 126.9523°E)
📍 격자 좌표: (x=60, y=95)
📍 실제 위치: (36.1068°N, 126.9669°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산_용안면,8005128,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,익산_용안면,8005128,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,익산_용안면,8005128,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,익산_용안면,8005128,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,익산_용안면,8005128,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,익산_용안면,8005128,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,익산_용안면,8005128,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,익산_용안면,8005128,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,익산_용안면,8005128,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,익산_용안면,8005128,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,익산_용안면,8005128,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,익산_용안면,8005128,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,익산_용안면,8005128,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,익산_용안면,8005128,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,익산_용안면,8005128,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,익산_용안면,8005128,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,익산_용안면,8005128,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,익산_용안면,8005128,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,익산_용안면,8005128,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,익산_용안면,8005128,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,익산_용안면,8005128,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,익산_용안면,8005128,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,익산_용안면,8005128,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,익산_용안면,8005128,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,익산_용안면,8005128,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,익산_용안면,8005128,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,익산_용안면,8005128,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,익산_용안면,8005128,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,익산_용안면,8005128,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,익산_용안면,8005128,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,익산_용안면,8005128,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,익산_용안면,8005128,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,익산_용안면,8005128,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,익산_용안면,8005128,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,익산_용안면,8005128,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,익산_용안면,8005128,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,익산_용안면,8005128,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,익산_용안면,8005128,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,익산_용안면,8005128,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,익산_용안면,8005128,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,익산_용안면,8005128,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,익산_용안면,8005128,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 완주_대둔산  [8005200]  (36.11517, 127.3333)
📍 요청 위치: (36.1152°N, 127.3333°E)
📍 격자 좌표: (x=66, y=95)
📍 실제 위치: (36.1029°N, 127.3081°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,완주_대둔산,8005200,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,완주_대둔산,8005200,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,완주_대둔산,8005200,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,완주_대둔산,8005200,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,완주_대둔산,8005200,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,완주_대둔산,8005200,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,완주_대둔산,8005200,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,완주_대둔산,8005200,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,완주_대둔산,8005200,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,완주_대둔산,8005200,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,완주_대둔산,8005200,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,완주_대둔산,8005200,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,완주_대둔산,8005200,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,완주_대둔산,8005200,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,완주_대둔산,8005200,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,완주_대둔산,8005200,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,완주_대둔산,8005200,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,완주_대둔산,8005200,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,완주_대둔산,8005200,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,완주_대둔산,8005200,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,완주_대둔산,8005200,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,완주_대둔산,8005200,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,완주_대둔산,8005200,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,완주_대둔산,8005200,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,완주_대둔산,8005200,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,완주_대둔산,8005200,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,완주_대둔산,8005200,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,완주_대둔산,8005200,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,완주_대둔산,8005200,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,완주_대둔산,8005200,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,완주_대둔산,8005200,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,완주_대둔산,8005200,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,완주_대둔산,8005200,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,완주_대둔산,8005200,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,완주_대둔산,8005200,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,완주_대둔산,8005200,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,완주_대둔산,8005200,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,완주_대둔산,8005200,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,완주_대둔산,8005200,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,완주_대둔산,8005200,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,완주_대둔산,8005200,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,완주_대둔산,8005200,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 우성동대  [8004157]  (36.4709, 127.0497)
📍 요청 위치: (36.4709°N, 127.0497°E)
📍 격자 좌표: (x=61, y=103)
📍 실제 위치: (36.4740°N, 127.0296°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,우성동대,8004157,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,우성동대,8004157,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,우성동대,8004157,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,우성동대,8004157,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,우성동대,8004157,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,우성동대,8004157,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,우성동대,8004157,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,우성동대,8004157,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,우성동대,8004157,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,우성동대,8004157,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,우성동대,8004157,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,우성동대,8004157,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,우성동대,8004157,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,우성동대,8004157,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,우성동대,8004157,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,우성동대,8004157,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,우성동대,8004157,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,우성동대,8004157,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,우성동대,8004157,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,우성동대,8004157,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,우성동대,8004157,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,우성동대,8004157,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,우성동대,8004157,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,우성동대,8004157,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,우성동대,8004157,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,우성동대,8004157,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,우성동대,8004157,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,우성동대,8004157,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,우성동대,8004157,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,우성동대,8004157,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,우성동대,8004157,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,우성동대,8004157,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,우성동대,8004157,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,우성동대,8004157,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,우성동대,8004157,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,우성동대,8004157,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,우성동대,8004157,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,우성동대,8004157,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,우성동대,8004157,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,우성동대,8004157,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,우성동대,8004157,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,우성동대,8004157,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주봉황  [8004158]  (36.4471, 127.1192)
📍 요청 위치: (36.4471°N, 127.1192°E)
📍 격자 좌표: (x=63, y=102)
📍 실제 위치: (36.4267°N, 127.1432°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주봉황,8004158,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주봉황,8004158,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주봉황,8004158,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주봉황,8004158,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주봉황,8004158,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주봉황,8004158,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주봉황,8004158,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주봉황,8004158,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주봉황,8004158,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주봉황,8004158,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주봉황,8004158,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주봉황,8004158,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주봉황,8004158,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주봉황,8004158,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주봉황,8004158,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주봉황,8004158,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주봉황,8004158,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주봉황,8004158,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주봉황,8004158,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주봉황,8004158,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주봉황,8004158,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주봉황,8004158,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주봉황,8004158,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주봉황,8004158,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주봉황,8004158,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주봉황,8004158,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주봉황,8004158,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주봉황,8004158,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주봉황,8004158,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주봉황,8004158,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주봉황,8004158,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주봉황,8004158,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주봉황,8004158,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주봉황,8004158,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주봉황,8004158,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주봉황,8004158,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주봉황,8004158,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주봉황,8004158,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주봉황,8004158,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주봉황,8004158,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주봉황,8004158,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주봉황,8004158,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 신풍산정  [8004159]  (36.5147, 126.9554)
📍 요청 위치: (36.5147°N, 126.9554°E)
📍 격자 좌표: (x=60, y=104)
📍 실제 위치: (36.5205°N, 126.9731°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,신풍산정,8004159,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,신풍산정,8004159,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,신풍산정,8004159,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,신풍산정,8004159,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,신풍산정,8004159,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,신풍산정,8004159,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,신풍산정,8004159,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,신풍산정,8004159,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,신풍산정,8004159,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,신풍산정,8004159,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,신풍산정,8004159,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,신풍산정,8004159,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,신풍산정,8004159,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,신풍산정,8004159,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,신풍산정,8004159,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,신풍산정,8004159,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,신풍산정,8004159,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,신풍산정,8004159,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,신풍산정,8004159,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,신풍산정,8004159,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,신풍산정,8004159,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,신풍산정,8004159,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,신풍산정,8004159,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,신풍산정,8004159,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,신풍산정,8004159,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,신풍산정,8004159,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,신풍산정,8004159,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,신풍산정,8004159,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,신풍산정,8004159,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,신풍산정,8004159,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,신풍산정,8004159,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,신풍산정,8004159,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,신풍산정,8004159,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,신풍산정,8004159,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,신풍산정,8004159,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,신풍산정,8004159,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,신풍산정,8004159,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,신풍산정,8004159,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,신풍산정,8004159,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,신풍산정,8004159,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,신풍산정,8004159,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,신풍산정,8004159,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡월암  [8004162]  (36.3603, 127.1419)
📍 요청 위치: (36.3603°N, 127.1419°E)
📍 격자 좌표: (x=63, y=101)
📍 실제 위치: (36.3808°N, 127.1423°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡월암,8004162,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,계룡월암,8004162,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,계룡월암,8004162,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,계룡월암,8004162,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,계룡월암,8004162,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,계룡월암,8004162,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,계룡월암,8004162,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,계룡월암,8004162,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,계룡월암,8004162,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,계룡월암,8004162,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,계룡월암,8004162,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,계룡월암,8004162,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,계룡월암,8004162,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,계룡월암,8004162,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,계룡월암,8004162,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,계룡월암,8004162,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,계룡월암,8004162,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,계룡월암,8004162,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,계룡월암,8004162,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,계룡월암,8004162,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,계룡월암,8004162,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,계룡월암,8004162,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,계룡월암,8004162,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,계룡월암,8004162,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,계룡월암,8004162,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,계룡월암,8004162,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,계룡월암,8004162,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,계룡월암,8004162,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,계룡월암,8004162,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,계룡월암,8004162,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,계룡월암,8004162,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,계룡월암,8004162,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,계룡월암,8004162,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,계룡월암,8004162,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,계룡월암,8004162,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,계룡월암,8004162,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,계룡월암,8004162,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,계룡월암,8004162,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,계룡월암,8004162,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,계룡월암,8004162,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,계룡월암,8004162,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,계룡월암,8004162,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 복수곡남  [8004166]  (36.1665, 127.3983)
📍 요청 위치: (36.1665°N, 127.3983°E)
📍 격자 좌표: (x=68, y=96)
📍 실제 위치: (36.1473°N, 127.4228°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,복수곡남,8004166,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,복수곡남,8004166,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,복수곡남,8004166,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,복수곡남,8004166,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,복수곡남,8004166,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,복수곡남,8004166,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,복수곡남,8004166,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,복수곡남,8004166,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,복수곡남,8004166,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,복수곡남,8004166,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,복수곡남,8004166,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,복수곡남,8004166,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,복수곡남,8004166,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,복수곡남,8004166,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,복수곡남,8004166,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,복수곡남,8004166,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,복수곡남,8004166,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,복수곡남,8004166,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,복수곡남,8004166,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,복수곡남,8004166,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,복수곡남,8004166,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,복수곡남,8004166,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,복수곡남,8004166,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,복수곡남,8004166,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,복수곡남,8004166,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,복수곡남,8004166,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,복수곡남,8004166,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,복수곡남,8004166,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,복수곡남,8004166,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,복수곡남,8004166,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,복수곡남,8004166,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,복수곡남,8004166,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,복수곡남,8004166,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,복수곡남,8004166,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,복수곡남,8004166,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,복수곡남,8004166,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,복수곡남,8004166,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,복수곡남,8004166,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,복수곡남,8004166,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,복수곡남,8004166,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,복수곡남,8004166,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,복수곡남,8004166,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 벌곡한삼천  [8004180]  (36.2059, 127.2648)
📍 요청 위치: (36.2059°N, 127.2648°E)
📍 격자 좌표: (x=65, y=97)
📍 실제 위치: (36.1955°N, 127.2530°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,벌곡한삼천,8004180,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,벌곡한삼천,8004180,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,벌곡한삼천,8004180,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,벌곡한삼천,8004180,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,벌곡한삼천,8004180,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,벌곡한삼천,8004180,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,벌곡한삼천,8004180,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,벌곡한삼천,8004180,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,벌곡한삼천,8004180,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,벌곡한삼천,8004180,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,벌곡한삼천,8004180,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,벌곡한삼천,8004180,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,벌곡한삼천,8004180,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,벌곡한삼천,8004180,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,벌곡한삼천,8004180,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,벌곡한삼천,8004180,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,벌곡한삼천,8004180,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,벌곡한삼천,8004180,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,벌곡한삼천,8004180,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,벌곡한삼천,8004180,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,벌곡한삼천,8004180,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,벌곡한삼천,8004180,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,벌곡한삼천,8004180,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,벌곡한삼천,8004180,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,벌곡한삼천,8004180,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,벌곡한삼천,8004180,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,벌곡한삼천,8004180,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,벌곡한삼천,8004180,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,벌곡한삼천,8004180,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,벌곡한삼천,8004180,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,벌곡한삼천,8004180,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,벌곡한삼천,8004180,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,벌곡한삼천,8004180,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,벌곡한삼천,8004180,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,벌곡한삼천,8004180,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,벌곡한삼천,8004180,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,벌곡한삼천,8004180,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,벌곡한삼천,8004180,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,벌곡한삼천,8004180,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,벌곡한삼천,8004180,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,벌곡한삼천,8004180,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,벌곡한삼천,8004180,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성동원남  [8004185]  (36.2035, 127.0336)
📍 요청 위치: (36.2035°N, 127.0336°E)
📍 격자 좌표: (x=61, y=97)
📍 실제 위치: (36.1981°N, 127.0252°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성동원남,8004185,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,성동원남,8004185,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,성동원남,8004185,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,성동원남,8004185,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,성동원남,8004185,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,성동원남,8004185,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,성동원남,8004185,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,성동원남,8004185,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,성동원남,8004185,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,성동원남,8004185,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,성동원남,8004185,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,성동원남,8004185,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,성동원남,8004185,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,성동원남,8004185,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,성동원남,8004185,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,성동원남,8004185,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,성동원남,8004185,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,성동원남,8004185,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,성동원남,8004185,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,성동원남,8004185,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,성동원남,8004185,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,성동원남,8004185,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,성동원남,8004185,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,성동원남,8004185,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,성동원남,8004185,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,성동원남,8004185,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,성동원남,8004185,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,성동원남,8004185,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,성동원남,8004185,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,성동원남,8004185,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,성동원남,8004185,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,성동원남,8004185,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,성동원남,8004185,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,성동원남,8004185,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,성동원남,8004185,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,성동원남,8004185,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,성동원남,8004185,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,성동원남,8004185,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,성동원남,8004185,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,성동원남,8004185,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,성동원남,8004185,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,성동원남,8004185,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가야곡육곡  [8004186]  (36.1368, 127.1587)
📍 요청 위치: (36.1368°N, 127.1587°E)
📍 격자 좌표: (x=63, y=96)
📍 실제 위치: (36.1509°N, 127.1383°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가야곡육곡,8004186,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,가야곡육곡,8004186,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,가야곡육곡,8004186,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,가야곡육곡,8004186,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,가야곡육곡,8004186,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,가야곡육곡,8004186,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,가야곡육곡,8004186,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,가야곡육곡,8004186,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,가야곡육곡,8004186,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,가야곡육곡,8004186,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,가야곡육곡,8004186,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,가야곡육곡,8004186,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,가야곡육곡,8004186,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,가야곡육곡,8004186,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,가야곡육곡,8004186,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,가야곡육곡,8004186,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,가야곡육곡,8004186,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,가야곡육곡,8004186,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,가야곡육곡,8004186,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,가야곡육곡,8004186,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,가야곡육곡,8004186,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,가야곡육곡,8004186,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,가야곡육곡,8004186,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,가야곡육곡,8004186,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,가야곡육곡,8004186,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,가야곡육곡,8004186,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,가야곡육곡,8004186,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,가야곡육곡,8004186,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,가야곡육곡,8004186,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,가야곡육곡,8004186,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,가야곡육곡,8004186,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,가야곡육곡,8004186,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,가야곡육곡,8004186,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,가야곡육곡,8004186,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,가야곡육곡,8004186,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,가야곡육곡,8004186,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,가야곡육곡,8004186,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,가야곡육곡,8004186,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,가야곡육곡,8004186,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,가야곡육곡,8004186,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,가야곡육곡,8004186,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,가야곡육곡,8004186,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노성읍내  [8004187]  (36.2782, 127.1302)
📍 요청 위치: (36.2782°N, 127.1302°E)
📍 격자 좌표: (x=63, y=99)
📍 실제 위치: (36.2888°N, 127.1407°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노성읍내,8004187,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,노성읍내,8004187,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,노성읍내,8004187,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,노성읍내,8004187,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,노성읍내,8004187,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,노성읍내,8004187,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,노성읍내,8004187,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,노성읍내,8004187,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,노성읍내,8004187,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,노성읍내,8004187,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,노성읍내,8004187,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,노성읍내,8004187,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,노성읍내,8004187,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,노성읍내,8004187,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,노성읍내,8004187,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,노성읍내,8004187,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,노성읍내,8004187,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,노성읍내,8004187,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,노성읍내,8004187,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,노성읍내,8004187,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,노성읍내,8004187,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,노성읍내,8004187,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,노성읍내,8004187,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,노성읍내,8004187,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,노성읍내,8004187,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,노성읍내,8004187,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,노성읍내,8004187,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,노성읍내,8004187,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,노성읍내,8004187,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,노성읍내,8004187,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,노성읍내,8004187,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,노성읍내,8004187,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,노성읍내,8004187,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,노성읍내,8004187,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,노성읍내,8004187,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,노성읍내,8004187,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,노성읍내,8004187,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,노성읍내,8004187,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,노성읍내,8004187,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,노성읍내,8004187,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,노성읍내,8004187,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,노성읍내,8004187,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 임천군사  [8004214]  (36.1912, 126.8949)
📍 요청 위치: (36.1912°N, 126.8949°E)
📍 격자 좌표: (x=59, y=97)
📍 실제 위치: (36.1992°N, 126.9113°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,임천군사,8004214,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,임천군사,8004214,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,임천군사,8004214,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,임천군사,8004214,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,임천군사,8004214,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,임천군사,8004214,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,임천군사,8004214,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,임천군사,8004214,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,임천군사,8004214,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,임천군사,8004214,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,임천군사,8004214,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,임천군사,8004214,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,임천군사,8004214,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,임천군사,8004214,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,임천군사,8004214,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,임천군사,8004214,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,임천군사,8004214,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,임천군사,8004214,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,임천군사,8004214,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,임천군사,8004214,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,임천군사,8004214,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,임천군사,8004214,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,임천군사,8004214,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,임천군사,8004214,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,임천군사,8004214,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,임천군사,8004214,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,임천군사,8004214,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,임천군사,8004214,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,임천군사,8004214,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,임천군사,8004214,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,임천군사,8004214,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,임천군사,8004214,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,임천군사,8004214,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,임천군사,8004214,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,임천군사,8004214,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,임천군사,8004214,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,임천군사,8004214,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,임천군사,8004214,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,임천군사,8004214,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,임천군사,8004214,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,임천군사,8004214,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,임천군사,8004214,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남면회동  [8004216]  (36.2121, 126.8063)
📍 요청 위치: (36.2121°N, 126.8063°E)
📍 격자 좌표: (x=57, y=97)
📍 실제 위치: (36.2002°N, 126.7974°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남면회동,8004216,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,남면회동,8004216,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,남면회동,8004216,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,남면회동,8004216,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,남면회동,8004216,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,남면회동,8004216,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,남면회동,8004216,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,남면회동,8004216,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,남면회동,8004216,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,남면회동,8004216,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,남면회동,8004216,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,남면회동,8004216,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,남면회동,8004216,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,남면회동,8004216,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,남면회동,8004216,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,남면회동,8004216,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,남면회동,8004216,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,남면회동,8004216,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,남면회동,8004216,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,남면회동,8004216,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,남면회동,8004216,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,남면회동,8004216,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,남면회동,8004216,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,남면회동,8004216,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,남면회동,8004216,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,남면회동,8004216,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,남면회동,8004216,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,남면회동,8004216,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,남면회동,8004216,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,남면회동,8004216,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,남면회동,8004216,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,남면회동,8004216,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,남면회동,8004216,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,남면회동,8004216,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,남면회동,8004216,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,남면회동,8004216,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,남면회동,8004216,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,남면회동,8004216,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,남면회동,8004216,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,남면회동,8004216,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,남면회동,8004216,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,남면회동,8004216,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 은산신대  [8004219]  (36.3105, 126.8542)
📍 요청 위치: (36.3105°N, 126.8542°E)
📍 격자 좌표: (x=58, y=99)
📍 실제 위치: (36.2917°N, 126.8556°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,은산신대,8004219,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,은산신대,8004219,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,은산신대,8004219,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,은산신대,8004219,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,은산신대,8004219,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,은산신대,8004219,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,은산신대,8004219,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,은산신대,8004219,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,은산신대,8004219,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,은산신대,8004219,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,은산신대,8004219,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,은산신대,8004219,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,은산신대,8004219,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,은산신대,8004219,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,은산신대,8004219,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,은산신대,8004219,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,은산신대,8004219,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,은산신대,8004219,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,은산신대,8004219,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,은산신대,8004219,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,은산신대,8004219,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,은산신대,8004219,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,은산신대,8004219,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,은산신대,8004219,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,은산신대,8004219,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,은산신대,8004219,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,은산신대,8004219,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,은산신대,8004219,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,은산신대,8004219,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,은산신대,8004219,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,은산신대,8004219,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,은산신대,8004219,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,은산신대,8004219,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,은산신대,8004219,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,은산신대,8004219,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,은산신대,8004219,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,은산신대,8004219,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,은산신대,8004219,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,은산신대,8004219,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,은산신대,8004219,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,은산신대,8004219,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,은산신대,8004219,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 내산운치  [8004223]  (36.2752, 126.7806)
📍 요청 위치: (36.2752°N, 126.7806°E)
📍 격자 좌표: (x=57, y=99)
📍 실제 위치: (36.2922°N, 126.7985°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,내산운치,8004223,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,내산운치,8004223,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,내산운치,8004223,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,내산운치,8004223,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,내산운치,8004223,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,내산운치,8004223,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,내산운치,8004223,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,내산운치,8004223,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,내산운치,8004223,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,내산운치,8004223,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,내산운치,8004223,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,내산운치,8004223,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,내산운치,8004223,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,내산운치,8004223,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,내산운치,8004223,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,내산운치,8004223,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,내산운치,8004223,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,내산운치,8004223,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,내산운치,8004223,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,내산운치,8004223,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,내산운치,8004223,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,내산운치,8004223,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,내산운치,8004223,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,내산운치,8004223,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,내산운치,8004223,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,내산운치,8004223,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,내산운치,8004223,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,내산운치,8004223,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,내산운치,8004223,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,내산운치,8004223,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,내산운치,8004223,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,내산운치,8004223,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,내산운치,8004223,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,내산운치,8004223,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,내산운치,8004223,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,내산운치,8004223,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,내산운치,8004223,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,내산운치,8004223,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,내산운치,8004223,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,내산운치,8004223,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,내산운치,8004223,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,내산운치,8004223,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 석성증산  [8004226]  (36.2532, 127.0024)
📍 요청 위치: (36.2532°N, 127.0024°E)
📍 격자 좌표: (x=61, y=98)
📍 실제 위치: (36.2441°N, 127.0259°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,석성증산,8004226,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,석성증산,8004226,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,석성증산,8004226,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,석성증산,8004226,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,석성증산,8004226,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,석성증산,8004226,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,석성증산,8004226,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,석성증산,8004226,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,석성증산,8004226,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,석성증산,8004226,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,석성증산,8004226,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,석성증산,8004226,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,석성증산,8004226,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,석성증산,8004226,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,석성증산,8004226,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,석성증산,8004226,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,석성증산,8004226,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,석성증산,8004226,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,석성증산,8004226,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,석성증산,8004226,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,석성증산,8004226,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,석성증산,8004226,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,석성증산,8004226,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,석성증산,8004226,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,석성증산,8004226,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,석성증산,8004226,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,석성증산,8004226,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,석성증산,8004226,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,석성증산,8004226,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,석성증산,8004226,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,석성증산,8004226,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,석성증산,8004226,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,석성증산,8004226,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,석성증산,8004226,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,석성증산,8004226,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,석성증산,8004226,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,석성증산,8004226,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,석성증산,8004226,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,석성증산,8004226,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,석성증산,8004226,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,석성증산,8004226,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,석성증산,8004226,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 문산신농  [8004245]  (36.1423, 126.7522)
📍 요청 위치: (36.1423°N, 126.7522°E)
📍 격자 좌표: (x=56, y=96)
📍 실제 위치: (36.1547°N, 126.7399°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,문산신농,8004245,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,문산신농,8004245,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,문산신농,8004245,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,문산신농,8004245,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,문산신농,8004245,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,문산신농,8004245,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,문산신농,8004245,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,문산신농,8004245,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,문산신농,8004245,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,문산신농,8004245,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,문산신농,8004245,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,문산신농,8004245,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,문산신농,8004245,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,문산신농,8004245,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,문산신농,8004245,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,문산신농,8004245,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,문산신농,8004245,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,문산신농,8004245,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,문산신농,8004245,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,문산신농,8004245,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,문산신농,8004245,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,문산신농,8004245,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,문산신농,8004245,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,문산신농,8004245,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,문산신농,8004245,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,문산신농,8004245,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,문산신농,8004245,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,문산신농,8004245,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,문산신농,8004245,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,문산신농,8004245,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,문산신농,8004245,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,문산신농,8004245,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,문산신농,8004245,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,문산신농,8004245,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,문산신농,8004245,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,문산신농,8004245,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,문산신농,8004245,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,문산신농,8004245,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,문산신농,8004245,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,문산신농,8004245,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,문산신농,8004245,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,문산신농,8004245,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 송악역촌  [8004261]  (36.4353, 127.009)
📍 요청 위치: (36.4353°N, 127.0090°E)
📍 격자 좌표: (x=61, y=102)
📍 실제 위치: (36.4280°N, 127.0288°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,송악역촌,8004261,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,송악역촌,8004261,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,송악역촌,8004261,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,송악역촌,8004261,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,송악역촌,8004261,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,송악역촌,8004261,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,송악역촌,8004261,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,송악역촌,8004261,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,송악역촌,8004261,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,송악역촌,8004261,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,송악역촌,8004261,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,송악역촌,8004261,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,송악역촌,8004261,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,송악역촌,8004261,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,송악역촌,8004261,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,송악역촌,8004261,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,송악역촌,8004261,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,송악역촌,8004261,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,송악역촌,8004261,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,송악역촌,8004261,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,송악역촌,8004261,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,송악역촌,8004261,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,송악역촌,8004261,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,송악역촌,8004261,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,송악역촌,8004261,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,송악역촌,8004261,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,송악역촌,8004261,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,송악역촌,8004261,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,송악역촌,8004261,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,송악역촌,8004261,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,송악역촌,8004261,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,송악역촌,8004261,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,송악역촌,8004261,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,송악역촌,8004261,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,송악역촌,8004261,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,송악역촌,8004261,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,송악역촌,8004261,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,송악역촌,8004261,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,송악역촌,8004261,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,송악역촌,8004261,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,송악역촌,8004261,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,송악역촌,8004261,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장평중추  [8004308]  (36.3418, 126.893)
📍 요청 위치: (36.3418°N, 126.8930°E)
📍 격자 좌표: (x=59, y=100)
📍 실제 위치: (36.3371°N, 126.9132°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장평중추,8004308,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,장평중추,8004308,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,장평중추,8004308,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,장평중추,8004308,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,장평중추,8004308,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,장평중추,8004308,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,장평중추,8004308,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,장평중추,8004308,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,장평중추,8004308,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,장평중추,8004308,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,장평중추,8004308,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,장평중추,8004308,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,장평중추,8004308,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,장평중추,8004308,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,장평중추,8004308,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,장평중추,8004308,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,장평중추,8004308,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,장평중추,8004308,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,장평중추,8004308,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,장평중추,8004308,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,장평중추,8004308,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,장평중추,8004308,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,장평중추,8004308,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,장평중추,8004308,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,장평중추,8004308,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,장평중추,8004308,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,장평중추,8004308,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,장평중추,8004308,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,장평중추,8004308,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,장평중추,8004308,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,장평중추,8004308,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,장평중추,8004308,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,장평중추,8004308,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,장평중추,8004308,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,장평중추,8004308,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,장평중추,8004308,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,장평중추,8004308,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,장평중추,8004308,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,장평중추,8004308,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,장평중추,8004308,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,장평중추,8004308,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,장평중추,8004308,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 북면보건지소  [8004394]  (36.8276, 127.2732)
📍 요청 위치: (36.8276°N, 127.2732°E)
📍 격자 좌표: (x=65, y=111)
📍 실제 위치: (36.8394°N, 127.2656°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,북면보건지소,8004394,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,북면보건지소,8004394,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,북면보건지소,8004394,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,북면보건지소,8004394,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,북면보건지소,8004394,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,북면보건지소,8004394,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,북면보건지소,8004394,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,북면보건지소,8004394,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,북면보건지소,8004394,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,북면보건지소,8004394,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,북면보건지소,8004394,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,북면보건지소,8004394,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,북면보건지소,8004394,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,북면보건지소,8004394,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,북면보건지소,8004394,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,북면보건지소,8004394,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,북면보건지소,8004394,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,북면보건지소,8004394,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,북면보건지소,8004394,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,북면보건지소,8004394,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,북면보건지소,8004394,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,북면보건지소,8004394,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,북면보건지소,8004394,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,북면보건지소,8004394,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,북면보건지소,8004394,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,북면보건지소,8004394,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,북면보건지소,8004394,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,북면보건지소,8004394,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,북면보건지소,8004394,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,북면보건지소,8004394,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,북면보건지소,8004394,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,북면보건지소,8004394,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,북면보건지소,8004394,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,북면보건지소,8004394,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,북면보건지소,8004394,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,북면보건지소,8004394,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,북면보건지소,8004394,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,북면보건지소,8004394,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,북면보건지소,8004394,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,북면보건지소,8004394,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,북면보건지소,8004394,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,북면보건지소,8004394,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 목천보건지소  [8004395]  (36.785, 127.2347)
📍 요청 위치: (36.7850°N, 127.2347°E)
📍 격자 좌표: (x=64, y=110)
📍 실제 위치: (36.7941°N, 127.2072°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,목천보건지소,8004395,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,목천보건지소,8004395,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,목천보건지소,8004395,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,목천보건지소,8004395,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,목천보건지소,8004395,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,목천보건지소,8004395,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,목천보건지소,8004395,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,목천보건지소,8004395,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,목천보건지소,8004395,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,목천보건지소,8004395,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,목천보건지소,8004395,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,목천보건지소,8004395,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,목천보건지소,8004395,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,목천보건지소,8004395,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,목천보건지소,8004395,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,목천보건지소,8004395,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,목천보건지소,8004395,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,목천보건지소,8004395,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,목천보건지소,8004395,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,목천보건지소,8004395,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,목천보건지소,8004395,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,목천보건지소,8004395,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,목천보건지소,8004395,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,목천보건지소,8004395,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,목천보건지소,8004395,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,목천보건지소,8004395,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,목천보건지소,8004395,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,목천보건지소,8004395,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,목천보건지소,8004395,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,목천보건지소,8004395,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,목천보건지소,8004395,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,목천보건지소,8004395,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,목천보건지소,8004395,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,목천보건지소,8004395,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,목천보건지소,8004395,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,목천보건지소,8004395,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,목천보건지소,8004395,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,목천보건지소,8004395,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,목천보건지소,8004395,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,목천보건지소,8004395,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,목천보건지소,8004395,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,목천보건지소,8004395,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성남보건지소  [8004397]  (36.7429, 127.236)
📍 요청 위치: (36.7429°N, 127.2360°E)
📍 격자 좌표: (x=65, y=109)
📍 실제 위치: (36.7474°N, 127.2638°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성남보건지소,8004397,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,성남보건지소,8004397,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,성남보건지소,8004397,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,성남보건지소,8004397,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,성남보건지소,8004397,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,성남보건지소,8004397,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,성남보건지소,8004397,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,성남보건지소,8004397,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,성남보건지소,8004397,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,성남보건지소,8004397,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,성남보건지소,8004397,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,성남보건지소,8004397,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,성남보건지소,8004397,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,성남보건지소,8004397,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,성남보건지소,8004397,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,성남보건지소,8004397,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,성남보건지소,8004397,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,성남보건지소,8004397,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,성남보건지소,8004397,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,성남보건지소,8004397,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,성남보건지소,8004397,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,성남보건지소,8004397,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,성남보건지소,8004397,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,성남보건지소,8004397,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,성남보건지소,8004397,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,성남보건지소,8004397,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,성남보건지소,8004397,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,성남보건지소,8004397,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,성남보건지소,8004397,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,성남보건지소,8004397,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,성남보건지소,8004397,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,성남보건지소,8004397,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,성남보건지소,8004397,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,성남보건지소,8004397,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,성남보건지소,8004397,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,성남보건지소,8004397,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,성남보건지소,8004397,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,성남보건지소,8004397,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,성남보건지소,8004397,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,성남보건지소,8004397,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,성남보건지소,8004397,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,성남보건지소,8004397,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동면보건지소  [8004400]  (36.7762, 127.3441)
📍 요청 위치: (36.7762°N, 127.3441°E)
📍 격자 좌표: (x=66, y=110)
📍 실제 위치: (36.7927°N, 127.3221°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동면보건지소,8004400,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,동면보건지소,8004400,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,동면보건지소,8004400,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,동면보건지소,8004400,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,동면보건지소,8004400,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,동면보건지소,8004400,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,동면보건지소,8004400,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,동면보건지소,8004400,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,동면보건지소,8004400,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,동면보건지소,8004400,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,동면보건지소,8004400,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,동면보건지소,8004400,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,동면보건지소,8004400,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,동면보건지소,8004400,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,동면보건지소,8004400,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,동면보건지소,8004400,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,동면보건지소,8004400,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,동면보건지소,8004400,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,동면보건지소,8004400,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,동면보건지소,8004400,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,동면보건지소,8004400,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,동면보건지소,8004400,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,동면보건지소,8004400,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,동면보건지소,8004400,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,동면보건지소,8004400,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,동면보건지소,8004400,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,동면보건지소,8004400,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,동면보건지소,8004400,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,동면보건지소,8004400,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,동면보건지소,8004400,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,동면보건지소,8004400,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,동면보건지소,8004400,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,동면보건지소,8004400,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,동면보건지소,8004400,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,동면보건지소,8004400,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,동면보건지소,8004400,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,동면보건지소,8004400,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,동면보건지소,8004400,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,동면보건지소,8004400,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,동면보건지소,8004400,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,동면보건지소,8004400,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,동면보건지소,8004400,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 선동  [8003186]  (36.48657, 127.42401)
📍 요청 위치: (36.4866°N, 127.4240°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,선동,8003186,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,선동,8003186,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,선동,8003186,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,선동,8003186,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,선동,8003186,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,선동,8003186,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,선동,8003186,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,선동,8003186,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,선동,8003186,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,선동,8003186,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,선동,8003186,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,선동,8003186,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,선동,8003186,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,선동,8003186,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,선동,8003186,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,선동,8003186,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,선동,8003186,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,선동,8003186,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,선동,8003186,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,선동,8003186,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,선동,8003186,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,선동,8003186,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,선동,8003186,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,선동,8003186,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,선동,8003186,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,선동,8003186,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,선동,8003186,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,선동,8003186,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,선동,8003186,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,선동,8003186,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,선동,8003186,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,선동,8003186,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,선동,8003186,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,선동,8003186,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,선동,8003186,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,선동,8003186,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,선동,8003186,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,선동,8003186,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,선동,8003186,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,선동,8003186,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,선동,8003186,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,선동,8003186,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 신대  [8003187]  (36.73901, 127.54172)
📍 요청 위치: (36.7390°N, 127.5417°E)
📍 격자 좌표: (x=70, y=109)
📍 실제 위치: (36.7433°N, 127.5509°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,신대,8003187,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,신대,8003187,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,신대,8003187,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,신대,8003187,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,신대,8003187,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,신대,8003187,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,신대,8003187,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,신대,8003187,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,신대,8003187,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,신대,8003187,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,신대,8003187,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,신대,8003187,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,신대,8003187,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,신대,8003187,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,신대,8003187,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,신대,8003187,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,신대,8003187,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,신대,8003187,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,신대,8003187,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,신대,8003187,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,신대,8003187,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,신대,8003187,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,신대,8003187,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,신대,8003187,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,신대,8003187,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,신대,8003187,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,신대,8003187,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,신대,8003187,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,신대,8003187,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,신대,8003187,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,신대,8003187,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,신대,8003187,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,신대,8003187,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,신대,8003187,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,신대,8003187,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,신대,8003187,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,신대,8003187,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,신대,8003187,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,신대,8003187,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,신대,8003187,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,신대,8003187,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,신대,8003187,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오산  [8003188]  (36.66461, 127.37557)
📍 요청 위치: (36.6646°N, 127.3756°E)
📍 격자 좌표: (x=67, y=107)
📍 실제 위치: (36.6538°N, 127.3767°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오산,8003188,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,오산,8003188,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,오산,8003188,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,오산,8003188,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,오산,8003188,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,오산,8003188,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,오산,8003188,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,오산,8003188,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,오산,8003188,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,오산,8003188,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,오산,8003188,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,오산,8003188,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,오산,8003188,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,오산,8003188,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,오산,8003188,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,오산,8003188,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,오산,8003188,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,오산,8003188,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,오산,8003188,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,오산,8003188,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,오산,8003188,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,오산,8003188,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,오산,8003188,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,오산,8003188,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,오산,8003188,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,오산,8003188,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,오산,8003188,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,오산,8003188,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,오산,8003188,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,오산,8003188,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,오산,8003188,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,오산,8003188,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,오산,8003188,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,오산,8003188,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,오산,8003188,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,오산,8003188,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,오산,8003188,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,오산,8003188,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,오산,8003188,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,오산,8003188,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,오산,8003188,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,오산,8003188,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오송  [8003189]  (36.60915, 127.324454)
📍 요청 위치: (36.6091°N, 127.3245°E)
📍 격자 좌표: (x=66, y=106)
📍 실제 위치: (36.6086°N, 127.3184°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오송,8003189,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,오송,8003189,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,오송,8003189,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,오송,8003189,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,오송,8003189,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,오송,8003189,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,오송,8003189,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,오송,8003189,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,오송,8003189,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,오송,8003189,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,오송,8003189,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,오송,8003189,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,오송,8003189,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,오송,8003189,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,오송,8003189,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,오송,8003189,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,오송,8003189,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,오송,8003189,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,오송,8003189,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,오송,8003189,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,오송,8003189,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,오송,8003189,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,오송,8003189,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,오송,8003189,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,오송,8003189,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,오송,8003189,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,오송,8003189,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,오송,8003189,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,오송,8003189,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,오송,8003189,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,오송,8003189,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,오송,8003189,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,오송,8003189,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,오송,8003189,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,오송,8003189,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,오송,8003189,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,오송,8003189,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,오송,8003189,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,오송,8003189,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,오송,8003189,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,오송,8003189,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,오송,8003189,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 척산  [8003193]  (36.56066, 127.43347)
📍 요청 위치: (36.5607°N, 127.4335°E)
📍 격자 좌표: (x=68, y=105)
📍 실제 위치: (36.5610°N, 127.4320°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,척산,8003193,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,척산,8003193,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,척산,8003193,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,척산,8003193,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,척산,8003193,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,척산,8003193,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,척산,8003193,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,척산,8003193,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,척산,8003193,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,척산,8003193,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,척산,8003193,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,척산,8003193,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,척산,8003193,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,척산,8003193,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,척산,8003193,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,척산,8003193,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,척산,8003193,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,척산,8003193,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,척산,8003193,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,척산,8003193,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,척산,8003193,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,척산,8003193,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,척산,8003193,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,척산,8003193,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,척산,8003193,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,척산,8003193,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,척산,8003193,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,척산,8003193,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,척산,8003193,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,척산,8003193,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,척산,8003193,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,척산,8003193,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,척산,8003193,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,척산,8003193,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,척산,8003193,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,척산,8003193,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,척산,8003193,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,척산,8003193,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,척산,8003193,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,척산,8003193,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,척산,8003193,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,척산,8003193,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 탑연  [8003194]  (36.62083, 127.35731)
📍 요청 위치: (36.6208°N, 127.3573°E)
📍 격자 좌표: (x=67, y=106)
📍 실제 위치: (36.6078°N, 127.3757°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,탑연,8003194,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,탑연,8003194,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,탑연,8003194,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,탑연,8003194,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,탑연,8003194,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,탑연,8003194,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,탑연,8003194,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,탑연,8003194,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,탑연,8003194,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,탑연,8003194,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,탑연,8003194,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,탑연,8003194,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,탑연,8003194,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,탑연,8003194,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,탑연,8003194,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,탑연,8003194,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,탑연,8003194,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,탑연,8003194,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,탑연,8003194,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,탑연,8003194,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,탑연,8003194,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,탑연,8003194,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,탑연,8003194,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,탑연,8003194,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,탑연,8003194,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,탑연,8003194,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,탑연,8003194,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,탑연,8003194,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,탑연,8003194,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,탑연,8003194,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,탑연,8003194,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,탑연,8003194,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,탑연,8003194,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,탑연,8003194,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,탑연,8003194,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,탑연,8003194,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,탑연,8003194,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,탑연,8003194,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,탑연,8003194,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,탑연,8003194,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,탑연,8003194,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,탑연,8003194,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남차  [8003224]  (36.72401, 127.62135)
📍 요청 위치: (36.7240°N, 127.6214°E)
📍 격자 좌표: (x=71, y=109)
📍 실제 위치: (36.7424°N, 127.6083°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남차,8003224,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,남차,8003224,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,남차,8003224,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,남차,8003224,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,남차,8003224,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,남차,8003224,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,남차,8003224,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,남차,8003224,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,남차,8003224,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,남차,8003224,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,남차,8003224,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,남차,8003224,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,남차,8003224,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,남차,8003224,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,남차,8003224,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,남차,8003224,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,남차,8003224,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,남차,8003224,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,남차,8003224,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,남차,8003224,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,남차,8003224,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,남차,8003224,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,남차,8003224,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,남차,8003224,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,남차,8003224,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,남차,8003224,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,남차,8003224,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,남차,8003224,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,남차,8003224,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,남차,8003224,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,남차,8003224,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,남차,8003224,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,남차,8003224,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,남차,8003224,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,남차,8003224,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,남차,8003224,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,남차,8003224,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,남차,8003224,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,남차,8003224,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,남차,8003224,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,남차,8003224,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,남차,8003224,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥성  [8003175]  (36.78457, 127.43723)
📍 요청 위치: (36.7846°N, 127.4372°E)
📍 격자 좌표: (x=68, y=110)
📍 실제 위치: (36.7911°N, 127.4371°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥성,8003175,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,옥성,8003175,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,옥성,8003175,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,옥성,8003175,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,옥성,8003175,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,옥성,8003175,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,옥성,8003175,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,옥성,8003175,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,옥성,8003175,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,옥성,8003175,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,옥성,8003175,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,옥성,8003175,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,옥성,8003175,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,옥성,8003175,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,옥성,8003175,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,옥성,8003175,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,옥성,8003175,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,옥성,8003175,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,옥성,8003175,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,옥성,8003175,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,옥성,8003175,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,옥성,8003175,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,옥성,8003175,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,옥성,8003175,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,옥성,8003175,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,옥성,8003175,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,옥성,8003175,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,옥성,8003175,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,옥성,8003175,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,옥성,8003175,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,옥성,8003175,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,옥성,8003175,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,옥성,8003175,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,옥성,8003175,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,옥성,8003175,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,옥성,8003175,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,옥성,8003175,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,옥성,8003175,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,옥성,8003175,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,옥성,8003175,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,옥성,8003175,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,옥성,8003175,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 석현  [8003176]  (36.88395, 127.37683)
📍 요청 위치: (36.8839°N, 127.3768°E)
📍 격자 좌표: (x=67, y=112)
📍 실제 위치: (36.8839°N, 127.3816°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,석현,8003176,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,석현,8003176,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,석현,8003176,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,석현,8003176,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,석현,8003176,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,석현,8003176,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,석현,8003176,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,석현,8003176,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,석현,8003176,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,석현,8003176,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,석현,8003176,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,석현,8003176,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,석현,8003176,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,석현,8003176,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,석현,8003176,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,석현,8003176,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,석현,8003176,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,석현,8003176,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,석현,8003176,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,석현,8003176,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,석현,8003176,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,석현,8003176,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,석현,8003176,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,석현,8003176,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,석현,8003176,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,석현,8003176,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,석현,8003176,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,석현,8003176,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,석현,8003176,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,석현,8003176,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,석현,8003176,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,석현,8003176,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,석현,8003176,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,석현,8003176,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,석현,8003176,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,석현,8003176,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,석현,8003176,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,석현,8003176,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,석현,8003176,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,석현,8003176,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,석현,8003176,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,석현,8003176,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용몽  [8003178]  (36.9138, 127.5094)
📍 요청 위치: (36.9138°N, 127.5094°E)
📍 격자 좌표: (x=69, y=113)
📍 실제 위치: (36.9283°N, 127.4978°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용몽,8003178,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,용몽,8003178,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,용몽,8003178,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,용몽,8003178,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,용몽,8003178,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,용몽,8003178,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,용몽,8003178,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,용몽,8003178,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,용몽,8003178,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,용몽,8003178,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,용몽,8003178,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,용몽,8003178,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,용몽,8003178,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,용몽,8003178,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,용몽,8003178,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,용몽,8003178,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,용몽,8003178,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,용몽,8003178,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,용몽,8003178,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,용몽,8003178,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,용몽,8003178,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,용몽,8003178,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,용몽,8003178,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,용몽,8003178,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,용몽,8003178,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,용몽,8003178,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,용몽,8003178,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,용몽,8003178,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,용몽,8003178,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,용몽,8003178,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,용몽,8003178,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,용몽,8003178,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,용몽,8003178,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,용몽,8003178,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,용몽,8003178,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,용몽,8003178,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,용몽,8003178,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,용몽,8003178,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,용몽,8003178,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,용몽,8003178,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,용몽,8003178,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,용몽,8003178,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노원  [8003179]  (36.92567, 127.42846)
📍 요청 위치: (36.9257°N, 127.4285°E)
📍 격자 좌표: (x=68, y=113)
📍 실제 위치: (36.9292°N, 127.4402°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노원,8003179,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,노원,8003179,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,노원,8003179,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,노원,8003179,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,노원,8003179,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,노원,8003179,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,노원,8003179,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,노원,8003179,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,노원,8003179,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,노원,8003179,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,노원,8003179,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,노원,8003179,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,노원,8003179,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,노원,8003179,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,노원,8003179,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,노원,8003179,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,노원,8003179,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,노원,8003179,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,노원,8003179,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,노원,8003179,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,노원,8003179,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,노원,8003179,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,노원,8003179,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,노원,8003179,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,노원,8003179,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,노원,8003179,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,노원,8003179,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,노원,8003179,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,노원,8003179,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,노원,8003179,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,노원,8003179,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,노원,8003179,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,노원,8003179,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,노원,8003179,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,노원,8003179,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,노원,8003179,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,노원,8003179,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,노원,8003179,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,노원,8003179,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,노원,8003179,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,노원,8003179,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,노원,8003179,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용정  [8003181]  (36.8461, 127.52639)
📍 요청 위치: (36.8461°N, 127.5264°E)
📍 격자 좌표: (x=70, y=111)
📍 실제 위치: (36.8354°N, 127.5531°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용정,8003181,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,용정,8003181,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,용정,8003181,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,용정,8003181,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,용정,8003181,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,용정,8003181,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,용정,8003181,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,용정,8003181,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,용정,8003181,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,용정,8003181,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,용정,8003181,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,용정,8003181,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,용정,8003181,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,용정,8003181,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,용정,8003181,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,용정,8003181,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,용정,8003181,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,용정,8003181,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,용정,8003181,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,용정,8003181,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,용정,8003181,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,용정,8003181,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,용정,8003181,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,용정,8003181,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,용정,8003181,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,용정,8003181,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,용정,8003181,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,용정,8003181,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,용정,8003181,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,용정,8003181,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,용정,8003181,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,용정,8003181,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,용정,8003181,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,용정,8003181,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,용정,8003181,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,용정,8003181,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,용정,8003181,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,용정,8003181,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,용정,8003181,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,용정,8003181,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,용정,8003181,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,용정,8003181,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 사담  [8003105]  (36.81691, 127.64871)
📍 요청 위치: (36.8169°N, 127.6487°E)
📍 격자 좌표: (x=72, y=111)
📍 실제 위치: (36.8335°N, 127.6682°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,사담,8003105,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,사담,8003105,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,사담,8003105,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,사담,8003105,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,사담,8003105,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,사담,8003105,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,사담,8003105,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,사담,8003105,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,사담,8003105,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,사담,8003105,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,사담,8003105,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,사담,8003105,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,사담,8003105,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,사담,8003105,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,사담,8003105,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,사담,8003105,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,사담,8003105,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,사담,8003105,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,사담,8003105,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,사담,8003105,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,사담,8003105,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,사담,8003105,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,사담,8003105,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,사담,8003105,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,사담,8003105,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,사담,8003105,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,사담,8003105,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,사담,8003105,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,사담,8003105,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,사담,8003105,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,사담,8003105,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,사담,8003105,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,사담,8003105,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,사담,8003105,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,사담,8003105,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,사담,8003105,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,사담,8003105,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,사담,8003105,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,사담,8003105,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,사담,8003105,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,사담,8003105,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,사담,8003105,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 읍내  [8003108]  (36.772, 127.63951)
📍 요청 위치: (36.7720°N, 127.6395°E)
📍 격자 좌표: (x=72, y=110)
📍 실제 위치: (36.7875°N, 127.6670°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,읍내,8003108,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,읍내,8003108,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,읍내,8003108,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,읍내,8003108,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,읍내,8003108,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,읍내,8003108,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,읍내,8003108,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,읍내,8003108,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,읍내,8003108,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,읍내,8003108,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,읍내,8003108,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,읍내,8003108,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,읍내,8003108,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,읍내,8003108,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,읍내,8003108,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,읍내,8003108,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,읍내,8003108,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,읍내,8003108,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,읍내,8003108,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,읍내,8003108,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,읍내,8003108,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,읍내,8003108,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,읍내,8003108,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,읍내,8003108,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,읍내,8003108,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,읍내,8003108,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,읍내,8003108,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,읍내,8003108,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,읍내,8003108,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,읍내,8003108,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,읍내,8003108,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,읍내,8003108,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,읍내,8003108,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,읍내,8003108,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,읍내,8003108,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,읍내,8003108,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,읍내,8003108,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,읍내,8003108,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,읍내,8003108,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,읍내,8003108,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,읍내,8003108,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,읍내,8003108,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕정  [8003156]  (37.01838, 127.49516)
📍 요청 위치: (37.0184°N, 127.4952°E)
📍 격자 좌표: (x=69, y=115)
📍 실제 위치: (37.0204°N, 127.4999°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕정,8003156,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,덕정,8003156,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,덕정,8003156,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,덕정,8003156,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,덕정,8003156,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,덕정,8003156,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,덕정,8003156,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,덕정,8003156,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,덕정,8003156,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,덕정,8003156,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,덕정,8003156,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,덕정,8003156,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,덕정,8003156,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,덕정,8003156,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,덕정,8003156,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,덕정,8003156,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,덕정,8003156,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,덕정,8003156,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,덕정,8003156,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,덕정,8003156,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,덕정,8003156,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,덕정,8003156,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,덕정,8003156,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,덕정,8003156,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,덕정,8003156,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,덕정,8003156,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,덕정,8003156,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,덕정,8003156,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,덕정,8003156,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,덕정,8003156,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,덕정,8003156,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,덕정,8003156,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,덕정,8003156,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,덕정,8003156,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,덕정,8003156,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,덕정,8003156,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,덕정,8003156,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,덕정,8003156,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,덕정,8003156,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,덕정,8003156,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,덕정,8003156,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,덕정,8003156,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 쌍정  [8003159]  (36.9302, 127.5627)
📍 요청 위치: (36.9302°N, 127.5627°E)
📍 격자 좌표: (x=70, y=113)
📍 실제 위치: (36.9274°N, 127.5554°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,쌍정,8003159,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,쌍정,8003159,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,쌍정,8003159,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,쌍정,8003159,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,쌍정,8003159,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,쌍정,8003159,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,쌍정,8003159,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,쌍정,8003159,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,쌍정,8003159,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,쌍정,8003159,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,쌍정,8003159,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,쌍정,8003159,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,쌍정,8003159,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,쌍정,8003159,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,쌍정,8003159,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,쌍정,8003159,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,쌍정,8003159,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,쌍정,8003159,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,쌍정,8003159,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,쌍정,8003159,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,쌍정,8003159,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,쌍정,8003159,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,쌍정,8003159,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,쌍정,8003159,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,쌍정,8003159,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,쌍정,8003159,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,쌍정,8003159,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,쌍정,8003159,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,쌍정,8003159,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,쌍정,8003159,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,쌍정,8003159,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,쌍정,8003159,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,쌍정,8003159,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,쌍정,8003159,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,쌍정,8003159,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,쌍정,8003159,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,쌍정,8003159,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,쌍정,8003159,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,쌍정,8003159,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,쌍정,8003159,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,쌍정,8003159,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,쌍정,8003159,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동학사  [8004921]  (36.35921, 127.24289)
📍 요청 위치: (36.3592°N, 127.2429°E)
📍 격자 좌표: (x=65, y=101)
📍 실제 위치: (36.3794°N, 127.2566°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동학사,8004921,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,동학사,8004921,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,동학사,8004921,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,동학사,8004921,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,동학사,8004921,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,동학사,8004921,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,동학사,8004921,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,동학사,8004921,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,동학사,8004921,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,동학사,8004921,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,동학사,8004921,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,동학사,8004921,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,동학사,8004921,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,동학사,8004921,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,동학사,8004921,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,동학사,8004921,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,동학사,8004921,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,동학사,8004921,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,동학사,8004921,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,동학사,8004921,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,동학사,8004921,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,동학사,8004921,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,동학사,8004921,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,동학사,8004921,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,동학사,8004921,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,동학사,8004921,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,동학사,8004921,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,동학사,8004921,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,동학사,8004921,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,동학사,8004921,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,동학사,8004921,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,동학사,8004921,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,동학사,8004921,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,동학사,8004921,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,동학사,8004921,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,동학사,8004921,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,동학사,8004921,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,동학사,8004921,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,동학사,8004921,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,동학사,8004921,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,동학사,8004921,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,동학사,8004921,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 갑사분소  [8004922]  (36.36947, 127.18212)
📍 요청 위치: (36.3695°N, 127.1821°E)
📍 격자 좌표: (x=64, y=101)
📍 실제 위치: (36.3801°N, 127.1994°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,갑사분소,8004922,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,갑사분소,8004922,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,갑사분소,8004922,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,갑사분소,8004922,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,갑사분소,8004922,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,갑사분소,8004922,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,갑사분소,8004922,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,갑사분소,8004922,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,갑사분소,8004922,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,갑사분소,8004922,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,갑사분소,8004922,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,갑사분소,8004922,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,갑사분소,8004922,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,갑사분소,8004922,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,갑사분소,8004922,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,갑사분소,8004922,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,갑사분소,8004922,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,갑사분소,8004922,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,갑사분소,8004922,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,갑사분소,8004922,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,갑사분소,8004922,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,갑사분소,8004922,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,갑사분소,8004922,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,갑사분소,8004922,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,갑사분소,8004922,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,갑사분소,8004922,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,갑사분소,8004922,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,갑사분소,8004922,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,갑사분소,8004922,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,갑사분소,8004922,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,갑사분소,8004922,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,갑사분소,8004922,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,갑사분소,8004922,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,갑사분소,8004922,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,갑사분소,8004922,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,갑사분소,8004922,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,갑사분소,8004922,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,갑사분소,8004922,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,갑사분소,8004922,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,갑사분소,8004922,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,갑사분소,8004922,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,갑사분소,8004922,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주공항*  [8000128]  (36.71666667, 127.5)
📍 요청 위치: (36.7167°N, 127.5000°E)
📍 격자 좌표: (x=69, y=108)
📍 실제 위치: (36.6982°N, 127.4924°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주공항*,8000128,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주공항*,8000128,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주공항*,8000128,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주공항*,8000128,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주공항*,8000128,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주공항*,8000128,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주공항*,8000128,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주공항*,8000128,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주공항*,8000128,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주공항*,8000128,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주공항*,8000128,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주공항*,8000128,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주공항*,8000128,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주공항*,8000128,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주공항*,8000128,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주공항*,8000128,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주공항*,8000128,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주공항*,8000128,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주공항*,8000128,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주공항*,8000128,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주공항*,8000128,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주공항*,8000128,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주공항*,8000128,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주공항*,8000128,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주공항*,8000128,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주공항*,8000128,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주공항*,8000128,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주공항*,8000128,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주공항*,8000128,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주공항*,8000128,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주공항*,8000128,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주공항*,8000128,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주공항*,8000128,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주공항*,8000128,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주공항*,8000128,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주공항*,8000128,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주공항*,8000128,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주공항*,8000128,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주공항*,8000128,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주공항*,8000128,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주공항*,8000128,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주공항*,8000128,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 괴산군(고마리)  [1004424]  (36.8155556, 127.7363889)
📍 요청 위치: (36.8156°N, 127.7364°E)
📍 격자 좌표: (x=73, y=111)
📍 실제 위치: (36.8325°N, 127.7257°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,괴산군(고마리),1004424,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,괴산군(고마리),1004424,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,괴산군(고마리),1004424,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,괴산군(고마리),1004424,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,괴산군(고마리),1004424,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,괴산군(고마리),1004424,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,괴산군(고마리),1004424,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,괴산군(고마리),1004424,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,괴산군(고마리),1004424,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,괴산군(고마리),1004424,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,괴산군(고마리),1004424,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,괴산군(고마리),1004424,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,괴산군(고마리),1004424,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,괴산군(고마리),1004424,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,괴산군(고마리),1004424,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,괴산군(고마리),1004424,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,괴산군(고마리),1004424,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,괴산군(고마리),1004424,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,괴산군(고마리),1004424,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,괴산군(고마리),1004424,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,괴산군(고마리),1004424,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,괴산군(고마리),1004424,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,괴산군(고마리),1004424,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,괴산군(고마리),1004424,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,괴산군(고마리),1004424,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,괴산군(고마리),1004424,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,괴산군(고마리),1004424,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,괴산군(고마리),1004424,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,괴산군(고마리),1004424,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,괴산군(고마리),1004424,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,괴산군(고마리),1004424,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,괴산군(고마리),1004424,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,괴산군(고마리),1004424,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,괴산군(고마리),1004424,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,괴산군(고마리),1004424,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,괴산군(고마리),1004424,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,괴산군(고마리),1004424,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,괴산군(고마리),1004424,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,괴산군(고마리),1004424,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,괴산군(고마리),1004424,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,괴산군(고마리),1004424,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,괴산군(고마리),1004424,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(삼산리)  [9000038]  (36.3427778, 126.7169444)
📍 요청 위치: (36.3428°N, 126.7169°E)
📍 격자 좌표: (x=56, y=100)
📍 실제 위치: (36.3386°N, 126.7420°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(삼산리),9000038,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,부여군(삼산리),9000038,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,부여군(삼산리),9000038,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,부여군(삼산리),9000038,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,부여군(삼산리),9000038,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,부여군(삼산리),9000038,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,부여군(삼산리),9000038,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,부여군(삼산리),9000038,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,부여군(삼산리),9000038,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,부여군(삼산리),9000038,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,부여군(삼산리),9000038,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,부여군(삼산리),9000038,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,부여군(삼산리),9000038,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,부여군(삼산리),9000038,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,부여군(삼산리),9000038,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,부여군(삼산리),9000038,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,부여군(삼산리),9000038,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,부여군(삼산리),9000038,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,부여군(삼산리),9000038,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,부여군(삼산리),9000038,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,부여군(삼산리),9000038,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,부여군(삼산리),9000038,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,부여군(삼산리),9000038,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,부여군(삼산리),9000038,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,부여군(삼산리),9000038,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,부여군(삼산리),9000038,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,부여군(삼산리),9000038,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,부여군(삼산리),9000038,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,부여군(삼산리),9000038,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,부여군(삼산리),9000038,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,부여군(삼산리),9000038,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,부여군(삼산리),9000038,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,부여군(삼산리),9000038,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,부여군(삼산리),9000038,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,부여군(삼산리),9000038,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,부여군(삼산리),9000038,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,부여군(삼산리),9000038,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,부여군(삼산리),9000038,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,부여군(삼산리),9000038,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,부여군(삼산리),9000038,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,부여군(삼산리),9000038,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,부여군(삼산리),9000038,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(마전리)  [3008440]  (36.19, 127.4694444)
📍 요청 위치: (36.1900°N, 127.4694°E)
📍 격자 좌표: (x=69, y=97)
📍 실제 위치: (36.1924°N, 127.4807°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(마전리),3008440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(마전리),3008440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(마전리),3008440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(마전리),3008440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(마전리),3008440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(마전리),3008440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(마전리),3008440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(마전리),3008440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(마전리),3008440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(마전리),3008440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(마전리),3008440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(마전리),3008440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(마전리),3008440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(마전리),3008440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(마전리),3008440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(마전리),3008440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(마전리),3008440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(마전리),3008440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(마전리),3008440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(마전리),3008440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(마전리),3008440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(마전리),3008440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(마전리),3008440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(마전리),3008440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(마전리),3008440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(마전리),3008440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(마전리),3008440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(마전리),3008440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(마전리),3008440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(마전리),3008440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(마전리),3008440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(마전리),3008440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(마전리),3008440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(마전리),3008440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
📍 요청 위치: (36.5128°N, 127.5086°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(상장리),9000017,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(상장리),9000017,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(상장리),9000017,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(상장리),9000017,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(상장리),9000017,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(상장리),9000017,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(상장리),9000017,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(상장리),9000017,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(상장리),9000017,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(상장리),9000017,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(상장리),9000017,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(상장리),9000017,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(상장리),9000017,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(상장리),9000017,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(상장리),9000017,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(상장리),9000017,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(상장리),9000017,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(상장리),9000017,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(상장리),9000017,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(상장리),9000017,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(상장리),9000017,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(상장리),9000017,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(상장리),9000017,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(상장리),9000017,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(상장리),9000017,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(상장리),9000017,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(상장리),9000017,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(상장리),9000017,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(상장리),9000017,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(상장리),9000017,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(상장리),9000017,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(상장리),9000017,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(상장리),9000017,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(상장리),9000017,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 미원(전)  [28]  (36.7402778, 127.6711111)
📍 요청 위치: (36.7403°N, 127.6711°E)
📍 격자 좌표: (x=72, y=109)
📍 실제 위치: (36.7415°N, 127.6658°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,미원(전),28,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,미원(전),28,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,미원(전),28,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,미원(전),28,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,미원(전),28,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,미원(전),28,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,미원(전),28,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,미원(전),28,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,미원(전),28,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,미원(전),28,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,미원(전),28,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,미원(전),28,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,미원(전),28,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,미원(전),28,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,미원(전),28,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,미원(전),28,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,미원(전),28,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,미원(전),28,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,미원(전),28,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,미원(전),28,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,미원(전),28,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,미원(전),28,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,미원(전),28,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,미원(전),28,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,미원(전),28,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,미원(전),28,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,미원(전),28,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,미원(전),28,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,미원(전),28,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,미원(전),28,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,미원(전),28,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,미원(전),28,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,미원(전),28,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,미원(전),28,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,미원(전),28,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,미원(전),28,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,미원(전),28,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,미원(전),28,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,미원(전),28,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,미원(전),28,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,미원(전),28,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,미원(전),28,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
📍 요청 위치: (36.4550°N, 127.4442°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(문화재조사연구단),3008460,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
📍 요청 위치: (36.3236°N, 127.4344°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(인창교),9000121,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(인창교),9000121,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(인창교),9000121,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(인창교),9000121,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(인창교),9000121,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(인창교),9000121,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(인창교),9000121,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(인창교),9000121,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(인창교),9000121,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(인창교),9000121,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(인창교),9000121,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(인창교),9000121,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(인창교),9000121,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(인창교),9000121,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(인창교),9000121,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(인창교),9000121,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(인창교),9000121,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(인창교),9000121,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(인창교),9000121,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(인창교),9000121,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(인창교),9000121,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(인창교),9000121,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(인창교),9000121,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(인창교),9000121,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(인창교),9000121,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(인창교),9000121,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(인창교),9000121,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(인창교),9000121,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(인창교),9000121,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(인창교),9000121,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(인창교),9000121,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(인창교),9000121,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(인창교),9000121,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(인창교),9000121,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(두계교)  [9000079]  (36.26638889, 127.2788889)
📍 요청 위치: (36.2664°N, 127.2789°E)
📍 격자 좌표: (x=65, y=99)
📍 실제 위치: (36.2874°N, 127.2548°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(두계교),9000079,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(두계교),9000079,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(두계교),9000079,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(두계교),9000079,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(두계교),9000079,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(두계교),9000079,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(두계교),9000079,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(두계교),9000079,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(두계교),9000079,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(두계교),9000079,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(두계교),9000079,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(두계교),9000079,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(두계교),9000079,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(두계교),9000079,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(두계교),9000079,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(두계교),9000079,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(두계교),9000079,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(두계교),9000079,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(두계교),9000079,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(두계교),9000079,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(두계교),9000079,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(두계교),9000079,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(두계교),9000079,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(두계교),9000079,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(두계교),9000079,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(두계교),9000079,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(두계교),9000079,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(두계교),9000079,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(두계교),9000079,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(두계교),9000079,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(두계교),9000079,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(두계교),9000079,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(두계교),9000079,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(두계교),9000079,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(두계교),9000079,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(두계교),9000079,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(두계교),9000079,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(두계교),9000079,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(두계교),9000079,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(두계교),9000079,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(두계교),9000079,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(두계교),9000079,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(만년교)  [9000117]  (36.35166667, 127.3497222)
📍 요청 위치: (36.3517°N, 127.3497°E)
📍 격자 좌표: (x=67, y=100)
📍 실제 위치: (36.3319°N, 127.3698°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(만년교),9000117,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(만년교),9000117,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(만년교),9000117,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(만년교),9000117,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(만년교),9000117,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(만년교),9000117,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(만년교),9000117,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(만년교),9000117,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(만년교),9000117,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(만년교),9000117,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(만년교),9000117,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(만년교),9000117,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(만년교),9000117,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(만년교),9000117,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(만년교),9000117,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(만년교),9000117,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(만년교),9000117,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(만년교),9000117,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(만년교),9000117,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(만년교),9000117,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(만년교),9000117,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(만년교),9000117,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(만년교),9000117,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(만년교),9000117,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(만년교),9000117,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(만년교),9000117,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(만년교),9000117,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(만년교),9000117,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(만년교),9000117,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(만년교),9000117,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(만년교),9000117,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(만년교),9000117,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(만년교),9000117,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(만년교),9000117,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(만년교),9000117,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(만년교),9000117,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(만년교),9000117,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(만년교),9000117,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(만년교),9000117,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(만년교),9000117,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(만년교),9000117,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(만년교),9000117,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(원촌교)  [3009420]  (36.37833333, 127.41)
📍 요청 위치: (36.3783°N, 127.4100°E)
📍 격자 좌표: (x=68, y=101)
📍 실제 위치: (36.3771°N, 127.4279°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,대전시(원촌교),3009420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,대전시(원촌교),3009420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,대전시(원촌교),3009420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,대전시(원촌교),3009420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,대전시(원촌교),3009420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,대전시(원촌교),3009420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,대전시(원촌교),3009420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,대전시(원촌교),3009420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,대전시(원촌교),3009420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,대전시(원촌교),3009420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,대전시(원촌교),3009420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,대전시(원촌교),3009420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,대전시(원촌교),3009420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,대전시(원촌교),3009420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,대전시(원촌교),3009420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,대전시(원촌교),3009420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,대전시(원촌교),3009420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,대전시(원촌교),3009420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,대전시(원촌교),3009420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,대전시(원촌교),3009420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,대전시(원촌교),3009420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,대전시(원촌교),3009420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,대전시(원촌교),3009420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,대전시(원촌교),3009420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,대전시(원촌교),3009420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,대전시(원촌교),3009420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,대전시(원촌교),3009420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,대전시(원촌교),3009420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,대전시(원촌교),3009420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,대전시(원촌교),3009420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,대전시(원촌교),3009420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,대전시(원촌교),3009420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(부강면사무소)  [3011440]  (36.52916667, 127.3711111)
📍 요청 위치: (36.5292°N, 127.3711°E)
📍 격자 좌표: (x=67, y=104)
📍 실제 위치: (36.5158°N, 127.3737°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(부강면사무소),3011440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종시(부강면사무소),3011440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종시(부강면사무소),3011440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종시(부강면사무소),3011440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종시(부강면사무소),3011440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종시(부강면사무소),3011440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종시(부강면사무소),3011440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종시(부강면사무소),3011440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종시(부강면사무소),3011440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종시(부강면사무소),3011440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종시(부강면사무소),3011440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종시(부강면사무소),3011440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종시(부강면사무소),3011440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종시(부강면사무소),3011440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종시(부강면사무소),3011440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종시(부강면사무소),3011440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종시(부강면사무소),3011440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진천군(진천여중)  [3011420]  (36.86916667, 127.4561111)
📍 요청 위치: (36.8692°N, 127.4561°E)
📍 격자 좌표: (x=68, y=112)
📍 실제 위치: (36.8831°N, 127.4392°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진천군(진천여중),3011420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진천군(진천여중),3011420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진천군(진천여중),3011420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진천군(진천여중),3011420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진천군(진천여중),3011420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진천군(진천여중),3011420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진천군(진천여중),3011420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진천군(진천여중),3011420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진천군(진천여중),3011420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진천군(진천여중),3011420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진천군(진천여중),3011420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진천군(진천여중),3011420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진천군(진천여중),3011420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진천군(진천여중),3011420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진천군(진천여중),3011420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진천군(진천여중),3011420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진천군(진천여중),3011420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진천군(진천여중),3011420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진천군(진천여중),3011420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진천군(진천여중),3011420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진천군(진천여중),3011420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진천군(진천여중),3011420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진천군(진천여중),3011420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진천군(진천여중),3011420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진천군(진천여중),3011420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진천군(진천여중),3011420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진천군(진천여중),3011420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진천군(진천여중),3011420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진천군(진천여중),3011420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진천군(진천여중),3011420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진천군(진천여중),3011420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진천군(진천여중),3011420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진천군(진천여중),3011420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진천군(진천여중),3011420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진천군(진천여중),3011420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진천군(진천여중),3011420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진천군(진천여중),3011420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진천군(진천여중),3011420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진천군(진천여중),3011420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진천군(진천여중),3011420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진천군(진천여중),3011420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진천군(진천여중),3011420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 증평군(반탄교)  [3011450]  (36.78361111, 127.5725)
📍 요청 위치: (36.7836°N, 127.5725°E)
📍 격자 좌표: (x=70, y=110)
📍 실제 위치: (36.7894°N, 127.5520°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,증평군(반탄교),3011450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,증평군(반탄교),3011450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,증평군(반탄교),3011450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,증평군(반탄교),3011450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,증평군(반탄교),3011450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,증평군(반탄교),3011450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,증평군(반탄교),3011450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,증평군(반탄교),3011450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,증평군(반탄교),3011450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,증평군(반탄교),3011450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,증평군(반탄교),3011450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,증평군(반탄교),3011450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,증평군(반탄교),3011450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,증평군(반탄교),3011450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,증평군(반탄교),3011450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,증평군(반탄교),3011450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,증평군(반탄교),3011450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,증평군(반탄교),3011450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,증평군(반탄교),3011450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,증평군(반탄교),3011450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,증평군(반탄교),3011450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,증평군(반탄교),3011450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,증평군(반탄교),3011450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,증평군(반탄교),3011450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,증평군(반탄교),3011450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,증평군(반탄교),3011450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,증평군(반탄교),3011450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,증평군(반탄교),3011450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,증평군(반탄교),3011450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,증평군(반탄교),3011450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,증평군(반탄교),3011450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,증평군(반탄교),3011450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,증평군(반탄교),3011450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,증평군(반탄교),3011450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,증평군(반탄교),3011450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,증평군(반탄교),3011450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,증평군(반탄교),3011450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,증평군(반탄교),3011450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,증평군(반탄교),3011450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,증평군(반탄교),3011450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,증평군(반탄교),3011450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,증평군(반탄교),3011450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
📍 요청 위치: (36.5781°N, 127.5775°E)
📍 격자 좌표: (x=71, y=105)
📍 실제 위치: (36.5584°N, 127.6037°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(가덕초교),3011430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(가덕초교),3011430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(가덕초교),3011430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(가덕초교),3011430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(가덕초교),3011430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(가덕초교),3011430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(가덕초교),3011430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(흥덕교)  [3011460]  (36.64666667, 127.4813889)
📍 요청 위치: (36.6467°N, 127.4814°E)
📍 격자 좌표: (x=69, y=107)
📍 실제 위치: (36.6522°N, 127.4913°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(흥덕교),3011460,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청주시(흥덕교),3011460,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청주시(흥덕교),3011460,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청주시(흥덕교),3011460,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청주시(흥덕교),3011460,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청주시(흥덕교),3011460,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청주시(흥덕교),3011460,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청주시(흥덕교),3011460,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청주시(흥덕교),3011460,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청주시(흥덕교),3011460,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청주시(흥덕교),3011460,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청주시(흥덕교),3011460,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청주시(흥덕교),3011460,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청주시(흥덕교),3011460,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청주시(흥덕교),3011460,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청주시(흥덕교),3011460,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청주시(흥덕교),3011460,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(병천초교)  [3011410]  (36.765, 127.3)
📍 요청 위치: (36.7650°N, 127.3000°E)
📍 격자 좌표: (x=66, y=109)
📍 실제 위치: (36.7466°N, 127.3212°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(병천초교),3011410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안시(병천초교),3011410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안시(병천초교),3011410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안시(병천초교),3011410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안시(병천초교),3011410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안시(병천초교),3011410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안시(병천초교),3011410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안시(병천초교),3011410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안시(병천초교),3011410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안시(병천초교),3011410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안시(병천초교),3011410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안시(병천초교),3011410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안시(병천초교),3011410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안시(병천초교),3011410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안시(병천초교),3011410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안시(병천초교),3011410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안시(병천초교),3011410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안시(병천초교),3011410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안시(병천초교),3011410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안시(병천초교),3011410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안시(병천초교),3011410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안시(병천초교),3011410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안시(병천초교),3011410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안시(병천초교),3011410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안시(병천초교),3011410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안시(병천초교),3011410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안시(병천초교),3011410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안시(병천초교),3011410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안시(병천초교),3011410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안시(병천초교),3011410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안시(병천초교),3011410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안시(병천초교),3011410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안시(병천초교),3011410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안시(병천초교),3011410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안시(병천초교),3011410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안시(병천초교),3011410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안시(병천초교),3011410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안시(병천초교),3011410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안시(병천초교),3011410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안시(병천초교),3011410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안시(병천초교),3011410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안시(병천초교),3011410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 괴산군(문당리)  [9000078]  (36.74055, 127.67111)
📍 요청 위치: (36.7405°N, 127.6711°E)
📍 격자 좌표: (x=72, y=109)
📍 실제 위치: (36.7415°N, 127.6658°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,괴산군(문당리),9000078,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,괴산군(문당리),9000078,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,괴산군(문당리),9000078,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,괴산군(문당리),9000078,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,괴산군(문당리),9000078,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,괴산군(문당리),9000078,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,괴산군(문당리),9000078,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,괴산군(문당리),9000078,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,괴산군(문당리),9000078,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,괴산군(문당리),9000078,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,괴산군(문당리),9000078,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,괴산군(문당리),9000078,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,괴산군(문당리),9000078,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,괴산군(문당리),9000078,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,괴산군(문당리),9000078,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,괴산군(문당리),9000078,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,괴산군(문당리),9000078,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,괴산군(문당리),9000078,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,괴산군(문당리),9000078,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,괴산군(문당리),9000078,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,괴산군(문당리),9000078,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,괴산군(문당리),9000078,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,괴산군(문당리),9000078,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,괴산군(문당리),9000078,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,괴산군(문당리),9000078,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,괴산군(문당리),9000078,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,괴산군(문당리),9000078,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,괴산군(문당리),9000078,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,괴산군(문당리),9000078,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,괴산군(문당리),9000078,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,괴산군(문당리),9000078,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,괴산군(문당리),9000078,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,괴산군(문당리),9000078,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,괴산군(문당리),9000078,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,괴산군(문당리),9000078,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,괴산군(문당리),9000078,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,괴산군(문당리),9000078,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,괴산군(문당리),9000078,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,괴산군(문당리),9000078,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,괴산군(문당리),9000078,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,괴산군(문당리),9000078,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,괴산군(문당리),9000078,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 안성시(안성서운중교)  [1101422]  (36.94472, 127.26305)
📍 요청 위치: (36.9447°N, 127.2631°E)
📍 격자 좌표: (x=65, y=113)
📍 실제 위치: (36.9315°N, 127.2674°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,안성시(안성서운중교),1101422,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,안성시(안성서운중교),1101422,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,안성시(안성서운중교),1101422,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,안성시(안성서운중교),1101422,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,안성시(안성서운중교),1101422,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,안성시(안성서운중교),1101422,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,안성시(안성서운중교),1101422,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,안성시(안성서운중교),1101422,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,안성시(안성서운중교),1101422,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,안성시(안성서운중교),1101422,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,안성시(안성서운중교),1101422,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,안성시(안성서운중교),1101422,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,안성시(안성서운중교),1101422,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,안성시(안성서운중교),1101422,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,안성시(안성서운중교),1101422,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,안성시(안성서운중교),1101422,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,안성시(안성서운중교),1101422,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(음성고교)  [1004428]  (36.93416, 127.68611)
📍 요청 위치: (36.9342°N, 127.6861°E)
📍 격자 좌표: (x=72, y=113)
📍 실제 위치: (36.9256°N, 127.6706°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(음성고교),1004428,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,음성군(음성고교),1004428,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,음성군(음성고교),1004428,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,음성군(음성고교),1004428,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,음성군(음성고교),1004428,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,음성군(음성고교),1004428,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,음성군(음성고교),1004428,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,음성군(음성고교),1004428,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,음성군(음성고교),1004428,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,음성군(음성고교),1004428,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,음성군(음성고교),1004428,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,음성군(음성고교),1004428,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,음성군(음성고교),1004428,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,음성군(음성고교),1004428,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,음성군(음성고교),1004428,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,음성군(음성고교),1004428,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,음성군(음성고교),1004428,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,음성군(음성고교),1004428,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,음성군(음성고교),1004428,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,음성군(음성고교),1004428,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,음성군(음성고교),1004428,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,음성군(음성고교),1004428,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,음성군(음성고교),1004428,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,음성군(음성고교),1004428,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,음성군(음성고교),1004428,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,음성군(음성고교),1004428,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,음성군(음성고교),1004428,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,음성군(음성고교),1004428,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,음성군(음성고교),1004428,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,음성군(음성고교),1004428,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,음성군(음성고교),1004428,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,음성군(음성고교),1004428,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,음성군(음성고교),1004428,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,음성군(음성고교),1004428,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,음성군(음성고교),1004428,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,음성군(음성고교),1004428,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,음성군(음성고교),1004428,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,음성군(음성고교),1004428,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,음성군(음성고교),1004428,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,음성군(음성고교),1004428,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,음성군(음성고교),1004428,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,음성군(음성고교),1004428,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(성거읍사무소)  [1101424]  (36.87805, 127.19916)
📍 요청 위치: (36.8781°N, 127.1992°E)
📍 격자 좌표: (x=64, y=112)
📍 실제 위치: (36.8862°N, 127.2089°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안시(성거읍사무소),1101424,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안시(성거읍사무소),1101424,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안시(성거읍사무소),1101424,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안시(성거읍사무소),1101424,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안시(성거읍사무소),1101424,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안시(성거읍사무소),1101424,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(대소보건지소)  [3011440]  (36.9725, 127.4838889)
📍 요청 위치: (36.9725°N, 127.4839°E)
📍 격자 좌표: (x=69, y=114)
📍 실제 위치: (36.9744°N, 127.4989°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(대소보건지소),3011440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,음성군(대소보건지소),3011440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,음성군(대소보건지소),3011440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,음성군(대소보건지소),3011440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,음성군(대소보건지소),3011440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,음성군(대소보건지소),3011440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,음성군(대소보건지소),3011440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,음성군(대소보건지소),3011440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,음성군(대소보건지소),3011440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,음성군(대소보건지소),3011440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,음성군(대소보건지소),3011440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,음성군(대소보건지소),3011440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,음성군(대소보건지소),3011440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,음성군(대소보건지소),3011440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,음성군(대소보건지소),3011440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,음성군(대소보건지소),3011440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,음성군(대소보건지소),3011440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(쌍봉리)  [9000188]  (37.00277778, 127.5552778)
📍 요청 위치: (37.0028°N, 127.5553°E)
📍 격자 좌표: (x=70, y=115)
📍 실제 위치: (37.0195°N, 127.5576°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(쌍봉리),9000188,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,음성군(쌍봉리),9000188,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,음성군(쌍봉리),9000188,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,음성군(쌍봉리),9000188,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,음성군(쌍봉리),9000188,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,음성군(쌍봉리),9000188,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,음성군(쌍봉리),9000188,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,음성군(쌍봉리),9000188,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,음성군(쌍봉리),9000188,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,음성군(쌍봉리),9000188,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,음성군(쌍봉리),9000188,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,음성군(쌍봉리),9000188,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,음성군(쌍봉리),9000188,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,음성군(쌍봉리),9000188,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,음성군(쌍봉리),9000188,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,음성군(쌍봉리),9000188,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,음성군(쌍봉리),9000188,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(농정원)  [3011470]  (36.5925, 127.2925)
📍 요청 위치: (36.5925°N, 127.2925°E)
📍 격자 좌표: (x=66, y=106)
📍 실제 위치: (36.6086°N, 127.3184°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(농정원),3011470,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종시(농정원),3011470,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종시(농정원),3011470,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종시(농정원),3011470,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종시(농정원),3011470,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종시(농정원),3011470,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종시(농정원),3011470,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종시(농정원),3011470,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종시(농정원),3011470,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종시(농정원),3011470,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종시(농정원),3011470,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종시(농정원),3011470,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종시(농정원),3011470,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종시(농정원),3011470,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종시(농정원),3011470,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종시(농정원),3011470,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종시(농정원),3011470,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종시(농정원),3011470,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종시(농정원),3011470,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종시(농정원),3011470,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종시(농정원),3011470,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종시(농정원),3011470,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종시(농정원),3011470,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종시(농정원),3011470,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종시(농정원),3011470,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종시(농정원),3011470,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종시(농정원),3011470,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종시(농정원),3011470,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종시(농정원),3011470,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종시(농정원),3011470,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종시(농정원),3011470,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종시(농정원),3011470,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종시(농정원),3011470,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종시(농정원),3011470,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종시(농정원),3011470,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종시(농정원),3011470,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종시(농정원),3011470,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종시(농정원),3011470,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종시(농정원),3011470,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종시(농정원),3011470,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종시(농정원),3011470,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종시(농정원),3011470,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(문성교)  [9000191]  (36.51472222, 127.1961111)
📍 요청 위치: (36.5147°N, 127.1961°E)
📍 격자 좌표: (x=64, y=104)
📍 실제 위치: (36.5180°N, 127.2020°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(문성교),9000191,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,세종시(문성교),9000191,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,세종시(문성교),9000191,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,세종시(문성교),9000191,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,세종시(문성교),9000191,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,세종시(문성교),9000191,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,세종시(문성교),9000191,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,세종시(문성교),9000191,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,세종시(문성교),9000191,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,세종시(문성교),9000191,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,세종시(문성교),9000191,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,세종시(문성교),9000191,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,세종시(문성교),9000191,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,세종시(문성교),9000191,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,세종시(문성교),9000191,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,세종시(문성교),9000191,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,세종시(문성교),9000191,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,세종시(문성교),9000191,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,세종시(문성교),9000191,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,세종시(문성교),9000191,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,세종시(문성교),9000191,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,세종시(문성교),9000191,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,세종시(문성교),9000191,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,세종시(문성교),9000191,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,세종시(문성교),9000191,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,세종시(문성교),9000191,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,세종시(문성교),9000191,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,세종시(문성교),9000191,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,세종시(문성교),9000191,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,세종시(문성교),9000191,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,세종시(문성교),9000191,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,세종시(문성교),9000191,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,세종시(문성교),9000191,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,세종시(문성교),9000191,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,세종시(문성교),9000191,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,세종시(문성교),9000191,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,세종시(문성교),9000191,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,세종시(문성교),9000191,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,세종시(문성교),9000191,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,세종시(문성교),9000191,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,세종시(문성교),9000191,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,세종시(문성교),9000191,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(화청교)  [9000194]  (36.76194444, 127.3980556)
📍 요청 위치: (36.7619°N, 127.3981°E)
📍 격자 좌표: (x=67, y=109)
📍 실제 위치: (36.7459°N, 127.3786°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(화청교),9000194,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안시(화청교),9000194,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안시(화청교),9000194,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안시(화청교),9000194,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안시(화청교),9000194,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안시(화청교),9000194,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안시(화청교),9000194,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안시(화청교),9000194,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안시(화청교),9000194,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안시(화청교),9000194,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안시(화청교),9000194,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안시(화청교),9000194,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안시(화청교),9000194,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안시(화청교),9000194,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안시(화청교),9000194,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안시(화청교),9000194,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안시(화청교),9000194,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안시(화청교),9000194,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안시(화청교),9000194,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안시(화청교),9000194,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안시(화청교),9000194,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안시(화청교),9000194,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안시(화청교),9000194,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안시(화청교),9000194,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안시(화청교),9000194,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안시(화청교),9000194,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안시(화청교),9000194,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안시(화청교),9000194,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안시(화청교),9000194,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안시(화청교),9000194,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안시(화청교),9000194,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안시(화청교),9000194,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안시(화청교),9000194,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안시(화청교),9000194,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안시(화청교),9000194,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안시(화청교),9000194,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안시(화청교),9000194,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안시(화청교),9000194,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안시(화청교),9000194,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안시(화청교),9000194,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안시(화청교),9000194,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안시(화청교),9000194,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(신흥교)  [9000200]  (36.70305556, 127.1133333)
📍 요청 위치: (36.7031°N, 127.1133°E)
📍 격자 좌표: (x=62, y=108)
📍 실제 위치: (36.7034°N, 127.0907°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(신흥교),9000200,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,천안시(신흥교),9000200,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,천안시(신흥교),9000200,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,천안시(신흥교),9000200,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,천안시(신흥교),9000200,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,천안시(신흥교),9000200,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,천안시(신흥교),9000200,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,천안시(신흥교),9000200,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,천안시(신흥교),9000200,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,천안시(신흥교),9000200,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,천안시(신흥교),9000200,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,천안시(신흥교),9000200,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,천안시(신흥교),9000200,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,천안시(신흥교),9000200,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,천안시(신흥교),9000200,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,천안시(신흥교),9000200,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,천안시(신흥교),9000200,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,천안시(신흥교),9000200,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,천안시(신흥교),9000200,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,천안시(신흥교),9000200,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,천안시(신흥교),9000200,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,천안시(신흥교),9000200,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,천안시(신흥교),9000200,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,천안시(신흥교),9000200,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,천안시(신흥교),9000200,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,천안시(신흥교),9000200,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,천안시(신흥교),9000200,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,천안시(신흥교),9000200,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,천안시(신흥교),9000200,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,천안시(신흥교),9000200,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,천안시(신흥교),9000200,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,천안시(신흥교),9000200,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,천안시(신흥교),9000200,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,천안시(신흥교),9000200,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,천안시(신흥교),9000200,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,천안시(신흥교),9000200,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,천안시(신흥교),9000200,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,천안시(신흥교),9000200,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,천안시(신흥교),9000200,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,천안시(신흥교),9000200,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,천안시(신흥교),9000200,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,천안시(신흥교),9000200,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(금강교)  [3012405]  (36.47027778, 127.1277778)
📍 요청 위치: (36.4703°N, 127.1278°E)
📍 격자 좌표: (x=63, y=103)
📍 실제 위치: (36.4727°N, 127.1440°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(금강교),3012405,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(금강교),3012405,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(금강교),3012405,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(금강교),3012405,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(금강교),3012405,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(금강교),3012405,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(금강교),3012405,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(금강교),3012405,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(금강교),3012405,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(금강교),3012405,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(금강교),3012405,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(금강교),3012405,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(금강교),3012405,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(금강교),3012405,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(금강교),3012405,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(금강교),3012405,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(금강교),3012405,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(금강교),3012405,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(금강교),3012405,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(금강교),3012405,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(금강교),3012405,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(금강교),3012405,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(금강교),3012405,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(금강교),3012405,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(금강교),3012405,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(금강교),3012405,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(금강교),3012405,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(금강교),3012405,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(금강교),3012405,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(금강교),3012405,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(금강교),3012405,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(금강교),3012405,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(금강교),3012405,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(금강교),3012405,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(금강교),3012405,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(금강교),3012405,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(금강교),3012405,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(금강교),3012405,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(금강교),3012405,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(금강교),3012405,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(금강교),3012405,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(금강교),3012405,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(신대리)  [3009410]  (36.21388889, 127.3791667)
📍 요청 위치: (36.2139°N, 127.3792°E)
📍 격자 좌표: (x=67, y=97)
📍 실제 위치: (36.1940°N, 127.3669°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(신대리),3009410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,금산군(신대리),3009410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,금산군(신대리),3009410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,금산군(신대리),3009410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,금산군(신대리),3009410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,금산군(신대리),3009410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,금산군(신대리),3009410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,금산군(신대리),3009410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,금산군(신대리),3009410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,금산군(신대리),3009410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,금산군(신대리),3009410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,금산군(신대리),3009410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,금산군(신대리),3009410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,금산군(신대리),3009410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,금산군(신대리),3009410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,금산군(신대리),3009410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,금산군(신대리),3009410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,금산군(신대리),3009410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,금산군(신대리),3009410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,금산군(신대리),3009410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,금산군(신대리),3009410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,금산군(신대리),3009410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,금산군(신대리),3009410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,금산군(신대리),3009410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,금산군(신대리),3009410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,금산군(신대리),3009410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,금산군(신대리),3009410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,금산군(신대리),3009410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,금산군(신대리),3009410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,금산군(신대리),3009410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,금산군(신대리),3009410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,금산군(신대리),3009410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,금산군(신대리),3009410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,금산군(신대리),3009410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,금산군(신대리),3009410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,금산군(신대리),3009410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,금산군(신대리),3009410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,금산군(신대리),3009410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,금산군(신대리),3009410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,금산군(신대리),3009410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,금산군(신대리),3009410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,금산군(신대리),3009410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(정안면사무소)  [3012430]  (36.60861111, 127.1202778)
📍 요청 위치: (36.6086°N, 127.1203°E)
📍 격자 좌표: (x=63, y=106)
📍 실제 위치: (36.6107°N, 127.1464°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(정안면사무소),3012430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(정안면사무소),3012430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(정안면사무소),3012430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(정안면사무소),3012430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(정안면사무소),3012430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(정안면사무소),3012430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(정안면사무소),3012430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(정안면사무소),3012430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(정안면사무소),3012430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(정안면사무소),3012430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(정안면사무소),3012430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(정안면사무소),3012430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(정안면사무소),3012430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(정안면사무소),3012430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(정안면사무소),3012430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(정안면사무소),3012430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(정안면사무소),3012430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(반포중)  [3012425]  (36.40361111, 127.2430556)
📍 요청 위치: (36.4036°N, 127.2431°E)
📍 격자 좌표: (x=65, y=102)
📍 실제 위치: (36.4254°N, 127.2574°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(반포중),3012425,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(반포중),3012425,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(반포중),3012425,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(반포중),3012425,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(반포중),3012425,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(반포중),3012425,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(반포중),3012425,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(반포중),3012425,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(반포중),3012425,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(반포중),3012425,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(반포중),3012425,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(반포중),3012425,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(반포중),3012425,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(반포중),3012425,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(반포중),3012425,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(반포중),3012425,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(반포중),3012425,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(반포중),3012425,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(반포중),3012425,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(반포중),3012425,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(반포중),3012425,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(반포중),3012425,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(반포중),3012425,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(반포중),3012425,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(반포중),3012425,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(반포중),3012425,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(반포중),3012425,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(반포중),3012425,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(반포중),3012425,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(반포중),3012425,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(반포중),3012425,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(반포중),3012425,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(반포중),3012425,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(반포중),3012425,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(반포중),3012425,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(반포중),3012425,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(반포중),3012425,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(반포중),3012425,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(반포중),3012425,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(반포중),3012425,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(반포중),3012425,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(반포중),3012425,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(복룡리)  [3012440]  (36.34555556, 127.0680556)
📍 요청 위치: (36.3456°N, 127.0681°E)
📍 격자 좌표: (x=62, y=100)
📍 실제 위치: (36.3354°N, 127.0845°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(복룡리),3012440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(복룡리),3012440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(복룡리),3012440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(복룡리),3012440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(복룡리),3012440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(복룡리),3012440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(복룡리),3012440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(복룡리),3012440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(복룡리),3012440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(복룡리),3012440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(복룡리),3012440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(복룡리),3012440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(복룡리),3012440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(복룡리),3012440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(복룡리),3012440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(복룡리),3012440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(복룡리),3012440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(복룡리),3012440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(복룡리),3012440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(복룡리),3012440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(복룡리),3012440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(복룡리),3012440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(복룡리),3012440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(복룡리),3012440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(복룡리),3012440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(복룡리),3012440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(복룡리),3012440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(복룡리),3012440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(복룡리),3012440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(복룡리),3012440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(복룡리),3012440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(복룡리),3012440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(복룡리),3012440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(복룡리),3012440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(복룡리),3012440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(복룡리),3012440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(복룡리),3012440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(복룡리),3012440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(복룡리),3012440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(복룡리),3012440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(복룡리),3012440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(복룡리),3012440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(유구초교)  [3012445]  (36.55361111, 126.9505556)
📍 요청 위치: (36.5536°N, 126.9506°E)
📍 격자 좌표: (x=60, y=105)
📍 실제 위치: (36.5665°N, 126.9738°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(유구초교),3012445,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,공주시(유구초교),3012445,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,공주시(유구초교),3012445,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,공주시(유구초교),3012445,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,공주시(유구초교),3012445,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,공주시(유구초교),3012445,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,공주시(유구초교),3012445,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,공주시(유구초교),3012445,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,공주시(유구초교),3012445,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,공주시(유구초교),3012445,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,공주시(유구초교),3012445,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,공주시(유구초교),3012445,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,공주시(유구초교),3012445,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,공주시(유구초교),3012445,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,공주시(유구초교),3012445,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,공주시(유구초교),3012445,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,공주시(유구초교),3012445,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,공주시(유구초교),3012445,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,공주시(유구초교),3012445,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,공주시(유구초교),3012445,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,공주시(유구초교),3012445,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,공주시(유구초교),3012445,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,공주시(유구초교),3012445,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,공주시(유구초교),3012445,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,공주시(유구초교),3012445,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,공주시(유구초교),3012445,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,공주시(유구초교),3012445,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,공주시(유구초교),3012445,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,공주시(유구초교),3012445,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,공주시(유구초교),3012445,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,공주시(유구초교),3012445,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,공주시(유구초교),3012445,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,공주시(유구초교),3012445,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,공주시(유구초교),3012445,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,공주시(유구초교),3012445,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,공주시(유구초교),3012445,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,공주시(유구초교),3012445,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,공주시(유구초교),3012445,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,공주시(유구초교),3012445,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,공주시(유구초교),3012445,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,공주시(유구초교),3012445,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,공주시(유구초교),3012445,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(홍산초교)  [3012410]  (36.2175, 126.7625)
📍 요청 위치: (36.2175°N, 126.7625°E)
📍 격자 좌표: (x=56, y=97)
📍 실제 위치: (36.2007°N, 126.7404°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(홍산초교),3012410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,부여군(홍산초교),3012410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,부여군(홍산초교),3012410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,부여군(홍산초교),3012410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,부여군(홍산초교),3012410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,부여군(홍산초교),3012410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,부여군(홍산초교),3012410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,부여군(홍산초교),3012410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,부여군(홍산초교),3012410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,부여군(홍산초교),3012410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,부여군(홍산초교),3012410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,부여군(홍산초교),3012410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,부여군(홍산초교),3012410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,부여군(홍산초교),3012410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,부여군(홍산초교),3012410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,부여군(홍산초교),3012410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,부여군(홍산초교),3012410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(백제교)  [3012450]  (36.27583333, 126.8916667)
📍 요청 위치: (36.2758°N, 126.8917°E)
📍 격자 좌표: (x=59, y=99)
📍 실제 위치: (36.2912°N, 126.9126°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(백제교),3012450,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,부여군(백제교),3012450,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,부여군(백제교),3012450,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,부여군(백제교),3012450,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,부여군(백제교),3012450,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,부여군(백제교),3012450,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,부여군(백제교),3012450,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,부여군(백제교),3012450,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,부여군(백제교),3012450,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,부여군(백제교),3012450,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,부여군(백제교),3012450,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,부여군(백제교),3012450,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,부여군(백제교),3012450,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,부여군(백제교),3012450,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,부여군(백제교),3012450,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,부여군(백제교),3012450,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,부여군(백제교),3012450,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,부여군(백제교),3012450,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,부여군(백제교),3012450,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,부여군(백제교),3012450,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,부여군(백제교),3012450,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,부여군(백제교),3012450,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,부여군(백제교),3012450,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,부여군(백제교),3012450,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,부여군(백제교),3012450,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,부여군(백제교),3012450,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,부여군(백제교),3012450,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,부여군(백제교),3012450,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,부여군(백제교),3012450,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,부여군(백제교),3012450,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,부여군(백제교),3012450,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,부여군(백제교),3012450,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,부여군(백제교),3012450,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,부여군(백제교),3012450,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,부여군(백제교),3012450,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,부여군(백제교),3012450,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,부여군(백제교),3012450,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,부여군(백제교),3012450,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,부여군(백제교),3012450,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,부여군(백제교),3012450,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,부여군(백제교),3012450,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,부여군(백제교),3012450,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양군(청양읍사무소)  [3012420]  (36.45361111, 126.8066667)
📍 요청 위치: (36.4536°N, 126.8067°E)
📍 격자 좌표: (x=57, y=103)
📍 실제 위치: (36.4761°N, 126.8008°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청양군(청양읍사무소),3012420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청양군(청양읍사무소),3012420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청양군(청양읍사무소),3012420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청양군(청양읍사무소),3012420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청양군(청양읍사무소),3012420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청양군(청양읍사무소),3012420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양군(119안전센터)  [3012435]  (36.41805556, 126.94)
📍 요청 위치: (36.4181°N, 126.9400°E)
📍 격자 좌표: (x=59, y=102)
📍 실제 위치: (36.4291°N, 126.9145°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양군(119안전센터),3012435,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,청양군(119안전센터),3012435,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,청양군(119안전센터),3012435,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,청양군(119안전센터),3012435,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,청양군(119안전센터),3012435,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,청양군(119안전센터),3012435,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,청양군(119안전센터),3012435,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,청양군(119안전센터),3012435,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,청양군(119안전센터),3012435,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,청양군(119안전센터),3012435,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,청양군(119안전센터),3012435,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,청양군(119안전센터),3012435,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,청양군(119안전센터),3012435,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,청양군(119안전센터),3012435,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,청양군(119안전센터),3012435,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,청양군(119안전센터),3012435,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,청양군(119안전센터),3012435,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보령시(미산면사무소)  [3203442]  (36.21083333, 126.6775)
📍 요청 위치: (36.2108°N, 126.6775°E)
📍 격자 좌표: (x=55, y=97)
📍 실제 위치: (36.2011°N, 126.6835°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보령시(미산면사무소),3203442,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,보령시(미산면사무소),3203442,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,보령시(미산면사무소),3203442,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,보령시(미산면사무소),3203442,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,보령시(미산면사무소),3203442,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,보령시(미산면사무소),3203442,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,보령시(미산면사무소),3203442,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,보령시(미산면사무소),3203442,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,보령시(미산면사무소),3203442,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,보령시(미산면사무소),3203442,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,보령시(미산면사무소),3203442,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,보령시(미산면사무소),3203442,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,보령시(미산면사무소),3203442,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,보령시(미산면사무소),3203442,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,보령시(미산면사무소),3203442,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,보령시(미산면사무소),3203442,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,보령시(미산면사무소),3203442,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(연산중)  [3013420]  (36.21333333, 127.2069444)
📍 요청 위치: (36.2133°N, 127.2069°E)
📍 격자 좌표: (x=64, y=97)
📍 실제 위치: (36.1962°N, 127.1960°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(연산중),3013420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산시(연산중),3013420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산시(연산중),3013420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산시(연산중),3013420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산시(연산중),3013420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산시(연산중),3013420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산시(연산중),3013420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산시(연산중),3013420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산시(연산중),3013420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산시(연산중),3013420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산시(연산중),3013420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산시(연산중),3013420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산시(연산중),3013420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산시(연산중),3013420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산시(연산중),3013420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산시(연산중),3013420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산시(연산중),3013420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산시(연산중),3013420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산시(연산중),3013420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산시(연산중),3013420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산시(연산중),3013420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산시(연산중),3013420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산시(연산중),3013420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산시(연산중),3013420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산시(연산중),3013420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산시(연산중),3013420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산시(연산중),3013420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산시(연산중),3013420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산시(연산중),3013420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산시(연산중),3013420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산시(연산중),3013420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산시(연산중),3013420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산시(연산중),3013420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산시(연산중),3013420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산시(연산중),3013420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산시(연산중),3013420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산시(연산중),3013420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산시(연산중),3013420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산시(연산중),3013420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산시(연산중),3013420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산시(연산중),3013420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산시(연산중),3013420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(동산초교)  [3013440]  (36.14027778, 127.2416667)
📍 요청 위치: (36.1403°N, 127.2417°E)
📍 격자 좌표: (x=65, y=96)
📍 실제 위치: (36.1496°N, 127.2521°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(동산초교),3013440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산시(동산초교),3013440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산시(동산초교),3013440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산시(동산초교),3013440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산시(동산초교),3013440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산시(동산초교),3013440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산시(동산초교),3013440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산시(동산초교),3013440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산시(동산초교),3013440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산시(동산초교),3013440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산시(동산초교),3013440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산시(동산초교),3013440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산시(동산초교),3013440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산시(동산초교),3013440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산시(동산초교),3013440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산시(동산초교),3013440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산시(동산초교),3013440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산시(동산초교),3013440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산시(동산초교),3013440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산시(동산초교),3013440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산시(동산초교),3013440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산시(동산초교),3013440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산시(동산초교),3013440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산시(동산초교),3013440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산시(동산초교),3013440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산시(동산초교),3013440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산시(동산초교),3013440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산시(동산초교),3013440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산시(동산초교),3013440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산시(동산초교),3013440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산시(동산초교),3013440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산시(동산초교),3013440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산시(동산초교),3013440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산시(동산초교),3013440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산시(동산초교),3013440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산시(동산초교),3013440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산시(동산초교),3013440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산시(동산초교),3013440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산시(동산초교),3013440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산시(동산초교),3013440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산시(동산초교),3013440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산시(동산초교),3013440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(토양리)  [9000190]  (36.14916667, 127.1025)
📍 요청 위치: (36.1492°N, 127.1025°E)
📍 격자 좌표: (x=62, y=96)
📍 실제 위치: (36.1516°N, 127.0814°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(토양리),9000190,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산시(토양리),9000190,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산시(토양리),9000190,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산시(토양리),9000190,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산시(토양리),9000190,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산시(토양리),9000190,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산시(토양리),9000190,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산시(토양리),9000190,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산시(토양리),9000190,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산시(토양리),9000190,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산시(토양리),9000190,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산시(토양리),9000190,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산시(토양리),9000190,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산시(토양리),9000190,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산시(토양리),9000190,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산시(토양리),9000190,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산시(토양리),9000190,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산시(토양리),9000190,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산시(토양리),9000190,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산시(토양리),9000190,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산시(토양리),9000190,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산시(토양리),9000190,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산시(토양리),9000190,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산시(토양리),9000190,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산시(토양리),9000190,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산시(토양리),9000190,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산시(토양리),9000190,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산시(토양리),9000190,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산시(토양리),9000190,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산시(토양리),9000190,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산시(토양리),9000190,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산시(토양리),9000190,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산시(토양리),9000190,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산시(토양리),9000190,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산시(토양리),9000190,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산시(토양리),9000190,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산시(토양리),9000190,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산시(토양리),9000190,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산시(토양리),9000190,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산시(토양리),9000190,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산시(토양리),9000190,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산시(토양리),9000190,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(황산리)  [3013410]  (36.15444444, 127.0086111)
📍 요청 위치: (36.1544°N, 127.0086°E)
📍 격자 좌표: (x=61, y=96)
📍 실제 위치: (36.1522°N, 127.0245°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(황산리),3013410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,논산시(황산리),3013410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,논산시(황산리),3013410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,논산시(황산리),3013410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,논산시(황산리),3013410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,논산시(황산리),3013410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,논산시(황산리),3013410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,논산시(황산리),3013410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,논산시(황산리),3013410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,논산시(황산리),3013410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,논산시(황산리),3013410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,논산시(황산리),3013410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,논산시(황산리),3013410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,논산시(황산리),3013410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,논산시(황산리),3013410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,논산시(황산리),3013410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,논산시(황산리),3013410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,논산시(황산리),3013410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,논산시(황산리),3013410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,논산시(황산리),3013410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,논산시(황산리),3013410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,논산시(황산리),3013410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,논산시(황산리),3013410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,논산시(황산리),3013410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,논산시(황산리),3013410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,논산시(황산리),3013410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,논산시(황산리),3013410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,논산시(황산리),3013410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,논산시(황산리),3013410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,논산시(황산리),3013410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,논산시(황산리),3013410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,논산시(황산리),3013410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,논산시(황산리),3013410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,논산시(황산리),3013410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,논산시(황산리),3013410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,논산시(황산리),3013410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,논산시(황산리),3013410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,논산시(황산리),3013410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,논산시(황산리),3013410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,논산시(황산리),3013410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,논산시(황산리),3013410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,논산시(황산리),3013410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천군(망월리)  [3203440]  (36.02944444, 126.7569444)
📍 요청 위치: (36.0294°N, 126.7569°E)
📍 격자 좌표: (x=56, y=93)
📍 실제 위치: (36.0169°N, 126.7383°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천군(망월리),3203440,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,서천군(망월리),3203440,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,서천군(망월리),3203440,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,서천군(망월리),3203440,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,서천군(망월리),3203440,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,서천군(망월리),3203440,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,서천군(망월리),3203440,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,서천군(망월리),3203440,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,서천군(망월리),3203440,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,서천군(망월리),3203440,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,서천군(망월리),3203440,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,서천군(망월리),3203440,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,서천군(망월리),3203440,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,서천군(망월리),3203440,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,서천군(망월리),3203440,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,서천군(망월리),3203440,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,서천군(망월리),3203440,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,서천군(망월리),3203440,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,서천군(망월리),3203440,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,서천군(망월리),3203440,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,서천군(망월리),3203440,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,서천군(망월리),3203440,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,서천군(망월리),3203440,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,서천군(망월리),3203440,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,서천군(망월리),3203440,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,서천군(망월리),3203440,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,서천군(망월리),3203440,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,서천군(망월리),3203440,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,서천군(망월리),3203440,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,서천군(망월리),3203440,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,서천군(망월리),3203440,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,서천군(망월리),3203440,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,서천군(망월리),3203440,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,서천군(망월리),3203440,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,서천군(망월리),3203440,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,서천군(망월리),3203440,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,서천군(망월리),3203440,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,서천군(망월리),3203440,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,서천군(망월리),3203440,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,서천군(망월리),3203440,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,서천군(망월리),3203440,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,서천군(망월리),3203440,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천군(충남디자인예술고)  [3014430]  (36.08916667, 126.8036111)
📍 요청 위치: (36.0892°N, 126.8036°E)
📍 격자 좌표: (x=57, y=95)
📍 실제 위치: (36.1083°N, 126.7963°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,서천군(충남디자인예술고),3014430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,서천군(충남디자인예술고),3014430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,서천군(충남디자인예술고),3014430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,서천군(충남디자인예술고),3014430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,서천군(충남디자인예술고),3014430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,서천군(충남디자인예술고),3014430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(대불리)  [3001442]  (35.96166667, 127.365)
📍 요청 위치: (35.9617°N, 127.3650°E)
📍 격자 좌표: (x=67, y=92)
📍 실제 위치: (35.9643°N, 127.3620°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(대불리),3001442,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,진안군(대불리),3001442,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,진안군(대불리),3001442,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,진안군(대불리),3001442,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,진안군(대불리),3001442,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,진안군(대불리),3001442,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,진안군(대불리),3001442,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,진안군(대불리),3001442,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,진안군(대불리),3001442,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,진안군(대불리),3001442,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,진안군(대불리),3001442,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,진안군(대불리),3001442,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,진안군(대불리),3001442,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,진안군(대불리),3001442,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,진안군(대불리),3001442,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,진안군(대불리),3001442,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,진안군(대불리),3001442,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,진안군(대불리),3001442,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,진안군(대불리),3001442,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,진안군(대불리),3001442,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,진안군(대불리),3001442,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,진안군(대불리),3001442,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,진안군(대불리),3001442,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,진안군(대불리),3001442,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,진안군(대불리),3001442,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,진안군(대불리),3001442,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,진안군(대불리),3001442,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,진안군(대불리),3001442,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,진안군(대불리),3001442,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,진안군(대불리),3001442,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,진안군(대불리),3001442,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,진안군(대불리),3001442,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,진안군(대불리),3001442,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,진안군(대불리),3001442,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,진안군(대불리),3001442,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,진안군(대불리),3001442,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,진안군(대불리),3001442,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,진안군(대불리),3001442,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,진안군(대불리),3001442,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,진안군(대불리),3001442,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,진안군(대불리),3001442,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,진안군(대불리),3001442,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 완주군(장선초교)  [3013430]  (36.09111111, 127.2791667)
📍 요청 위치: (36.0911°N, 127.2792°E)
📍 격자 좌표: (x=65, y=95)
📍 실제 위치: (36.1036°N, 127.2512°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,완주군(장선초교),3013430,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,완주군(장선초교),3013430,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,완주군(장선초교),3013430,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,완주군(장선초교),3013430,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,완주군(장선초교),3013430,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,완주군(장선초교),3013430,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,완주군(장선초교),3013430,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,완주군(장선초교),3013430,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,완주군(장선초교),3013430,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,완주군(장선초교),3013430,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,완주군(장선초교),3013430,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,완주군(장선초교),3013430,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,완주군(장선초교),3013430,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,완주군(장선초교),3013430,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,완주군(장선초교),3013430,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,완주군(장선초교),3013430,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,완주군(장선초교),3013430,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,완주군(장선초교),3013430,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,완주군(장선초교),3013430,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,완주군(장선초교),3013430,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,완주군(장선초교),3013430,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,완주군(장선초교),3013430,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,완주군(장선초교),3013430,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,완주군(장선초교),3013430,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,완주군(장선초교),3013430,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,완주군(장선초교),3013430,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,완주군(장선초교),3013430,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,완주군(장선초교),3013430,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,완주군(장선초교),3013430,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,완주군(장선초교),3013430,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,완주군(장선초교),3013430,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,완주군(장선초교),3013430,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,완주군(장선초교),3013430,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,완주군(장선초교),3013430,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,완주군(장선초교),3013430,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,완주군(장선초교),3013430,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,완주군(장선초교),3013430,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,완주군(장선초교),3013430,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,완주군(장선초교),3013430,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,완주군(장선초교),3013430,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,완주군(장선초교),3013430,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,완주군(장선초교),3013430,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산시(함열초교)  [3014410]  (36.07972222, 126.9652778)
📍 요청 위치: (36.0797°N, 126.9653°E)
📍 격자 좌표: (x=60, y=94)
📍 실제 위치: (36.0609°N, 126.9662°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산시(함열초교),3014410,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,익산시(함열초교),3014410,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,익산시(함열초교),3014410,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,익산시(함열초교),3014410,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,익산시(함열초교),3014410,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,익산시(함열초교),3014410,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,익산시(함열초교),3014410,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,익산시(함열초교),3014410,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,익산시(함열초교),3014410,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,익산시(함열초교),3014410,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,익산시(함열초교),3014410,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,익산시(함열초교),3014410,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,익산시(함열초교),3014410,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,익산시(함열초교),3014410,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,익산시(함열초교),3014410,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,익산시(함열초교),3014410,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,익산시(함열초교),3014410,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,익산시(함열초교),3014410,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,익산시(함열초교),3014410,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,익산시(함열초교),3014410,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,익산시(함열초교),3014410,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,익산시(함열초교),3014410,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,익산시(함열초교),3014410,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,익산시(함열초교),3014410,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,익산시(함열초교),3014410,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,익산시(함열초교),3014410,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,익산시(함열초교),3014410,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,익산시(함열초교),3014410,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,익산시(함열초교),3014410,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,익산시(함열초교),3014410,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,익산시(함열초교),3014410,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,익산시(함열초교),3014410,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,익산시(함열초교),3014410,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,익산시(함열초교),3014410,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,익산시(함열초교),3014410,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,익산시(함열초교),3014410,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,익산시(함열초교),3014410,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,익산시(함열초교),3014410,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,익산시(함열초교),3014410,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,익산시(함열초교),3014410,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,익산시(함열초교),3014410,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,익산시(함열초교),3014410,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군산시(임피초교)  [9000216]  (35.98748, 126.84899)
📍 요청 위치: (35.9875°N, 126.8490°E)
📍 격자 좌표: (x=58, y=92)
📍 실제 위치: (35.9700°N, 126.8513°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군산시(임피초교),9000216,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,군산시(임피초교),9000216,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,군산시(임피초교),9000216,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,군산시(임피초교),9000216,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,군산시(임피초교),9000216,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,군산시(임피초교),9000216,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,군산시(임피초교),9000216,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,군산시(임피초교),9000216,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,군산시(임피초교),9000216,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,군산시(임피초교),9000216,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,군산시(임피초교),9000216,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,군산시(임피초교),9000216,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,군산시(임피초교),9000216,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,군산시(임피초교),9000216,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,군산시(임피초교),9000216,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,군산시(임피초교),9000216,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,군산시(임피초교),9000216,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,군산시(임피초교),9000216,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,군산시(임피초교),9000216,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,군산시(임피초교),9000216,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,군산시(임피초교),9000216,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,군산시(임피초교),9000216,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,군산시(임피초교),9000216,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,군산시(임피초교),9000216,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,군산시(임피초교),9000216,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,군산시(임피초교),9000216,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,군산시(임피초교),9000216,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,군산시(임피초교),9000216,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,군산시(임피초교),9000216,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,군산시(임피초교),9000216,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,군산시(임피초교),9000216,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,군산시(임피초교),9000216,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,군산시(임피초교),9000216,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,군산시(임피초교),9000216,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,군산시(임피초교),9000216,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,군산시(임피초교),9000216,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,군산시(임피초교),9000216,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,군산시(임피초교),9000216,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,군산시(임피초교),9000216,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,군산시(임피초교),9000216,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,군산시(임피초교),9000216,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,군산시(임피초교),9000216,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산시(연동리)  [3014420]  (36.03388889, 127.035)
📍 요청 위치: (36.0339°N, 127.0350°E)
📍 격자 좌표: (x=61, y=93)
📍 실제 위치: (36.0144°N, 127.0223°E)

✅ 36개 시계열 데이터 추출 완료

  [원본 10분 데이터 — 36행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산시(연동리),3014420,2026-05-10 20:00:00,0.166667,2026-05-10 20:10:00,PCP,0.0,unknown
1,익산시(연동리),3014420,2026-05-10 20:00:00,0.333333,2026-05-10 20:20:00,PCP,0.0,unknown
2,익산시(연동리),3014420,2026-05-10 20:00:00,0.500000,2026-05-10 20:30:00,PCP,0.0,unknown
3,익산시(연동리),3014420,2026-05-10 20:00:00,0.666667,2026-05-10 20:40:00,PCP,0.0,unknown
4,익산시(연동리),3014420,2026-05-10 20:00:00,0.833333,2026-05-10 20:50:00,PCP,0.0,unknown
5,익산시(연동리),3014420,2026-05-10 20:00:00,1.000000,2026-05-10 21:00:00,PCP,0.0,unknown
6,익산시(연동리),3014420,2026-05-10 20:00:00,1.166667,2026-05-10 21:10:00,PCP,0.0,unknown
7,익산시(연동리),3014420,2026-05-10 20:00:00,1.333333,2026-05-10 21:20:00,PCP,0.0,unknown
8,익산시(연동리),3014420,2026-05-10 20:00:00,1.500000,2026-05-10 21:30:00,PCP,0.0,unknown
9,익산시(연동리),3014420,2026-05-10 20:00:00,1.666667,2026-05-10 21:40:00,PCP,0.0,unknown
10,익산시(연동리),3014420,2026-05-10 20:00:00,1.833333,2026-05-10 21:50:00,PCP,0.0,unknown
11,익산시(연동리),3014420,2026-05-10 20:00:00,2.000000,2026-05-10 22:00:00,PCP,0.0,unknown
12,익산시(연동리),3014420,2026-05-10 20:00:00,2.166667,2026-05-10 22:10:00,PCP,0.0,unknown
13,익산시(연동리),3014420,2026-05-10 20:00:00,2.333333,2026-05-10 22:20:00,PCP,0.0,unknown
14,익산시(연동리),3014420,2026-05-10 20:00:00,2.500000,2026-05-10 22:30:00,PCP,0.0,unknown
15,익산시(연동리),3014420,2026-05-10 20:00:00,2.666667,2026-05-10 22:40:00,PCP,0.0,unknown
16,익산시(연동리),3014420,2026-05-10 20:00:00,2.833333,2026-05-10 22:50:00,PCP,0.0,unknown
17,익산시(연동리),3014420,2026-05-10 20:00:00,3.000000,2026-05-10 23:00:00,PCP,0.0,unknown
18,익산시(연동리),3014420,2026-05-10 20:00:00,3.166667,2026-05-10 23:10:00,PCP,0.0,unknown
19,익산시(연동리),3014420,2026-05-10 20:00:00,3.333333,2026-05-10 23:20:00,PCP,0.0,unknown
20,익산시(연동리),3014420,2026-05-10 20:00:00,3.500000,2026-05-10 23:30:00,PCP,0.0,unknown
21,익산시(연동리),3014420,2026-05-10 20:00:00,3.666667,2026-05-10 23:40:00,PCP,0.0,unknown
22,익산시(연동리),3014420,2026-05-10 20:00:00,3.833333,2026-05-10 23:50:00,PCP,0.0,unknown
23,익산시(연동리),3014420,2026-05-10 20:00:00,4.000000,2026-05-11 00:00:00,PCP,0.0,unknown
24,익산시(연동리),3014420,2026-05-10 20:00:00,4.166667,2026-05-11 00:10:00,PCP,0.0,unknown
25,익산시(연동리),3014420,2026-05-10 20:00:00,4.333333,2026-05-11 00:20:00,PCP,0.0,unknown
26,익산시(연동리),3014420,2026-05-10 20:00:00,4.500000,2026-05-11 00:30:00,PCP,0.0,unknown
27,익산시(연동리),3014420,2026-05-10 20:00:00,4.666667,2026-05-11 00:40:00,PCP,0.0,unknown
28,익산시(연동리),3014420,2026-05-10 20:00:00,4.833333,2026-05-11 00:50:00,PCP,0.0,unknown
29,익산시(연동리),3014420,2026-05-10 20:00:00,5.000000,2026-05-11 01:00:00,PCP,0.0,unknown
30,익산시(연동리),3014420,2026-05-10 20:00:00,5.166667,2026-05-11 01:10:00,PCP,0.0,unknown
31,익산시(연동리),3014420,2026-05-10 20:00:00,5.333333,2026-05-11 01:20:00,PCP,0.0,unknown
32,익산시(연동리),3014420,2026-05-10 20:00:00,5.500000,2026-05-11 01:30:00,PCP,0.0,unknown
33,익산시(연동리),3014420,2026-05-10 20:00:00,5.666667,2026-05-11 01:40:00,PCP,0.0,unknown
34,익산시(연동리),3014420,2026-05-10 20:00:00,5.833333,2026-05-11 01:50:00,PCP,0.0,unknown
35,익산시(연동리),3014420,2026-05-10 20:00:00,6.000000,2026-05-11 02:00:00,PCP,0.0,unknown

  [1시간 합산 데이터 — 6행]

,point_name,point_code,valid_time,base_time,forecast_hour,variable,value,units
0,익산시(연동리),3014420,2026-05-10 21:00:00,2026-05-10 20:00:00,1.0,PCP,0.0,unknown
1,익산시(연동리),3014420,2026-05-10 22:00:00,2026-05-10 20:00:00,2.0,PCP,0.0,unknown
2,익산시(연동리),3014420,2026-05-10 23:00:00,2026-05-10 20:00:00,3.0,PCP,0.0,unknown
3,익산시(연동리),3014420,2026-05-11 00:00:00,2026-05-10 20:00:00,4.0,PCP,0.0,unknown
4,익산시(연동리),3014420,2026-05-11 01:00:00,2026-05-10 20:00:00,5.0,PCP,0.0,unknown
5,익산시(연동리),3014420,2026-05-11 02:00:00,2026-05-10 20:00:00,6.0,PCP,0.0,unknown

============================================================
▶ SHRT 개별 읽기
============================================================

──────────────────────────────────────────────────
지점: 금산  [8000238]  (36.10565, 127.48185)
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산,8000238,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산,8000238,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산,8000238,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산,8000238,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산,8000238,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산,8000238,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산,8000238,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산,8000238,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산,8000238,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산,8000238,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세천  [8000643]  (36.34019, 127.49378)
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세천,8000643,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세천,8000643,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세천,8000643,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세천,8000643,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세천,8000643,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,세천,8000643,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세천,8000643,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세천,8000643,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세천,8000643,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세천,8000643,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장동  [8000648]  (36.41347, 127.43821)
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장동,8000648,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,장동,8000648,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,장동,8000648,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,장동,8000648,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,장동,8000648,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,장동,8000648,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,장동,8000648,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,장동,8000648,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,장동,8000648,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,장동,8000648,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 설천봉  [8000314]  (35.86621, 127.74312)
📍 요청 위치: (35.8662°N, 127.7431°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,설천봉,8000314,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,설천봉,8000314,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,설천봉,8000314,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,설천봉,8000314,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,설천봉,8000314,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,설천봉,8000314,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,설천봉,8000314,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,설천봉,8000314,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,설천봉,8000314,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,설천봉,8000314,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주  [8000701]  (36.001683, 127.668358)
📍 요청 위치: (36.0017°N, 127.6684°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주,8000701,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주,8000701,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주,8000701,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주,8000701,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주,8000701,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주,8000701,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주,8000701,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주,8000701,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주,8000701,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주,8000701,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕유산  [8000735]  (35.89424, 127.77306)
📍 요청 위치: (35.8942°N, 127.7731°E)
📍 격자 좌표: (x=74, y=91)
📍 실제 위치: (35.9121°N, 127.7579°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕유산,8000735,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,덕유산,8000735,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,덕유산,8000735,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,덕유산,8000735,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,덕유산,8000735,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,덕유산,8000735,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,덕유산,8000735,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,덕유산,8000735,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,덕유산,8000735,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,덕유산,8000735,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안주천  [8000757]  (35.97436, 127.43596)
📍 요청 위치: (35.9744°N, 127.4360°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안주천,8000757,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진안주천,8000757,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진안주천,8000757,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진안주천,8000757,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진안주천,8000757,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,진안주천,8000757,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진안주천,8000757,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진안주천,8000757,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진안주천,8000757,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진안주천,8000757,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동향  [8000758]  (35.83519, 127.57117)
📍 요청 위치: (35.8352°N, 127.5712°E)
📍 격자 좌표: (x=71, y=89)
📍 실제 위치: (35.8232°N, 127.5856°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동향,8000758,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,동향,8000758,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,동향,8000758,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,동향,8000758,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,동향,8000758,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,동향,8000758,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,동향,8000758,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,동향,8000758,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,동향,8000758,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,동향,8000758,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공성  [8000821]  (36.28187, 128.07393)
📍 요청 위치: (36.2819°N, 128.0739°E)
📍 격자 좌표: (x=79, y=99)
📍 실제 위치: (36.2741°N, 128.0530°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공성,8000821,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공성,8000821,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공성,8000821,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공성,8000821,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공성,8000821,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,공성,8000821,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공성,8000821,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공성,8000821,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공성,8000821,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공성,8000821,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 화서  [8000834]  (36.44122, 127.9442)
📍 요청 위치: (36.4412°N, 127.9442°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,화서,8000834,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,화서,8000834,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,화서,8000834,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,화서,8000834,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,화서,8000834,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,화서,8000834,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,화서,8000834,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,화서,8000834,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,화서,8000834,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,화서,8000834,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 추풍령  [8000135]  (36.22025, 127.99458)
📍 요청 위치: (36.2203°N, 127.9946°E)
📍 격자 좌표: (x=78, y=98)
📍 실제 위치: (36.2294°N, 127.9945°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,추풍령,8000135,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,추풍령,8000135,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,추풍령,8000135,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,추풍령,8000135,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,추풍령,8000135,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,추풍령,8000135,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,추풍령,8000135,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,추풍령,8000135,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,추풍령,8000135,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,추풍령,8000135,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은  [8000226]  (36.48761, 127.73415)
📍 요청 위치: (36.4876°N, 127.7341°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은,8000226,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은,8000226,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은,8000226,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은,8000226,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,보은,8000226,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은,8000226,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은,8000226,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은,8000226,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은,8000226,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은,8000226,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천  [8000604]  (36.29995, 127.59654)
📍 요청 위치: (36.3000°N, 127.5965°E)
📍 격자 좌표: (x=71, y=99)
📍 실제 위치: (36.2825°N, 127.5969°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천,8000604,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천,8000604,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천,8000604,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천,8000604,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천,8000604,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,4.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천,8000604,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천,8000604,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천,8000604,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천,8000604,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천,8000604,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동  [8000605]  (36.16, 127.755)
📍 요청 위치: (36.1600°N, 127.7550°E)
📍 격자 좌표: (x=74, y=96)
📍 실제 위치: (36.1418°N, 127.7642°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동,8000605,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동,8000605,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동,8000605,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동,8000605,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동,8000605,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,영동,8000605,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동,8000605,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동,8000605,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동,8000605,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동,8000605,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천청산  [8000626]  (36.37052, 127.81538)
📍 요청 위치: (36.3705°N, 127.8154°E)
📍 격자 좌표: (x=75, y=101)
📍 실제 위치: (36.3705°N, 127.8275°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천청산,8000626,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천청산,8000626,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천청산,8000626,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천청산,8000626,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천청산,8000626,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천청산,8000626,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천청산,8000626,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천청산,8000626,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천청산,8000626,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천청산,8000626,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가덕  [8000641]  (36.5461, 127.52388)
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가덕,8000641,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,가덕,8000641,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,가덕,8000641,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,가덕,8000641,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,가덕,8000641,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,가덕,8000641,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,가덕,8000641,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,가덕,8000641,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청남대  [8000888]  (36.46267, 127.49074)
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청남대,8000888,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청남대,8000888,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청남대,8000888,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청남대,8000888,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청남대,8000888,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청남대,8000888,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청남대,8000888,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청남대,8000888,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(금성면)  [8004701]  (36.12584, 127.49408)
📍 요청 위치: (36.1258°N, 127.4941°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(금성면),8004701,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(금성면),8004701,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(금성면),8004701,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(금성면),8004701,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(금성면),8004701,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(금성면),8004701,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(금성면),8004701,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(금성면),8004701,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(금성면),8004701,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(금성면),8004701,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(심천면)  [8007732]  (36.20687, 127.71638)
📍 요청 위치: (36.2069°N, 127.7164°E)
📍 격자 좌표: (x=73, y=97)
📍 실제 위치: (36.1887°N, 127.7085°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(심천면),8007732,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(심천면),8007732,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(심천면),8007732,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(심천면),8007732,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(심천면),8007732,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(심천면),8007732,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(심천면),8007732,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(심천면),8007732,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(심천면),8007732,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(심천면),8007732,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 팔음산  [8003897]  (36.3504, 127.8795)
📍 요청 위치: (36.3504°N, 127.8795°E)
📍 격자 좌표: (x=76, y=101)
📍 실제 위치: (36.3695°N, 127.8846°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,팔음산,8003897,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,팔음산,8003897,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,팔음산,8003897,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,팔음산,8003897,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,팔음산,8003897,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,팔음산,8003897,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,팔음산,8003897,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,팔음산,8003897,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,팔음산,8003897,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,팔음산,8003897,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 탑산  [8003899]  (36.3236, 127.6436)
📍 요청 위치: (36.3236°N, 127.6436°E)
📍 격자 좌표: (x=72, y=100)
📍 실제 위치: (36.3276°N, 127.6551°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,탑산,8003899,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,탑산,8003899,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,탑산,8003899,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,탑산,8003899,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,탑산,8003899,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,탑산,8003899,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,탑산,8003899,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,탑산,8003899,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,탑산,8003899,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,탑산,8003899,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 삼봉산  [8003900]  (36.13, 127.8436)
📍 요청 위치: (36.1300°N, 127.8436°E)
📍 격자 좌표: (x=75, y=96)
📍 실제 위치: (36.1408°N, 127.8211°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,삼봉산,8003900,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,삼봉산,8003900,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,삼봉산,8003900,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,삼봉산,8003900,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,삼봉산,8003900,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,삼봉산,8003900,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,삼봉산,8003900,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,삼봉산,8003900,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,삼봉산,8003900,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,삼봉산,8003900,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 염동산  [8003903]  (36.48726, 127.63905)
📍 요청 위치: (36.4873°N, 127.6390°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,염동산,8003903,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,염동산,8003903,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,염동산,8003903,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,염동산,8003903,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,염동산,8003903,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,염동산,8003903,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,염동산,8003903,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,염동산,8003903,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,염동산,8003903,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,염동산,8003903,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주 불당상봉  [8003912]  (36.49826, 127.55856)
📍 요청 위치: (36.4983°N, 127.5586°E)
📍 격자 좌표: (x=70, y=104)
📍 실제 위치: (36.5133°N, 127.5454°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주 불당상봉,8003912,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주 불당상봉,8003912,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주 불당상봉,8003912,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주 불당상봉,8003912,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주 불당상봉,8003912,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주 불당상봉,8003912,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주 불당상봉,8003912,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주 불당상봉,8003912,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주 불당상봉,8003912,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주 불당상봉,8003912,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 암산  [8003913]  (36.39459, 127.62834)
📍 요청 위치: (36.3946°N, 127.6283°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 암산,8003913,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천 암산,8003913,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천 암산,8003913,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천 암산,8003913,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천 암산,8003913,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천 암산,8003913,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천 암산,8003913,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천 암산,8003913,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천 암산,8003913,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천 암산,8003913,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 거멍산  [8003914]  (36.43603, 127.67226)
📍 요청 위치: (36.4360°N, 127.6723°E)
📍 격자 좌표: (x=72, y=102)
📍 실제 위치: (36.4195°N, 127.6574°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 거멍산,8003914,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천 거멍산,8003914,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천 거멍산,8003914,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천 거멍산,8003914,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천 거멍산,8003914,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천 거멍산,8003914,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천 거멍산,8003914,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천 거멍산,8003914,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천 거멍산,8003914,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천 거멍산,8003914,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천 금적산  [8003916]  (36.38596, 127.70188)
📍 요청 위치: (36.3860°N, 127.7019°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천 금적산,8003916,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천 금적산,8003916,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천 금적산,8003916,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천 금적산,8003916,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천 금적산,8003916,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천 금적산,8003916,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천 금적산,8003916,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천 금적산,8003916,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천 금적산,8003916,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천 금적산,8003916,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은 노성산  [8003918]  (36.45745, 127.62589)
📍 요청 위치: (36.4575°N, 127.6259°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은 노성산,8003918,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은 노성산,8003918,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은 노성산,8003918,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은 노성산,8003918,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은 노성산,8003918,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은 노성산,8003918,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은 노성산,8003918,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은 노성산,8003918,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은 노성산,8003918,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은 노성산,8003918,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성주산  [8004890]  (36.07694, 127.63033)
📍 요청 위치: (36.0769°N, 127.6303°E)
📍 격자 좌표: (x=72, y=95)
📍 실제 위치: (36.0978°N, 127.6492°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성주산,8004890,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,성주산,8004890,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,성주산,8004890,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,성주산,8004890,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,성주산,8004890,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,성주산,8004890,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,성주산,8004890,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,성주산,8004890,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,성주산,8004890,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,성주산,8004890,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산 성치산  [8004900]  (36.01051, 127.45918)
📍 요청 위치: (36.0105°N, 127.4592°E)
📍 격자 좌표: (x=69, y=93)
📍 실제 위치: (36.0086°N, 127.4765°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산 성치산,8004900,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산 성치산,8004900,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산 성치산,8004900,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산 성치산,8004900,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산 성치산,8004900,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산 성치산,8004900,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산 성치산,8004900,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산 성치산,8004900,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산 성치산,8004900,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산 성치산,8004900,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산 백암산  [8004901]  (36.05146, 127.39897)
📍 요청 위치: (36.0515°N, 127.3990°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산 백암산,8004901,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산 백암산,8004901,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산 백암산,8004901,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산 백암산,8004901,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산 백암산,8004901,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,금산 백암산,8004901,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산 백암산,8004901,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산 백암산,8004901,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산 백암산,8004901,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산 백암산,8004901,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계족산  [8004912]  (36.3879, 127.4569)
📍 요청 위치: (36.3879°N, 127.4569°E)
📍 격자 좌표: (x=69, y=101)
📍 실제 위치: (36.3762°N, 127.4850°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계족산,8004912,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,계족산,8004912,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,계족산,8004912,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,계족산,8004912,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,계족산,8004912,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,계족산,8004912,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,계족산,8004912,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,계족산,8004912,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,계족산,8004912,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,계족산,8004912,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주 민주지산  [8005908]  (36.01256, 127.84766)
📍 요청 위치: (36.0126°N, 127.8477°E)
📍 격자 좌표: (x=76, y=93)
📍 실제 위치: (36.0019°N, 127.8739°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주 민주지산,8005908,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주 민주지산,8005908,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주 민주지산,8005908,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주 민주지산,8005908,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주 민주지산,8005908,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,무주 민주지산,8005908,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주 민주지산,8005908,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주 민주지산,8005908,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주 민주지산,8005908,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주 민주지산,8005908,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕유산  [8005910]  (35.8964, 127.8271)
📍 요청 위치: (35.8964°N, 127.8271°E)
📍 격자 좌표: (x=75, y=91)
📍 실제 위치: (35.9111°N, 127.8146°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕유산,8005910,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,덕유산,8005910,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,덕유산,8005910,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,덕유산,8005910,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,덕유산,8005910,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,7.0,unknown
...,...,...,...,...,...,...,...,...
65,덕유산,8005910,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,덕유산,8005910,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,덕유산,8005910,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,덕유산,8005910,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,덕유산,8005910,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산흥초교  [8004125]  (36.2287, 127.4484)
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산흥초교,8004125,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,산흥초교,8004125,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,산흥초교,8004125,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,산흥초교,8004125,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,산흥초교,8004125,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,산흥초교,8004125,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 모동면  [8007299]  (36.3201, 127.9594)
📍 요청 위치: (36.3201°N, 127.9594°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,모동면,8007299,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,모동면,8007299,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,모동면,8007299,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,모동면,8007299,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,모동면,8007299,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,모동면,8007299,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,모동면,8007299,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,모동면,8007299,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,모동면,8007299,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,모동면,8007299,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 화남면  [8007311]  (36.4483, 127.9055)
📍 요청 위치: (36.4483°N, 127.9055°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,화남면,8007311,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,화남면,8007311,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,화남면,8007311,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,화남면,8007311,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,화남면,8007311,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,화남면,8007311,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,화남면,8007311,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,화남면,8007311,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,화남면,8007311,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,화남면,8007311,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안_용담면  [8005221]  (35.96662, 127.52003)
📍 요청 위치: (35.9666°N, 127.5200°E)
📍 격자 좌표: (x=70, y=92)
📍 실제 위치: (35.9618°N, 127.5322°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안_용담면,8005221,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진안_용담면,8005221,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진안_용담면,8005221,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진안_용담면,8005221,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진안_용담면,8005221,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,진안_용담면,8005221,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진안_용담면,8005221,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진안_용담면,8005221,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진안_용담면,8005221,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진안_용담면,8005221,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군북두두  [8004167]  (36.1689, 127.5277)
📍 요청 위치: (36.1689°N, 127.5277°E)
📍 격자 좌표: (x=70, y=97)
📍 실제 위치: (36.1915°N, 127.5377°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군북두두,8004167,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,군북두두,8004167,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,군북두두,8004167,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,군북두두,8004167,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,군북두두,8004167,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,군북두두,8004167,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,군북두두,8004167,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,군북두두,8004167,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,군북두두,8004167,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,군북두두,8004167,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금성상가  [8004170]  (36.1308, 127.4539)
📍 요청 위치: (36.1308°N, 127.4539°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금성상가,8004170,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금성상가,8004170,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금성상가,8004170,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금성상가,8004170,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금성상가,8004170,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금성상가,8004170,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금성상가,8004170,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금성상가,8004170,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금성상가,8004170,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금성상가,8004170,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 제원제원  [8004172]  (36.1125, 127.5462)
📍 요청 위치: (36.1125°N, 127.5462°E)
📍 격자 좌표: (x=70, y=95)
📍 실제 위치: (36.0996°N, 127.5355°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,제원제원,8004172,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,제원제원,8004172,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,제원제원,8004172,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,제원제원,8004172,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,제원제원,8004172,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,제원제원,8004172,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,제원제원,8004172,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,제원제원,8004172,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,제원제원,8004172,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,제원제원,8004172,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남일초현  [8004173]  (36.0429, 127.5044)
📍 요청 위치: (36.0429°N, 127.5044°E)
📍 격자 좌표: (x=69, y=94)
📍 실제 위치: (36.0546°N, 127.4776°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남일초현,8004173,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,남일초현,8004173,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,남일초현,8004173,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,남일초현,8004173,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,남일초현,8004173,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,남일초현,8004173,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,남일초현,8004173,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,남일초현,8004173,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,남일초현,8004173,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,남일초현,8004173,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남이하금  [8004174]  (36.0454, 127.4367)
📍 요청 위치: (36.0454°N, 127.4367°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남이하금,8004174,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,남이하금,8004174,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,남이하금,8004174,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,남이하금,8004174,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,남이하금,8004174,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,남이하금,8004174,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,남이하금,8004174,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,남이하금,8004174,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,남이하금,8004174,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,남이하금,8004174,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부리현내  [8004175]  (36.0608, 127.555)
📍 요청 위치: (36.0608°N, 127.5550°E)
📍 격자 좌표: (x=70, y=94)
📍 실제 위치: (36.0537°N, 127.5344°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부리현내,8004175,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,부리현내,8004175,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,부리현내,8004175,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,부리현내,8004175,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,부리현내,8004175,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,부리현내,8004175,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,부리현내,8004175,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,부리현내,8004175,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,부리현내,8004175,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,부리현내,8004175,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 미천  [8003184]  (36.51762, 127.49627)
📍 요청 위치: (36.5176°N, 127.4963°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,미천,8003184,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,미천,8003184,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,미천,8003184,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,미천,8003184,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,미천,8003184,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,미천,8003184,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,미천,8003184,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,미천,8003184,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,미천,8003184,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,미천,8003184,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 척산  [8003193]  (36.56066, 127.43347)
📍 요청 위치: (36.5607°N, 127.4335°E)
📍 격자 좌표: (x=68, y=105)
📍 실제 위치: (36.5610°N, 127.4320°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,척산,8003193,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,척산,8003193,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,척산,8003193,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,척산,8003193,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,척산,8003193,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,척산,8003193,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,척산,8003193,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,척산,8003193,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,척산,8003193,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,척산,8003193,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 거교  [8003118]  (36.44547, 127.57925)
📍 요청 위치: (36.4455°N, 127.5793°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,거교,8003118,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,거교,8003118,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,거교,8003118,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,거교,8003118,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,거교,8003118,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,거교,8003118,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,거교,8003118,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,거교,8003118,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,거교,8003118,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,거교,8003118,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 구티  [8003120]  (36.55208, 127.73274)
📍 요청 위치: (36.5521°N, 127.7327°E)
📍 격자 좌표: (x=73, y=105)
📍 실제 위치: (36.5565°N, 127.7183°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,구티,8003120,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,구티,8003120,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,구티,8003120,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,구티,8003120,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,2.0,unknown
4,구티,8003120,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,구티,8003120,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,구티,8003120,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,구티,8003120,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,구티,8003120,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,구티,8003120,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 원남  [8003122]  (36.39588, 127.72779)
📍 요청 위치: (36.3959°N, 127.7278°E)
📍 격자 좌표: (x=73, y=102)
📍 실제 위치: (36.4185°N, 127.7146°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,원남,8003122,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,원남,8003122,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,원남,8003122,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,원남,8003122,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,원남,8003122,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,원남,8003122,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,원남,8003122,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,원남,8003122,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,원남,8003122,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,원남,8003122,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장안  [8004931]  (36.4698, 127.78879)
📍 요청 위치: (36.4698°N, 127.7888°E)
📍 격자 좌표: (x=74, y=103)
📍 실제 위치: (36.4635°N, 127.7730°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장안,8004931,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,장안,8004931,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,장안,8004931,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,장안,8004931,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,장안,8004931,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,장안,8004931,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,장안,8004931,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,장안,8004931,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,장안,8004931,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,장안,8004931,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 하장  [8003127]  (36.43072, 127.79613)
📍 요청 위치: (36.4307°N, 127.7961°E)
📍 격자 좌표: (x=74, y=102)
📍 실제 위치: (36.4175°N, 127.7717°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,하장,8003127,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,하장,8003127,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,하장,8003127,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,하장,8003127,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,하장,8003127,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,하장,8003127,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,하장,8003127,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,하장,8003127,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,하장,8003127,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,하장,8003127,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 후평  [8003128]  (36.47938, 127.69875)
📍 요청 위치: (36.4794°N, 127.6988°E)
📍 격자 좌표: (x=73, y=103)
📍 실제 위치: (36.4645°N, 127.7158°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,후평,8003128,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,후평,8003128,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,후평,8003128,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,후평,8003128,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,후평,8003128,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,후평,8003128,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,후평,8003128,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,후평,8003128,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,후평,8003128,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,후평,8003128,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산계  [8003148]  (36.32704, 127.75947)
📍 요청 위치: (36.3270°N, 127.7595°E)
📍 격자 좌표: (x=74, y=100)
📍 실제 위치: (36.3256°N, 127.7692°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산계,8003148,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,산계,8003148,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,산계,8003148,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,산계,8003148,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,산계,8003148,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,산계,8003148,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,산계,8003148,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,산계,8003148,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,산계,8003148,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,산계,8003148,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 삼양  [8003149]  (36.30664, 127.57154)
📍 요청 위치: (36.3066°N, 127.5715°E)
📍 격자 좌표: (x=71, y=100)
📍 실제 위치: (36.3285°N, 127.5980°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,삼양,8003149,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,삼양,8003149,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,삼양,8003149,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,삼양,8003149,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,삼양,8003149,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,삼양,8003149,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,삼양,8003149,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,삼양,8003149,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,삼양,8003149,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,삼양,8003149,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가곡  [8003129]  (36.12233, 127.66902)
📍 요청 위치: (36.1223°N, 127.6690°E)
📍 격자 좌표: (x=72, y=96)
📍 실제 위치: (36.1437°N, 127.6504°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가곡,8003129,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,가곡,8003129,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,가곡,8003129,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,가곡,8003129,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,가곡,8003129,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,가곡,8003129,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,가곡,8003129,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,가곡,8003129,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,가곡,8003129,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,가곡,8003129,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계산  [8003130]  (36.17515, 127.78376)
📍 요청 위치: (36.1752°N, 127.7838°E)
📍 격자 좌표: (x=74, y=97)
📍 실제 위치: (36.1877°N, 127.7654°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계산,8003130,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,계산,8003130,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,계산,8003130,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,계산,8003130,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,계산,8003130,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,계산,8003130,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,계산,8003130,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,계산,8003130,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,계산,8003130,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,계산,8003130,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남성  [8003134]  (36.22851, 127.91031)
📍 요청 위치: (36.2285°N, 127.9103°E)
📍 격자 좌표: (x=77, y=98)
📍 실제 위치: (36.2305°N, 127.9376°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남성,8003134,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,남성,8003134,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,남성,8003134,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,남성,8003134,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,남성,8003134,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,남성,8003134,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,남성,8003134,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,남성,8003134,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,남성,8003134,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,남성,8003134,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노천  [8003135]  (36.19089, 127.93212)
📍 요청 위치: (36.1909°N, 127.9321°E)
📍 격자 좌표: (x=77, y=97)
📍 실제 위치: (36.1845°N, 127.9362°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노천,8003135,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,노천,8003135,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,노천,8003135,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,노천,8003135,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,2.0,unknown
4,노천,8003135,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,노천,8003135,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,노천,8003135,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,노천,8003135,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,노천,8003135,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,노천,8003135,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서산  [8003138]  (36.09938, 127.68486)
📍 요청 위치: (36.0994°N, 127.6849°E)
📍 격자 좌표: (x=73, y=95)
📍 실제 위치: (36.0968°N, 127.7061°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서산,8003138,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,서산,8003138,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,서산,8003138,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,서산,8003138,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,서산,8003138,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,서산,8003138,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,서산,8003138,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,서산,8003138,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,서산,8003138,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,서산,8003138,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 심천  [8003139]  (36.23826, 127.72172)
📍 요청 위치: (36.2383°N, 127.7217°E)
📍 격자 좌표: (x=73, y=98)
📍 실제 위치: (36.2347°N, 127.7097°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,심천,8003139,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,심천,8003139,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,심천,8003139,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,심천,8003139,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,심천,8003139,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,심천,8003139,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,심천,8003139,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,심천,8003139,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,심천,8003139,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,심천,8003139,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용화  [8003140]  (36.02082, 127.76731)
📍 요청 위치: (36.0208°N, 127.7673°E)
📍 격자 좌표: (x=74, y=93)
📍 실제 위치: (36.0040°N, 127.7604°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용화,8003140,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,용화,8003140,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,용화,8003140,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,용화,8003140,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,용화,8003140,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,용화,8003140,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,용화,8003140,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,용화,8003140,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,용화,8003140,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,용화,8003140,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 임산  [8004770]  (36.14876, 127.91411)
📍 요청 위치: (36.1488°N, 127.9141°E)
📍 격자 좌표: (x=77, y=96)
📍 실제 위치: (36.1386°N, 127.9348°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,임산,8004770,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,임산,8004770,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,임산,8004770,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,임산,8004770,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,임산,8004770,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,임산,8004770,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,임산,8004770,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,임산,8004770,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,임산,8004770,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,임산,8004770,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 백련사  [8005924]  (35.86042, 127.7653)
📍 요청 위치: (35.8604°N, 127.7653°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,백련사,8005924,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,백련사,8005924,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,백련사,8005924,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,백련사,8005924,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,백련사,8005924,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,백련사,8005924,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,백련사,8005924,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,백련사,8005924,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,백련사,8005924,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,백련사,8005924,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 안성1  [8005925]  (35.83139, 127.73694)
📍 요청 위치: (35.8314°N, 127.7369°E)
📍 격자 좌표: (x=74, y=89)
📍 실제 위치: (35.8203°N, 127.7554°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,안성1,8005925,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,안성1,8005925,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,안성1,8005925,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,안성1,8005925,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,안성1,8005925,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,안성1,8005925,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,안성1,8005925,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,안성1,8005925,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,안성1,8005925,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,안성1,8005925,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 월음령  [8005928]  (35.87109, 127.78567)
📍 요청 위치: (35.8711°N, 127.7857°E)
📍 격자 좌표: (x=75, y=90)
📍 실제 위치: (35.8652°N, 127.8133°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,월음령,8005928,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,월음령,8005928,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,월음령,8005928,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,월음령,8005928,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,월음령,8005928,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,월음령,8005928,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,월음령,8005928,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,월음령,8005928,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,월음령,8005928,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,월음령,8005928,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 적상산  [8005931]  (35.9563, 127.69843)
📍 요청 위치: (35.9563°N, 127.6984°E)
📍 격자 좌표: (x=73, y=92)
📍 실제 위치: (35.9590°N, 127.7024°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,적상산,8005931,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,적상산,8005931,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,적상산,8005931,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,적상산,8005931,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,적상산,8005931,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,적상산,8005931,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,적상산,8005931,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,적상산,8005931,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,적상산,8005931,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,적상산,8005931,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 문장대  [8007924]  (36.56679, 127.86211)
📍 요청 위치: (36.5668°N, 127.8621°E)
📍 격자 좌표: (x=76, y=105)
📍 실제 위치: (36.5534°N, 127.8900°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,문장대,8007924,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,문장대,8007924,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,문장대,8007924,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,문장대,8007924,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,문장대,8007924,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,문장대,8007924,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,문장대,8007924,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,문장대,8007924,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,문장대,8007924,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,문장대,8007924,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(법주분교)  [1004410]  (36.51027778, 127.8063889)
📍 요청 위치: (36.5103°N, 127.8064°E)
📍 격자 좌표: (x=75, y=104)
📍 실제 위치: (36.5085°N, 127.8315°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(법주분교),1004410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(법주분교),1004410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(법주분교),1004410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(법주분교),1004410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(법주분교),1004410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(법주분교),1004410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(법주분교),1004410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(법주분교),1004410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(법주분교),1004410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(법주분교),1004410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(법주사)  [1004430]  (36.54083333, 127.8325)
📍 요청 위치: (36.5408°N, 127.8325°E)
📍 격자 좌표: (x=75, y=105)
📍 실제 위치: (36.5545°N, 127.8328°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(법주사),1004430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(법주사),1004430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(법주사),1004430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(법주사),1004430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(법주사),1004430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(법주사),1004430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(법주사),1004430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(법주사),1004430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(법주사),1004430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(법주사),1004430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(탁주리)  [9000133]  (36.56972222, 127.7488889)
📍 요청 위치: (36.5697°N, 127.7489°E)
📍 격자 좌표: (x=74, y=105)
📍 실제 위치: (36.5555°N, 127.7755°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(탁주리),9000133,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(탁주리),9000133,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(탁주리),9000133,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(탁주리),9000133,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,보은군(탁주리),9000133,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(탁주리),9000133,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(탁주리),9000133,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(탁주리),9000133,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(탁주리),9000133,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(탁주리),9000133,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(하송리)  [2008430]  (36.47138889, 127.9663889)
📍 요청 위치: (36.4714°N, 127.9664°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(하송리),2008430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(하송리),2008430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(하송리),2008430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(하송리),2008430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(하송리),2008430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(하송리),2008430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(하송리),2008430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(하송리),2008430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(하송리),2008430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(하송리),2008430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화북초교)  [2006440]  (36.56666667, 127.9119444)
📍 요청 위치: (36.5667°N, 127.9119°E)
📍 격자 좌표: (x=76, y=105)
📍 실제 위치: (36.5534°N, 127.8900°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화북초교),2006440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(화북초교),2006440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(화북초교),2006440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(화북초교),2006440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(화북초교),2006440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(화북초교),2006440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(화북초교),2006440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(화북초교),2006440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(화북초교),2006440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(화북초교),2006440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(안성초교)  [3001410]  (35.86555556, 127.655)
📍 요청 위치: (35.8656°N, 127.6550°E)
📍 격자 좌표: (x=72, y=90)
📍 실제 위치: (35.8682°N, 127.6434°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(안성초교),3001410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(안성초교),3001410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(안성초교),3001410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(안성초교),3001410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(안성초교),3001410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(안성초교),3001410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(안성초교),3001410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(안성초교),3001410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(안성초교),3001410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(안성초교),3001410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(무주중앙초교)  [3003452]  (36.01194444, 127.6630556)
📍 요청 위치: (36.0119°N, 127.6631°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(무주중앙초교),3003452,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(적상초교)  [3003420]  (35.93166667, 127.6566667)
📍 요청 위치: (35.9317°N, 127.6567°E)
📍 격자 좌표: (x=72, y=91)
📍 실제 위치: (35.9141°N, 127.6445°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(적상초교),3003420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(적상초교),3003420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(적상초교),3003420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(적상초교),3003420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(적상초교),3003420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(적상초교),3003420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(적상초교),3003420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(적상초교),3003420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(적상초교),3003420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(적상초교),3003420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(구천정수장)  [3003454]  (35.88583333, 127.7769444)
📍 요청 위치: (35.8858°N, 127.7769°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(구천정수장),3003454,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(구천정수장),3003454,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(구천정수장),3003454,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(구천정수장),3003454,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(구천정수장),3003454,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(구천정수장),3003454,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(구천정수장),3003454,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(구천정수장),3003454,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(구천정수장),3003454,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(구천정수장),3003454,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(삼포리)  [3005452]  (36.33861111, 127.9577778)
📍 요청 위치: (36.3386°N, 127.9578°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(삼포리),3005452,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(삼포리),3005452,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(삼포리),3005452,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(삼포리),3005452,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(삼포리),3005452,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(삼포리),3005452,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(삼포리),3005452,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(삼포리),3005452,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(삼포리),3005452,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(삼포리),3005452,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(궁촌리)  [3005454]  (36.10777778, 127.9175)
📍 요청 위치: (36.1078°N, 127.9175°E)
📍 격자 좌표: (x=77, y=95)
📍 실제 위치: (36.0927°N, 127.9334°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(궁촌리),3005454,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(궁촌리),3005454,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(궁촌리),3005454,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(궁촌리),3005454,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(궁촌리),3005454,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(궁촌리),3005454,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(궁촌리),3005454,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(궁촌리),3005454,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(궁촌리),3005454,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(궁촌리),3005454,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화동초교)  [3007455]  (36.39222222, 127.9519444)
📍 요청 위치: (36.3922°N, 127.9519°E)
📍 격자 좌표: (x=77, y=102)
📍 실제 위치: (36.4143°N, 127.9431°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화동초교),3007455,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(화동초교),3007455,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(화동초교),3007455,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(화동초교),3007455,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(화동초교),3007455,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(화동초교),3007455,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(화동초교),3007455,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(화동초교),3007455,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(화동초교),3007455,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(화동초교),3007455,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(화령초교)  [3007450]  (36.4475, 127.9522222)
📍 요청 위치: (36.4475°N, 127.9522°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(화령초교),3007450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(화령초교),3007450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(화령초교),3007450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(화령초교),3007450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(화령초교),3007450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(화령초교),3007450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(화령초교),3007450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(화령초교),3007450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(화령초교),3007450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(화령초교),3007450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(웅북리)  [3005450]  (36.25694444, 128.0202778)
📍 요청 위치: (36.2569°N, 128.0203°E)
📍 격자 좌표: (x=78, y=99)
📍 실제 위치: (36.2753°N, 127.9960°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(웅북리),3005450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(웅북리),3005450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(웅북리),3005450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(웅북리),3005450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(웅북리),3005450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(웅북리),3005450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(웅북리),3005450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(웅북리),3005450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(웅북리),3005450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(웅북리),3005450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(청산초교)  [3007477]  (36.34611111, 127.7941667)
📍 요청 위치: (36.3461°N, 127.7942°E)
📍 격자 좌표: (x=74, y=100)
📍 실제 위치: (36.3256°N, 127.7692°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(청산초교),3007477,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(청산초교),3007477,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(청산초교),3007477,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(청산초교),3007477,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(청산초교),3007477,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(청산초교),3007477,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(청산초교),3007477,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(청산초교),3007477,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(청산초교),3007477,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(청산초교),3007477,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(삼산초교)  [3007483]  (36.485, 127.7166667)
📍 요청 위치: (36.4850°N, 127.7167°E)
📍 격자 좌표: (x=73, y=103)
📍 실제 위치: (36.4645°N, 127.7158°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(삼산초교),3007483,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(삼산초교),3007483,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(삼산초교),3007483,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(삼산초교),3007483,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(삼산초교),3007483,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(삼산초교),3007483,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(삼산초교),3007483,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(삼산초교),3007483,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(삼산초교),3007483,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(삼산초교),3007483,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(관기초교)  [3007479]  (36.43555556, 127.8219444)
📍 요청 위치: (36.4356°N, 127.8219°E)
📍 격자 좌표: (x=75, y=102)
📍 실제 위치: (36.4165°N, 127.8288°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(관기초교),3007479,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(관기초교),3007479,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(관기초교),3007479,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(관기초교),3007479,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(관기초교),3007479,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(관기초교),3007479,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(관기초교),3007479,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(관기초교),3007479,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(관기초교),3007479,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(관기초교),3007479,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(도로관리사업소)  [3007435]  (36.37333333, 127.7341667)
📍 요청 위치: (36.3733°N, 127.7342°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(도로관리사업소),3007435,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(동정리)  [3007425]  (36.47361111, 127.6641667)
📍 요청 위치: (36.4736°N, 127.6642°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(동정리),3007425,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(동정리),3007425,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(동정리),3007425,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(동정리),3007425,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(동정리),3007425,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(동정리),3007425,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(동정리),3007425,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(동정리),3007425,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(동정리),3007425,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(동정리),3007425,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(이원리)  [3007430]  (36.54222222, 127.6777778)
📍 요청 위치: (36.5422°N, 127.6778°E)
📍 격자 좌표: (x=72, y=105)
📍 실제 위치: (36.5575°N, 127.6610°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(이원리),3007430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(이원리),3007430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(이원리),3007430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(이원리),3007430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(이원리),3007430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(이원리),3007430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(이원리),3007430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(이원리),3007430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(이원리),3007430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(이원리),3007430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(묘금리)  [3007460]  (36.27583333, 127.7322222)
📍 요청 위치: (36.2758°N, 127.7322°E)
📍 격자 좌표: (x=73, y=99)
📍 실제 위치: (36.2806°N, 127.7109°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(묘금리),3007460,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(묘금리),3007460,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(묘금리),3007460,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(묘금리),3007460,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(묘금리),3007460,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(묘금리),3007460,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(묘금리),3007460,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(묘금리),3007460,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(묘금리),3007460,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(묘금리),3007460,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(송죽초교)  [3007440]  (36.43722222, 127.7344444)
📍 요청 위치: (36.4372°N, 127.7344°E)
📍 격자 좌표: (x=73, y=102)
📍 실제 위치: (36.4185°N, 127.7146°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(송죽초교),3007440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(송죽초교),3007440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(송죽초교),3007440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(송죽초교),3007440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(송죽초교),3007440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(송죽초교),3007440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(송죽초교),3007440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(송죽초교),3007440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(송죽초교),3007440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(송죽초교),3007440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(삼가분교)  [3007481]  (36.49111111, 127.8608333)
📍 요청 위치: (36.4911°N, 127.8608°E)
📍 격자 좌표: (x=76, y=104)
📍 실제 위치: (36.5074°N, 127.8887°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(삼가분교),3007481,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(삼가분교),3007481,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(삼가분교),3007481,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(삼가분교),3007481,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(삼가분교),3007481,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(삼가분교),3007481,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(삼가분교),3007481,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(삼가분교),3007481,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(삼가분교),3007481,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(삼가분교),3007481,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(안내초교)  [3008420]  (36.39416667, 127.6616667)
📍 요청 위치: (36.3942°N, 127.6617°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(안내초교),3008420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(안내초교),3008420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(안내초교),3008420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(안내초교),3008420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(안내초교),3008420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(안내초교),3008420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(안내초교),3008420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(안내초교),3008420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(안내초교),3008420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(안내초교),3008420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
📍 요청 위치: (36.4550°N, 127.4442°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(원촌교)  [3009420]  (36.37833333, 127.41)
📍 요청 위치: (36.3783°N, 127.4100°E)
📍 격자 좌표: (x=68, y=101)
📍 실제 위치: (36.3771°N, 127.4279°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(원촌교),3009420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(원촌교),3009420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(원촌교),3009420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(원촌교),3009420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(원촌교),3009420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
📍 요청 위치: (36.3236°N, 127.4344°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(인창교),9000121,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(인창교),9000121,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(인창교),9000121,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(인창교),9000121,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(인창교),9000121,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(인창교),9000121,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
📍 요청 위치: (36.5781°N, 127.5775°E)
📍 격자 좌표: (x=71, y=105)
📍 실제 위치: (36.5584°N, 127.6037°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(가덕초교),3011430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(가덕초교),3011430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(가덕초교),3011430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(가덕초교),3011430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(가덕초교),3011430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(신괴리)  [9000027]  (35.8669444, 127.5466667)
📍 요청 위치: (35.8669°N, 127.5467°E)
📍 격자 좌표: (x=70, y=90)
📍 실제 위치: (35.8700°N, 127.5301°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(신괴리),9000027,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진안군(신괴리),9000027,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진안군(신괴리),9000027,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진안군(신괴리),9000027,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진안군(신괴리),9000027,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,진안군(신괴리),9000027,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진안군(신괴리),9000027,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진안군(신괴리),9000027,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진안군(신괴리),9000027,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진안군(신괴리),9000027,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(주양리)  [9000029]  (35.9677778, 127.4261111)
📍 요청 위치: (35.9678°N, 127.4261°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(주양리),9000029,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진안군(주양리),9000029,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진안군(주양리),9000029,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진안군(주양리),9000029,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진안군(주양리),9000029,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,진안군(주양리),9000029,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진안군(주양리),9000029,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진안군(주양리),9000029,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진안군(주양리),9000029,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진안군(주양리),9000029,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(삼가리)  [3003430]  (35.8930556, 127.6605556)
📍 요청 위치: (35.8931°N, 127.6606°E)
📍 격자 좌표: (x=72, y=91)
📍 실제 위치: (35.9141°N, 127.6445°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(삼가리),3003430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(삼가리),3003430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(삼가리),3003430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(삼가리),3003430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(삼가리),3003430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(삼가리),3003430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(삼가리),3003430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(삼가리),3003430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(삼가리),3003430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(삼가리),3003430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(증산리)  [3003450]  (35.9463889, 127.8472222)
📍 요청 위치: (35.9464°N, 127.8472°E)
📍 격자 좌표: (x=76, y=92)
📍 실제 위치: (35.9560°N, 127.8726°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(증산리),3003450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(증산리),3003450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(증산리),3003450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(증산리),3003450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(증산리),3003450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(증산리),3003450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(증산리),3003450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(증산리),3003450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(증산리),3003450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(증산리),3003450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 무주군(기곡리)  [3003431]  (36.0127778, 127.7180556)
📍 요청 위치: (36.0128°N, 127.7181°E)
📍 격자 좌표: (x=73, y=93)
📍 실제 위치: (36.0050°N, 127.7036°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,무주군(기곡리),3003431,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,무주군(기곡리),3003431,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,무주군(기곡리),3003431,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,무주군(기곡리),3003431,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,무주군(기곡리),3003431,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,무주군(기곡리),3003431,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,무주군(기곡리),3003431,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,무주군(기곡리),3003431,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,무주군(기곡리),3003431,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,무주군(기곡리),3003431,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(선원리)  [3004430]  (36.0705556, 127.5366667)
📍 요청 위치: (36.0706°N, 127.5367°E)
📍 격자 좌표: (x=70, y=94)
📍 실제 위치: (36.0537°N, 127.5344°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(선원리),3004430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(선원리),3004430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(선원리),3004430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(선원리),3004430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(선원리),3004430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(선원리),3004430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(선원리),3004430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(선원리),3004430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(선원리),3004430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(선원리),3004430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(산막리)  [3004440]  (36.1113889, 127.7913889)
📍 요청 위치: (36.1114°N, 127.7914°E)
📍 격자 좌표: (x=74, y=95)
📍 실제 위치: (36.0958°N, 127.7629°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(산막리),3004440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(산막리),3004440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(산막리),3004440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(산막리),3004440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(산막리),3004440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(산막리),3004440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(산막리),3004440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(산막리),3004440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(산막리),3004440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(산막리),3004440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(남성리)  [3005440]  (36.2358333, 127.9163889)
📍 요청 위치: (36.2358°N, 127.9164°E)
📍 격자 좌표: (x=77, y=98)
📍 실제 위치: (36.2305°N, 127.9376°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(남성리),3005440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(남성리),3005440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(남성리),3005440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(남성리),3005440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(남성리),3005440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(남성리),3005440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(남성리),3005440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(남성리),3005440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(남성리),3005440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(남성리),3005440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 상주시(득수리)  [9000016]  (36.3311111, 127.9002778)
📍 요청 위치: (36.3311°N, 127.9003°E)
📍 격자 좌표: (x=76, y=100)
📍 실제 위치: (36.3235°N, 127.8833°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,상주시(득수리),9000016,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,상주시(득수리),9000016,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,상주시(득수리),9000016,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,상주시(득수리),9000016,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,상주시(득수리),9000016,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,상주시(득수리),9000016,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,상주시(득수리),9000016,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,상주시(득수리),9000016,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,상주시(득수리),9000016,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,상주시(득수리),9000016,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 영동군(궁촌리2)  [9000018]  (36.3311111, 127.9288889)
📍 요청 위치: (36.3311°N, 127.9289°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,영동군(궁촌리2),9000018,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,영동군(궁촌리2),9000018,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,영동군(궁촌리2),9000018,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,영동군(궁촌리2),9000018,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,영동군(궁촌리2),9000018,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,영동군(궁촌리2),9000018,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,영동군(궁촌리2),9000018,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,영동군(궁촌리2),9000018,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,영동군(궁촌리2),9000018,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,영동군(궁촌리2),9000018,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(원동리)  [3005430]  (36.2388889, 127.6525)
📍 요청 위치: (36.2389°N, 127.6525°E)
📍 격자 좌표: (x=72, y=98)
📍 실제 위치: (36.2356°N, 127.6527°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(원동리),3005430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(원동리),3005430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(원동리),3005430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(원동리),3005430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(원동리),3005430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(원동리),3005430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(원동리),3005430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(원동리),3005430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(원동리),3005430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(원동리),3005430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(구병리)  [3007487]  (36.4752778, 127.8772222)
📍 요청 위치: (36.4753°N, 127.8772°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(구병리),3007487,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(구병리),3007487,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(구병리),3007487,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(구병리),3007487,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보은군(구병리),3007487,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(구병리),3007487,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(구병리),3007487,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(구병리),3007487,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(구병리),3007487,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(구병리),3007487,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보은군(신함리)  [3007470]  (36.5166667, 127.7272222)
📍 요청 위치: (36.5167°N, 127.7272°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보은군(신함리),3007470,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보은군(신함리),3007470,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보은군(신함리),3007470,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보은군(신함리),3007470,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,보은군(신함리),3007470,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보은군(신함리),3007470,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보은군(신함리),3007470,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보은군(신함리),3007470,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보은군(신함리),3007470,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보은군(신함리),3007470,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(산계리)  [3007475]  (36.3108333, 127.7372222)
📍 요청 위치: (36.3108°N, 127.7372°E)
📍 격자 좌표: (x=73, y=100)
📍 실제 위치: (36.3266°N, 127.7121°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(산계리),3007475,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(산계리),3007475,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(산계리),3007475,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(산계리),3007475,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(산계리),3007475,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(산계리),3007475,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(산계리),3007475,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(산계리),3007475,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(산계리),3007475,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(산계리),3007475,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(대정리)  [3008430]  (36.3847222, 127.5416667)
📍 요청 위치: (36.3847°N, 127.5417°E)
📍 격자 좌표: (x=70, y=101)
📍 실제 위치: (36.3754°N, 127.5421°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(대정리),3008430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(대정리),3008430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(대정리),3008430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(대정리),3008430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(대정리),3008430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(대정리),3008430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(대정리),3008430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(대정리),3008430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(대정리),3008430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(대정리),3008430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(마전리)  [3008440]  (36.19, 127.4694444)
📍 요청 위치: (36.1900°N, 127.4694°E)
📍 격자 좌표: (x=69, y=97)
📍 실제 위치: (36.1924°N, 127.4807°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(마전리),3008440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(마전리),3008440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(마전리),3008440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(마전리),3008440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(마전리),3008440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(마전리),3008440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(상곡리)  [3008450]  (36.2047222, 127.5763889)
📍 요청 위치: (36.2047°N, 127.5764°E)
📍 격자 좌표: (x=71, y=97)
📍 실제 위치: (36.1906°N, 127.5946°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(상곡리),3008450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(상곡리),3008450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(상곡리),3008450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(상곡리),3008450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(상곡리),3008450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(상곡리),3008450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(상곡리),3008450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(상곡리),3008450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(상곡리),3008450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(상곡리),3008450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
📍 요청 위치: (36.5128°N, 127.5086°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(상장리),9000017,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(상장리),9000017,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(상장리),9000017,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(상장리),9000017,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(상장리),9000017,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(상장리),9000017,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥천군(인포리)  [9000019]  (36.3697222, 127.6561111)
📍 요청 위치: (36.3697°N, 127.6561°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥천군(인포리),9000019,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥천군(인포리),9000019,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥천군(인포리),9000019,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥천군(인포리),9000019,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥천군(인포리),9000019,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,옥천군(인포리),9000019,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥천군(인포리),9000019,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥천군(인포리),9000019,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥천군(인포리),9000019,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥천군(인포리),9000019,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 김천시(월곡리)  [2010432]  (35.98222222, 127.9438889)
📍 요청 위치: (35.9822°N, 127.9439°E)
📍 격자 좌표: (x=77, y=93)
📍 실제 위치: (36.0008°N, 127.9307°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,김천시(월곡리),2010432,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,김천시(월곡리),2010432,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,김천시(월곡리),2010432,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,김천시(월곡리),2010432,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,김천시(월곡리),2010432,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,김천시(월곡리),2010432,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,김천시(월곡리),2010432,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,김천시(월곡리),2010432,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,김천시(월곡리),2010432,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,김천시(월곡리),2010432,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 김천시(파천리)  [2010434]  (36.02777778, 127.9469444)
📍 요청 위치: (36.0278°N, 127.9469°E)
📍 격자 좌표: (x=77, y=94)
📍 실제 위치: (36.0467°N, 127.9321°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,김천시(파천리),2010434,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,김천시(파천리),2010434,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,김천시(파천리),2010434,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,김천시(파천리),2010434,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,김천시(파천리),2010434,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,김천시(파천리),2010434,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,김천시(파천리),2010434,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,김천시(파천리),2010434,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,김천시(파천리),2010434,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,김천시(파천리),2010434,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전  [8000133]  (36.37199, 127.3721)
📍 요청 위치: (36.3720°N, 127.3721°E)
📍 격자 좌표: (x=67, y=101)
📍 실제 위치: (36.3779°N, 127.3708°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전,8000133,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전,8000133,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전,8000133,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전,8000133,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전,8000133,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,대전,8000133,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전,8000133,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전,8000133,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전,8000133,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전,8000133,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안  [8000232]  (36.76217, 127.29282)
📍 요청 위치: (36.7622°N, 127.2928°E)
📍 격자 좌표: (x=66, y=109)
📍 실제 위치: (36.7466°N, 127.3212°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안,8000232,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안,8000232,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안,8000232,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안,8000232,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,천안,8000232,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안,8000232,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안,8000232,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안,8000232,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안,8000232,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안,8000232,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여  [8000236]  (36.27242, 126.92078)
📍 요청 위치: (36.2724°N, 126.9208°E)
📍 격자 좌표: (x=59, y=99)
📍 실제 위치: (36.2912°N, 126.9126°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여,8000236,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,부여,8000236,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,부여,8000236,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,부여,8000236,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,부여,8000236,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,부여,8000236,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,부여,8000236,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,부여,8000236,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,부여,8000236,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,부여,8000236,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산  [8000238]  (36.10565, 127.48185)
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산,8000238,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산,8000238,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산,8000238,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산,8000238,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산,8000238,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산,8000238,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산,8000238,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산,8000238,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산,8000238,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산,8000238,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종  [8000239]  (36.48522, 127.24438)
📍 요청 위치: (36.4852°N, 127.2444°E)
📍 격자 좌표: (x=65, y=103)
📍 실제 위치: (36.4713°N, 127.2583°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종,8000239,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종,8000239,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종,8000239,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종,8000239,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종,8000239,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종,8000239,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종,8000239,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종,8000239,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종,8000239,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종,8000239,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종고운  [8000494]  (36.53152, 127.24064)
📍 요청 위치: (36.5315°N, 127.2406°E)
📍 격자 좌표: (x=65, y=104)
📍 실제 위치: (36.5173°N, 127.2592°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종고운,8000494,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종고운,8000494,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종고운,8000494,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종고운,8000494,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종고운,8000494,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종고운,8000494,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종고운,8000494,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종고운,8000494,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종고운,8000494,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종고운,8000494,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종금남  [8000496]  (36.45853, 127.26876)
📍 요청 위치: (36.4585°N, 127.2688°E)
📍 격자 좌표: (x=65, y=103)
📍 실제 위치: (36.4713°N, 127.2583°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종금남,8000496,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종금남,8000496,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종금남,8000496,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종금남,8000496,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종금남,8000496,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종금남,8000496,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종금남,8000496,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종금남,8000496,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종금남,8000496,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종금남,8000496,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종연서  [8000611]  (36.56667, 127.28056)
📍 요청 위치: (36.5667°N, 127.2806°E)
📍 격자 좌표: (x=65, y=105)
📍 실제 위치: (36.5633°N, 127.2601°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종연서,8000611,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종연서,8000611,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종연서,8000611,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종연서,8000611,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종연서,8000611,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종연서,8000611,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종연서,8000611,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종연서,8000611,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종연서,8000611,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종연서,8000611,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주  [8000612]  (36.48284, 127.13646)
📍 요청 위치: (36.4828°N, 127.1365°E)
📍 격자 좌표: (x=63, y=103)
📍 실제 위치: (36.4727°N, 127.1440°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주,8000612,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주,8000612,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주,8000612,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주,8000612,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주,8000612,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주,8000612,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주,8000612,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주,8000612,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주,8000612,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주,8000612,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천  [8000614]  (36.06248, 126.70411)
📍 요청 위치: (36.0625°N, 126.7041°E)
📍 격자 좌표: (x=55, y=94)
📍 실제 위치: (36.0632°N, 126.6820°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천,8000614,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,서천,8000614,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,서천,8000614,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,서천,8000614,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,서천,8000614,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,서천,8000614,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,서천,8000614,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,서천,8000614,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,서천,8000614,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,서천,8000614,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산  [8000615]  (36.21164, 127.10815)
📍 요청 위치: (36.2116°N, 127.1081°E)
📍 격자 좌표: (x=62, y=97)
📍 실제 위치: (36.1975°N, 127.0821°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산,8000615,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산,8000615,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산,8000615,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산,8000615,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산,8000615,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산,8000615,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산,8000615,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산,8000615,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산,8000615,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산,8000615,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양  [8000618]  (36.42371, 126.77906)
📍 요청 위치: (36.4237°N, 126.7791°E)
📍 격자 좌표: (x=57, y=102)
📍 실제 위치: (36.4301°N, 126.8002°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양,8000618,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청양,8000618,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청양,8000618,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청양,8000618,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청양,8000618,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청양,8000618,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청양,8000618,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청양,8000618,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청양,8000618,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청양,8000618,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종전의  [8000629]  (36.69076, 127.20047)
📍 요청 위치: (36.6908°N, 127.2005°E)
📍 격자 좌표: (x=64, y=108)
📍 실제 위치: (36.7021°N, 127.2055°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종전의,8000629,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종전의,8000629,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종전의,8000629,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종전의,8000629,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종전의,8000629,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종전의,8000629,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종전의,8000629,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종전의,8000629,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종전의,8000629,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종전의,8000629,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 유구  [8000632]  (36.54069, 126.93356)
📍 요청 위치: (36.5407°N, 126.9336°E)
📍 격자 좌표: (x=59, y=104)
📍 실제 위치: (36.5211°N, 126.9159°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,유구,8000632,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,유구,8000632,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,유구,8000632,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,유구,8000632,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,유구,8000632,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,유구,8000632,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,유구,8000632,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,유구,8000632,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,유구,8000632,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,유구,8000632,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정안  [8000633]  (36.55114, 127.09383)
📍 요청 위치: (36.5511°N, 127.0938°E)
📍 격자 좌표: (x=62, y=105)
📍 실제 위치: (36.5654°N, 127.0883°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정안,8000633,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,정안,8000633,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,정안,8000633,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,정안,8000633,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,정안,8000633,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,정안,8000633,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,정안,8000633,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,정안,8000633,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,정안,8000633,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,정안,8000633,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 양화  [8000635]  (36.1319, 126.86024)
📍 요청 위치: (36.1319°N, 126.8602°E)
📍 격자 좌표: (x=58, y=96)
📍 실제 위치: (36.1538°N, 126.8537°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,양화,8000635,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,양화,8000635,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,양화,8000635,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,양화,8000635,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,양화,8000635,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,양화,8000635,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,양화,8000635,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,양화,8000635,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,양화,8000635,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,양화,8000635,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡  [8000636]  (36.3132, 127.2407)
📍 요청 위치: (36.3132°N, 127.2407°E)
📍 격자 좌표: (x=65, y=100)
📍 실제 위치: (36.3334°N, 127.2557°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡,8000636,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,계룡,8000636,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,계룡,8000636,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,계룡,8000636,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,계룡,8000636,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,계룡,8000636,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,계룡,8000636,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,계룡,8000636,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,계룡,8000636,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,계룡,8000636,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오월드  [8000642]  (36.29129, 127.39586)
📍 요청 위치: (36.2913°N, 127.3959°E)
📍 격자 좌표: (x=67, y=99)
📍 실제 위치: (36.2859°N, 127.3688°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오월드,8000642,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,오월드,8000642,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,오월드,8000642,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,오월드,8000642,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,오월드,8000642,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,오월드,8000642,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,오월드,8000642,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,오월드,8000642,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,오월드,8000642,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,오월드,8000642,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세천  [8000643]  (36.34019, 127.49378)
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세천,8000643,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세천,8000643,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세천,8000643,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세천,8000643,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세천,8000643,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,세천,8000643,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세천,8000643,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세천,8000643,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세천,8000643,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세천,8000643,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 연무  [8000644]  (36.13662, 127.09004)
📍 요청 위치: (36.1366°N, 127.0900°E)
📍 격자 좌표: (x=62, y=96)
📍 실제 위치: (36.1516°N, 127.0814°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,연무,8000644,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,연무,8000644,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,연무,8000644,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,연무,8000644,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,연무,8000644,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,연무,8000644,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,연무,8000644,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,연무,8000644,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,연무,8000644,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,연무,8000644,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장동  [8000648]  (36.41347, 127.43821)
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장동,8000648,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,장동,8000648,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,장동,8000648,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,장동,8000648,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,장동,8000648,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,장동,8000648,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,장동,8000648,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,장동,8000648,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,장동,8000648,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,장동,8000648,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡산  [8000659]  (36.343, 127.2057)
📍 요청 위치: (36.3430°N, 127.2057°E)
📍 격자 좌표: (x=64, y=100)
📍 실제 위치: (36.3341°N, 127.1986°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡산,8000659,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,계룡산,8000659,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,계룡산,8000659,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,계룡산,8000659,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,계룡산,8000659,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,계룡산,8000659,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,계룡산,8000659,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,계룡산,8000659,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,계룡산,8000659,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,계룡산,8000659,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정산  [8000691]  (36.38617, 126.95652)
📍 요청 위치: (36.3862°N, 126.9565°E)
📍 격자 좌표: (x=60, y=101)
📍 실제 위치: (36.3826°N, 126.9710°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정산,8000691,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,정산,8000691,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,정산,8000691,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,정산,8000691,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,정산,8000691,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,정산,8000691,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,정산,8000691,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,정산,8000691,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,정산,8000691,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,정산,8000691,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 함라  [8000733]  (36.0461, 126.8917)
📍 요청 위치: (36.0461°N, 126.8917°E)
📍 격자 좌표: (x=59, y=94)
📍 실제 위치: (36.0614°N, 126.9094°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,함라,8000733,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,함라,8000733,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,함라,8000733,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,함라,8000733,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,함라,8000733,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,함라,8000733,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,함라,8000733,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,함라,8000733,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,함라,8000733,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,함라,8000733,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 여산  [8000763]  (36.0592, 127.062)
📍 요청 위치: (36.0592°N, 127.0620°E)
📍 격자 좌표: (x=62, y=94)
📍 실제 위치: (36.0597°N, 127.0798°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,여산,8000763,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,여산,8000763,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,여산,8000763,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,여산,8000763,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,여산,8000763,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,여산,8000763,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,여산,8000763,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,여산,8000763,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,여산,8000763,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,여산,8000763,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주  [8000131]  (36.63935, 127.44089)
📍 요청 위치: (36.6394°N, 127.4409°E)
📍 격자 좌표: (x=68, y=107)
📍 실제 위치: (36.6530°N, 127.4340°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주,8000131,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주,8000131,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주,8000131,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주,8000131,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주,8000131,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주,8000131,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주,8000131,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주,8000131,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주,8000131,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주,8000131,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서청주  [8000181]  (36.63972, 127.396944)
📍 요청 위치: (36.6397°N, 127.3969°E)
📍 격자 좌표: (x=67, y=107)
📍 실제 위치: (36.6538°N, 127.3767°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서청주,8000181,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,서청주,8000181,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,서청주,8000181,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,서청주,8000181,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,서청주,8000181,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,서청주,8000181,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,서청주,8000181,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,서청주,8000181,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,서청주,8000181,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,서청주,8000181,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주금천  [8000327]  (36.62611111, 127.5127778)
📍 요청 위치: (36.6261°N, 127.5128°E)
📍 격자 좌표: (x=69, y=106)
📍 실제 위치: (36.6062°N, 127.4903°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주금천,8000327,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주금천,8000327,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주금천,8000327,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주금천,8000327,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주금천,8000327,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주금천,8000327,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주금천,8000327,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주금천,8000327,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주금천,8000327,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주금천,8000327,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금왕  [8000600]  (36.97369, 127.58973)
📍 요청 위치: (36.9737°N, 127.5897°E)
📍 격자 좌표: (x=71, y=114)
📍 실제 위치: (36.9726°N, 127.6141°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금왕,8000600,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금왕,8000600,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금왕,8000600,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금왕,8000600,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금왕,8000600,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,금왕,8000600,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금왕,8000600,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금왕,8000600,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금왕,8000600,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금왕,8000600,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진천  [8000602]  (36.86338, 127.46231)
📍 요청 위치: (36.8634°N, 127.4623°E)
📍 격자 좌표: (x=68, y=112)
📍 실제 위치: (36.8831°N, 127.4392°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진천,8000602,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진천,8000602,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진천,8000602,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진천,8000602,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진천,8000602,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,진천,8000602,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진천,8000602,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진천,8000602,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진천,8000602,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진천,8000602,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 증평  [8000623]  (36.7956, 127.562)
📍 요청 위치: (36.7956°N, 127.5620°E)
📍 격자 좌표: (x=70, y=110)
📍 실제 위치: (36.7894°N, 127.5520°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,증평,8000623,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,증평,8000623,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,증평,8000623,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,증평,8000623,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,증평,8000623,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,증평,8000623,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,증평,8000623,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,증평,8000623,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,증평,8000623,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,증평,8000623,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가덕  [8000641]  (36.5461, 127.52388)
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가덕,8000641,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,가덕,8000641,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,가덕,8000641,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,가덕,8000641,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,가덕,8000641,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,가덕,8000641,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,가덕,8000641,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,가덕,8000641,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,가덕,8000641,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,가덕,8000641,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 위성센터  [8000676]  (36.9906, 127.42985)
📍 요청 위치: (36.9906°N, 127.4299°E)
📍 격자 좌표: (x=68, y=114)
📍 실제 위치: (36.9752°N, 127.4412°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,위성센터,8000676,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,위성센터,8000676,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,위성센터,8000676,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,위성센터,8000676,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,위성센터,8000676,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,위성센터,8000676,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,위성센터,8000676,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,위성센터,8000676,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,위성센터,8000676,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,위성센터,8000676,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오창  [8000693]  (36.72319, 127.44011)
📍 요청 위치: (36.7232°N, 127.4401°E)
📍 격자 좌표: (x=68, y=109)
📍 실제 위치: (36.7450°N, 127.4361°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오창,8000693,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,오창,8000693,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,오창,8000693,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,오창,8000693,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,오창,8000693,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,오창,8000693,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,오창,8000693,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,오창,8000693,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,오창,8000693,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,오창,8000693,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청남대  [8000888]  (36.46267, 127.49074)
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청남대,8000888,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청남대,8000888,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청남대,8000888,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청남대,8000888,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청남대,8000888,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청남대,8000888,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청남대,8000888,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청남대,8000888,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청남대,8000888,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청남대,8000888,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오창가곡  [8000977]  (36.72455, 127.46688)
📍 요청 위치: (36.7246°N, 127.4669°E)
📍 격자 좌표: (x=69, y=109)
📍 실제 위치: (36.7442°N, 127.4935°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오창가곡,8000977,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,오창가곡,8000977,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,오창가곡,8000977,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,오창가곡,8000977,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,오창가곡,8000977,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,오창가곡,8000977,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,오창가곡,8000977,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,오창가곡,8000977,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,오창가곡,8000977,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,오창가곡,8000977,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 사곡면  [8004870]  (36.52611, 127.03107)
📍 요청 위치: (36.5261°N, 127.0311°E)
📍 격자 좌표: (x=61, y=104)
📍 실제 위치: (36.5200°N, 127.0303°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,사곡면,8004870,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,사곡면,8004870,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,사곡면,8004870,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,사곡면,8004870,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,사곡면,8004870,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,사곡면,8004870,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,사곡면,8004870,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,사곡면,8004870,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,사곡면,8004870,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,사곡면,8004870,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(우성면)  [8004710]  (36.4934, 127.09924)
📍 요청 위치: (36.4934°N, 127.0992°E)
📍 격자 좌표: (x=62, y=103)
📍 실제 위치: (36.4734°N, 127.0868°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(우성면),8004710,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(우성면),8004710,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(우성면),8004710,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(우성면),8004710,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(우성면),8004710,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(우성면),8004710,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(우성면),8004710,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(우성면),8004710,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(우성면),8004710,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(우성면),8004710,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성 개미산  [8003023]  (36.87073, 127.62391)
📍 요청 위치: (36.8707°N, 127.6239°E)
📍 격자 좌표: (x=71, y=112)
📍 실제 위치: (36.8805°N, 127.6118°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성 개미산,8003023,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,음성 개미산,8003023,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,음성 개미산,8003023,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,음성 개미산,8003023,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,음성 개미산,8003023,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,음성 개미산,8003023,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,음성 개미산,8003023,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,음성 개미산,8003023,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,음성 개미산,8003023,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,음성 개미산,8003023,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주 오봉산  [8003911]  (36.58329, 127.61647)
📍 요청 위치: (36.5833°N, 127.6165°E)
📍 격자 좌표: (x=71, y=106)
📍 실제 위치: (36.6044°N, 127.6049°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주 오봉산,8003911,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주 오봉산,8003911,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주 오봉산,8003911,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주 오봉산,8003911,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주 오봉산,8003911,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주 오봉산,8003911,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주 오봉산,8003911,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주 오봉산,8003911,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주 오봉산,8003911,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주 오봉산,8003911,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 축융봉  [8004891]  (36.32578, 126.77832)
📍 요청 위치: (36.3258°N, 126.7783°E)
📍 격자 좌표: (x=57, y=100)
📍 실제 위치: (36.3381°N, 126.7991°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,축융봉,8004891,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,축융봉,8004891,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,축융봉,8004891,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,축융봉,8004891,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,축융봉,8004891,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,축융봉,8004891,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,축융봉,8004891,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,축융봉,8004891,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,축융봉,8004891,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,축융봉,8004891,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주 국사봉  [8004893]  (36.61002, 127.04296)
📍 요청 위치: (36.6100°N, 127.0430°E)
📍 격자 좌표: (x=61, y=106)
📍 실제 위치: (36.6120°N, 127.0318°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주 국사봉,8004893,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주 국사봉,8004893,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주 국사봉,8004893,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주 국사봉,8004893,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주 국사봉,8004893,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주 국사봉,8004893,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주 국사봉,8004893,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주 국사봉,8004893,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주 국사봉,8004893,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주 국사봉,8004893,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장군산  [8004897]  (36.46854, 127.19491)
📍 요청 위치: (36.4685°N, 127.1949°E)
📍 격자 좌표: (x=64, y=103)
📍 실제 위치: (36.4721°N, 127.2012°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장군산,8004897,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,장군산,8004897,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,장군산,8004897,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,장군산,8004897,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,장군산,8004897,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,장군산,8004897,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,장군산,8004897,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,장군산,8004897,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,장군산,8004897,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,장군산,8004897,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안 국사봉  [8004898]  (36.6263, 127.15825)
📍 요청 위치: (36.6263°N, 127.1582°E)
📍 격자 좌표: (x=63, y=106)
📍 실제 위치: (36.6107°N, 127.1464°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안 국사봉,8004898,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안 국사봉,8004898,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안 국사봉,8004898,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안 국사봉,8004898,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,천안 국사봉,8004898,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안 국사봉,8004898,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안 국사봉,8004898,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안 국사봉,8004898,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안 국사봉,8004898,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안 국사봉,8004898,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산 묘련봉  [8004899]  (36.16843, 127.2661)
📍 요청 위치: (36.1684°N, 127.2661°E)
📍 격자 좌표: (x=65, y=96)
📍 실제 위치: (36.1496°N, 127.2521°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산 묘련봉,8004899,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산 묘련봉,8004899,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산 묘련봉,8004899,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산 묘련봉,8004899,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산 묘련봉,8004899,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산 묘련봉,8004899,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산 묘련봉,8004899,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산 묘련봉,8004899,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산 묘련봉,8004899,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산 묘련봉,8004899,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 관불산  [8004910]  (36.5704, 127.2054)
📍 요청 위치: (36.5704°N, 127.2054°E)
📍 격자 좌표: (x=64, y=105)
📍 실제 위치: (36.5640°N, 127.2029°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,관불산,8004910,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,관불산,8004910,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,관불산,8004910,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,관불산,8004910,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,관불산,8004910,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,관불산,8004910,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,관불산,8004910,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,관불산,8004910,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,관불산,8004910,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,관불산,8004910,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 칠불산  [8004911]  (36.4864, 127.3465)
📍 요청 위치: (36.4864°N, 127.3465°E)
📍 격자 좌표: (x=67, y=103)
📍 실제 위치: (36.4698°N, 127.3727°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,칠불산,8004911,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,칠불산,8004911,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,칠불산,8004911,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,칠불산,8004911,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,칠불산,8004911,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,칠불산,8004911,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,칠불산,8004911,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,칠불산,8004911,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,칠불산,8004911,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,칠불산,8004911,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산내동  [8004102]  (36.2818, 127.4677)
📍 요청 위치: (36.2818°N, 127.4677°E)
📍 격자 좌표: (x=69, y=99)
📍 실제 위치: (36.2843°N, 127.4829°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산내동,8004102,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,산내동,8004102,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,산내동,8004102,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,산내동,8004102,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,산내동,8004102,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,3.0,unknown
...,...,...,...,...,...,...,...,...
65,산내동,8004102,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,산내동,8004102,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,산내동,8004102,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,산내동,8004102,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,산내동,8004102,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 기성동  [8004104]  (36.2557, 127.3416)
📍 요청 위치: (36.2557°N, 127.3416°E)
📍 격자 좌표: (x=67, y=98)
📍 실제 위치: (36.2400°N, 127.3678°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,기성동,8004104,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,기성동,8004104,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,기성동,8004104,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,기성동,8004104,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,기성동,8004104,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,기성동,8004104,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,기성동,8004104,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,기성동,8004104,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,기성동,8004104,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,기성동,8004104,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 정림동  [8004106]  (36.3045, 127.3667)
📍 요청 위치: (36.3045°N, 127.3667°E)
📍 격자 좌표: (x=67, y=99)
📍 실제 위치: (36.2859°N, 127.3688°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,정림동,8004106,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,정림동,8004106,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,정림동,8004106,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,정림동,8004106,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,정림동,8004106,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,정림동,8004106,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,정림동,8004106,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,정림동,8004106,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,정림동,8004106,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,정림동,8004106,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 구즉동  [8004107]  (36.4404, 127.3838)
📍 요청 위치: (36.4404°N, 127.3838°E)
📍 격자 좌표: (x=67, y=102)
📍 실제 위치: (36.4239°N, 127.3717°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,구즉동,8004107,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,구즉동,8004107,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,구즉동,8004107,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,구즉동,8004107,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,구즉동,8004107,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,구즉동,8004107,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,구즉동,8004107,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,구즉동,8004107,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,구즉동,8004107,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,구즉동,8004107,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진잠동  [8004110]  (36.2998, 127.3165)
📍 요청 위치: (36.2998°N, 127.3165°E)
📍 격자 좌표: (x=66, y=99)
📍 실제 위치: (36.2867°N, 127.3118°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진잠동,8004110,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진잠동,8004110,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진잠동,8004110,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진잠동,8004110,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진잠동,8004110,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,진잠동,8004110,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진잠동,8004110,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진잠동,8004110,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진잠동,8004110,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진잠동,8004110,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대덕구청  [8004115]  (36.3467, 127.4156)
📍 요청 위치: (36.3467°N, 127.4156°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대덕구청,8004115,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대덕구청,8004115,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대덕구청,8004115,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대덕구청,8004115,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대덕구청,8004115,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,대덕구청,8004115,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대덕구청,8004115,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대덕구청,8004115,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대덕구청,8004115,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대덕구청,8004115,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 산흥초교  [8004125]  (36.2287, 127.4484)
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,산흥초교,8004125,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,산흥초교,8004125,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,산흥초교,8004125,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,산흥초교,8004125,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,산흥초교,8004125,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,산흥초교,8004125,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,산흥초교,8004125,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,산흥초교,8004125,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,산흥초교,8004125,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,산흥초교,8004125,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노은터널  [8004127]  (36.36512, 127.30841)
📍 요청 위치: (36.3651°N, 127.3084°E)
📍 격자 좌표: (x=66, y=101)
📍 실제 위치: (36.3786°N, 127.3137°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노은터널,8004127,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,노은터널,8004127,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,노은터널,8004127,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,노은터널,8004127,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,노은터널,8004127,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,노은터널,8004127,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,노은터널,8004127,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,노은터널,8004127,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,노은터널,8004127,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,노은터널,8004127,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 어진동  [8004142]  (36.5158, 127.2617)
📍 요청 위치: (36.5158°N, 127.2617°E)
📍 격자 좌표: (x=65, y=104)
📍 실제 위치: (36.5173°N, 127.2592°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,어진동,8004142,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,어진동,8004142,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,어진동,8004142,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,어진동,8004142,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,어진동,8004142,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,어진동,8004142,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,어진동,8004142,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,어진동,8004142,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,어진동,8004142,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,어진동,8004142,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 연동내판  [8004266]  (36.55522, 127.32729)
📍 요청 위치: (36.5552°N, 127.3273°E)
📍 격자 좌표: (x=66, y=105)
📍 실제 위치: (36.5626°N, 127.3174°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,연동내판,8004266,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,연동내판,8004266,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,연동내판,8004266,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,연동내판,8004266,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,연동내판,8004266,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,연동내판,8004266,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,연동내판,8004266,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,연동내판,8004266,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,연동내판,8004266,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,연동내판,8004266,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 전동노장  [8004267]  (36.6628, 127.23358)
📍 요청 위치: (36.6628°N, 127.2336°E)
📍 격자 좌표: (x=65, y=107)
📍 실제 위치: (36.6553°N, 127.2620°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,전동노장,8004267,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,전동노장,8004267,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,전동노장,8004267,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,전동노장,8004267,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,전동노장,8004267,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,전동노장,8004267,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,전동노장,8004267,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,전동노장,8004267,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,전동노장,8004267,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,전동노장,8004267,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 시청보람동  [8004270]  (36.47993, 127.28882)
📍 요청 위치: (36.4799°N, 127.2888°E)
📍 격자 좌표: (x=66, y=103)
📍 실제 위치: (36.4706°N, 127.3155°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,시청보람동,8004270,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,시청보람동,8004270,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,시청보람동,8004270,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,시청보람동,8004270,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,시청보람동,8004270,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,시청보람동,8004270,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,시청보람동,8004270,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,시청보람동,8004270,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,시청보람동,8004270,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,시청보람동,8004270,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군산_나포면  [8005113]  (36.03047, 126.83204)
📍 요청 위치: (36.0305°N, 126.8320°E)
📍 격자 좌표: (x=58, y=93)
📍 실제 위치: (36.0160°N, 126.8519°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군산_나포면,8005113,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,군산_나포면,8005113,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,군산_나포면,8005113,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,군산_나포면,8005113,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,2.0,unknown
4,군산_나포면,8005113,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,군산_나포면,8005113,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,군산_나포면,8005113,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,군산_나포면,8005113,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,군산_나포면,8005113,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,군산_나포면,8005113,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산_용안면  [8005128]  (36.12, 126.9523)
📍 요청 위치: (36.1200°N, 126.9523°E)
📍 격자 좌표: (x=60, y=95)
📍 실제 위치: (36.1068°N, 126.9669°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산_용안면,8005128,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,익산_용안면,8005128,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,익산_용안면,8005128,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,익산_용안면,8005128,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,익산_용안면,8005128,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,익산_용안면,8005128,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,익산_용안면,8005128,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,익산_용안면,8005128,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,익산_용안면,8005128,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,익산_용안면,8005128,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 완주_대둔산  [8005200]  (36.11517, 127.3333)
📍 요청 위치: (36.1152°N, 127.3333°E)
📍 격자 좌표: (x=66, y=95)
📍 실제 위치: (36.1029°N, 127.3081°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,완주_대둔산,8005200,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,완주_대둔산,8005200,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,완주_대둔산,8005200,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,완주_대둔산,8005200,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,완주_대둔산,8005200,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,완주_대둔산,8005200,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,완주_대둔산,8005200,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,완주_대둔산,8005200,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,완주_대둔산,8005200,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,완주_대둔산,8005200,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 우성동대  [8004157]  (36.4709, 127.0497)
📍 요청 위치: (36.4709°N, 127.0497°E)
📍 격자 좌표: (x=61, y=103)
📍 실제 위치: (36.4740°N, 127.0296°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,우성동대,8004157,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,우성동대,8004157,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,우성동대,8004157,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,우성동대,8004157,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,우성동대,8004157,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,우성동대,8004157,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,우성동대,8004157,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,우성동대,8004157,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,우성동대,8004157,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,우성동대,8004157,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주봉황  [8004158]  (36.4471, 127.1192)
📍 요청 위치: (36.4471°N, 127.1192°E)
📍 격자 좌표: (x=63, y=102)
📍 실제 위치: (36.4267°N, 127.1432°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주봉황,8004158,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주봉황,8004158,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주봉황,8004158,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주봉황,8004158,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주봉황,8004158,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주봉황,8004158,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주봉황,8004158,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주봉황,8004158,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주봉황,8004158,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주봉황,8004158,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 신풍산정  [8004159]  (36.5147, 126.9554)
📍 요청 위치: (36.5147°N, 126.9554°E)
📍 격자 좌표: (x=60, y=104)
📍 실제 위치: (36.5205°N, 126.9731°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,신풍산정,8004159,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,신풍산정,8004159,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,신풍산정,8004159,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,신풍산정,8004159,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,신풍산정,8004159,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,신풍산정,8004159,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,신풍산정,8004159,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,신풍산정,8004159,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,신풍산정,8004159,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,신풍산정,8004159,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 계룡월암  [8004162]  (36.3603, 127.1419)
📍 요청 위치: (36.3603°N, 127.1419°E)
📍 격자 좌표: (x=63, y=101)
📍 실제 위치: (36.3808°N, 127.1423°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,계룡월암,8004162,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,계룡월암,8004162,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,계룡월암,8004162,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,계룡월암,8004162,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,계룡월암,8004162,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,계룡월암,8004162,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,계룡월암,8004162,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,계룡월암,8004162,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,계룡월암,8004162,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,계룡월암,8004162,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 복수곡남  [8004166]  (36.1665, 127.3983)
📍 요청 위치: (36.1665°N, 127.3983°E)
📍 격자 좌표: (x=68, y=96)
📍 실제 위치: (36.1473°N, 127.4228°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,복수곡남,8004166,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,복수곡남,8004166,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,복수곡남,8004166,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,복수곡남,8004166,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,복수곡남,8004166,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,복수곡남,8004166,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,복수곡남,8004166,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,복수곡남,8004166,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,복수곡남,8004166,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,복수곡남,8004166,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 벌곡한삼천  [8004180]  (36.2059, 127.2648)
📍 요청 위치: (36.2059°N, 127.2648°E)
📍 격자 좌표: (x=65, y=97)
📍 실제 위치: (36.1955°N, 127.2530°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,벌곡한삼천,8004180,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,벌곡한삼천,8004180,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,벌곡한삼천,8004180,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,벌곡한삼천,8004180,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,벌곡한삼천,8004180,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,벌곡한삼천,8004180,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,벌곡한삼천,8004180,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,벌곡한삼천,8004180,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,벌곡한삼천,8004180,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,벌곡한삼천,8004180,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성동원남  [8004185]  (36.2035, 127.0336)
📍 요청 위치: (36.2035°N, 127.0336°E)
📍 격자 좌표: (x=61, y=97)
📍 실제 위치: (36.1981°N, 127.0252°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성동원남,8004185,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,성동원남,8004185,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,성동원남,8004185,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,성동원남,8004185,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,성동원남,8004185,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,성동원남,8004185,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,성동원남,8004185,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,성동원남,8004185,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,성동원남,8004185,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,성동원남,8004185,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 가야곡육곡  [8004186]  (36.1368, 127.1587)
📍 요청 위치: (36.1368°N, 127.1587°E)
📍 격자 좌표: (x=63, y=96)
📍 실제 위치: (36.1509°N, 127.1383°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,가야곡육곡,8004186,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,가야곡육곡,8004186,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,가야곡육곡,8004186,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,가야곡육곡,8004186,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,가야곡육곡,8004186,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,가야곡육곡,8004186,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,가야곡육곡,8004186,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,가야곡육곡,8004186,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,가야곡육곡,8004186,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,가야곡육곡,8004186,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노성읍내  [8004187]  (36.2782, 127.1302)
📍 요청 위치: (36.2782°N, 127.1302°E)
📍 격자 좌표: (x=63, y=99)
📍 실제 위치: (36.2888°N, 127.1407°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노성읍내,8004187,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,노성읍내,8004187,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,노성읍내,8004187,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,노성읍내,8004187,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,노성읍내,8004187,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,노성읍내,8004187,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,노성읍내,8004187,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,노성읍내,8004187,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,노성읍내,8004187,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,노성읍내,8004187,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 임천군사  [8004214]  (36.1912, 126.8949)
📍 요청 위치: (36.1912°N, 126.8949°E)
📍 격자 좌표: (x=59, y=97)
📍 실제 위치: (36.1992°N, 126.9113°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,임천군사,8004214,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,임천군사,8004214,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,임천군사,8004214,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,임천군사,8004214,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,임천군사,8004214,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,임천군사,8004214,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,임천군사,8004214,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,임천군사,8004214,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,임천군사,8004214,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,임천군사,8004214,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남면회동  [8004216]  (36.2121, 126.8063)
📍 요청 위치: (36.2121°N, 126.8063°E)
📍 격자 좌표: (x=57, y=97)
📍 실제 위치: (36.2002°N, 126.7974°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남면회동,8004216,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,남면회동,8004216,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,남면회동,8004216,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,남면회동,8004216,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,남면회동,8004216,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,남면회동,8004216,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,남면회동,8004216,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,남면회동,8004216,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,남면회동,8004216,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,남면회동,8004216,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 은산신대  [8004219]  (36.3105, 126.8542)
📍 요청 위치: (36.3105°N, 126.8542°E)
📍 격자 좌표: (x=58, y=99)
📍 실제 위치: (36.2917°N, 126.8556°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,은산신대,8004219,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,은산신대,8004219,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,은산신대,8004219,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,은산신대,8004219,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,은산신대,8004219,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,은산신대,8004219,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,은산신대,8004219,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,은산신대,8004219,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,은산신대,8004219,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,은산신대,8004219,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 내산운치  [8004223]  (36.2752, 126.7806)
📍 요청 위치: (36.2752°N, 126.7806°E)
📍 격자 좌표: (x=57, y=99)
📍 실제 위치: (36.2922°N, 126.7985°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,내산운치,8004223,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,내산운치,8004223,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,내산운치,8004223,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,내산운치,8004223,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,내산운치,8004223,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,내산운치,8004223,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,내산운치,8004223,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,내산운치,8004223,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,내산운치,8004223,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,내산운치,8004223,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 석성증산  [8004226]  (36.2532, 127.0024)
📍 요청 위치: (36.2532°N, 127.0024°E)
📍 격자 좌표: (x=61, y=98)
📍 실제 위치: (36.2441°N, 127.0259°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,석성증산,8004226,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,석성증산,8004226,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,석성증산,8004226,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,석성증산,8004226,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,석성증산,8004226,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,석성증산,8004226,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,석성증산,8004226,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,석성증산,8004226,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,석성증산,8004226,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,석성증산,8004226,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 문산신농  [8004245]  (36.1423, 126.7522)
📍 요청 위치: (36.1423°N, 126.7522°E)
📍 격자 좌표: (x=56, y=96)
📍 실제 위치: (36.1547°N, 126.7399°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,문산신농,8004245,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,문산신농,8004245,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,문산신농,8004245,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,문산신농,8004245,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,문산신농,8004245,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,문산신농,8004245,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,문산신농,8004245,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,문산신농,8004245,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,문산신농,8004245,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,문산신농,8004245,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 송악역촌  [8004261]  (36.4353, 127.009)
📍 요청 위치: (36.4353°N, 127.0090°E)
📍 격자 좌표: (x=61, y=102)
📍 실제 위치: (36.4280°N, 127.0288°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,송악역촌,8004261,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,송악역촌,8004261,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,송악역촌,8004261,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,송악역촌,8004261,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,송악역촌,8004261,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,송악역촌,8004261,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,송악역촌,8004261,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,송악역촌,8004261,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,송악역촌,8004261,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,송악역촌,8004261,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 장평중추  [8004308]  (36.3418, 126.893)
📍 요청 위치: (36.3418°N, 126.8930°E)
📍 격자 좌표: (x=59, y=100)
📍 실제 위치: (36.3371°N, 126.9132°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,장평중추,8004308,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,장평중추,8004308,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,장평중추,8004308,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,장평중추,8004308,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,장평중추,8004308,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,장평중추,8004308,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,장평중추,8004308,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,장평중추,8004308,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,장평중추,8004308,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,장평중추,8004308,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 북면보건지소  [8004394]  (36.8276, 127.2732)
📍 요청 위치: (36.8276°N, 127.2732°E)
📍 격자 좌표: (x=65, y=111)
📍 실제 위치: (36.8394°N, 127.2656°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,북면보건지소,8004394,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,북면보건지소,8004394,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,북면보건지소,8004394,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,북면보건지소,8004394,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,북면보건지소,8004394,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,북면보건지소,8004394,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,북면보건지소,8004394,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,북면보건지소,8004394,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,북면보건지소,8004394,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,북면보건지소,8004394,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 목천보건지소  [8004395]  (36.785, 127.2347)
📍 요청 위치: (36.7850°N, 127.2347°E)
📍 격자 좌표: (x=64, y=110)
📍 실제 위치: (36.7941°N, 127.2072°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,목천보건지소,8004395,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,목천보건지소,8004395,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,목천보건지소,8004395,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,목천보건지소,8004395,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,목천보건지소,8004395,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,목천보건지소,8004395,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,목천보건지소,8004395,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,목천보건지소,8004395,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,목천보건지소,8004395,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,목천보건지소,8004395,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 성남보건지소  [8004397]  (36.7429, 127.236)
📍 요청 위치: (36.7429°N, 127.2360°E)
📍 격자 좌표: (x=65, y=109)
📍 실제 위치: (36.7474°N, 127.2638°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,성남보건지소,8004397,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,성남보건지소,8004397,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,성남보건지소,8004397,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,성남보건지소,8004397,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,성남보건지소,8004397,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,성남보건지소,8004397,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,성남보건지소,8004397,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,성남보건지소,8004397,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,성남보건지소,8004397,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,성남보건지소,8004397,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동면보건지소  [8004400]  (36.7762, 127.3441)
📍 요청 위치: (36.7762°N, 127.3441°E)
📍 격자 좌표: (x=66, y=110)
📍 실제 위치: (36.7927°N, 127.3221°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동면보건지소,8004400,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,동면보건지소,8004400,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,동면보건지소,8004400,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,동면보건지소,8004400,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,동면보건지소,8004400,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,동면보건지소,8004400,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,동면보건지소,8004400,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,동면보건지소,8004400,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,동면보건지소,8004400,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,동면보건지소,8004400,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 선동  [8003186]  (36.48657, 127.42401)
📍 요청 위치: (36.4866°N, 127.4240°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,선동,8003186,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,선동,8003186,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,선동,8003186,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,선동,8003186,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,선동,8003186,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,선동,8003186,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,선동,8003186,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,선동,8003186,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,선동,8003186,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,선동,8003186,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 신대  [8003187]  (36.73901, 127.54172)
📍 요청 위치: (36.7390°N, 127.5417°E)
📍 격자 좌표: (x=70, y=109)
📍 실제 위치: (36.7433°N, 127.5509°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,신대,8003187,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,신대,8003187,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,신대,8003187,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,신대,8003187,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,신대,8003187,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,신대,8003187,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,신대,8003187,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,신대,8003187,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,신대,8003187,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,신대,8003187,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오산  [8003188]  (36.66461, 127.37557)
📍 요청 위치: (36.6646°N, 127.3756°E)
📍 격자 좌표: (x=67, y=107)
📍 실제 위치: (36.6538°N, 127.3767°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오산,8003188,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,오산,8003188,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,오산,8003188,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,오산,8003188,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,오산,8003188,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,오산,8003188,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,오산,8003188,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,오산,8003188,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,오산,8003188,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,오산,8003188,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 오송  [8003189]  (36.60915, 127.324454)
📍 요청 위치: (36.6091°N, 127.3245°E)
📍 격자 좌표: (x=66, y=106)
📍 실제 위치: (36.6086°N, 127.3184°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,오송,8003189,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,오송,8003189,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,오송,8003189,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,오송,8003189,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,오송,8003189,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,오송,8003189,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,오송,8003189,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,오송,8003189,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,오송,8003189,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,오송,8003189,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 척산  [8003193]  (36.56066, 127.43347)
📍 요청 위치: (36.5607°N, 127.4335°E)
📍 격자 좌표: (x=68, y=105)
📍 실제 위치: (36.5610°N, 127.4320°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,척산,8003193,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,척산,8003193,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,척산,8003193,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,척산,8003193,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,척산,8003193,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,척산,8003193,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,척산,8003193,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,척산,8003193,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,척산,8003193,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,척산,8003193,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 탑연  [8003194]  (36.62083, 127.35731)
📍 요청 위치: (36.6208°N, 127.3573°E)
📍 격자 좌표: (x=67, y=106)
📍 실제 위치: (36.6078°N, 127.3757°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,탑연,8003194,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,탑연,8003194,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,탑연,8003194,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,탑연,8003194,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,탑연,8003194,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,탑연,8003194,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,탑연,8003194,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,탑연,8003194,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,탑연,8003194,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,탑연,8003194,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 남차  [8003224]  (36.72401, 127.62135)
📍 요청 위치: (36.7240°N, 127.6214°E)
📍 격자 좌표: (x=71, y=109)
📍 실제 위치: (36.7424°N, 127.6083°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,남차,8003224,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,남차,8003224,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,남차,8003224,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,남차,8003224,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,남차,8003224,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,남차,8003224,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,남차,8003224,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,남차,8003224,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,남차,8003224,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,남차,8003224,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 옥성  [8003175]  (36.78457, 127.43723)
📍 요청 위치: (36.7846°N, 127.4372°E)
📍 격자 좌표: (x=68, y=110)
📍 실제 위치: (36.7911°N, 127.4371°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,옥성,8003175,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,옥성,8003175,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,옥성,8003175,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,옥성,8003175,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,옥성,8003175,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,옥성,8003175,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,옥성,8003175,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,옥성,8003175,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,옥성,8003175,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,옥성,8003175,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 석현  [8003176]  (36.88395, 127.37683)
📍 요청 위치: (36.8839°N, 127.3768°E)
📍 격자 좌표: (x=67, y=112)
📍 실제 위치: (36.8839°N, 127.3816°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,석현,8003176,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,석현,8003176,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,석현,8003176,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,석현,8003176,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,석현,8003176,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,석현,8003176,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,석현,8003176,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,석현,8003176,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,석현,8003176,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,석현,8003176,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용몽  [8003178]  (36.9138, 127.5094)
📍 요청 위치: (36.9138°N, 127.5094°E)
📍 격자 좌표: (x=69, y=113)
📍 실제 위치: (36.9283°N, 127.4978°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용몽,8003178,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,용몽,8003178,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,용몽,8003178,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,용몽,8003178,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,용몽,8003178,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,용몽,8003178,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,용몽,8003178,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,용몽,8003178,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,용몽,8003178,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,용몽,8003178,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 노원  [8003179]  (36.92567, 127.42846)
📍 요청 위치: (36.9257°N, 127.4285°E)
📍 격자 좌표: (x=68, y=113)
📍 실제 위치: (36.9292°N, 127.4402°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,노원,8003179,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,노원,8003179,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,노원,8003179,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,노원,8003179,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,노원,8003179,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,노원,8003179,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,노원,8003179,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,노원,8003179,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,노원,8003179,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,노원,8003179,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 용정  [8003181]  (36.8461, 127.52639)
📍 요청 위치: (36.8461°N, 127.5264°E)
📍 격자 좌표: (x=70, y=111)
📍 실제 위치: (36.8354°N, 127.5531°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,용정,8003181,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,용정,8003181,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,용정,8003181,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,용정,8003181,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,용정,8003181,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,용정,8003181,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,용정,8003181,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,용정,8003181,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,용정,8003181,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,용정,8003181,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 사담  [8003105]  (36.81691, 127.64871)
📍 요청 위치: (36.8169°N, 127.6487°E)
📍 격자 좌표: (x=72, y=111)
📍 실제 위치: (36.8335°N, 127.6682°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,사담,8003105,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,사담,8003105,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,사담,8003105,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,사담,8003105,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,사담,8003105,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,사담,8003105,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,사담,8003105,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,사담,8003105,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,사담,8003105,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,사담,8003105,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 읍내  [8003108]  (36.772, 127.63951)
📍 요청 위치: (36.7720°N, 127.6395°E)
📍 격자 좌표: (x=72, y=110)
📍 실제 위치: (36.7875°N, 127.6670°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,읍내,8003108,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,읍내,8003108,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,읍내,8003108,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,읍내,8003108,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,읍내,8003108,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,읍내,8003108,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,읍내,8003108,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,읍내,8003108,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,읍내,8003108,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,읍내,8003108,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 덕정  [8003156]  (37.01838, 127.49516)
📍 요청 위치: (37.0184°N, 127.4952°E)
📍 격자 좌표: (x=69, y=115)
📍 실제 위치: (37.0204°N, 127.4999°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,덕정,8003156,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,덕정,8003156,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,덕정,8003156,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,덕정,8003156,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,덕정,8003156,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,덕정,8003156,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,덕정,8003156,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,덕정,8003156,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,덕정,8003156,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,덕정,8003156,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 쌍정  [8003159]  (36.9302, 127.5627)
📍 요청 위치: (36.9302°N, 127.5627°E)
📍 격자 좌표: (x=70, y=113)
📍 실제 위치: (36.9274°N, 127.5554°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,쌍정,8003159,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,쌍정,8003159,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,쌍정,8003159,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,쌍정,8003159,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,쌍정,8003159,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,쌍정,8003159,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,쌍정,8003159,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,쌍정,8003159,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,쌍정,8003159,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,쌍정,8003159,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 동학사  [8004921]  (36.35921, 127.24289)
📍 요청 위치: (36.3592°N, 127.2429°E)
📍 격자 좌표: (x=65, y=101)
📍 실제 위치: (36.3794°N, 127.2566°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,동학사,8004921,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,동학사,8004921,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,동학사,8004921,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,동학사,8004921,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,동학사,8004921,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,동학사,8004921,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,동학사,8004921,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,동학사,8004921,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,동학사,8004921,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,동학사,8004921,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 갑사분소  [8004922]  (36.36947, 127.18212)
📍 요청 위치: (36.3695°N, 127.1821°E)
📍 격자 좌표: (x=64, y=101)
📍 실제 위치: (36.3801°N, 127.1994°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,갑사분소,8004922,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,갑사분소,8004922,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,갑사분소,8004922,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,갑사분소,8004922,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,갑사분소,8004922,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,갑사분소,8004922,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,갑사분소,8004922,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,갑사분소,8004922,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,갑사분소,8004922,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,갑사분소,8004922,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주공항*  [8000128]  (36.71666667, 127.5)
📍 요청 위치: (36.7167°N, 127.5000°E)
📍 격자 좌표: (x=69, y=108)
📍 실제 위치: (36.6982°N, 127.4924°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주공항*,8000128,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주공항*,8000128,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주공항*,8000128,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주공항*,8000128,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주공항*,8000128,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주공항*,8000128,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주공항*,8000128,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주공항*,8000128,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주공항*,8000128,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주공항*,8000128,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 괴산군(고마리)  [1004424]  (36.8155556, 127.7363889)
📍 요청 위치: (36.8156°N, 127.7364°E)
📍 격자 좌표: (x=73, y=111)
📍 실제 위치: (36.8325°N, 127.7257°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,괴산군(고마리),1004424,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,괴산군(고마리),1004424,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,괴산군(고마리),1004424,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,괴산군(고마리),1004424,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,괴산군(고마리),1004424,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,괴산군(고마리),1004424,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,괴산군(고마리),1004424,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,괴산군(고마리),1004424,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,괴산군(고마리),1004424,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,괴산군(고마리),1004424,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(삼산리)  [9000038]  (36.3427778, 126.7169444)
📍 요청 위치: (36.3428°N, 126.7169°E)
📍 격자 좌표: (x=56, y=100)
📍 실제 위치: (36.3386°N, 126.7420°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(삼산리),9000038,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,부여군(삼산리),9000038,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,부여군(삼산리),9000038,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,부여군(삼산리),9000038,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,부여군(삼산리),9000038,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,부여군(삼산리),9000038,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,부여군(삼산리),9000038,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,부여군(삼산리),9000038,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,부여군(삼산리),9000038,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,부여군(삼산리),9000038,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(마전리)  [3008440]  (36.19, 127.4694444)
📍 요청 위치: (36.1900°N, 127.4694°E)
📍 격자 좌표: (x=69, y=97)
📍 실제 위치: (36.1924°N, 127.4807°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(마전리),3008440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(마전리),3008440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(마전리),3008440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(마전리),3008440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(마전리),3008440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(마전리),3008440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(마전리),3008440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(마전리),3008440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(마전리),3008440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(마전리),3008440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(상장리)  [9000017]  (36.5127778, 127.5086111)
📍 요청 위치: (36.5128°N, 127.5086°E)
📍 격자 좌표: (x=69, y=104)
📍 실제 위치: (36.5142°N, 127.4882°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(상장리),9000017,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(상장리),9000017,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(상장리),9000017,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(상장리),9000017,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(상장리),9000017,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(상장리),9000017,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(상장리),9000017,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(상장리),9000017,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(상장리),9000017,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(상장리),9000017,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 미원(전)  [28]  (36.7402778, 127.6711111)
📍 요청 위치: (36.7403°N, 127.6711°E)
📍 격자 좌표: (x=72, y=109)
📍 실제 위치: (36.7415°N, 127.6658°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,미원(전),28,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,미원(전),28,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,미원(전),28,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,미원(전),28,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,미원(전),28,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,미원(전),28,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,미원(전),28,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,미원(전),28,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,미원(전),28,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,미원(전),28,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(문화재조사연구단)  [3008460]  (36.455, 127.4441667)
📍 요청 위치: (36.4550°N, 127.4442°E)
📍 격자 좌표: (x=68, y=103)
📍 실제 위치: (36.4690°N, 127.4299°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(문화재조사연구단),3008460,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(인창교)  [9000121]  (36.32361111, 127.4344444)
📍 요청 위치: (36.3236°N, 127.4344°E)
📍 격자 좌표: (x=68, y=100)
📍 실제 위치: (36.3311°N, 127.4268°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(인창교),9000121,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(인창교),9000121,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(인창교),9000121,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(인창교),9000121,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(인창교),9000121,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(인창교),9000121,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(인창교),9000121,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(인창교),9000121,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(인창교),9000121,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(인창교),9000121,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(두계교)  [9000079]  (36.26638889, 127.2788889)
📍 요청 위치: (36.2664°N, 127.2789°E)
📍 격자 좌표: (x=65, y=99)
📍 실제 위치: (36.2874°N, 127.2548°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(두계교),9000079,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(두계교),9000079,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(두계교),9000079,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(두계교),9000079,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(두계교),9000079,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(두계교),9000079,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(두계교),9000079,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(두계교),9000079,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(두계교),9000079,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(두계교),9000079,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(만년교)  [9000117]  (36.35166667, 127.3497222)
📍 요청 위치: (36.3517°N, 127.3497°E)
📍 격자 좌표: (x=67, y=100)
📍 실제 위치: (36.3319°N, 127.3698°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(만년교),9000117,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(만년교),9000117,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(만년교),9000117,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(만년교),9000117,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(만년교),9000117,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(만년교),9000117,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(만년교),9000117,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(만년교),9000117,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(만년교),9000117,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(만년교),9000117,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 대전시(원촌교)  [3009420]  (36.37833333, 127.41)
📍 요청 위치: (36.3783°N, 127.4100°E)
📍 격자 좌표: (x=68, y=101)
📍 실제 위치: (36.3771°N, 127.4279°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,대전시(원촌교),3009420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,대전시(원촌교),3009420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,대전시(원촌교),3009420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,대전시(원촌교),3009420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,대전시(원촌교),3009420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,1.0,unknown
...,...,...,...,...,...,...,...,...
65,대전시(원촌교),3009420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,대전시(원촌교),3009420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,대전시(원촌교),3009420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,대전시(원촌교),3009420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,대전시(원촌교),3009420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(부강면사무소)  [3011440]  (36.52916667, 127.3711111)
📍 요청 위치: (36.5292°N, 127.3711°E)
📍 격자 좌표: (x=67, y=104)
📍 실제 위치: (36.5158°N, 127.3737°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(부강면사무소),3011440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종시(부강면사무소),3011440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종시(부강면사무소),3011440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종시(부강면사무소),3011440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종시(부강면사무소),3011440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종시(부강면사무소),3011440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종시(부강면사무소),3011440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종시(부강면사무소),3011440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종시(부강면사무소),3011440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종시(부강면사무소),3011440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진천군(진천여중)  [3011420]  (36.86916667, 127.4561111)
📍 요청 위치: (36.8692°N, 127.4561°E)
📍 격자 좌표: (x=68, y=112)
📍 실제 위치: (36.8831°N, 127.4392°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진천군(진천여중),3011420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진천군(진천여중),3011420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진천군(진천여중),3011420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진천군(진천여중),3011420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,진천군(진천여중),3011420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,진천군(진천여중),3011420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진천군(진천여중),3011420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진천군(진천여중),3011420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진천군(진천여중),3011420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진천군(진천여중),3011420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 증평군(반탄교)  [3011450]  (36.78361111, 127.5725)
📍 요청 위치: (36.7836°N, 127.5725°E)
📍 격자 좌표: (x=70, y=110)
📍 실제 위치: (36.7894°N, 127.5520°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,증평군(반탄교),3011450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,증평군(반탄교),3011450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,증평군(반탄교),3011450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,증평군(반탄교),3011450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,증평군(반탄교),3011450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,증평군(반탄교),3011450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,증평군(반탄교),3011450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,증평군(반탄교),3011450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,증평군(반탄교),3011450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,증평군(반탄교),3011450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(가덕초교)  [3011430]  (36.57805556, 127.5775)
📍 요청 위치: (36.5781°N, 127.5775°E)
📍 격자 좌표: (x=71, y=105)
📍 실제 위치: (36.5584°N, 127.6037°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(가덕초교),3011430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(가덕초교),3011430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(가덕초교),3011430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(가덕초교),3011430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(가덕초교),3011430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(가덕초교),3011430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(가덕초교),3011430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(가덕초교),3011430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(가덕초교),3011430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(가덕초교),3011430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청주시(흥덕교)  [3011460]  (36.64666667, 127.4813889)
📍 요청 위치: (36.6467°N, 127.4814°E)
📍 격자 좌표: (x=69, y=107)
📍 실제 위치: (36.6522°N, 127.4913°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청주시(흥덕교),3011460,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청주시(흥덕교),3011460,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청주시(흥덕교),3011460,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청주시(흥덕교),3011460,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청주시(흥덕교),3011460,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청주시(흥덕교),3011460,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청주시(흥덕교),3011460,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청주시(흥덕교),3011460,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청주시(흥덕교),3011460,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청주시(흥덕교),3011460,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(병천초교)  [3011410]  (36.765, 127.3)
📍 요청 위치: (36.7650°N, 127.3000°E)
📍 격자 좌표: (x=66, y=109)
📍 실제 위치: (36.7466°N, 127.3212°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(병천초교),3011410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안시(병천초교),3011410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안시(병천초교),3011410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안시(병천초교),3011410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,천안시(병천초교),3011410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안시(병천초교),3011410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안시(병천초교),3011410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안시(병천초교),3011410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안시(병천초교),3011410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안시(병천초교),3011410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 괴산군(문당리)  [9000078]  (36.74055, 127.67111)
📍 요청 위치: (36.7405°N, 127.6711°E)
📍 격자 좌표: (x=72, y=109)
📍 실제 위치: (36.7415°N, 127.6658°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,괴산군(문당리),9000078,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,괴산군(문당리),9000078,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,괴산군(문당리),9000078,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,괴산군(문당리),9000078,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,괴산군(문당리),9000078,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,괴산군(문당리),9000078,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,괴산군(문당리),9000078,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,괴산군(문당리),9000078,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,괴산군(문당리),9000078,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,괴산군(문당리),9000078,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 안성시(안성서운중교)  [1101422]  (36.94472, 127.26305)
📍 요청 위치: (36.9447°N, 127.2631°E)
📍 격자 좌표: (x=65, y=113)
📍 실제 위치: (36.9315°N, 127.2674°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,안성시(안성서운중교),1101422,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,안성시(안성서운중교),1101422,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,안성시(안성서운중교),1101422,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,안성시(안성서운중교),1101422,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,안성시(안성서운중교),1101422,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,안성시(안성서운중교),1101422,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,안성시(안성서운중교),1101422,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,안성시(안성서운중교),1101422,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,안성시(안성서운중교),1101422,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,안성시(안성서운중교),1101422,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(음성고교)  [1004428]  (36.93416, 127.68611)
📍 요청 위치: (36.9342°N, 127.6861°E)
📍 격자 좌표: (x=72, y=113)
📍 실제 위치: (36.9256°N, 127.6706°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(음성고교),1004428,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,음성군(음성고교),1004428,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,음성군(음성고교),1004428,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,음성군(음성고교),1004428,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,음성군(음성고교),1004428,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,음성군(음성고교),1004428,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,음성군(음성고교),1004428,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,음성군(음성고교),1004428,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,음성군(음성고교),1004428,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,음성군(음성고교),1004428,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(성거읍사무소)  [1101424]  (36.87805, 127.19916)
📍 요청 위치: (36.8781°N, 127.1992°E)
📍 격자 좌표: (x=64, y=112)
📍 실제 위치: (36.8862°N, 127.2089°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안시(성거읍사무소),1101424,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(대소보건지소)  [3011440]  (36.9725, 127.4838889)
📍 요청 위치: (36.9725°N, 127.4839°E)
📍 격자 좌표: (x=69, y=114)
📍 실제 위치: (36.9744°N, 127.4989°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(대소보건지소),3011440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,음성군(대소보건지소),3011440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,음성군(대소보건지소),3011440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,음성군(대소보건지소),3011440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,음성군(대소보건지소),3011440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,음성군(대소보건지소),3011440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,음성군(대소보건지소),3011440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,음성군(대소보건지소),3011440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,음성군(대소보건지소),3011440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,음성군(대소보건지소),3011440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 음성군(쌍봉리)  [9000188]  (37.00277778, 127.5552778)
📍 요청 위치: (37.0028°N, 127.5553°E)
📍 격자 좌표: (x=70, y=115)
📍 실제 위치: (37.0195°N, 127.5576°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,음성군(쌍봉리),9000188,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,음성군(쌍봉리),9000188,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,음성군(쌍봉리),9000188,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,음성군(쌍봉리),9000188,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,음성군(쌍봉리),9000188,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,음성군(쌍봉리),9000188,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,음성군(쌍봉리),9000188,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,음성군(쌍봉리),9000188,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,음성군(쌍봉리),9000188,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,음성군(쌍봉리),9000188,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(농정원)  [3011470]  (36.5925, 127.2925)
📍 요청 위치: (36.5925°N, 127.2925°E)
📍 격자 좌표: (x=66, y=106)
📍 실제 위치: (36.6086°N, 127.3184°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(농정원),3011470,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종시(농정원),3011470,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종시(농정원),3011470,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종시(농정원),3011470,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종시(농정원),3011470,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종시(농정원),3011470,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종시(농정원),3011470,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종시(농정원),3011470,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종시(농정원),3011470,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종시(농정원),3011470,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 세종시(문성교)  [9000191]  (36.51472222, 127.1961111)
📍 요청 위치: (36.5147°N, 127.1961°E)
📍 격자 좌표: (x=64, y=104)
📍 실제 위치: (36.5180°N, 127.2020°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,세종시(문성교),9000191,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,세종시(문성교),9000191,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,세종시(문성교),9000191,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,세종시(문성교),9000191,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,세종시(문성교),9000191,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,세종시(문성교),9000191,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,세종시(문성교),9000191,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,세종시(문성교),9000191,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,세종시(문성교),9000191,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,세종시(문성교),9000191,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(화청교)  [9000194]  (36.76194444, 127.3980556)
📍 요청 위치: (36.7619°N, 127.3981°E)
📍 격자 좌표: (x=67, y=109)
📍 실제 위치: (36.7459°N, 127.3786°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(화청교),9000194,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안시(화청교),9000194,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안시(화청교),9000194,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안시(화청교),9000194,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,1.0,unknown
4,천안시(화청교),9000194,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안시(화청교),9000194,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안시(화청교),9000194,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안시(화청교),9000194,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안시(화청교),9000194,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안시(화청교),9000194,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 천안시(신흥교)  [9000200]  (36.70305556, 127.1133333)
📍 요청 위치: (36.7031°N, 127.1133°E)
📍 격자 좌표: (x=62, y=108)
📍 실제 위치: (36.7034°N, 127.0907°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,천안시(신흥교),9000200,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,천안시(신흥교),9000200,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,천안시(신흥교),9000200,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,천안시(신흥교),9000200,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,천안시(신흥교),9000200,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,천안시(신흥교),9000200,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,천안시(신흥교),9000200,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,천안시(신흥교),9000200,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,천안시(신흥교),9000200,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,천안시(신흥교),9000200,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(금강교)  [3012405]  (36.47027778, 127.1277778)
📍 요청 위치: (36.4703°N, 127.1278°E)
📍 격자 좌표: (x=63, y=103)
📍 실제 위치: (36.4727°N, 127.1440°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(금강교),3012405,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(금강교),3012405,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(금강교),3012405,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(금강교),3012405,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(금강교),3012405,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(금강교),3012405,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(금강교),3012405,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(금강교),3012405,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(금강교),3012405,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(금강교),3012405,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 금산군(신대리)  [3009410]  (36.21388889, 127.3791667)
📍 요청 위치: (36.2139°N, 127.3792°E)
📍 격자 좌표: (x=67, y=97)
📍 실제 위치: (36.1940°N, 127.3669°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,금산군(신대리),3009410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,금산군(신대리),3009410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,금산군(신대리),3009410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,금산군(신대리),3009410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,금산군(신대리),3009410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,금산군(신대리),3009410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,금산군(신대리),3009410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,금산군(신대리),3009410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,금산군(신대리),3009410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,금산군(신대리),3009410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(정안면사무소)  [3012430]  (36.60861111, 127.1202778)
📍 요청 위치: (36.6086°N, 127.1203°E)
📍 격자 좌표: (x=63, y=106)
📍 실제 위치: (36.6107°N, 127.1464°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(정안면사무소),3012430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(정안면사무소),3012430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(정안면사무소),3012430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(정안면사무소),3012430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(정안면사무소),3012430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(정안면사무소),3012430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(정안면사무소),3012430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(정안면사무소),3012430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(정안면사무소),3012430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(정안면사무소),3012430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(반포중)  [3012425]  (36.40361111, 127.2430556)
📍 요청 위치: (36.4036°N, 127.2431°E)
📍 격자 좌표: (x=65, y=102)
📍 실제 위치: (36.4254°N, 127.2574°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(반포중),3012425,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(반포중),3012425,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(반포중),3012425,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(반포중),3012425,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(반포중),3012425,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(반포중),3012425,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(반포중),3012425,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(반포중),3012425,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(반포중),3012425,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(반포중),3012425,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(복룡리)  [3012440]  (36.34555556, 127.0680556)
📍 요청 위치: (36.3456°N, 127.0681°E)
📍 격자 좌표: (x=62, y=100)
📍 실제 위치: (36.3354°N, 127.0845°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(복룡리),3012440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(복룡리),3012440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(복룡리),3012440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(복룡리),3012440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(복룡리),3012440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(복룡리),3012440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(복룡리),3012440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(복룡리),3012440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(복룡리),3012440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(복룡리),3012440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 공주시(유구초교)  [3012445]  (36.55361111, 126.9505556)
📍 요청 위치: (36.5536°N, 126.9506°E)
📍 격자 좌표: (x=60, y=105)
📍 실제 위치: (36.5665°N, 126.9738°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,공주시(유구초교),3012445,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,공주시(유구초교),3012445,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,공주시(유구초교),3012445,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,공주시(유구초교),3012445,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,공주시(유구초교),3012445,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,공주시(유구초교),3012445,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,공주시(유구초교),3012445,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,공주시(유구초교),3012445,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,공주시(유구초교),3012445,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,공주시(유구초교),3012445,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(홍산초교)  [3012410]  (36.2175, 126.7625)
📍 요청 위치: (36.2175°N, 126.7625°E)
📍 격자 좌표: (x=56, y=97)
📍 실제 위치: (36.2007°N, 126.7404°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(홍산초교),3012410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,부여군(홍산초교),3012410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,부여군(홍산초교),3012410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,부여군(홍산초교),3012410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,부여군(홍산초교),3012410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,부여군(홍산초교),3012410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,부여군(홍산초교),3012410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,부여군(홍산초교),3012410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,부여군(홍산초교),3012410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,부여군(홍산초교),3012410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 부여군(백제교)  [3012450]  (36.27583333, 126.8916667)
📍 요청 위치: (36.2758°N, 126.8917°E)
📍 격자 좌표: (x=59, y=99)
📍 실제 위치: (36.2912°N, 126.9126°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,부여군(백제교),3012450,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,부여군(백제교),3012450,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,부여군(백제교),3012450,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,부여군(백제교),3012450,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,부여군(백제교),3012450,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,부여군(백제교),3012450,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,부여군(백제교),3012450,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,부여군(백제교),3012450,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,부여군(백제교),3012450,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,부여군(백제교),3012450,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양군(청양읍사무소)  [3012420]  (36.45361111, 126.8066667)
📍 요청 위치: (36.4536°N, 126.8067°E)
📍 격자 좌표: (x=57, y=103)
📍 실제 위치: (36.4761°N, 126.8008°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청양군(청양읍사무소),3012420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 청양군(119안전센터)  [3012435]  (36.41805556, 126.94)
📍 요청 위치: (36.4181°N, 126.9400°E)
📍 격자 좌표: (x=59, y=102)
📍 실제 위치: (36.4291°N, 126.9145°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,청양군(119안전센터),3012435,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,청양군(119안전센터),3012435,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,청양군(119안전센터),3012435,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,청양군(119안전센터),3012435,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,청양군(119안전센터),3012435,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,청양군(119안전센터),3012435,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,청양군(119안전센터),3012435,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,청양군(119안전센터),3012435,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,청양군(119안전센터),3012435,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,청양군(119안전센터),3012435,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 보령시(미산면사무소)  [3203442]  (36.21083333, 126.6775)
📍 요청 위치: (36.2108°N, 126.6775°E)
📍 격자 좌표: (x=55, y=97)
📍 실제 위치: (36.2011°N, 126.6835°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,보령시(미산면사무소),3203442,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,보령시(미산면사무소),3203442,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,보령시(미산면사무소),3203442,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,보령시(미산면사무소),3203442,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,보령시(미산면사무소),3203442,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,보령시(미산면사무소),3203442,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,보령시(미산면사무소),3203442,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,보령시(미산면사무소),3203442,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,보령시(미산면사무소),3203442,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,보령시(미산면사무소),3203442,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(연산중)  [3013420]  (36.21333333, 127.2069444)
📍 요청 위치: (36.2133°N, 127.2069°E)
📍 격자 좌표: (x=64, y=97)
📍 실제 위치: (36.1962°N, 127.1960°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(연산중),3013420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산시(연산중),3013420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산시(연산중),3013420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산시(연산중),3013420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산시(연산중),3013420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산시(연산중),3013420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산시(연산중),3013420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산시(연산중),3013420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산시(연산중),3013420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산시(연산중),3013420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(동산초교)  [3013440]  (36.14027778, 127.2416667)
📍 요청 위치: (36.1403°N, 127.2417°E)
📍 격자 좌표: (x=65, y=96)
📍 실제 위치: (36.1496°N, 127.2521°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(동산초교),3013440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산시(동산초교),3013440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산시(동산초교),3013440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산시(동산초교),3013440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산시(동산초교),3013440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산시(동산초교),3013440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산시(동산초교),3013440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산시(동산초교),3013440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산시(동산초교),3013440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산시(동산초교),3013440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(토양리)  [9000190]  (36.14916667, 127.1025)
📍 요청 위치: (36.1492°N, 127.1025°E)
📍 격자 좌표: (x=62, y=96)
📍 실제 위치: (36.1516°N, 127.0814°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(토양리),9000190,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산시(토양리),9000190,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산시(토양리),9000190,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산시(토양리),9000190,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산시(토양리),9000190,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산시(토양리),9000190,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산시(토양리),9000190,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산시(토양리),9000190,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산시(토양리),9000190,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산시(토양리),9000190,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 논산시(황산리)  [3013410]  (36.15444444, 127.0086111)
📍 요청 위치: (36.1544°N, 127.0086°E)
📍 격자 좌표: (x=61, y=96)
📍 실제 위치: (36.1522°N, 127.0245°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,논산시(황산리),3013410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,논산시(황산리),3013410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,논산시(황산리),3013410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,논산시(황산리),3013410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,논산시(황산리),3013410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,논산시(황산리),3013410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,논산시(황산리),3013410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,논산시(황산리),3013410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,논산시(황산리),3013410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,논산시(황산리),3013410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천군(망월리)  [3203440]  (36.02944444, 126.7569444)
📍 요청 위치: (36.0294°N, 126.7569°E)
📍 격자 좌표: (x=56, y=93)
📍 실제 위치: (36.0169°N, 126.7383°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천군(망월리),3203440,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,서천군(망월리),3203440,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,서천군(망월리),3203440,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,서천군(망월리),3203440,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,서천군(망월리),3203440,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,서천군(망월리),3203440,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,서천군(망월리),3203440,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,서천군(망월리),3203440,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,서천군(망월리),3203440,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,서천군(망월리),3203440,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 서천군(충남디자인예술고)  [3014430]  (36.08916667, 126.8036111)
📍 요청 위치: (36.0892°N, 126.8036°E)
📍 격자 좌표: (x=57, y=95)
📍 실제 위치: (36.1083°N, 126.7963°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,서천군(충남디자인예술고),3014430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 진안군(대불리)  [3001442]  (35.96166667, 127.365)
📍 요청 위치: (35.9617°N, 127.3650°E)
📍 격자 좌표: (x=67, y=92)
📍 실제 위치: (35.9643°N, 127.3620°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,진안군(대불리),3001442,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,진안군(대불리),3001442,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,진안군(대불리),3001442,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,진안군(대불리),3001442,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,4.0,unknown
4,진안군(대불리),3001442,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,7.0,unknown
...,...,...,...,...,...,...,...,...
65,진안군(대불리),3001442,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,진안군(대불리),3001442,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,진안군(대불리),3001442,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,진안군(대불리),3001442,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,진안군(대불리),3001442,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 완주군(장선초교)  [3013430]  (36.09111111, 127.2791667)
📍 요청 위치: (36.0911°N, 127.2792°E)
📍 격자 좌표: (x=65, y=95)
📍 실제 위치: (36.1036°N, 127.2512°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,완주군(장선초교),3013430,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,완주군(장선초교),3013430,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,완주군(장선초교),3013430,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,완주군(장선초교),3013430,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,0.0,unknown
4,완주군(장선초교),3013430,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,완주군(장선초교),3013430,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,완주군(장선초교),3013430,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,완주군(장선초교),3013430,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,완주군(장선초교),3013430,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,완주군(장선초교),3013430,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산시(함열초교)  [3014410]  (36.07972222, 126.9652778)
📍 요청 위치: (36.0797°N, 126.9653°E)
📍 격자 좌표: (x=60, y=94)
📍 실제 위치: (36.0609°N, 126.9662°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산시(함열초교),3014410,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,익산시(함열초교),3014410,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,익산시(함열초교),3014410,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,익산시(함열초교),3014410,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,2.0,unknown
4,익산시(함열초교),3014410,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,익산시(함열초교),3014410,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,익산시(함열초교),3014410,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,익산시(함열초교),3014410,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,익산시(함열초교),3014410,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,익산시(함열초교),3014410,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 군산시(임피초교)  [9000216]  (35.98748, 126.84899)
📍 요청 위치: (35.9875°N, 126.8490°E)
📍 격자 좌표: (x=58, y=92)
📍 실제 위치: (35.9700°N, 126.8513°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,군산시(임피초교),9000216,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,군산시(임피초교),9000216,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,군산시(임피초교),9000216,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,군산시(임피초교),9000216,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,3.0,unknown
4,군산시(임피초교),9000216,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,0.0,unknown
...,...,...,...,...,...,...,...,...
65,군산시(임피초교),9000216,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,군산시(임피초교),9000216,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,군산시(임피초교),9000216,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,군산시(임피초교),9000216,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,군산시(임피초교),9000216,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

──────────────────────────────────────────────────
지점: 익산시(연동리)  [3014420]  (36.03388889, 127.035)
📍 요청 위치: (36.0339°N, 127.0350°E)
📍 격자 좌표: (x=61, y=93)
📍 실제 위치: (36.0144°N, 127.0223°E)

✅ 70개 시계열 데이터 추출 완료

  [SHRT 데이터 — 70행]

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,units
0,익산시(연동리),3014420,2026-05-10 20:00:00,7,2026-05-11 03:00:00,PCP,0.0,unknown
1,익산시(연동리),3014420,2026-05-10 20:00:00,8,2026-05-11 04:00:00,PCP,0.0,unknown
2,익산시(연동리),3014420,2026-05-10 20:00:00,9,2026-05-11 05:00:00,PCP,0.0,unknown
3,익산시(연동리),3014420,2026-05-10 20:00:00,10,2026-05-11 06:00:00,PCP,3.0,unknown
4,익산시(연동리),3014420,2026-05-10 20:00:00,11,2026-05-11 07:00:00,PCP,2.0,unknown
...,...,...,...,...,...,...,...,...
65,익산시(연동리),3014420,2026-05-10 20:00:00,80,2026-05-14 04:00:00,PCP,0.0,unknown
66,익산시(연동리),3014420,2026-05-10 20:00:00,83,2026-05-14 07:00:00,PCP,0.0,unknown
67,익산시(연동리),3014420,2026-05-10 20:00:00,86,2026-05-14 10:00:00,PCP,0.0,unknown
68,익산시(연동리),3014420,2026-05-10 20:00:00,89,2026-05-14 13:00:00,PCP,0.0,unknown
69,익산시(연동리),3014420,2026-05-10 20:00:00,92,2026-05-14 16:00:00,PCP,0.0,unknown

## 4) 지점별 VSRT + SHRT 병합 시계열 추출 → CSV 저장

`read_kma_grib_merged`가 폴더에서 VSRT·SHRT를 자동 감지하고,  
겹치는 시각은 VSRT 우선으로 합쳐 hourly 시계열을 반환합니다.  
모든 지점의 결과를 `OUTPUT_CSV`에 저장합니다.

In [5]:
POINTS = globals().get("POINTS")
if not POINTS:
    raise RuntimeError("POINTS가 없습니다. 설정 셀을 먼저 실행하세요.")

OUTPUT_COLS = globals().get(
    "OUTPUT_COLS",
    ["point_name", "point_code", "base_time", "forecast_hour", "valid_time", "variable", "value", "forecast_type"],
)
VSRT_GLOB = globals().get("VSRT_GLOB", "*VSRT*PCP*")
SHRT_GLOB = globals().get("SHRT_GLOB", "*SHRT*PCP*")

frames: list[pd.DataFrame] = []
for pt in POINTS:
    name = pt.get("name") or f"{pt['lat']:.4f}_{pt['lon']:.4f}"
    code = pt.get("code", "")
    print(f"\n{'='*50}")
    print(f"지점: {name}  [{code}]  ({pt['lat']}, {pt['lon']})")
    df_pt = read_kma_grib_merged(
        DATA_FOLDER,
        float(pt["lat"]),
        float(pt["lon"]),
        vsrt_glob=VSRT_GLOB,
        shrt_glob=SHRT_GLOB,
    )
    df_pt.insert(0, "point_code", code)
    df_pt.insert(0, "point_name", name)
    frames.append(df_pt)

df_all = pd.concat(frames, ignore_index=True)

missing = [c for c in OUTPUT_COLS if c not in df_all.columns]
if missing:
    raise ValueError(f"저장할 열이 결과에 없습니다: {missing}")

df_out = df_all[OUTPUT_COLS].copy()
OUTPUT_CSV = globals().get("OUTPUT_CSV", Path("kr_rf_forecast.csv"))
df_out.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
print(f"\n{'='*50}")
print(f"저장 완료: {Path(OUTPUT_CSV).resolve()}")
print(f"행 수: {len(df_out)},  열: {list(df_out.columns)}")
df_out.head(10)

==================================================
지점: 금산  [8000238]  (36.10565, 127.48185)
[VSRT] 1개 파일
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.1056°N, 127.4818°E)
📍 격자 좌표: (x=69, y=95)
📍 실제 위치: (36.1005°N, 127.4786°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 세천  [8000643]  (36.34019, 127.49378)
[VSRT] 1개 파일
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3402°N, 127.4938°E)
📍 격자 좌표: (x=69, y=100)
📍 실제 위치: (36.3303°N, 127.4839°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 장동  [8000648]  (36.41347, 127.43821)
[VSRT] 1개 파일
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4135°N, 127.4382°E)
📍 격자 좌표: (x=68, y=102)
📍 실제 위치: (36.4230°N, 127.4289°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 설천봉  [8000314]  (35.86621, 127.74312)
[VSRT] 1개 파일
📍 요청 위치: (35.8662°N, 127.7431°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.8662°N, 127.7431°E)
📍 격자 좌표: (x=74, y=90)
📍 실제 위치: (35.8662°N, 127.7567°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 무주  [8000701]  (36.001683, 127.668358)
[VSRT] 1개 파일
📍 요청 위치: (36.0017°N, 127.6684°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.0017°N, 127.6684°E)
📍 격자 좌표: (x=72, y=93)
📍 실제 위치: (36.0059°N, 127.6469°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 덕유산  [8000735]  (35.89424, 127.77306)
[VSRT] 1개 파일
📍 요청 위치: (35.8942°N, 127.7731°E)
📍 격자 좌표: (x=74, y=91)
📍 실제 위치: (35.9121°N, 127.7579°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.8942°N, 127.7731°E)
📍 격자 좌표: (x=74, y=91)
📍 실제 위치: (35.9121°N, 127.7579°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 진안주천  [8000757]  (35.97436, 127.43596)
[VSRT] 1개 파일
📍 요청 위치: (35.9744°N, 127.4360°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.9744°N, 127.4360°E)
📍 격자 좌표: (x=68, y=92)
📍 실제 위치: (35.9635°N, 127.4188°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 동향  [8000758]  (35.83519, 127.57117)
[VSRT] 1개 파일
📍 요청 위치: (35.8352°N, 127.5712°E)
📍 격자 좌표: (x=71, y=89)
📍 실제 위치: (35.8232°N, 127.5856°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.8352°N, 127.5712°E)
📍 격자 좌표: (x=71, y=89)
📍 실제 위치: (35.8232°N, 127.5856°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 공성  [8000821]  (36.28187, 128.07393)
[VSRT] 1개 파일
📍 요청 위치: (36.2819°N, 128.0739°E)
📍 격자 좌표: (x=79, y=99)
📍 실제 위치: (36.2741°N, 128.0530°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.2819°N, 128.0739°E)
📍 격자 좌표: (x=79, y=99)
📍 실제 위치: (36.2741°N, 128.0530°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 화서  [8000834]  (36.44122, 127.9442)
[VSRT] 1개 파일
📍 요청 위치: (36.4412°N, 127.9442°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4412°N, 127.9442°E)
📍 격자 좌표: (x=77, y=103)
📍 실제 위치: (36.4603°N, 127.9445°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 추풍령  [8000135]  (36.22025, 127.99458)
[VSRT] 1개 파일
📍 요청 위치: (36.2203°N, 127.9946°E)
📍 격자 좌표: (x=78, y=98)
📍 실제 위치: (36.2294°N, 127.9945°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.2203°N, 127.9946°E)
📍 격자 좌표: (x=78, y=98)
📍 실제 위치: (36.2294°N, 127.9945°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 보은  [8000226]  (36.48761, 127.73415)
[VSRT] 1개 파일
📍 요청 위치: (36.4876°N, 127.7341°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4876°N, 127.7341°E)
📍 격자 좌표: (x=73, y=104)
📍 실제 위치: (36.5105°N, 127.7170°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 옥천  [8000604]  (36.29995, 127.59654)
[VSRT] 1개 파일
📍 요청 위치: (36.3000°N, 127.5965°E)
📍 격자 좌표: (x=71, y=99)
📍 실제 위치: (36.2825°N, 127.5969°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3000°N, 127.5965°E)
📍 격자 좌표: (x=71, y=99)
📍 실제 위치: (36.2825°N, 127.5969°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 영동  [8000605]  (36.16, 127.755)
[VSRT] 1개 파일
📍 요청 위치: (36.1600°N, 127.7550°E)
📍 격자 좌표: (x=74, y=96)
📍 실제 위치: (36.1418°N, 127.7642°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.1600°N, 127.7550°E)
📍 격자 좌표: (x=74, y=96)
📍 실제 위치: (36.1418°N, 127.7642°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 옥천청산  [8000626]  (36.37052, 127.81538)
[VSRT] 1개 파일
📍 요청 위치: (36.3705°N, 127.8154°E)
📍 격자 좌표: (x=75, y=101)
📍 실제 위치: (36.3705°N, 127.8275°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3705°N, 127.8154°E)
📍 격자 좌표: (x=75, y=101)
📍 실제 위치: (36.3705°N, 127.8275°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 가덕  [8000641]  (36.5461, 127.52388)
[VSRT] 1개 파일
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.5461°N, 127.5239°E)
📍 격자 좌표: (x=70, y=105)
📍 실제 위치: (36.5593°N, 127.5465°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 청남대  [8000888]  (36.46267, 127.49074)
[VSRT] 1개 파일
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4627°N, 127.4907°E)
📍 격자 좌표: (x=69, y=103)
📍 실제 위치: (36.4682°N, 127.4871°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 금산군(금성면)  [8004701]  (36.12584, 127.49408)
[VSRT] 1개 파일
📍 요청 위치: (36.1258°N, 127.4941°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.1258°N, 127.4941°E)
📍 격자 좌표: (x=69, y=96)
📍 실제 위치: (36.1464°N, 127.4797°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 영동군(심천면)  [8007732]  (36.20687, 127.71638)
[VSRT] 1개 파일
📍 요청 위치: (36.2069°N, 127.7164°E)
📍 격자 좌표: (x=73, y=97)
📍 실제 위치: (36.1887°N, 127.7085°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.2069°N, 127.7164°E)
📍 격자 좌표: (x=73, y=97)
📍 실제 위치: (36.1887°N, 127.7085°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 팔음산  [8003897]  (36.3504, 127.8795)
[VSRT] 1개 파일
📍 요청 위치: (36.3504°N, 127.8795°E)
📍 격자 좌표: (x=76, y=101)
📍 실제 위치: (36.3695°N, 127.8846°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3504°N, 127.8795°E)
📍 격자 좌표: (x=76, y=101)
📍 실제 위치: (36.3695°N, 127.8846°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 탑산  [8003899]  (36.3236, 127.6436)
[VSRT] 1개 파일
📍 요청 위치: (36.3236°N, 127.6436°E)
📍 격자 좌표: (x=72, y=100)
📍 실제 위치: (36.3276°N, 127.6551°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3236°N, 127.6436°E)
📍 격자 좌표: (x=72, y=100)
📍 실제 위치: (36.3276°N, 127.6551°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 삼봉산  [8003900]  (36.13, 127.8436)
[VSRT] 1개 파일
📍 요청 위치: (36.1300°N, 127.8436°E)
📍 격자 좌표: (x=75, y=96)
📍 실제 위치: (36.1408°N, 127.8211°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.1300°N, 127.8436°E)
📍 격자 좌표: (x=75, y=96)
📍 실제 위치: (36.1408°N, 127.8211°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 염동산  [8003903]  (36.48726, 127.63905)
[VSRT] 1개 파일
📍 요청 위치: (36.4873°N, 127.6390°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4873°N, 127.6390°E)
📍 격자 좌표: (x=72, y=103)
📍 실제 위치: (36.4655°N, 127.6586°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 청주 불당상봉  [8003912]  (36.49826, 127.55856)
[VSRT] 1개 파일
📍 요청 위치: (36.4983°N, 127.5586°E)
📍 격자 좌표: (x=70, y=104)
📍 실제 위치: (36.5133°N, 127.5454°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4983°N, 127.5586°E)
📍 격자 좌표: (x=70, y=104)
📍 실제 위치: (36.5133°N, 127.5454°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 옥천 암산  [8003913]  (36.39459, 127.62834)
[VSRT] 1개 파일
📍 요청 위치: (36.3946°N, 127.6283°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3946°N, 127.6283°E)
📍 격자 좌표: (x=72, y=101)
📍 실제 위치: (36.3735°N, 127.6563°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 옥천 거멍산  [8003914]  (36.43603, 127.67226)
[VSRT] 1개 파일
📍 요청 위치: (36.4360°N, 127.6723°E)
📍 격자 좌표: (x=72, y=102)
📍 실제 위치: (36.4195°N, 127.6574°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4360°N, 127.6723°E)
📍 격자 좌표: (x=72, y=102)
📍 실제 위치: (36.4195°N, 127.6574°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 옥천 금적산  [8003916]  (36.38596, 127.70188)
[VSRT] 1개 파일
📍 요청 위치: (36.3860°N, 127.7019°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3860°N, 127.7019°E)
📍 격자 좌표: (x=73, y=101)
📍 실제 위치: (36.3726°N, 127.7134°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 보은 노성산  [8003918]  (36.45745, 127.62589)
[VSRT] 1개 파일
📍 요청 위치: (36.4575°N, 127.6259°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4575°N, 127.6259°E)
📍 격자 좌표: (x=71, y=103)
📍 실제 위치: (36.4664°N, 127.6015°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 성주산  [8004890]  (36.07694, 127.63033)
[VSRT] 1개 파일
📍 요청 위치: (36.0769°N, 127.6303°E)
📍 격자 좌표: (x=72, y=95)
📍 실제 위치: (36.0978°N, 127.6492°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.0769°N, 127.6303°E)
📍 격자 좌표: (x=72, y=95)
📍 실제 위치: (36.0978°N, 127.6492°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 금산 성치산  [8004900]  (36.01051, 127.45918)
[VSRT] 1개 파일
📍 요청 위치: (36.0105°N, 127.4592°E)
📍 격자 좌표: (x=69, y=93)
📍 실제 위치: (36.0086°N, 127.4765°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.0105°N, 127.4592°E)
📍 격자 좌표: (x=69, y=93)
📍 실제 위치: (36.0086°N, 127.4765°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 금산 백암산  [8004901]  (36.05146, 127.39897)
[VSRT] 1개 파일
📍 요청 위치: (36.0515°N, 127.3990°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.0515°N, 127.3990°E)
📍 격자 좌표: (x=68, y=94)
📍 실제 위치: (36.0554°N, 127.4208°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 계족산  [8004912]  (36.3879, 127.4569)
[VSRT] 1개 파일
📍 요청 위치: (36.3879°N, 127.4569°E)
📍 격자 좌표: (x=69, y=101)
📍 실제 위치: (36.3762°N, 127.4850°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3879°N, 127.4569°E)
📍 격자 좌표: (x=69, y=101)
📍 실제 위치: (36.3762°N, 127.4850°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 무주 민주지산  [8005908]  (36.01256, 127.84766)
[VSRT] 1개 파일
📍 요청 위치: (36.0126°N, 127.8477°E)
📍 격자 좌표: (x=76, y=93)
📍 실제 위치: (36.0019°N, 127.8739°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.0126°N, 127.8477°E)
📍 격자 좌표: (x=76, y=93)
📍 실제 위치: (36.0019°N, 127.8739°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 덕유산  [8005910]  (35.8964, 127.8271)
[VSRT] 1개 파일
📍 요청 위치: (35.8964°N, 127.8271°E)
📍 격자 좌표: (x=75, y=91)
📍 실제 위치: (35.9111°N, 127.8146°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.8964°N, 127.8271°E)
📍 격자 좌표: (x=75, y=91)
📍 실제 위치: (35.9111°N, 127.8146°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 산흥초교  [8004125]  (36.2287, 127.4484)
[VSRT] 1개 파일
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.2287°N, 127.4484°E)
📍 격자 좌표: (x=68, y=98)
📍 실제 위치: (36.2392°N, 127.4248°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 모동면  [8007299]  (36.3201, 127.9594)
[VSRT] 1개 파일
📍 요청 위치: (36.3201°N, 127.9594°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.3201°N, 127.9594°E)
📍 격자 좌표: (x=77, y=100)
📍 실제 위치: (36.3224°N, 127.9403°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 화남면  [8007311]  (36.4483, 127.9055)
[VSRT] 1개 파일
📍 요청 위치: (36.4483°N, 127.9055°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (36.4483°N, 127.9055°E)
📍 격자 좌표: (x=76, y=103)
📍 실제 위치: (36.4614°N, 127.8873°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 진안_용담면  [8005221]  (35.96662, 127.52003)
[VSRT] 1개 파일
📍 요청 위치: (35.9666°N, 127.5200°E)
📍 격자 좌표: (x=70, y=92)
📍 실제 위치: (35.9618°N, 127.5322°E)

✅ 36개 시계열 데이터 추출 완료

[SHRT] 1개 파일
📍 요청 위치: (35.9666°N, 127.5200°E)
📍 격자 좌표: (x=70, y=92)
📍 실제 위치: (35.9618°N, 127.5322°E)

✅ 70개 시계열 데이터 추출 완료
  3시간 간격 구간 제거: 8행 삭제 (마지막 hourly valid_time: 2026-05-13 16:00:00)

병합 결과: VSRT 6행 + SHRT 62행 (SHRT 중복 제거 0행, VSRT 우선)
✅ 최종 68개 hourly 데이터 (2026-05-10 21:00:00 ~ 2026-05-13 16:00:00)

==================================================
지점: 군북두두  [8004167]  (36.1689, 127.5277)
[VSRT] 1개 파일

,point_name,point_code,base_time,forecast_hour,valid_time,variable,value,forecast_type
0,금산,8000238,2026-05-10 20:00:00,1.0,2026-05-10 21:00:00,PCP,0.0,VSRT
1,금산,8000238,2026-05-10 20:00:00,2.0,2026-05-10 22:00:00,PCP,0.0,VSRT
2,금산,8000238,2026-05-10 20:00:00,3.0,2026-05-10 23:00:00,PCP,0.0,VSRT
3,금산,8000238,2026-05-10 20:00:00,4.0,2026-05-11 00:00:00,PCP,0.0,VSRT
4,금산,8000238,2026-05-10 20:00:00,5.0,2026-05-11 01:00:00,PCP,0.0,VSRT
5,금산,8000238,2026-05-10 20:00:00,6.0,2026-05-11 02:00:00,PCP,0.0,VSRT
6,금산,8000238,2026-05-10 20:00:00,7.0,2026-05-11 03:00:00,PCP,0.0,SHRT
7,금산,8000238,2026-05-10 20:00:00,8.0,2026-05-11 04:00:00,PCP,0.0,SHRT
8,금산,8000238,2026-05-10 20:00:00,9.0,2026-05-11 05:00:00,PCP,0.0,SHRT
9,금산,8000238,2026-05-10 20:00:00,10.0,2026-05-11 06:00:00,PCP,0.0,SHRT